import { describe, expect, it } from 'vitest';
import { hashPassword, verifyPassword } from '../src/auth/password';

const KNOWN_PASSWORD = 'CorrectHorse14';
const KNOWN_HASH =
	'pbkdf2-sha256$210000$MDEyMzQ1Njc4OWFiY2RlZg$rpegAdyviY8BuekS6uCP0LD3qe_M793gDj2YE9786aU';

describe('admin password hashing', () => {
	it('verifies a PBKDF2-SHA256 hash generated by Node-compatible tooling', async () => {
		expect(await verifyPassword(KNOWN_PASSWORD, KNOWN_HASH)).toBe(true);
		expect(await verifyPassword('WrongPassword14', KNOWN_HASH)).toBe(false);
	});

	it('round-trips newly generated PBKDF2-SHA256 hashes', async () => {
		const hash = await hashPassword(KNOWN_PASSWORD);
		expect(hash.startsWith('pbkdf2-sha256$210000$')).toBe(true);
		expect(await verifyPassword(KNOWN_PASSWORD, hash)).toBe(true);
		expect(await verifyPassword(`${KNOWN_PASSWORD}!`, hash)).toBe(false);
	});
});
