-- 0017_it_skill_catalog_seed_01.sql
-- Split IT skill master seed; safe for Cloudflare D1 / SQLite statement limits.

INSERT OR IGNORE INTO it_skill_catalog
(skill_key, name, category, skill_type, usage_area, aliases, display_order)
VALUES
('javascript','JavaScript','Programming','Language','Frontend,Backend,Web','JS,ECMAScript',10),
('typescript','TypeScript','Programming','Language','Frontend,Backend,Web','TS',20),
('java','Java','Programming','Language','Backend,Enterprise,Android','JVM',30),
('kotlin','Kotlin','Programming','Language','Backend,Android,Mobile','JVM',40),
('python','Python','Programming','Language','Backend,DataAI,Automation','Py',50),
('c-lang','C','Programming','Language','System,Embedded','C language',60),
('cpp','C++','Programming','Language','System,Game,Embedded','CPP',70),
('csharp','C#','Programming','Language','Backend,Desktop,Game','C Sharp,.NET',80),
('go-lang','Go','Programming','Language','Backend,Cloud,Server','Golang',90),
('rust','Rust','Programming','Language','System,Backend,WebAssembly','',100),
('php','PHP','Programming','Language','Backend,Web','',110),
('ruby','Ruby','Programming','Language','Backend,Web','',120),
('swift','Swift','Programming','Language','Mobile,iOS','',130),
('dart','Dart','Programming','Language','Mobile,Frontend','Flutter',140),
('scala','Scala','Programming','Language','Backend,DataAI','JVM',150),
('r-lang','R','Programming','Language','DataAI,Statistics','R language',160),
('shell-script','Shell Script','Programming','Language','Server,DevOps,Automation','Bash,sh',170),
('powershell','PowerShell','Programming','Language','Windows,Server,Automation','pwsh',180),
('sql','SQL','Programming','Language','Database,Backend,Data','Structured Query Language',190),
('groovy','Groovy','Programming','Language','Backend,DevOps','JVM',200),
('lua','Lua','Programming','Language','Game,Embedded,Scripting','',210),
('perl','Perl','Programming','Language','Server,Automation','',220),
('objective-c','Objective-C','Programming','Language','Mobile,iOS','ObjC',230),
('visual-basic','Visual Basic','Programming','Language','Desktop,Enterprise','VB,VB.NET',240),
('matlab','MATLAB','Programming','Language','DataAI,Engineering','',250),
('cobol','COBOL','Programming','Language','Mainframe,Enterprise','',260),
('assembly','Assembly','Programming','Language','System,Embedded','ASM',270),
('elixir','Elixir','Programming','Language','Backend,Distributed','',280),
('haskell','Haskell','Programming','Language','Backend,Functional','',290),
('solidity','Solidity','Programming','Language','Blockchain,SmartContract','',300),
('html','HTML','Frontend','Standard','Frontend,Web','HTML5',310),
('css','CSS','Frontend','Standard','Frontend,Web','CSS3',320),
('sass-scss','Sass / SCSS','Frontend','Language','Frontend,Web','SCSS',330),
('less','Less','Frontend','Language','Frontend,Web','',340),
('react','React','Frontend','Library','Frontend,Web,SPA','React.js',350),
('next-js','Next.js','Frontend','Framework','Frontend,Backend,Web,SSR','Next',360),
('vue-js','Vue.js','Frontend','Framework','Frontend,Web,SPA','Vue',370),
('nuxt','Nuxt','Frontend','Framework','Frontend,Backend,Web,SSR','Nuxt.js',380),
('angular','Angular','Frontend','Framework','Frontend,Web,SPA','AngularJS',390),
('svelte','Svelte','Frontend','Framework','Frontend,Web','',400),
('sveltekit','SvelteKit','Frontend','Framework','Frontend,Backend,Web,SSR','',410),
('jquery','jQuery','Frontend','Library','Frontend,Web','',420),
('bootstrap','Bootstrap','Frontend','Framework','Frontend,UI','',430),
('tailwind-css','Tailwind CSS','Frontend','Framework','Frontend,UI','Tailwind',440),
('material-ui','Material UI','Frontend','Library','Frontend,UI,React','MUI',450),
('chakra-ui','Chakra UI','Frontend','Library','Frontend,UI,React','',460),
('ant-design','Ant Design','Frontend','Library','Frontend,UI,React','AntD',470),
('redux','Redux','Frontend','Library','Frontend,StateManagement','Redux Toolkit,RTK',480),
('zustand','Zustand','Frontend','Library','Frontend,StateManagement','',490),
('pinia','Pinia','Frontend','Library','Frontend,StateManagement,Vue','',500),
('rxjs','RxJS','Frontend','Library','Frontend,Reactive','ReactiveX',510),
('webpack','Webpack','Frontend','Tool','Frontend,Build','',520),
('vite','Vite','Frontend','Tool','Frontend,Build','',530),
('babel','Babel','Frontend','Tool','Frontend,Build','',540),
('eslint','ESLint','Frontend','Tool','Frontend,Quality','',550),
('prettier','Prettier','Frontend','Tool','Frontend,Quality','',560),
('storybook','Storybook','Frontend','Tool','Frontend,UI,Testing','',570),
('web-components','Web Components','Frontend','Standard','Frontend,Web','Custom Elements,Shadow DOM',580),
('three-js','Three.js','Frontend','Library','Frontend,3D,WebGL','',590),
('d3-js','D3.js','Frontend','Library','Frontend,DataVisualization','D3',600);
