-- 0018_it_skill_catalog_seed_02.sql
-- Split IT skill master seed; safe for Cloudflare D1 / SQLite statement limits.

INSERT OR IGNORE INTO it_skill_catalog
(skill_key, name, category, skill_type, usage_area, aliases, display_order)
VALUES
('chart-js','Chart.js','Frontend','Library','Frontend,DataVisualization','',610),
('apollo-client','Apollo Client','Frontend','Library','Frontend,GraphQL','',620),
('tanstack-query','TanStack Query','Frontend','Library','Frontend,DataFetching','React Query',630),
('electron','Electron','Frontend','Framework','Desktop,JavaScript','',640),
('tauri','Tauri','Frontend','Framework','Desktop,Rust,Frontend','',650),
('node-js','Node.js','Backend','Runtime','Backend,Server,Web','Node',660),
('deno','Deno','Backend','Runtime','Backend,Server','',670),
('bun','Bun','Backend','Runtime','Backend,Server,JavaScript','',680),
('spring-framework','Spring Framework','Backend','Framework','Backend,Enterprise,Java','Spring',690),
('spring-boot','Spring Boot','Backend','Framework','Backend,API,Java','',700),
('spring-security','Spring Security','Backend','Framework','Backend,Security,Java','',710),
('spring-batch','Spring Batch','Backend','Framework','Backend,Batch,Java','',720),
('jakarta-ee','Jakarta EE','Backend','Platform','Backend,Enterprise,Java','Java EE,J2EE',730),
('jpa','JPA','Backend','Standard','Backend,Database,Java','Java Persistence API',740),
('hibernate','Hibernate','Backend','Framework','Backend,ORM,Java','',750),
('mybatis','MyBatis','Backend','Framework','Backend,Database,Java','',760),
('quarkus','Quarkus','Backend','Framework','Backend,Cloud,Java','',770),
('micronaut','Micronaut','Backend','Framework','Backend,Cloud,Java','',780),
('express-js','Express.js','Backend','Framework','Backend,API,Node','Express',790),
('nestjs','NestJS','Backend','Framework','Backend,API,Node','',800),
('fastify','Fastify','Backend','Framework','Backend,API,Node','',810),
('koa','Koa','Backend','Framework','Backend,API,Node','',820),
('django','Django','Backend','Framework','Backend,Web,Python','',830),
('flask','Flask','Backend','Framework','Backend,API,Python','',840),
('fastapi','FastAPI','Backend','Framework','Backend,API,Python','',850),
('ruby-on-rails','Ruby on Rails','Backend','Framework','Backend,Web,Ruby','Rails',860),
('laravel','Laravel','Backend','Framework','Backend,Web,PHP','',870),
('symfony','Symfony','Backend','Framework','Backend,Web,PHP','',880),
('aspnet-core','ASP.NET Core','Backend','Framework','Backend,Web,.NET','ASP.NET',890),
('dotnet','.NET','Backend','Platform','Backend,Desktop,Cloud','dotnet',900),
('entity-framework-core','Entity Framework Core','Backend','Framework','Backend,ORM,.NET','EF Core',910),
('gin','Gin','Backend','Framework','Backend,API,Go','',920),
('fiber','Fiber','Backend','Framework','Backend,API,Go','',930),
('actix-web','Actix Web','Backend','Framework','Backend,API,Rust','',940),
('rocket','Rocket','Backend','Framework','Backend,API,Rust','',950),
('phoenix','Phoenix','Backend','Framework','Backend,Web,Elixir','',960),
('grpc','gRPC','Backend','Protocol','Backend,API,Microservices','',970),
('graphql','GraphQL','Backend','Standard','API,Backend,Frontend','',980),
('websocket','WebSocket','Backend','Protocol','Realtime,Backend,Frontend','',990),
('openapi','OpenAPI','Backend','Standard','API,Documentation','Swagger',1000),
('postgresql','PostgreSQL','Database','Database','Database,Backend,RDBMS','Postgres',1010),
('mysql','MySQL','Database','Database','Database,Backend,RDBMS','',1020),
('mariadb','MariaDB','Database','Database','Database,Backend,RDBMS','',1030),
('oracle-database','Oracle Database','Database','Database','Database,Enterprise,RDBMS','Oracle',1040),
('ibm-db2','IBM Db2','Database','Database','Database,Enterprise,RDBMS','Db2',1050),
('microsoft-sql-server','Microsoft SQL Server','Database','Database','Database,Enterprise,RDBMS','SQL Server,MSSQL',1060),
('sqlite','SQLite','Database','Database','Database,Embedded,RDBMS','',1070),
('h2-database','H2 Database','Database','Database','Database,Testing,Java','H2',1080),
('mongodb','MongoDB','Database','Database','Database,NoSQL,Document','',1090),
('redis','Redis','Database','Database','Database,Cache,NoSQL','',1100),
('elasticsearch','Elasticsearch','Database','Database','Search,Analytics,NoSQL','Elastic',1110),
('opensearch','OpenSearch','Database','Database','Search,Analytics,NoSQL','',1120),
('cassandra','Cassandra','Database','Database','Database,NoSQL,Distributed','',1130),
('dynamodb','DynamoDB','Database','CloudService','Database,NoSQL,AWS','',1140),
('firestore','Firestore','Database','CloudService','Database,NoSQL,GCP','',1150),
('bigquery','BigQuery','Database','CloudService','DataWarehouse,Analytics,GCP','',1160),
('snowflake','Snowflake','Database','Service','DataWarehouse,Analytics,Cloud','',1170),
('amazon-rds','Amazon RDS','Database','CloudService','Database,RDBMS,AWS','RDS',1180),
('amazon-aurora','Amazon Aurora','Database','CloudService','Database,RDBMS,AWS','Aurora',1190),
('amazon-redshift','Amazon Redshift','Database','CloudService','DataWarehouse,Analytics,AWS','Redshift',1200);
