-- 0019_it_skill_catalog_seed_03.sql
-- Split IT skill master seed; safe for Cloudflare D1 / SQLite statement limits.

INSERT OR IGNORE INTO it_skill_catalog
(skill_key, name, category, skill_type, usage_area, aliases, display_order)
VALUES
('azure-sql-database','Azure SQL Database','Database','CloudService','Database,RDBMS,Azure','',1210),
('cosmos-db','Cosmos DB','Database','CloudService','Database,NoSQL,Azure','',1220),
('neo4j','Neo4j','Database','Database','Database,Graph','',1230),
('influxdb','InfluxDB','Database','Database','Database,TimeSeries','',1240),
('timescaledb','TimescaleDB','Database','Database','Database,TimeSeries,PostgreSQL','',1250),
('cockroachdb','CockroachDB','Database','Database','Database,Distributed,RDBMS','',1260),
('supabase','Supabase','Database','Service','Database,Backend,PostgreSQL','',1270),
('firebase-realtime-database','Firebase Realtime Database','Database','CloudService','Database,Realtime,Firebase','',1280),
('prisma','Prisma','Database','Tool','Backend,ORM,Database','',1290),
('liquibase','Liquibase','Database','Tool','Database,Migration','',1300),
('flyway','Flyway','Database','Tool','Database,Migration','',1310),
('aws','Amazon Web Services','Cloud','Platform','Cloud,Infrastructure','AWS',1320),
('azure','Microsoft Azure','Cloud','Platform','Cloud,Infrastructure','Azure',1330),
('gcp','Google Cloud','Cloud','Platform','Cloud,Infrastructure','GCP',1340),
('cloudflare','Cloudflare','Cloud','Platform','Cloud,Edge,Web','',1350),
('cloudflare-workers','Cloudflare Workers','Cloud','CloudService','Edge,Serverless,Web','Workers',1360),
('cloudflare-d1','Cloudflare D1','Cloud','CloudService','Database,Edge,Cloudflare','D1',1370),
('cloudflare-r2','Cloudflare R2','Cloud','CloudService','Storage,ObjectStorage,Cloudflare','R2',1380),
('aws-ec2','AWS EC2','Cloud','CloudService','Compute,Server,AWS','EC2',1390),
('aws-lambda','AWS Lambda','Cloud','CloudService','Serverless,Compute,AWS','Lambda',1400),
('amazon-s3','Amazon S3','Cloud','CloudService','Storage,ObjectStorage,AWS','S3',1410),
('amazon-cloudfront','Amazon CloudFront','Cloud','CloudService','CDN,Edge,AWS','CloudFront',1420),
('aws-route53','Amazon Route 53','Cloud','CloudService','DNS,Network,AWS','Route53',1430),
('amazon-vpc','Amazon VPC','Cloud','CloudService','Network,Infrastructure,AWS','VPC',1440),
('aws-elb','Elastic Load Balancing','Cloud','CloudService','LoadBalancing,Network,AWS','ELB,ALB,NLB',1450),
('aws-iam','AWS IAM','Cloud','CloudService','Security,Identity,AWS','IAM',1460),
('aws-kms','AWS KMS','Cloud','CloudService','Security,Encryption,AWS','KMS',1470),
('amazon-ecs','Amazon ECS','Cloud','CloudService','Container,Compute,AWS','ECS',1480),
('amazon-eks','Amazon EKS','Cloud','CloudService','Kubernetes,Container,AWS','EKS',1490),
('aws-fargate','AWS Fargate','Cloud','CloudService','Container,Serverless,AWS','Fargate',1500),
('aws-cloudformation','AWS CloudFormation','Cloud','CloudService','IaC,Infrastructure,AWS','CloudFormation',1510),
('aws-cloudwatch','AWS CloudWatch','Cloud','CloudService','Monitoring,Logging,AWS','CloudWatch',1520),
('aws-api-gateway','AWS API Gateway','Cloud','CloudService','API,Serverless,AWS','API Gateway',1530),
('aws-sqs','AWS SQS','Cloud','CloudService','Messaging,Queue,AWS','SQS',1540),
('aws-sns','AWS SNS','Cloud','CloudService','Messaging,Notification,AWS','SNS',1550),
('aws-eventbridge','AWS EventBridge','Cloud','CloudService','Messaging,Event,AWS','EventBridge',1560),
('aws-secrets-manager','AWS Secrets Manager','Cloud','CloudService','Security,Secrets,AWS','',1570),
('azure-functions','Azure Functions','Cloud','CloudService','Serverless,Compute,Azure','',1580),
('azure-app-service','Azure App Service','Cloud','CloudService','Web,Hosting,Azure','',1590),
('azure-blob-storage','Azure Blob Storage','Cloud','CloudService','Storage,ObjectStorage,Azure','',1600),
('azure-devops','Azure DevOps','Cloud','Service','DevOps,CI,ProjectManagement,Azure','',1610),
('google-cloud-run','Google Cloud Run','Cloud','CloudService','Serverless,Container,GCP','Cloud Run',1620),
('google-kubernetes-engine','Google Kubernetes Engine','Cloud','CloudService','Kubernetes,Container,GCP','GKE',1630),
('google-cloud-storage','Google Cloud Storage','Cloud','CloudService','Storage,ObjectStorage,GCP','GCS',1640),
('google-cloud-functions','Google Cloud Functions','Cloud','CloudService','Serverless,Compute,GCP','',1650),
('vercel','Vercel','Cloud','Service','Hosting,Frontend,Serverless','',1660),
('netlify','Netlify','Cloud','Service','Hosting,Frontend,Serverless','',1670),
('heroku','Heroku','Cloud','Service','PaaS,Hosting,Backend','',1680),
('git','Git','DevOps','Tool','VersionControl,Development','',1690),
('github','GitHub','DevOps','Service','VersionControl,Collaboration,CI','',1700),
('gitlab','GitLab','DevOps','Service','VersionControl,Collaboration,CI','',1710),
('bitbucket','Bitbucket','DevOps','Service','VersionControl,Collaboration','',1720),
('github-actions','GitHub Actions','DevOps','Service','CI,CD,Automation','',1730),
('gitlab-ci-cd','GitLab CI/CD','DevOps','Service','CI,CD,Automation','',1740),
('jenkins','Jenkins','DevOps','Tool','CI,CD,Automation','',1750),
('circleci','CircleCI','DevOps','Service','CI,CD,Automation','',1760),
('travis-ci','Travis CI','DevOps','Service','CI,CD,Automation','',1770),
('argo-cd','Argo CD','DevOps','Tool','CD,Kubernetes,GitOps','ArgoCD',1780),
('flux-cd','Flux CD','DevOps','Tool','CD,Kubernetes,GitOps','Flux',1790),
('docker','Docker','DevOps','Platform','Container,DevOps','',1800);
