-- 0020_it_skill_catalog_seed_04.sql
-- Split IT skill master seed; safe for Cloudflare D1 / SQLite statement limits.

INSERT OR IGNORE INTO it_skill_catalog
(skill_key, name, category, skill_type, usage_area, aliases, display_order)
VALUES
('docker-compose','Docker Compose','DevOps','Tool','Container,LocalDevelopment','',1810),
('kubernetes','Kubernetes','DevOps','Platform','Container,Orchestration','K8s',1820),
('helm','Helm','DevOps','Tool','Kubernetes,PackageManagement','',1830),
('kustomize','Kustomize','DevOps','Tool','Kubernetes,Configuration','',1840),
('terraform','Terraform','DevOps','Tool','IaC,Cloud,Infrastructure','',1850),
('ansible','Ansible','DevOps','Tool','ConfigurationManagement,Automation','',1860),
('packer','Packer','DevOps','Tool','IaC,ImageBuild','',1870),
('vagrant','Vagrant','DevOps','Tool','Virtualization,Development','',1880),
('maven','Maven','DevOps','Tool','Build,Java','Apache Maven',1890),
('gradle','Gradle','DevOps','Tool','Build,Java,Kotlin','',1900),
('npm','npm','DevOps','Tool','PackageManagement,JavaScript','',1910),
('yarn','Yarn','DevOps','Tool','PackageManagement,JavaScript','',1920),
('pnpm','pnpm','DevOps','Tool','PackageManagement,JavaScript','',1930),
('nexus-repository','Nexus Repository','DevOps','Service','ArtifactRepository,DevOps','Nexus',1940),
('jfrog-artifactory','JFrog Artifactory','DevOps','Service','ArtifactRepository,DevOps','Artifactory',1950),
('sonarqube','SonarQube','DevOps','Tool','Quality,StaticAnalysis','',1960),
('dependabot','Dependabot','DevOps','Service','Security,Dependency,GitHub','',1970),
('renovate','Renovate','DevOps','Service','Dependency,Automation','',1980),
('trivy','Trivy','DevOps','Tool','Security,Container,Scanning','',1990),
('snyk','Snyk','DevOps','Service','Security,Dependency,Scanning','',2000),
('ci-cd','CI/CD','DevOps','Methodology','DevOps,Automation,Deployment','CICD',2010),
('devops','DevOps','DevOps','Methodology','Development,Operations,Automation','',2020),
('gitops','GitOps','DevOps','Methodology','DevOps,Kubernetes,Automation','',2030),
('linux','Linux','Server','OS','Server,Cloud,Development','',2040),
('ubuntu','Ubuntu','Server','OS','Server,Cloud,Linux','',2050),
('red-hat-enterprise-linux','Red Hat Enterprise Linux','Server','OS','Server,Enterprise,Linux','RHEL',2060),
('centos','CentOS','Server','OS','Server,Linux','',2070),
('rocky-linux','Rocky Linux','Server','OS','Server,Linux','',2080),
('almalinux','AlmaLinux','Server','OS','Server,Linux','',2090),
('windows-server','Windows Server','Server','OS','Server,Enterprise,Windows','',2100),
('nginx','Nginx','Server','Tool','WebServer,ReverseProxy,LoadBalancing','',2110),
('apache-http-server','Apache HTTP Server','Server','Tool','WebServer,Server','Apache',2120),
('apache-tomcat','Apache Tomcat','Server','Platform','ApplicationServer,Java,Web','Tomcat',2130),
('open-liberty','Open Liberty','Server','Platform','ApplicationServer,Java,JakartaEE','Liberty',2140),
('ibm-websphere-application-server','IBM WebSphere Application Server','Server','Platform','ApplicationServer,Java,Enterprise','WebSphere,WAS',2150),
('wildfly','WildFly','Server','Platform','ApplicationServer,Java,JakartaEE','JBoss',2160),
('jetty','Jetty','Server','Platform','ApplicationServer,Java,Web','',2170),
('iis','IIS','Server','Platform','WebServer,Windows,.NET','Internet Information Services',2180),
('haproxy','HAProxy','Server','Tool','LoadBalancing,Proxy,Server','',2190),
('traefik','Traefik','Server','Tool','ReverseProxy,CloudNative,Server','',2200),
('vmware-vsphere','VMware vSphere','Server','Platform','Virtualization,Infrastructure','vSphere',2210),
('vmware-esxi','VMware ESXi','Server','Platform','Virtualization,Infrastructure','ESXi',2220),
('hyper-v','Hyper-V','Server','Platform','Virtualization,Windows','',2230),
('virtualbox','VirtualBox','Server','Tool','Virtualization,Development','',2240),
('ssh','SSH','Server','Protocol','Server,Security,RemoteAccess','Secure Shell',2250),
('ftp-sftp','FTP / SFTP','Server','Protocol','FileTransfer,Server','FTPS,SFTP',2260),
('dns','DNS','Server','Protocol','Network,Infrastructure,Web','Domain Name System',2270),
('tcp-ip','TCP/IP','Server','Protocol','Network,Server,Infrastructure','TCP,IP',2280),
('http-https','HTTP / HTTPS','Server','Protocol','Web,Network,API','HTTP2,HTTP3,TLS',2290),
('jp1','JP1','Server','Platform','Operations,JobScheduler,Enterprise','JP1/AJS',2300),
('nec-jobcenter','NEC JobCenter','Server','Platform','Operations,JobScheduler,Enterprise','JobCenter',2310),
('cron','cron','Server','Tool','Server,JobScheduler,Automation','',2320),
('systemd','systemd','Server','Tool','Linux,ServiceManagement,Server','',2330),
('junit','JUnit','Testing','Framework','Testing,Java,UnitTest','',2340),
('mockito','Mockito','Testing','Framework','Testing,Java,Mock','',2350),
('assertj','AssertJ','Testing','Library','Testing,Java,Assertion','',2360),
('testng','TestNG','Testing','Framework','Testing,Java','',2370),
('vitest','Vitest','Testing','Framework','Testing,JavaScript,TypeScript','',2380),
('jest','Jest','Testing','Framework','Testing,JavaScript,TypeScript','',2390),
('mocha','Mocha','Testing','Framework','Testing,JavaScript','',2400);
