-- 0021_it_skill_catalog_seed_05.sql
-- Split IT skill master seed; safe for Cloudflare D1 / SQLite statement limits.

INSERT OR IGNORE INTO it_skill_catalog
(skill_key, name, category, skill_type, usage_area, aliases, display_order)
VALUES
('cypress','Cypress','Testing','Framework','Testing,E2E,Frontend','',2410),
('playwright','Playwright','Testing','Framework','Testing,E2E,Browser','',2420),
('selenium','Selenium','Testing','Framework','Testing,E2E,Browser','',2430),
('puppeteer','Puppeteer','Testing','Library','Testing,Browser,Automation','',2440),
('cucumber','Cucumber','Testing','Framework','Testing,BDD','Gherkin',2450),
('postman','Postman','Testing','Tool','API,Testing,Development','',2460),
('insomnia','Insomnia','Testing','Tool','API,Testing,Development','',2470),
('jmeter','JMeter','Testing','Tool','Testing,Performance,Load','Apache JMeter',2480),
('k6','k6','Testing','Tool','Testing,Performance,Load','',2490),
('gatling','Gatling','Testing','Tool','Testing,Performance,Load','',2500),
('locust','Locust','Testing','Tool','Testing,Performance,Python','',2510),
('owasp-zap','OWASP ZAP','Testing','Tool','Security,Testing,Web','ZAP',2520),
('burp-suite','Burp Suite','Testing','Tool','Security,Testing,Web','',2530),
('wiremock','WireMock','Testing','Tool','Testing,Mock,API','',2540),
('testcontainers','Testcontainers','Testing','Library','Testing,Container,Integration','',2550),
('pact','Pact','Testing','Framework','Testing,Contract,API','',2560),
('jacoco','JaCoCo','Testing','Tool','Testing,Coverage,Java','',2570),
('istanbul','Istanbul','Testing','Tool','Testing,Coverage,JavaScript','nyc',2580),
('apache-kafka','Apache Kafka','DataAI','Platform','Messaging,Streaming,Backend','Kafka',2590),
('rabbitmq','RabbitMQ','DataAI','Platform','Messaging,Queue,Backend','',2600),
('apache-pulsar','Apache Pulsar','DataAI','Platform','Messaging,Streaming,Backend','Pulsar',2610),
('apache-spark','Apache Spark','DataAI','Platform','Data,Distributed,Analytics','Spark',2620),
('apache-hadoop','Apache Hadoop','DataAI','Platform','Data,Distributed,Storage','Hadoop',2630),
('apache-flink','Apache Flink','DataAI','Platform','Data,Streaming,Distributed','Flink',2640),
('apache-airflow','Apache Airflow','DataAI','Platform','Data,Workflow,ETL','Airflow',2650),
('dbt','dbt','DataAI','Tool','Data,Transformation,Analytics','',2660),
('pandas','Pandas','DataAI','Library','DataAI,Python,Analysis','',2670),
('numpy','NumPy','DataAI','Library','DataAI,Python,Numerical','',2680),
('scipy','SciPy','DataAI','Library','DataAI,Python,Scientific','',2690),
('scikit-learn','scikit-learn','DataAI','Library','DataAI,MachineLearning,Python','sklearn',2700),
('tensorflow','TensorFlow','DataAI','Framework','DataAI,DeepLearning,Python','',2710),
('pytorch','PyTorch','DataAI','Framework','DataAI,DeepLearning,Python','',2720),
('keras','Keras','DataAI','Framework','DataAI,DeepLearning,Python','',2730),
('hugging-face','Hugging Face','DataAI','Platform','DataAI,LLM,NLP','Transformers',2740),
('openai-api','OpenAI API','DataAI','Service','AI,LLM,API','',2750),
('langchain','LangChain','DataAI','Framework','AI,LLM,Agent','',2760),
('llamaindex','LlamaIndex','DataAI','Framework','AI,LLM,RAG','',2770),
('mlflow','MLflow','DataAI','Platform','AI,MLOps,Experiment','',2780),
('kubeflow','Kubeflow','DataAI','Platform','AI,MLOps,Kubernetes','',2790),
('jupyter-notebook','Jupyter Notebook','DataAI','Tool','DataAI,Python,Notebook','Jupyter',2800),
('opencv','OpenCV','DataAI','Library','AI,ComputerVision','',2810),
('spacy','spaCy','DataAI','Library','AI,NLP,Python','',2820),
('nltk','NLTK','DataAI','Library','AI,NLP,Python','',2830),
('onnx','ONNX','DataAI','Standard','AI,Model,Interoperability','',2840),
('vector-database','Vector Database','DataAI','Database','AI,RAG,Search','Vector DB',2850),
('pinecone','Pinecone','DataAI','Service','AI,VectorDatabase,RAG','',2860),
('milvus','Milvus','DataAI','Database','AI,VectorDatabase,RAG','',2870),
('weaviate','Weaviate','DataAI','Database','AI,VectorDatabase,RAG','',2880),
('oauth2','OAuth 2.0','Security','Standard','Security,Identity,API','OAuth2',2890),
('openid-connect','OpenID Connect','Security','Standard','Security,Identity,SSO','OIDC',2900),
('saml','SAML','Security','Standard','Security,Identity,SSO','SAML2',2910),
('jwt','JWT','Security','Standard','Security,Authentication,API','JSON Web Token',2920),
('tls','TLS','Security','Protocol','Security,Network,Encryption','SSL',2930),
('mtls','mTLS','Security','Protocol','Security,Network,Authentication','Mutual TLS',2940),
('owasp-top10','OWASP Top 10','Security','Standard','Security,Web,Testing','OWASP',2950),
('csp','CSP','Security','Standard','Security,Web,Frontend','Content Security Policy',2960),
('cors','CORS','Security','Standard','Security,Web,API','Cross Origin Resource Sharing',2970),
('csrf-protection','CSRF Protection','Security','Methodology','Security,Web,Backend','CSRF',2980),
('xss-prevention','XSS Prevention','Security','Methodology','Security,Web,Frontend','XSS',2990),
('rbac','RBAC','Security','Methodology','Security,Authorization,Identity','Role Based Access Control',3000);
