-- 0022_it_skill_catalog_seed_06.sql
-- Split IT skill master seed; safe for Cloudflare D1 / SQLite statement limits.

INSERT OR IGNORE INTO it_skill_catalog
(skill_key, name, category, skill_type, usage_area, aliases, display_order)
VALUES
('abac','ABAC','Security','Methodology','Security,Authorization,Identity','Attribute Based Access Control',3010),
('hashicorp-vault','HashiCorp Vault','Security','Tool','Security,Secrets,DevOps','Vault',3020),
('keycloak','Keycloak','Security','Platform','Security,Identity,SSO','',3030),
('okta','Okta','Security','Service','Security,Identity,SSO','',3040),
('microsoft-entra-id','Microsoft Entra ID','Security','Service','Security,Identity,Azure','Azure AD',3050),
('waf','WAF','Security','Platform','Security,Web,Network','Web Application Firewall',3060),
('siem','SIEM','Security','Platform','Security,Monitoring,Logging','',3070),
('zero-trust','Zero Trust','Security','Methodology','Security,Network,Identity','',3080),
('prometheus','Prometheus','Monitoring','Tool','Monitoring,Metrics,CloudNative','',3090),
('grafana','Grafana','Monitoring','Tool','Monitoring,Visualization,Metrics','',3100),
('datadog','Datadog','Monitoring','Service','Monitoring,APM,Logging','',3110),
('new-relic','New Relic','Monitoring','Service','Monitoring,APM,Logging','',3120),
('splunk','Splunk','Monitoring','Platform','Logging,Search,Monitoring','',3130),
('elastic-stack','Elastic Stack','Monitoring','Platform','Logging,Search,Monitoring','ELK',3140),
('logstash','Logstash','Monitoring','Tool','Logging,ETL,Elastic','',3150),
('kibana','Kibana','Monitoring','Tool','Logging,Visualization,Elastic','',3160),
('fluentd','Fluentd','Monitoring','Tool','Logging,Collection','',3170),
('fluent-bit','Fluent Bit','Monitoring','Tool','Logging,Collection','',3180),
('opentelemetry','OpenTelemetry','Monitoring','Standard','Monitoring,Tracing,Metrics','OTel',3190),
('jaeger','Jaeger','Monitoring','Tool','Monitoring,Tracing,Distributed','',3200),
('zipkin','Zipkin','Monitoring','Tool','Monitoring,Tracing,Distributed','',3210),
('sentry','Sentry','Monitoring','Service','Monitoring,ErrorTracking,Frontend','',3220),
('pagerduty','PagerDuty','Monitoring','Service','Operations,Incident,Alerting','',3230),
('zabbix','Zabbix','Monitoring','Tool','Monitoring,Infrastructure','',3240),
('nagios','Nagios','Monitoring','Tool','Monitoring,Infrastructure','',3250),
('cloudwatch-generic','CloudWatch','Monitoring','CloudService','Monitoring,Logging,AWS','AWS CloudWatch',3260),
('azure-monitor','Azure Monitor','Monitoring','CloudService','Monitoring,Logging,Azure','',3270),
('google-cloud-monitoring','Google Cloud Monitoring','Monitoring','CloudService','Monitoring,Logging,GCP','Stackdriver',3280),
('android-sdk','Android SDK','MobileGame','Platform','Mobile,Android','',3290),
('jetpack-compose','Jetpack Compose','MobileGame','Framework','Mobile,Android,UI','Compose',3300),
('ios-sdk','iOS SDK','MobileGame','Platform','Mobile,iOS','',3310),
('swiftui','SwiftUI','MobileGame','Framework','Mobile,iOS,UI','',3320),
('flutter','Flutter','MobileGame','Framework','Mobile,CrossPlatform,Frontend','',3330),
('react-native','React Native','MobileGame','Framework','Mobile,CrossPlatform,React','RN',3340),
('xamarin','Xamarin','MobileGame','Framework','Mobile,CrossPlatform,.NET','',3350),
('dotnet-maui','.NET MAUI','MobileGame','Framework','Mobile,CrossPlatform,.NET','MAUI',3360),
('unity','Unity','MobileGame','Engine','Game,3D,Mobile','Unity Engine',3370),
('unreal-engine','Unreal Engine','MobileGame','Engine','Game,3D','UE,UE5',3380),
('godot-engine','Godot Engine','MobileGame','Engine','Game,2D,3D','Godot',3390),
('cocos2d-x','Cocos2d-x','MobileGame','Engine','Game,2D,Mobile','',3400),
('arkit','ARKit','MobileGame','Framework','Mobile,AR,iOS','',3410),
('arcore','ARCore','MobileGame','Framework','Mobile,AR,Android','',3420),
('opengl','OpenGL','MobileGame','Standard','Graphics,3D,Game','',3430),
('webgl','WebGL','MobileGame','Standard','Frontend,Graphics,3D','',3440),
('vulkan','Vulkan','MobileGame','Standard','Graphics,3D,Game','',3450),
('directx','DirectX','MobileGame','Platform','Graphics,Game,Windows','',3460),
('figma','Figma','DesignCollab','Tool','Design,UI,UX,Collaboration','',3470),
('adobe-xd','Adobe XD','DesignCollab','Tool','Design,UI,UX','XD',3480),
('adobe-photoshop','Adobe Photoshop','DesignCollab','Tool','Design,Image','Photoshop,PS',3490),
('adobe-illustrator','Adobe Illustrator','DesignCollab','Tool','Design,Vector','Illustrator,AI',3500),
('sketch','Sketch','DesignCollab','Tool','Design,UI,UX,macOS','',3510),
('jira','Jira','DesignCollab','Tool','ProjectManagement,Agile,IssueTracking','',3520),
('confluence','Confluence','DesignCollab','Tool','Documentation,Collaboration','',3530),
('slack','Slack','DesignCollab','Service','Communication,Collaboration','',3540),
('microsoft-teams','Microsoft Teams','DesignCollab','Service','Communication,Collaboration','Teams',3550),
('notion','Notion','DesignCollab','Tool','Documentation,ProjectManagement','',3560),
('redmine','Redmine','DesignCollab','Tool','ProjectManagement,IssueTracking','',3570),
('trello','Trello','DesignCollab','Tool','ProjectManagement,Kanban','',3580),
('backlog','Backlog','DesignCollab','Service','ProjectManagement,IssueTracking','Nulab Backlog',3590),
('asana','Asana','DesignCollab','Service','ProjectManagement,TaskManagement','',3600);
