-- 0023_it_skill_catalog_seed_07.sql
-- Split IT skill master seed; safe for Cloudflare D1 / SQLite statement limits.

INSERT OR IGNORE INTO it_skill_catalog
(skill_key, name, category, skill_type, usage_area, aliases, display_order)
VALUES
('miro','Miro','DesignCollab','Tool','Collaboration,Whiteboard,Design','',3610),
('draw-io','Draw.io','DesignCollab','Tool','Documentation,Diagram','diagrams.net',3620),
('plantuml','PlantUML','DesignCollab','Tool','Documentation,Diagram,UML','',3630),
('mermaid','Mermaid','DesignCollab','Tool','Documentation,Diagram,Markdown','',3640),
('markdown','Markdown','DesignCollab','Standard','Documentation,Writing','MD',3650),
('uml','UML','DesignCollab','Standard','Architecture,Documentation,Design','',3660),
('rest','REST','Architecture','Standard','API,Backend,Web','RESTful,REST API',3670),
('soap','SOAP','Architecture','Protocol','API,Enterprise,Integration','WSDL',3680),
('microservices','Microservices','Architecture','Methodology','Architecture,Backend,Cloud','MSA',3690),
('monolithic-architecture','Monolithic Architecture','Architecture','Methodology','Architecture,Backend','Monolith',3700),
('event-driven-architecture','Event-Driven Architecture','Architecture','Methodology','Architecture,Messaging,Backend','EDA',3710),
('domain-driven-design','Domain-Driven Design','Architecture','Methodology','Architecture,Design,Backend','DDD',3720),
('clean-architecture','Clean Architecture','Architecture','Methodology','Architecture,Design','',3730),
('hexagonal-architecture','Hexagonal Architecture','Architecture','Methodology','Architecture,Design','Ports and Adapters',3740),
('mvc','MVC','Architecture','Pattern','Architecture,Frontend,Backend','Model View Controller',3750),
('mvvm','MVVM','Architecture','Pattern','Architecture,Frontend,Mobile','',3760),
('cqrs','CQRS','Architecture','Pattern','Architecture,Backend,Data','',3770),
('event-sourcing','Event Sourcing','Architecture','Pattern','Architecture,Backend,Data','',3780),
('solid-principles','SOLID Principles','Architecture','Methodology','Design,OOP,Architecture','SOLID',3790),
('design-patterns','Design Patterns','Architecture','Methodology','Design,OOP,Architecture','GoF',3800),
('agile','Agile','Architecture','Methodology','ProjectManagement,Development','Agile Development',3810),
('scrum','Scrum','Architecture','Methodology','ProjectManagement,Agile','',3820),
('kanban','Kanban','Architecture','Methodology','ProjectManagement,Agile','',3830),
('site-reliability-engineering','Site Reliability Engineering','Architecture','Methodology','Operations,Reliability,Cloud','SRE',3840),
('twelve-factor-app','Twelve-Factor App','Architecture','Methodology','Cloud,Architecture,Backend','12 Factor',3850),
('api-gateway-pattern','API Gateway Pattern','Architecture','Pattern','Architecture,API,Microservices','',3860),
('saga-pattern','Saga Pattern','Architecture','Pattern','Architecture,Microservices,Transaction','',3870),
('circuit-breaker','Circuit Breaker','Architecture','Pattern','Architecture,Reliability,Microservices','',3880),
('repository-pattern','Repository Pattern','Architecture','Pattern','Architecture,Backend,Data','',3890),
('dependency-injection','Dependency Injection','Architecture','Pattern','Architecture,Design,Backend','DI',3900),
('visual-studio-code','Visual Studio Code','Tools','Tool','Development,IDE','VS Code',3910),
('intellij-idea','IntelliJ IDEA','Tools','Tool','Development,IDE,Java','IDEA',3920),
('eclipse-ide','Eclipse IDE','Tools','Tool','Development,IDE,Java','Eclipse',3930),
('visual-studio','Visual Studio','Tools','Tool','Development,IDE,.NET','VS',3940),
('android-studio','Android Studio','Tools','Tool','Development,IDE,Android','',3950),
('xcode','Xcode','Tools','Tool','Development,IDE,iOS','',3960),
('dbeaver','DBeaver','Tools','Tool','Database,Development','',3970),
('a5sql','A5:SQL Mk-2','Tools','Tool','Database,Development','A5M2,A5:SQL',3980),
('pgadmin','pgAdmin','Tools','Tool','Database,PostgreSQL','',3990),
('oracle-sql-developer','Oracle SQL Developer','Tools','Tool','Database,Oracle','SQL Developer',4000),
('tera-term','Tera Term','Tools','Tool','Server,SSH,Terminal','TeraTerm',4010),
('putty','PuTTY','Tools','Tool','Server,SSH,Terminal','',4020),
('winscp','WinSCP','Tools','Tool','FileTransfer,SFTP,Server','',4030),
('filezilla','FileZilla','Tools','Tool','FileTransfer,FTP','',4040),
('wireshark','Wireshark','Tools','Tool','Network,Debugging,Security','',4050),
('curl','curl','Tools','Tool','Network,API,CLI','',4060),
('wget','wget','Tools','Tool','Network,Download,CLI','',4070),
('jq','jq','Tools','Tool','JSON,CLI,Automation','',4080),
('make','Make','Tools','Tool','Build,Automation','',4090),
('cmake','CMake','Tools','Tool','Build,C,C++','',4100),
('gradle-wrapper','Gradle Wrapper','Tools','Tool','Build,Java,Kotlin','gradlew',4110),
('psql','PostgreSQL psql','Tools','Tool','Database,PostgreSQL,CLI','psql',4120),
('mysql-cli','MySQL CLI','Tools','Tool','Database,MySQL,CLI','mysql',4130),
('redis-cli','Redis CLI','Tools','Tool','Database,Redis,CLI','redis-cli',4140),
('servicenow','ServiceNow','Tools','Service','ITSM,Operations,Workflow','',4150),
('box','Box','Tools','Service','FileSharing,Collaboration','',4160),
('google-workspace','Google Workspace','Tools','Service','Collaboration,Productivity','',4170),
('microsoft-365','Microsoft 365','Tools','Service','Collaboration,Productivity','Office 365',4180),
('excel','Excel','Tools','Tool','Data,Office,Analysis','Microsoft Excel',4190),
('power-bi','Power BI','Tools','Tool','Data,BI,Visualization','',4200);
