-- 0048_ap_concept_library.sql
-- AP 개념정리: 일본어 기본 + 한국어 병기, 유형별 예상문제
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS ap_concepts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  concept_code TEXT NOT NULL UNIQUE,
  exam_part TEXT NOT NULL DEFAULT 'A' CHECK (exam_part IN ('A','B','AB')),
  unit_ko TEXT NOT NULL, unit_ja TEXT NOT NULL,
  title_ko TEXT NOT NULL, title_ja TEXT NOT NULL,
  definition_ko TEXT NOT NULL, definition_ja TEXT NOT NULL,
  principle_ko TEXT NOT NULL, principle_ja TEXT NOT NULL,
  key_points_ko TEXT NOT NULL, key_points_ja TEXT NOT NULL,
  method_ko TEXT NOT NULL, method_ja TEXT NOT NULL,
  traps_ko TEXT NOT NULL, traps_ja TEXT NOT NULL,
  memory_ko TEXT NOT NULL, memory_ja TEXT NOT NULL,
  example_ko TEXT NOT NULL, example_ja TEXT NOT NULL,
  sort_order INTEGER NOT NULL UNIQUE,
  is_published INTEGER NOT NULL DEFAULT 1 CHECK (is_published IN (0,1)),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
CREATE TABLE IF NOT EXISTS ap_concept_problem_types (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  concept_id INTEGER NOT NULL,
  type_no INTEGER NOT NULL CHECK(type_no>0),
  type_name_ko TEXT NOT NULL, type_name_ja TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  UNIQUE(concept_id,type_no),
  FOREIGN KEY(concept_id) REFERENCES ap_concepts(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS ap_concept_questions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  problem_type_id INTEGER NOT NULL,
  question_no INTEGER NOT NULL CHECK(question_no>0),
  question_ko TEXT NOT NULL, question_ja TEXT NOT NULL,
  choices_ko_json TEXT, choices_ja_json TEXT,
  correct_choice INTEGER,
  answer_ko TEXT NOT NULL, answer_ja TEXT NOT NULL,
  explanation_ko TEXT NOT NULL, explanation_ja TEXT NOT NULL,
  difficulty INTEGER NOT NULL DEFAULT 2 CHECK(difficulty BETWEEN 1 AND 3),
  sort_order INTEGER NOT NULL,
  UNIQUE(problem_type_id,question_no),
  FOREIGN KEY(problem_type_id) REFERENCES ap_concept_problem_types(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ap_concepts_published_order ON ap_concepts(is_published,sort_order);
CREATE INDEX IF NOT EXISTS idx_ap_problem_types_concept_order ON ap_concept_problem_types(concept_id,sort_order);
CREATE INDEX IF NOT EXISTS idx_ap_questions_type_order ON ap_concept_questions(problem_type_id,sort_order);

INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES
('A-01','A','기초이론','基礎理論','2진수·16진수','2進数・16進数','2진수는 0과 1, 16진수는 0~9와 A~F를 사용하는 수 표현 방식이다. 비트 패턴을 사람이 읽기 쉽게 표현할 때 16진수를 자주 사용한다.','2進数は0と1、16進数は0～9とA～Fを使う数の表現方法である。bit列を人が読みやすく表すため16進数をよく使う。','각 자리값은 자리 숫자×밑의 거듭제곱이다. 2진수 1자리는 1bit, 16진수 1자리는 정확히 4bit에 대응한다.','各桁は桁値×基数の累乗で決まる。2進数1桁は1bit、16進数1桁はちょうど4bitに対応する。','2↔16진 변환은 4bit씩 묶는다. nbit 무부호 정수는 0~2^n-1이다. 10진→2진은 2로 나눈 나머지를 역순으로 읽는다.','2↔16進変換は4bitずつ区切る。n bit符号なし整数は0～2^n-1。10進→2進は2で割った余りを逆順に読む。','2진→10진은 1인 자리의 2^k를 합한다. 2진→16진은 오른쪽부터 4자리씩 묶고, 16진→2진은 한 자리를 4bit로 바꾼다.','2進→10進は1の桁の2^kを加算。2進→16進は右から4桁ずつ区切り、16進→2進は各1桁を4bitへ変換する。','왼쪽부터 2^0으로 두는 실수, A=10~F=15를 잊는 실수, 4bit 묶음의 선행 0을 잘못 처리하는 함정이 많다.','左端を2^0とするミス、A=10～F=15を忘れるミス、4bit区切りの先頭0の扱いに注意する。','16진수 1자리=2진수 4자리. 1·2·4·8 자리값을 먼저 적는다.','16進数1桁=2進数4桁。1・2・4・8の重みを先に書く。','101101₂=32+8+4+1=45₁₀=2D₁₆.','101101₂=32+8+4+1=45₁₀=2D₁₆。',1,1),
('A-02','A','기초이론','基礎理論','2의 보수','2の補数','2의 보수는 고정 bit에서 음수를 표현하는 대표 방식이다. 최상위 bit가 1이면 음수로 해석한다.','2の補数は固定bit幅で負数を表す代表方式。最上位bitが1なら負数として解釈する。','nbit에서 -x는 2^n-x이며, 양수 bit를 모두 반전하고 1을 더해 같은 표현을 얻는다.','n bitで-xは2^n-x。正数の全bitを反転し1を加えて同じ表現を得る。','nbit 범위는 -2^(n-1)~2^(n-1)-1. 반전+1로 부호를 바꿀 수 있다. 같은 부호끼리 더해 결과 부호가 바뀌면 overflow를 의심한다.','n bit範囲は-2^(n-1)～2^(n-1)-1。反転+1で符号を変換。同符号加算で結果符号が変わればoverflowを疑う。','8bit -18: 18=00010010→11101101→+1=11101110. 범위 문제는 bit 수부터 확인한다.','8bit -18：18=00010010→11101101→+1=11101110。範囲問題はbit数を最初に確認する。','부호 bit만 바꾸는 것은 2의 보수가 아니다. 8bit 10000000은 +128이 아니라 -128이다.','符号bitだけ変えるのは2の補数ではない。8bit 10000000は+128ではなく-128。','뒤집고 +1, 그리고 음수 범위가 양수보다 하나 더 많다.','反転して+1、負数側が一つ多い。','8bit에서 +127+1은 실제 +128을 표현할 수 없어 overflow다.','8bitで+127+1は本来の+128を表現できずoverflowとなる。',2,1),
('A-03','A','기초이론','基礎理論','논리연산','論理演算','AND·OR·XOR·NOT은 참/거짓 또는 bit 0/1을 규칙에 따라 계산하는 기본 논리연산이다.','AND・OR・XOR・NOTは真偽またはbit 0/1を規則に従って計算する基本論理演算。','AND는 둘 다 1, OR은 하나라도 1, XOR은 서로 다를 때 1, NOT은 0↔1 반전이다.','ANDは両方1、ORはいずれか1、XORは異なると1、NOTは0↔1反転。','AND는 bit 남기기, OR은 bit 켜기, XOR은 toggle에 자주 쓴다. De Morgan: ¬(A∧B)=¬A∨¬B, ¬(A∨B)=¬A∧¬B.','ANDはbit抽出、ORはbit設定、XORはtoggleに使う。De Morgan：¬(A∧B)=¬A∨¬B、¬(A∨B)=¬A∧¬B。','진리표는 00,01,10,11을 전부 적고, bit열은 자릿수를 맞춰 열별로 계산한다.','真理値表は00,01,10,11を全て書き、bit列は桁をそろえて列ごとに計算する。','XOR에서 1 XOR 1=0이다. De Morgan에서는 NOT만 붙이는 것이 아니라 AND↔OR도 바뀐다.','XORでは1 XOR 1=0。De Morganでは否定だけでなくAND↔ORも変わる。','AND=공통, OR=하나라도, XOR=다른 것만, NOT=반대.','AND=共通、OR=どちらか、XOR=異なるものだけ、NOT=反転。','1010 AND 1100=1000, OR=1110, XOR=0110.','1010 AND 1100=1000、OR=1110、XOR=0110。',3,1),
('A-04','A','기초이론','基礎理論','확률','確率','확률은 특정 사건이 일어날 가능성을 0~1로 나타낸 값이다. AP에서는 독립사건, 합사건, 조건부확률, 기대값 계산이 중요하다.','確率は事象が起こる可能性を0～1で表す。APでは独立事象、和事象、条件付き確率、期待値が重要。','독립 A,B가 동시에 발생할 확률은 P(A)P(B). 적어도 하나는 1-P(전부 실패). P(A|B)=P(A∩B)/P(B).','独立A,Bの同時発生はP(A)P(B)。少なくとも一つは1-P(全部失敗)。P(A|B)=P(A∩B)/P(B)。','겹칠 수 있는 합사건은 P(A∪B)=P(A)+P(B)-P(A∩B). 기대값은 결과값×확률의 합이다.','重なり得る和事象はP(A∪B)=P(A)+P(B)-P(A∩B)。期待値は値×確率の総和。','먼저 독립 조건인지 확인한다. 적어도 하나는 여사건으로, 조건부는 분모가 조건 사건임을 확인한다.','まず独立条件を確認。少なくとも一つは余事象、条件付きは分母が条件事象であることを確認する。','서로 배반과 독립은 다르다. 배반은 동시 발생 불가, 독립은 서로 확률에 영향을 주지 않는다는 뜻이다.','排反と独立は異なる。排反は同時発生不可、独立は互いの確率に影響しない。','적어도 하나=1-아무것도 안 일어남.','少なくとも一つ=1-一つも起こらない。','독립 장치 정상확률 0.9,0.8이면 둘 다 정상은 0.72.','独立装置の正常率0.9,0.8なら両方正常は0.72。',4,1),
('A-05','A','기초이론','基礎理論','정보량·엔트로피','情報量・エントロピー','정보량은 드문 사건일수록 더 큰 정보를 준다는 개념을 수치화한 것이고 엔트로피는 평균 정보량이다.','情報量は珍しい事象ほど大きな情報を与える考えを数値化したもの。entropyは平均情報量。','확률 p의 자기정보량 I=-log2 p=log2(1/p), 엔트로피 H=-Σp log2 p. 결과가 균등할수록 엔트로피가 커진다.','確率pの自己情報量I=-log2 p、entropy H=-Σp log2 p。結果が均等なほどentropyは大きい。','1/2→1bit, 1/4→2bit, 1/8→3bit를 즉시 계산한다. n개 균등 결과는 log2 n bit.','1/2→1bit、1/4→2bit、1/8→3bitを即答。n個等確率ならlog2 n bit。','각 사건의 정보량을 구해 확률을 곱한 뒤 합한다. 계산 전 확률 합이 1인지 확인한다.','各事象の情報量を求め確率を掛けて合計。先に確率合計が1か確認する。','확률이 높을수록 정보량이 크다는 선택지는 반대다. 확률 1인 사건은 정보량 0이다.','確率が高いほど情報量が大きいという選択肢は逆。確率1の事象は0bit。','희귀할수록 정보량 큼, 균등할수록 엔트로피 큼.','珍しいほど情報量大、均等ほどentropy大。','확률 1/2,1/4,1/4의 엔트로피는 1.5bit.','確率1/2,1/4,1/4のentropyは1.5bit。',5,1),
('A-06','A','기초이론','基礎理論','부동소수점·오차','浮動小数点・誤差','부동소수점은 실수를 부호·지수·가수로 나눠 제한된 bit 안에 근사 표현하는 방식이다.','浮動小数点は実数を符号・指数・仮数に分け、限られたbitで近似表現する方式。','m×b^e 형태로 정규화해 저장한다. 가수 bit는 정밀도, 지수 bit는 표현 가능한 크기 범위에 크게 영향을 준다.','m×b^eへ正規化して格納。仮数bitは精度、指数bitは表現範囲に大きく影響する。','큰 수+아주 작은 수에서는 情報落ち, 비슷한 큰 수의 뺄셈에서는 桁落ち가 발생하기 쉽다. 범위를 넘으면 overflow/underflow다.','大きい数+非常に小さい数では情報落ち、近い大数の減算では桁落ちが起こりやすい。範囲外はoverflow/underflow。','문제에서 부호→지수→가수 배치를 먼저 표시하고, 오차는 어떤 연산에서 생겼는지로 종류를 판단한다.','符号→指数→仮数の配置を先に確認し、誤差はどの演算で生じたかで種類を判断する。','情報落ち와 桁落ち를 바꿔 고르는 함정이 많다. underflow는 0과 같은 뜻이 아니라 너무 작은 절댓값 문제다.','情報落ちと桁落ちを逆に選ぶ罠が多い。underflowは単に0という意味ではなく小さすぎる絶対値の問題。','큰+작은=情報落ち, 비슷한 수 빼기=桁落ち.','大+小=情報落ち、近い数の差=桁落ち。','큰 값에 매우 작은 값을 더하면 가수 유효범위 밖으로 작은 값이 밀려 사라질 수 있다.','大きい値に非常に小さい値を足すと仮数の有効範囲外へ押し出され消えることがある。',6,1),
('A-07','A','알고리즘','アルゴリズム','Big-O','Big-O記法','Big-O는 입력 n이 커질 때 알고리즘 처리량의 증가율을 나타내는 표기다.','Big-Oは入力nが大きくなるときの処理量の増加率を表す記法。','상수배와 낮은 차수는 생략한다. 3n+10→O(n), 2n²+n→O(n²), 매번 절반이면 O(log n).','定数倍と低次項を省略。3n+10→O(n)、2n²+n→O(n²)、毎回半分ならO(log n)。','증가율은 O(1)<O(log n)<O(n)<O(n log n)<O(n²)<O(2^n). 중첩 loop는 실제 반복 횟수를 계산한다.','増加率はO(1)<O(log n)<O(n)<O(n log n)<O(n²)<O(2^n)。nest loopは実反復回数を数える。','연속 블록은 더해 지배항만 남기고, 중첩은 반복 횟수를 곱한다. i*=2는 log n이다.','連続blockは足して支配項だけ残し、nestは反復回数を掛ける。i*=2はlog n。','Big-O는 실제 초 단위 시간이 아니다. n이 작으면 상수항 때문에 실측속도 순서가 다를 수 있다.','Big-Oは実時間秒ではない。nが小さいと定数項で実測順が異なる場合がある。','연속=더해 큰 것, 중첩=곱, 절반=log.','連続=足して最大、nest=掛ける、半分=log。','n×n 중첩 loop는 n²회 실행되어 O(n²).','n×nの二重loopはn²回でO(n²)。',7,1),
('A-08','A','알고리즘','アルゴリズム','선형탐색','線形探索','선형탐색은 처음부터 차례대로 목표값과 비교하는 가장 단순한 탐색법이다.','線形探索は先頭から順に目的値と比較する最も単純な探索法。','정렬 여부와 무관하게 사용한다. 첫 원소면 1회, 없거나 마지막이면 n회 비교해 최악 O(n).','整列不要。先頭なら1回、存在しないか末尾ならn回比較し最悪O(n)。','작은 데이터나 한 번만 검색할 때 단순하고 유리할 수 있다. 성공 위치가 균등하면 평균 비교 횟수는 약 (n+1)/2.','小規模/一度だけの検索では単純で有利な場合がある。成功位置が一様なら平均比較回数は約(n+1)/2。','의사코드를 한 줄씩 추적하며 비교가 증가하는 시점을 센다. sentinel을 써도 점근복잡도는 O(n).','疑似コードを1行ずつtraceし比較回数を数える。番兵法でも漸近計算量はO(n)。','선형탐색 자체 비용과 정렬 후 반복검색의 전체 비용을 혼동하지 않는다.','線形探索自体の費用と整列後の反復検索の総費用を混同しない。','정렬 필요 없음, 앞에서 하나씩, 최악 n번.','整列不要、先頭から一つずつ、最悪n回。','[7,2,9,4]에서 9는 3회 비교한다.','[7,2,9,4]で9は3回比較する。',8,1),
('A-09','A','알고리즘','アルゴリズム','이분탐색','二分探索','이분탐색은 정렬된 데이터의 가운데와 비교하며 탐색 범위를 절반씩 버리는 탐색법이다.','二分探索は整列済みデータの中央と比較し探索範囲を半分ずつ捨てる探索法。','오름차순에서 target<mid이면 오른쪽을 버리고 target>mid이면 왼쪽을 버린다. O(log n).','昇順でtarget<midなら右、target>midなら左を捨てる。O(log n)。','정렬이 필수다. low/high/mid의 포함 규칙을 일관되게 써야 off-by-one과 무한 loop를 피한다.','整列が必須。low/high/midの包含規則を一貫させoff-by-oneや無限loopを防ぐ。','while low<=high라면 mid=floor((low+high)/2), 작으면 low=mid+1, 크면 high=mid-1.','while low<=highならmid=floor((low+high)/2)、小ならlow=mid+1、大ならhigh=mid-1。','미정렬 배열에 바로 적용하는 선택지가 대표 함정이다. 최악 비교횟수 표현은 문제의 경계 정의를 확인한다.','未整列配列へ直接適用する選択肢が代表的な罠。最悪比較回数は設問の境界定義を確認する。','정렬+반씩 제거=log.','整列+半分ずつ除外=log。','[2,5,8,12,16,23,38]에서 16은 12→23→16 순으로 찾는다.','[2,5,8,12,16,23,38]で16は12→23→16の順に発見。',9,1),
('A-10','A','알고리즘','アルゴリズム','스택·큐','スタック・キュー','스택은 LIFO, 큐는 FIFO 자료구조다.','StackはLIFO、QueueはFIFOのデータ構造。','Stack push/pop은 top에서, Queue enqueue는 rear, dequeue는 front에서 수행한다. 기본 연산은 보통 O(1).','Stack push/popはtop、Queue enqueueはrear、dequeueはfront。基本操作は通常O(1)。','Stack은 함수호출·괄호검사·DFS, Queue는 작업대기열·BFS에 자주 사용한다. 원형 Queue도 빈출이다.','Stackは関数呼出し・括弧・DFS、Queueは待ち行列・BFSに頻出。循環Queueも重要。','연산열은 매 연산 뒤 상태를 기록한다. 원형 Queue index는 (i+1)%N 형태로 이동한다.','操作列は各操作後の状態を書く。循環Queue indexは(i+1)%Nで進める。','Stack/Queue 꺼내는 방향을 반대로 고르는 함정과 원형 Queue의 empty/full 표현 방식을 주의한다.','Stack/Queueの取り出し方向を逆にする罠、循環Queueのempty/full表現方式に注意。','Stack=접시, Queue=줄서기.','Stack=皿、Queue=行列。','A,B,C를 Stack에서 pop하면 C부터, Queue에서 dequeue하면 A부터 나온다.','A,B,CならStackはCから、QueueはAから取り出す。',10,1),
('A-11','A','알고리즘','アルゴリズム','트리·이진탐색트리','木・二分探索木','트리는 부모-자식 계층구조이며 BST는 왼쪽<노드<오른쪽 규칙의 이진트리다.','木は親子の階層構造。BSTは左<node<右の規則を持つ二分木。','root는 부모 없음, leaf는 자식 없음. 균형 BST 탐색은 O(log n), 한쪽으로 치우치면 O(n).','rootは親なし、leafは子なし。平衡BST探索はO(log n)、片寄るとO(n)。','BST inorder는 오름차순. preorder=root-left-right, inorder=left-root-right, postorder=left-right-root.','BST inorderは昇順。preorder=root-left-right、inorder=left-root-right、postorder=left-right-root。','삽입은 root부터 비교해 작으면 왼쪽, 크면 오른쪽 빈 위치까지 내려간다.','挿入はrootから比較し、小なら左、大なら右の空位置まで進む。','이진트리라고 모두 BST는 아니다. 완전이진트리 높이와 임의 BST 높이를 같다고 보면 안 된다.','二分木が全てBSTではない。完全二分木の高さと任意BSTの高さを同一視しない。','BST=왼쪽 작고 오른쪽 큼, inorder=작은 것부터.','BST=左小・右大、inorder=小さい順。','50에 30,70,20,40을 넣으면 30/70은 좌우, 20/40은 30의 좌우다.','50へ30,70,20,40を入れると30/70は左右、20/40は30の左右。',11,1),
('A-12','A','알고리즘','アルゴリズム','그래프 BFS·DFS','グラフ BFS・DFS','그래프는 정점과 간선으로 관계를 표현하며 BFS는 폭 우선, DFS는 깊이 우선 탐색이다.','Graphは頂点と辺で関係を表し、BFSは幅優先、DFSは深さ優先探索。','BFS는 Queue, DFS는 Stack/재귀. 인접리스트 기준 둘 다 O(V+E). 무가중 그래프 최단 간선수는 BFS가 보장한다.','BFSはQueue、DFSはStack/再帰。隣接listならO(V+E)。重みなし最短辺数はBFSが保証。','visited를 추가 시점에 표시하면 중복 삽입을 줄인다. 방문순서는 인접 정점 나열순서에 따라 달라질 수 있다.','visitedを追加時に付けると重複挿入を減らせる。訪問順は隣接頂点の列挙順で変わり得る。','BFS는 Queue/distance, DFS는 호출 Stack/방문순서를 표로 추적한다.','BFSはQueue/distance、DFSはcall Stack/訪問順を表でtraceする。','최단경로라는 말만 보고 BFS를 고르면 안 된다. 서로 다른 양의 가중치가 있으면 Dijkstra 등이 필요하다.','最短経路という語だけでBFSを選ばない。異なる正重みがあればDijkstra等が必要。','BFS=Breadth=Queue, DFS=Depth=Stack/재귀.','BFS=Breadth=Queue、DFS=Depth=Stack/再帰。','0:[1,2],1:[3],2:[4]에서 BFS는 0,1,2,3,4 순이다.','0:[1,2],1:[3],2:[4]でBFSは0,1,2,3,4順。',12,1),
('A-13','A','알고리즘','アルゴリズム','정렬','整列アルゴリズム','정렬은 데이터를 key 순서로 재배치하는 처리이며 AP에서는 trace, 계산량, 안정성, 추가공간을 비교한다.','整列はデータをkey順へ並べ替える処理。APではtrace、計算量、安定性、追加領域を比較する。','Bubble/Selection/Insertion 기본은 O(n²). Merge는 O(n log n), Quick은 평균 O(n log n)·최악 O(n²), Heap은 O(n log n).','Bubble/Selection/Insertion基本はO(n²)。MergeはO(n log n)、Quickは平均O(n log n)・最悪O(n²)、HeapはO(n log n)。','거의 정렬된 작은 배열은 Insertion이 유리할 수 있다. Stable sort는 동일 key의 원래 상대순서를 유지한다.','ほぼ整列済みの小配列ではInsertionが有利な場合がある。Stable sortは同一keyの相対順を維持する。','trace는 문제의 의사코드와 pass 정의를 그대로 따른다. Quick은 pivot 규칙에 따라 중간상태가 달라진다.','traceは設問の疑似コードとpass定義に従う。Quickはpivot規則で途中状態が変わる。','Quick을 항상 O(n log n)이라고 고르는 함정이 많다. Selection은 교환이 적어도 비교는 O(n²).','Quickを常にO(n log n)とする罠が多い。Selectionは交換が少なくても比較O(n²)。','기본3종 n², Merge/Heap n log n, Quick 평균 n log n·최악 n².','基本3種n²、Merge/Heap n log n、Quick平均n log n・最悪n²。','[5,1,4,2] Bubble 첫 pass에서 가장 큰 5가 끝으로 이동한다.','[5,1,4,2]のBubble 1 passで最大5が末尾へ移動。',13,1);

-- 문제유형: 각 개념에서 실제로 자주 달라지는 출제방식을 분리한다.
INSERT OR REPLACE INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,1,'진법 변환','基数変換',1 FROM ap_concepts WHERE concept_code='A-01';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,2,'범위·비트수','範囲・bit数',2 FROM ap_concepts WHERE concept_code='A-01';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,3,'비트패턴','bit列',3 FROM ap_concepts WHERE concept_code='A-01';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,1,'2의 보수 변환','2の補数変換',1 FROM ap_concepts WHERE concept_code='A-02';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,2,'표현범위','表現範囲',2 FROM ap_concepts WHERE concept_code='A-02';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,3,'overflow 판단','overflow判定',3 FROM ap_concepts WHERE concept_code='A-02';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,1,'진리표·기본연산','真理値表・基本演算',1 FROM ap_concepts WHERE concept_code='A-03';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,2,'비트연산·마스크','bit演算・mask',2 FROM ap_concepts WHERE concept_code='A-03';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,3,'드모르간 법칙','De Morgan',3 FROM ap_concepts WHERE concept_code='A-03';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,1,'독립·합사건','独立・和事象',1 FROM ap_concepts WHERE concept_code='A-04';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,2,'조건부확률','条件付き確率',2 FROM ap_concepts WHERE concept_code='A-04';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,3,'기대값','期待値',3 FROM ap_concepts WHERE concept_code='A-04';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,1,'자기정보량','自己情報量',1 FROM ap_concepts WHERE concept_code='A-05';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,2,'엔트로피 계산','entropy計算',2 FROM ap_concepts WHERE concept_code='A-05';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,3,'최대 엔트로피 판단','最大entropy判定',3 FROM ap_concepts WHERE concept_code='A-05';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,1,'구조·정규화','構造・正規化',1 FROM ap_concepts WHERE concept_code='A-06';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,2,'오차 종류 판단','誤差種類判定',2 FROM ap_concepts WHERE concept_code='A-06';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,3,'overflow·underflow','overflow・underflow',3 FROM ap_concepts WHERE concept_code='A-06';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,1,'단일·연속 반복문','単一・連続loop',1 FROM ap_concepts WHERE concept_code='A-07';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,2,'중첩·로그 반복문','nest・log loop',2 FROM ap_concepts WHERE concept_code='A-07';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,3,'성장률 비교','増加率比較',3 FROM ap_concepts WHERE concept_code='A-07';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,1,'탐색 trace·비교횟수','探索trace・比較回数',1 FROM ap_concepts WHERE concept_code='A-08';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,2,'평균·최악 계산량','平均・最悪計算量',2 FROM ap_concepts WHERE concept_code='A-08';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,3,'적용조건·sentinel','適用条件・番兵法',3 FROM ap_concepts WHERE concept_code='A-08';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,1,'전제·복잡도','前提・計算量',1 FROM ap_concepts WHERE concept_code='A-09';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,2,'low·high·mid trace','low・high・mid trace',2 FROM ap_concepts WHERE concept_code='A-09';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,3,'비교횟수·경계','比較回数・境界',3 FROM ap_concepts WHERE concept_code='A-09';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,1,'연산열 trace','操作列trace',1 FROM ap_concepts WHERE concept_code='A-10';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,2,'응용판단','用途判定',2 FROM ap_concepts WHERE concept_code='A-10';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,3,'원형큐','循環Queue',3 FROM ap_concepts WHERE concept_code='A-10';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,1,'용어·순회','用語・巡回',1 FROM ap_concepts WHERE concept_code='A-11';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,2,'BST 삽입·탐색 trace','BST挿入・探索trace',2 FROM ap_concepts WHERE concept_code='A-11';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,3,'높이·최악복잡도','高さ・最悪計算量',3 FROM ap_concepts WHERE concept_code='A-11';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,1,'BFS trace·최단거리','BFS trace・最短距離',1 FROM ap_concepts WHERE concept_code='A-12';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,2,'DFS·재귀 trace','DFS・再帰trace',2 FROM ap_concepts WHERE concept_code='A-12';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,3,'복잡도·자료표현','計算量・表現',3 FROM ap_concepts WHERE concept_code='A-12';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,1,'정렬 trace','sort trace',1 FROM ap_concepts WHERE concept_code='A-13';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,2,'복잡도 비교','計算量比較',2 FROM ap_concepts WHERE concept_code='A-13';
INSERT OR REPLACE INTO ap_concept_problem_types SELECT NULL,id,3,'안정성·공간·선택','安定性・領域・選択',3 FROM ap_concepts WHERE concept_code='A-13';

-- 각 유형의 기본 예상문제. 동일 유형의 추가 문제는 같은 problem_type_id에 question_no만 늘려 확장한다.
INSERT OR REPLACE INTO ap_concept_questions(problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT id,1,'101101₂를 10진수로 바꾸면?','101101₂を10進数に変換するとどれか。','["43","44","45","46"]','["43","44","45","46"]',2,'45','45','32+8+4+1=45.','32+8+4+1=45。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-01') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'0~1000을 모두 표현하려면 최소 몇 bit가 필요한가?','0～1000を全て表すために最低何bit必要か。','["9","10","11","12"]','["9","10","11","12"]',1,'10bit','10bit','2^9=512는 부족하고 2^10=1024로 0~1023을 표현한다.','2^9=512では不足し、2^10=1024で0～1023を表せる。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-01') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'11110000₂의 16진수 표현은?','11110000₂の16進数表現はどれか。','["E0","F0","0F","FF"]','["E0","F0","0F","FF"]',1,'F0','F0','1111=F, 0000=0이므로 F0.','1111=F、0000=0なのでF0。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-01') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'8bit에서 -18의 2의 보수는?','8bitで-18の2の補数表現はどれか。','["11101110","11101101","10010010","00010010"]','["11101110","11101101","10010010","00010010"]',0,'11101110','11101110','18=00010010을 반전해 11101101, +1하면 11101110.','18=00010010を反転し11101101、+1で11101110。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-02') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'8bit 2의 보수 정수 범위는?','8bit 2の補数整数の範囲はどれか。','["-127~127","-128~127","-128~128","0~255"]','["-127~127","-128~127","-128~128","0~255"]',1,'-128~127','-128～127','-2^7~2^7-1이다.','-2^7～2^7-1である。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-02') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'8bit에서 100+40의 결과는?','8bitで100+40の結果はどうなるか。','["정상","overflow","underflow","0"]','["正常","overflow","underflow","0"]',1,'overflow','overflow','8bit signed 최대 127보다 실제 합 140이 크다.','8bit signed最大127を実際の和140が超える。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-02') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'A=1,B=1일 때 A XOR B는?','A=1,B=1のときA XOR Bはどれか。','["0","1","A","B"]','["0","1","A","B"]',0,'0','0','XOR은 서로 다를 때만 1이다.','XORは異なるときだけ1。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-03') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'x의 하위 4bit만 남길 AND mask는?','xの下位4bitだけ残すAND maskはどれか。','["00001111","11110000","11111111","00000000"]','["00001111","11110000","11111111","00000000"]',0,'00001111','00001111','AND에서 남길 위치를 1로 둔다.','ANDでは残す位置を1にする。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-03') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'¬(A∧B)와 동치인 것은?','¬(A∧B)と等価なのはどれか。','["¬A∧¬B","¬A∨¬B","A∨B","A⊕B"]','["¬A∧¬B","¬A∨¬B","A∨B","A⊕B"]',1,'¬A∨¬B','¬A∨¬B','De Morgan에서 AND가 OR로 바뀐다.','De MorganでANDがORへ変わる。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-03') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'독립 A,B 성공확률이 0.8,0.9일 때 둘 다 성공할 확률은?','独立A,Bの成功率が0.8,0.9のとき両方成功する確率は?','["0.17","0.72","0.80","0.98"]','["0.17","0.72","0.80","0.98"]',1,'0.72','0.72','독립 동시발생은 0.8×0.9=0.72.','独立な同時発生は0.8×0.9=0.72。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-04') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'P(A∩B)=0.2, P(B)=0.5일 때 P(A|B)는?','P(A∩B)=0.2、P(B)=0.5のときP(A|B)は?','["0.1","0.2","0.4","0.7"]','["0.1","0.2","0.4","0.7"]',2,'0.4','0.4','0.2/0.5=0.4.','0.2/0.5=0.4。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-04') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'100원을 받을 확률 0.3, 0원 확률 0.7의 기대값은?','100円を得る確率0.3、0円0.7の期待値は?','["30","50","70","100"]','["30","50","70","100"]',0,'30','30','100×0.3+0×0.7=30.','100×0.3+0×0.7=30。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-04') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'확률 1/8인 사건의 자기정보량은?','確率1/8の事象の自己情報量は?','["1bit","2bit","3bit","8bit"]','["1bit","2bit","3bit","8bit"]',2,'3bit','3bit','-log2(1/8)=3.','-log2(1/8)=3。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-05') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'확률 1/2,1/4,1/4의 엔트로피는?','確率1/2,1/4,1/4のentropyは?','["1","1.25","1.5","2"]','["1","1.25","1.5","2"]',2,'1.5bit','1.5bit','0.5×1+0.25×2+0.25×2=1.5.','0.5×1+0.25×2+0.25×2=1.5。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-05') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'4개 결과에서 엔트로피가 최대인 분포는?','4結果でentropyが最大の分布は?','["1,0,0,0","0.7,0.1,0.1,0.1","0.25,0.25,0.25,0.25","0.4,0.3,0.2,0.1"]','["1,0,0,0","0.7,0.1,0.1,0.1","0.25,0.25,0.25,0.25","0.4,0.3,0.2,0.1"]',2,'균등분포','一様分布','동일 개수의 결과에서는 균등할수록 불확실성이 최대다.','同じ結果数では一様分布で不確実性が最大。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-05') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'가수부 bit 수가 주로 영향을 주는 것은?','仮数部bit数が主に影響するものは?','["정밀도","부호","정렬","주소"]','["精度","符号","sort","address"]',0,'정밀도','精度','가수부는 유효숫자의 정밀도를 결정한다.','仮数部は有効数字の精度を決める。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-06') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'큰 수에 매우 작은 수를 더해 작은 값이 사라지는 것은?','大数に非常に小さい数を加え小さい値が消えるのは?','["桁落ち","情報落ち","overflow","deadlock"]','["桁落ち","情報落ち","overflow","deadlock"]',1,'情報落ち','情報落ち','작은 수가 가수의 유효자리 밖으로 밀린다.','小さい値が仮数の有効桁外へ押し出される。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-06') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'표현 가능한 최대 절댓값을 넘는 현상은?','表現可能な最大絶対値を超える現象は?','["underflow","overflow","桁落ち","丸め"]','["underflow","overflow","桁落ち","丸め"]',1,'overflow','overflow','표현범위 상단을 넘는다.','表現範囲上限を超える。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-06') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'O(n) 블록 뒤 O(n²) 블록이 실행되면 전체 Big-O는?','O(n)の後にO(n²)が実行される全体Big-Oは?','["O(n)","O(n²)","O(n³)","O(2n²)"]','["O(n)","O(n²)","O(n³)","O(2n²)"]',1,'O(n²)','O(n²)','연속 비용을 더한 뒤 지배항 n²만 남긴다.','連続費用を足し支配項n²だけ残す。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-07') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'i=1에서 매번 i*=2로 n까지 반복하면?','i=1から毎回i*=2でnまで反復すると?','["O(1)","O(log n)","O(n)","O(n²)"]','["O(1)","O(log n)","O(n)","O(n²)"]',1,'O(log n)','O(log n)','2^k≈n이므로 k≈log2 n.','2^k≈nなのでk≈log2 n。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-07') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'n이 클 때 가장 느리게 증가하는 것은?','nが大きいとき最も遅く増加するのは?','["O(n²)","O(n log n)","O(log n)","O(n)"]','["O(n²)","O(n log n)","O(log n)","O(n)"]',2,'O(log n)','O(log n)','log n이 가장 완만하다.','log nが最も緩やか。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-07') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[4,8,1,7,3]에서 7을 선형탐색하면 비교횟수는?','[4,8,1,7,3]から7を線形探索する比較回数は?','["2","3","4","5"]','["2","3","4","5"]',2,'4회','4回','4→8→1→7 순으로 네 번 비교한다.','4→8→1→7の4回比較。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-08') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'성공 위치가 균등한 n개 배열의 평균 비교횟수는?','成功位置が一様なn要素配列の平均比較回数は?','["1","log n","(n+1)/2","n²/2"]','["1","log n","(n+1)/2","n²/2"]',2,'(n+1)/2','(n+1)/2','1~n 비교횟수의 평균이다.','1～nの比較回数の平均。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-08') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'선형탐색의 장점은?','線形探索の利点は?','["정렬 필수","정렬 없이 사용 가능","항상 O(1)","중복 불가"]','["整列必須","整列なしで使用可能","常にO(1)","重複不可"]',1,'정렬 없이 사용 가능','整列なしで使用可能','앞에서부터 비교하므로 사전 정렬이 필요 없다.','先頭から比較するため事前整列不要。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-08') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'이분탐색의 필수 전제는?','二分探索の必須前提は?','["정렬됨","중복 없음","n이 짝수","Queue 사용"]','["整列済み","重複なし","nが偶数","Queue使用"]',0,'정렬됨','整列済み','비교 후 버릴 절반을 결정하려면 정렬 규칙이 필요하다.','比較後に捨てる半分を決めるには整列規則が必要。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-09') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'오름차순에서 target>a[mid]이면?','昇順でtarget>a[mid]なら?','["high=mid-1","low=mid+1","mid=0","종료"]','["high=mid-1","low=mid+1","mid=0","終了"]',1,'low=mid+1','low=mid+1','mid와 왼쪽은 후보가 아니므로 제거한다.','midと左側を候補から除外する。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-09') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'1024=2^10개 원소의 이분탐색 비교 규모는?','1024=2^10要素の二分探索の比較規模は?','["10회 정도","100회","512회","1024회"]','["約10回","100回","512回","1024回"]',0,'약 10회','約10回','범위를 10번 정도 절반으로 줄이면 1개 수준이 된다.','約10回半分にすると1要素程度になる。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-09') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'Stack에 A,B,C push 후 pop 값은?','StackにA,B,Cをpush後popする値は?','["A","B","C","없음"]','["A","B","C","なし"]',2,'C','C','LIFO이므로 마지막 C가 먼저 나온다.','LIFOなので最後のCが先。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-10') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'BFS 구현에 대표적으로 쓰는 자료구조는?','BFS実装で代表的に使うデータ構造は?','["Stack","Queue","Tree만","Hash만"]','["Stack","Queue","Treeのみ","Hashのみ"]',1,'Queue','Queue','같은 거리의 정점을 먼저 처리하는 FIFO가 필요하다.','同じ距離の頂点を先に処理するFIFOが必要。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-10') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'크기 N 원형Queue index의 전형적 다음 위치는?','大きさNの循環Queue indexの典型的な次位置は?','["i+N","i%2","(i+1)%N","N-i"]','["i+N","i%2","(i+1)%N","N-i"]',2,'(i+1)%N','(i+1)%N','끝 다음을 0으로 순환시키기 위해 mod N을 쓴다.','末尾の次を0へ循環させるためmod Nを使う。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-10') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'BST를 inorder 순회하면?','BSTをinorder巡回すると?','["오름차순","삽입순","무작위","항상 내림차순"]','["昇順","挿入順","random","常に降順"]',0,'오름차순','昇順','left-root-right와 BST 대소관계 때문에 오름차순이다.','left-root-rightとBST大小関係により昇順。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-11') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'BST root=50에 30을 삽입할 위치는?','BST root=50へ30を挿入する位置は?','["왼쪽","오른쪽","root교체","불가"]','["左","右","root置換","不可"]',0,'왼쪽','左','30<50이므로 왼쪽으로 내려간다.','30<50なので左へ進む。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-11') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'BST가 한쪽으로 완전히 치우치면 탐색 최악은?','BSTが片側へ完全に偏ると探索最悪は?','["O(1)","O(log n)","O(n)","O(n²)"]','["O(1)","O(log n)","O(n)","O(n²)"]',2,'O(n)','O(n)','높이가 n 수준이 되어 연결list처럼 탐색한다.','高さがn程度となりlistのように探索する。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-11') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'무가중 그래프에서 최소 간선수 거리를 구할 때 적합한 것은?','重みなしgraphで最小辺数距離を求めるのに適するのは?','["BFS","DFS만","Bubble","Hash"]','["BFS","DFSのみ","Bubble","Hash"]',0,'BFS','BFS','레벨 순 최초 방문이 최소 간선 수를 보장한다.','level順の初回訪問が最小辺数を保証。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-12') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'DFS의 대표 구현 구조는?','DFSの代表的実装構造は?','["Queue만","Stack 또는 재귀","Heap만","정렬"]','["Queueのみ","Stackまたは再帰","Heapのみ","sort"]',1,'Stack 또는 재귀','Stackまたは再帰','깊게 들어갔다 되돌아오므로 LIFO 성질을 쓴다.','深く進んで戻るためLIFO性質を使う。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-12') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'인접list 기반 BFS/DFS의 시간복잡도는?','隣接list型BFS/DFSの時間計算量は?','["O(1)","O(log V)","O(V+E)","O(VE²)"]','["O(1)","O(log V)","O(V+E)","O(VE²)"]',2,'O(V+E)','O(V+E)','각 정점과 간선을 상수 횟수 확인한다.','各頂点と辺を定数回確認する。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-12') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[5,1,4,2] Bubble 오름차순 1 pass 후는?','[5,1,4,2]をBubble昇順で1 pass後は?','["1,4,2,5","1,5,2,4","5,1,2,4","1,2,4,5"]','["1,4,2,5","1,5,2,4","5,1,2,4","1,2,4,5"]',0,'1,4,2,5','1,4,2,5','인접 교환으로 가장 큰 5가 맨 뒤로 이동한다.','隣接交換で最大5が末尾へ移動する。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-13') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'Quick sort 평균/최악 조합은?','Quick sortの平均/最悪の組合せは?','["O(n),O(n)","O(n log n),O(n²)","O(n²),O(log n)","O(log n),O(n)"]','["O(n),O(n)","O(n log n),O(n²)","O(n²),O(log n)","O(log n),O(n)"]',1,'O(n log n), O(n²)','O(n log n), O(n²)','균형분할은 평균 n log n, 극단적 분할은 최악 n².','均衡分割は平均n log n、極端分割は最悪n²。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-13') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'안정 정렬의 의미는?','安定sortの意味は?','["모든 입력 O(n)","동일 key 상대순서 유지","추가 memory 0","재귀 없음"]','["全入力O(n)","同一keyの相対順維持","追加memory 0","再帰なし"]',1,'동일 key 상대순서 유지','同一keyの相対順維持','같은 key를 가진 레코드의 원래 순서를 보존한다.','同じkeyを持つrecordの元の順序を保つ。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-13') AND type_no=3;
