-- 0049_ap_concept_extra_questions.sql
-- 각 AP 개념 유형마다 두 번째 문제를 추가해 동일 개념의 다양한 출제 형태를 반복 연습한다.
PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'16진수 7B₁₆를 2진수로 바꾸면?','16進数7B₁₆を2進数にすると?','["0111 1011","0111 1101","1011 0111","1110 1011"]','["0111 1011","0111 1101","1011 0111","1110 1011"]',0,'0111 1011','0111 1011','7=0111, B=1011이므로 이어 붙이면 된다.','7=0111、B=1011なので連結する。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-01') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'8bit 무부호 정수의 최댓값은?','8bit符号なし整数の最大値は?','["127","128","255","256"]','["127","128","255","256"]',2,'255','255','2^8-1=255.','2^8-1=255。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-01') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'16진수 3A₁₆의 10진수 값은?','16進数3A₁₆の10進数値は?','["48","52","58","62"]','["48","52","58","62"]',2,'58','58','3×16+10=58.','3×16+10=58。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-01') AND type_no=3;

INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'8bit 11110110을 2의 보수 정수로 해석하면?','8bit 11110110を2の補数整数として解釈すると?','["-10","-9","10","246"]','["-10","-9","10","246"]',0,'-10','-10','반전 00001001 후 +1=10이므로 -10.','反転00001001後+1=10なので-10。',2,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-02') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'16bit 2의 보수에서 최솟값은?','16bit 2の補数で最小値は?','["-32768","-32767","-65535","-65536"]','["-32768","-32767","-65535","-65536"]',0,'-32768','-32768','-2^15=-32768.','-2^15=-32768。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-02') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'8bit에서 -100+-40에 대한 설명은?','8bitで-100+-40について正しい説明は?','["정상 -140","overflow","underflow","0"]','["正常-140","overflow","underflow","0"]',1,'overflow','overflow','-140은 8bit signed 최솟값 -128보다 작다.','-140は8bit signed最小値-128より小さい。',2,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-02') AND type_no=3;

INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'A=0,B=1일 때 NOT A AND B는?','A=0,B=1のときNOT A AND Bは?','["0","1","A","B"]','["0","1","A","B"]',1,'1','1','NOT A=1이고 1 AND 1=1.','NOT A=1、1 AND 1=1。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-03') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'1010 XOR 1100은?','1010 XOR 1100は?','["0110","1110","1000","0010"]','["0110","1110","1000","0010"]',0,'0110','0110','각 자리 값이 다를 때만 1이다.','各桁が異なるときだけ1。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-03') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'¬(A∨B)와 동치인 것은?','¬(A∨B)と等価なのは?','["¬A∧¬B","¬A∨¬B","A∧B","A⊕B"]','["¬A∧¬B","¬A∨¬B","A∧B","A⊕B"]',0,'¬A∧¬B','¬A∧¬B','De Morgan에서 OR은 AND로 바뀐다.','De MorganでORはANDへ変わる。',2,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-03') AND type_no=3;

INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'독립 장치 실패확률이 0.1,0.2일 때 적어도 하나 실패할 확률은?','独立装置の故障率0.1,0.2で少なくとも1台故障する確率は?','["0.02","0.28","0.30","0.72"]','["0.02","0.28","0.30","0.72"]',1,'0.28','0.28','1-(0.9×0.8)=0.28.','1-(0.9×0.8)=0.28。',2,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-04') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'P(A)=0.6,P(B)=0.5,P(A∩B)=0.3이면 독립인가?','P(A)=0.6,P(B)=0.5,P(A∩B)=0.3なら独立か?','["독립","비독립","판단불가","배반"]','["独立","非独立","判断不能","排反"]',0,'독립','独立','P(A)P(B)=0.3이 교집합 확률과 같다.','P(A)P(B)=0.3が積事象確率と一致する。',2,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-04') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'결과 10,20,40의 확률이 0.2,0.5,0.3일 때 기대값은?','結果10,20,40の確率が0.2,0.5,0.3の期待値は?','["20","22","24","26"]','["20","22","24","26"]',2,'24','24','10×0.2+20×0.5+40×0.3=24.','10×0.2+20×0.5+40×0.3=24。',2,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-04') AND type_no=3;

INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'확률 1인 사건의 자기정보량은?','確率1の事象の自己情報量は?','["0bit","1bit","2bit","∞"]','["0bit","1bit","2bit","∞"]',0,'0bit','0bit','-log2 1=0.','-log2 1=0。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-05') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'두 결과가 각각 1/2 확률일 때 엔트로피는?','2結果が各1/2のときentropyは?','["0","0.5","1","2"]','["0","0.5","1","2"]',2,'1bit','1bit','각 사건 정보량 1bit이고 평균도 1bit.','各事象1bitで平均も1bit。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-05') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'8개 결과가 모두 같은 확률이면 엔트로피는?','8結果が全て等確率ならentropyは?','["2bit","3bit","4bit","8bit"]','["2bit","3bit","4bit","8bit"]',1,'3bit','3bit','log2 8=3.','log2 8=3。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-05') AND type_no=3;

INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'지수부 bit 수가 증가하면 일반적으로 넓어지는 것은?','指数部bit数が増えると一般に広がるものは?','["값의 범위","정밀도만","문자코드","정렬속도"]','["値の範囲","精度だけ","文字code","sort速度"]',0,'값의 범위','値の範囲','더 큰/작은 지수를 표현할 수 있다.','より大きい/小さい指数を表現できる。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-06') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'서로 가까운 큰 수를 빼 유효숫자가 급감하는 것은?','近い大数の減算で有効数字が急減するのは?','["桁落ち","情報落ち","overflow","sampling"]','["桁落ち","情報落ち","overflow","sampling"]',0,'桁落ち','桁落ち','상위 유효자리들이 상쇄되며 유효자릿수가 줄어든다.','上位有効桁が相殺され有効桁数が減る。',2,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-06') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'0이 아닌 절댓값이 너무 작아 표현범위 아래가 되는 것은?','0でない絶対値が小さすぎ表現範囲下限を下回るのは?','["underflow","overflow","deadlock","entropy"]','["underflow","overflow","deadlock","entropy"]',0,'underflow','underflow','작은 쪽 표현범위를 벗어난다.','小さい側の表現範囲を外れる。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-06') AND type_no=3;

INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'2n²+100n+5의 Big-O는?','2n²+100n+5のBig-Oは?','["O(1)","O(n)","O(n²)","O(n³)"]','["O(1)","O(n)","O(n²)","O(n³)"]',2,'O(n²)','O(n²)','최고차항 n²만 남긴다.','最高次項n²だけ残す。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-07') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'n×n 중첩 loop의 시간복잡도는?','n×nの二重loopの時間計算量は?','["O(log n)","O(n)","O(n log n)","O(n²)"]','["O(log n)","O(n)","O(n log n)","O(n²)"]',3,'O(n²)','O(n²)','n회 안에서 다시 n회이므로 n×n.','n回の中でn回なのでn×n。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-07') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'O(n log n)과 O(n²) 중 큰 n에서 일반적으로 더 효율적인 것은?','O(n log n)とO(n²)で大きいnに一般に効率的なのは?','["O(n log n)","O(n²)","항상 동일","판단불가"]','["O(n log n)","O(n²)","常に同じ","判断不能"]',0,'O(n log n)','O(n log n)','n log n이 n²보다 느리게 증가한다.','n log nはn²より緩やかに増加する。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-07') AND type_no=3;

INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'n개 원소에 목표값이 없을 때 선형탐색 비교횟수는?','n要素に目的値がないとき線形探索の比較回数は?','["1","log n","n","n²"]','["1","log n","n","n²"]',2,'n','n','끝까지 모든 원소를 확인한다.','最後まで全要素を確認する。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-08') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'선형탐색의 최악 시간복잡도는?','線形探索の最悪時間計算量は?','["O(1)","O(log n)","O(n)","O(n log n)"]','["O(1)","O(log n)","O(n)","O(n log n)"]',2,'O(n)','O(n)','최대 n개 원소를 확인한다.','最大n要素を確認する。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-08') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'sentinel을 써도 선형탐색의 점근 복잡도는?','番兵法を使っても線形探索の漸近計算量は?','["O(1)","O(log n)","O(n)","O(n²)"]','["O(1)","O(log n)","O(n)","O(n²)"]',2,'O(n)','O(n)','경계검사 상수는 줄지만 n에 비례하는 성질은 같다.','境界判定の定数は減ってもn比例は同じ。',2,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-08') AND type_no=3;

INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'이분탐색의 시간복잡도는?','二分探索の時間計算量は?','["O(1)","O(log n)","O(n)","O(n²)"]','["O(1)","O(log n)","O(n)","O(n²)"]',1,'O(log n)','O(log n)','매 단계 후보가 절반으로 줄어든다.','毎段階で候補が半分になる。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-09') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'while low<=high에서 target<a[mid]이면?','while low<=highでtarget<a[mid]なら?','["low=mid","low=mid+1","high=mid-1","high=mid+1"]','["low=mid","low=mid+1","high=mid-1","high=mid+1"]',2,'high=mid-1','high=mid-1','mid 이상은 후보에서 제외한다.','mid以上を候補から除外する。',2,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-09') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'정렬되지 않은 배열에 이분탐색을 바로 적용해도 되는가?','未整列配列へ二分探索を直接適用してよいか?','["예","아니오","중복 없으면 예","짝수개면 예"]','["はい","いいえ","重複なしなら可","偶数個なら可"]',1,'아니오','いいえ','정렬 순서가 있어야 어느 절반을 버릴지 판단할 수 있다.','整列順がないと捨てる半分を判断できない。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-09') AND type_no=3;

INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'Queue에 A,B,C enqueue 후 dequeue 값은?','QueueにA,B,Cをenqueue後dequeueする値は?','["A","B","C","없음"]','["A","B","C","なし"]',0,'A','A','FIFO라 먼저 들어간 A가 먼저 나온다.','FIFOなので最初のAが先に出る。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-10') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'재귀 호출 문맥 관리와 가장 가까운 자료구조는?','再帰呼出し文脈管理に最も近いデータ構造は?','["Queue","Stack","Set","Hash"]','["Queue","Stack","Set","Hash"]',1,'Stack','Stack','가장 최근 호출부터 복귀하는 LIFO다.','最新の呼出しから戻るLIFO。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-10') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'원형Queue의 주요 장점은?','循環Queueの主な利点は?','["자동정렬","앞쪽 빈공간 재사용","검색 O(log n)","중복제거"]','["自動sort","前方空領域の再利用","検索O(log n)","重複除去"]',1,'앞쪽 빈공간 재사용','前方空領域の再利用','dequeue 후 생긴 공간을 순환해 다시 사용한다.','dequeue後の空領域を循環して再利用する。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-10') AND type_no=3;

INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'자식이 없는 트리 노드는?','子を持たない木のnodeは?','["root","leaf","edge","parent"]','["root","leaf","edge","parent"]',1,'leaf','leaf','leaf는 자식이 없는 끝 노드다.','leafは子を持たない末端node。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-11') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'균형 BST의 평균 탐색복잡도는?','平衡BSTの平均探索計算量は?','["O(1)","O(log n)","O(n)","O(n²)"]','["O(1)","O(log n)","O(n)","O(n²)"]',1,'O(log n)','O(log n)','균형일 때 높이가 log n 수준이다.','平衡なら高さがlog n程度。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-11') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'이진트리에 대한 올바른 설명은?','二分木の正しい説明は?','["모두 BST","각 노드 자식 최대2","항상 균형","항상 완전"]','["全てBST","各nodeの子は最大2","常に平衡","常に完全"]',1,'각 노드 자식 최대2','各nodeの子は最大2','이진트리의 정의이며 BST 조건은 별도다.','二分木の定義でありBST条件は別。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-11') AND type_no=3;

INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'0:[1,2],1:[3],2:[4]에서 0부터 BFS 순서는?','0:[1,2],1:[3],2:[4]で0からBFS順は?','["0,1,2,3,4","0,1,3,2,4","0,2,4,1,3","4,3,2,1,0"]','["0,1,2,3,4","0,1,3,2,4","0,2,4,1,3","4,3,2,1,0"]',0,'0,1,2,3,4','0,1,2,3,4','Queue로 같은 깊이를 먼저 방문한다.','Queueで同じ深さを先に訪問する。',2,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-12') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'DFS에서 visited가 중요한 이유는?','DFSでvisitedが重要な理由は?','["정렬","cycle 중복/무한탐색 방지","가중치변경","메모리삭제"]','["sort","cycleの重複/無限探索防止","重み変更","memory削除"]',1,'중복·무한탐색 방지','重複・無限探索防止','이미 방문한 정점을 다시 깊게 따라가지 않게 한다.','訪問済み頂点を再び深く辿らないようにする。',2,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-12') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'서로 다른 양의 가중치 최단경로에 BFS만 쓰는 것은?','異なる正の重み付き最短経路にBFSだけを使うのは?','["항상 적절","일반적으로 부적절","항상 DFS보다 좋음","정렬하면 적절"]','["常に適切","一般に不適切","常にDFSより良い","sortすれば適切"]',1,'일반적으로 부적절','一般に不適切','BFS는 무가중/동일가중 최단 간선수에 적합하다.','BFSは重みなし/同一重みの最短辺数向け。',2,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-12') AND type_no=3;

INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'Selection sort 오름차순의 전형적인 한 단계는?','Selection sort昇順の典型的な1段階は?','["미정렬 최소값을 찾아 앞과 교환","pivot분할","두 배열 merge","Queue사용"]','["未整列最小値を探し先頭と交換","pivot分割","2配列merge","Queue使用"]',0,'미정렬 최소값 선택 후 교환','未整列最小値を選び交換','Selection은 남은 구간에서 최소값을 선택한다.','Selectionは残区間から最小値を選択する。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-13') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'Merge sort의 대표 시간복잡도는?','Merge sortの代表的な時間計算量は?','["O(1)","O(log n)","O(n log n)","O(n²)만"]','["O(1)","O(log n)","O(n log n)","O(n²)のみ"]',2,'O(n log n)','O(n log n)','log n 분할 단계마다 전체 n 규모로 병합한다.','log n段の各段で全体n規模をmergeする。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-13') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'거의 정렬된 작은 배열에서 유리할 수 있는 기본 정렬은?','ほぼ整列済みの小配列で有利な場合がある基本sortは?','["Insertion","항상 Quick","BFS","Hash"]','["Insertion","常にQuick","BFS","Hash"]',0,'Insertion sort','Insertion sort','이미 제자리에 가까우면 이동/비교가 적어질 수 있다.','既に正しい位置に近ければ移動/比較が少なくなり得る。',1,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='A-13') AND type_no=3;
