-- 0050 AP concepts A-14..A-32: computer architecture, system, OS, database
PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES
('A-14','A','컴퓨터구성','コンピュータ構成','CPU 실행시간·CPI','CPU実行時間・CPI','CPU가 프로그램의 명령을 처리하는 데 걸리는 시간을 명령 수, 명령당 평균 클록 수(CPI), 클록 주기로 표현한다.','CPUがプログラムの命令を処理する時間を命令数、1命令当たり平均クロック数(CPI)、クロック周期で表す。','CPU시간=명령수×CPI×클록주기=명령수×CPI/클록주파수이다. 주파수가 높으면 주기는 짧아진다.','CPU時間=命令数×CPI×クロック周期=命令数×CPI/クロック周波数。周波数が高いほど周期は短い。','명령수·CPI·주파수 세 요소를 구분하고 MHz/GHz 단위를 초로 변환한다. 성능비는 실행시간의 역수 관계다.','命令数・CPI・周波数を区別しMHz/GHzを秒へ変換する。性能比は実行時間の逆数関係。','주기=1/주파수부터 구한 뒤 곱한다. 개선 전후 문제는 각 실행시간을 계산하거나 speedup=Told/Tnew를 사용한다.','周期=1/周波数を先に求めて掛ける。改善前後は各実行時間またはspeedup=Told/Tnewを使う。','클록주파수와 클록주기를 같은 방향으로 생각하지 않는다. GHz 숫자만 보고 CPU가 무조건 빠르다고 판단하지 않는다.','クロック周波数と周期は逆関係。GHzだけでCPUが必ず高速とは判断しない。','명령수×CPI=필요 클록 수, 그것을 주파수로 나누면 시간.','命令数×CPI=必要クロック数、それを周波数で割れば時間。','10^9명령, CPI 2, 2GHz라면 실행시간은 1초이다.','10^9命令、CPI 2、2GHzなら実行時間は1秒。',14,1),
('A-15','A','컴퓨터구성','コンピュータ構成','파이프라인','パイプライン','명령 실행을 여러 단계로 나누고 서로 다른 명령의 단계를 겹쳐 처리하여 처리량을 높이는 방식이다.','命令実行を複数段階に分け、異なる命令の段階を重ねて処理しスループットを高める方式。','k단계 파이프라인에서 이상적으로 첫 명령은 k cycle 후 완료되고 이후 매 cycle 한 명령씩 완료된다.','k段pipelineでは理想的に最初の命令はk cycle後、その後は毎cycle 1命令ずつ完了する。','구조 해저드, 데이터 해저드, 제어 해저드를 구분한다. forwarding, stall, branch prediction이 대표 대책이다.','構造hazard、data hazard、control hazardを区別。forwarding、stall、branch predictionが代表対策。','이상적 n개 명령 소요 cycle은 k+n-1. stall이 있으면 정지 cycle을 추가한다.','理想的なn命令の所要cycleはk+n-1。stallがあれば停止cycleを加える。','파이프라인이 한 명령의 latency 자체를 반드시 줄이는 것은 아니다. 분기 명령은 제어 해저드다.','pipelineは1命令のlatency自体を必ず短縮するわけではない。分岐命令はcontrol hazard。','겹쳐서 처리량↑, 의존·자원·분기가 흐름을 막는다.','重ねてthroughput↑、依存・資源・分岐が流れを止める。','5단계에서 10개 명령을 이상적으로 처리하면 14 cycle이다.','5段で10命令なら理想的に14 cycle。',15,1),
('A-16','A','컴퓨터구성','コンピュータ構成','캐시메모리','キャッシュメモリ','CPU와 주기억장치 사이에 자주 사용하는 데이터를 보관해 평균 접근시간을 줄이는 고속 메모리다.','CPUと主記憶の間で頻繁に使うデータを保持し平均アクセス時間を短縮する高速メモリ。','시간적·공간적 지역성을 이용한다. hit면 cache에서, miss면 하위 메모리에서 데이터를 가져온다.','時間的・空間的局所性を利用。hitならcache、missなら下位memoryから取得する。','hit율 h, cache시간 Tc, miss 시 추가 메모리시간 Tm을 문제 정의에 맞게 읽는다. write-through/write-back 차이도 중요하다.','hit率h、cache時間Tc、miss時追加memory時間Tmの定義を読む。write-through/write-backの違いも重要。','문제에서 miss 시간이 전체 miss 처리시간인지 추가시간인지 확인해 평균시간 식을 세운다. 흔한 형태는 Tc+(1-h)Tm이다.','miss時間が全処理時間か追加時間か確認して平均時間式を立てる。代表形はTc+(1-h)Tm。','hit율 90%를 90으로 넣지 말고 0.9로 쓴다. cache와 main memory 시간을 단순 평균하지 않는다.','hit率90%は0.9。cacheとmain memory時間を単純平均しない。','cache=지역성, hit는 빠름, miss penalty가 평균시간을 키움.','cache=局所性、hitは速い、miss penaltyが平均時間を増やす。','Tc=10ns, miss 추가=100ns, hit율 0.9면 평균 20ns이다.','Tc=10ns、miss追加=100ns、hit率0.9なら平均20ns。',16,1),
('A-17','A','컴퓨터구성','コンピュータ構成','RAID','RAID','여러 디스크를 조합해 성능, 용량, 내결함성을 개선하는 저장장치 구성 기술이다.','複数diskを組み合わせ性能・容量・耐障害性を改善する記憶装置構成技術。','RAID0은 striping, RAID1은 mirroring, RAID5는 분산 parity를 사용한다.','RAID0はstriping、RAID1はmirroring、RAID5は分散parityを使う。','RAID0은 내결함성 없음. RAID1 유효용량 약 1/2. RAID5는 최소 3대이며 1대 장애를 견딘다.','RAID0は耐障害性なし。RAID1有効容量約1/2。RAID5は最低3台で1台故障に耐える。','동일 용량 N개라면 RAID0=N×disk, RAID1은 일반적인 2중 mirror에서 절반, RAID5=(N-1)×disk로 계산한다.','同容量N台ならRAID0=N×disk、RAID1は一般的2重mirrorで半分、RAID5=(N-1)×disk。','RAID는 backup 자체가 아니다. RAID0에 parity가 있다고 착각하지 않는다.','RAIDはbackupそのものではない。RAID0にparityがあると誤解しない。','0=속도, 1=거울, 5=한 대 분 parity.','0=速度、1=鏡、5=1台分parity。','2TB 4대로 RAID5를 구성하면 유효용량은 6TB이다.','2TB×4台のRAID5なら有効容量6TB。',17,1),
('A-18','A','시스템','システム','가용성','可用性','시스템이 필요한 때 정상적으로 서비스를 제공할 수 있는 정도다.','必要なときシステムが正常にサービス提供できる度合い。','가용성=MTBF/(MTBF+MTTR). 직렬 구성은 모든 요소가 정상이어야 하고 병렬 이중화는 모두 고장일 때만 전체가 고장난다.','可用性=MTBF/(MTBF+MTTR)。直列は全要素正常が必要、並列冗長は全て故障した時だけ全体故障。','직렬 A=A1×A2..., 독립 병렬 2대 A=1-(1-A1)(1-A2). MTTR이 짧아져도 가용성은 오른다.','直列A=A1×A2...、独立並列2台A=1-(1-A1)(1-A2)。MTTR短縮でも可用性向上。','구성도를 먼저 직렬/병렬 블록으로 나눈 후 계산한다.','構成図を直列/並列blockへ分けてから計算する。','병렬 가용성을 A1+A2로 더하지 않는다. 신뢰도와 가용성의 정의를 혼동하지 않는다.','並列可用性をA1+A2とはしない。信頼性と可用性を混同しない。','직렬=곱, 병렬=1-모두 실패.','直列=積、並列=1-全て失敗。','가용성 0.9 장치 2대 병렬이면 1-0.1²=0.99이다.','可用性0.9の装置2台並列なら1-0.1²=0.99。',18,1),
('A-19','A','시스템','システム','이중화·Failover','冗長化・Failover','장애가 발생해도 서비스를 계속하기 위해 구성요소를 중복하고 정상 장치로 처리를 전환하는 방식이다.','障害時もサービス継続するため構成要素を冗長化し正常系へ処理を切り替える方式。','Active-Standby는 대기계가 인계하고 Active-Active는 여러 계가 평상시에도 처리한다. failover는 장애 전환, failback은 복구 후 원래 구성으로 되돌리는 과정이다.','Active-Standbyは待機系が引継ぎ、Active-Activeは複数系が平常時も処理。failoverは障害切替、failbackは復旧後の戻し。','hot/warm/cold standby의 준비 수준과 복구시간 차이, SPOF 제거, heartbeat와 장애검출을 이해한다.','hot/warm/cold standbyの準備度と復旧時間、SPOF除去、heartbeatによる障害検知を理解する。','요구 RTO와 비용을 보고 대기방식을 판단한다. 즉시 전환 요구면 hot standby가 유리하다.','要求RTOとcostから待機方式を判断。即時切替要求ならhot standbyが有利。','backup과 redundancy를 같은 것으로 보지 않는다. 장비만 이중화하고 공유 전원/회선이 하나면 SPOF가 남을 수 있다.','backupとredundancyは同じではない。装置だけ二重化して共有電源/回線が一つならSPOFが残る。','failover=고장 때 넘김, failback=복구 후 되돌림.','failover=故障時に切替、failback=復旧後に戻す。','주 서버 장애를 heartbeat로 감지해 대기 서버가 VIP를 인계하는 것이 failover 예다.','主server障害をheartbeatで検知し待機serverがVIPを引継ぐのがfailover例。',19,1),
('A-20','A','OS','OS','프로세스·스레드','プロセス・スレッド','프로세스는 실행 중인 프로그램의 자원 단위이고 스레드는 프로세스 안에서 CPU가 실행하는 흐름의 단위다.','processは実行中programの資源単位、threadはprocess内でCPUが実行する流れの単位。','같은 프로세스의 스레드는 code/data/heap 등을 공유하지만 각자 stack과 register 상태를 가진다. 프로세스 간 주소공간은 기본적으로 분리된다.','同一processのthreadはcode/data/heap等を共有するが各自stackとregister状態を持つ。process間address空間は基本的に分離。','thread 전환은 일반적으로 process 전환보다 가볍지만 공유데이터 동기화 문제가 생긴다.','thread切替は一般にprocess切替より軽いが共有data同期問題が生じる。','문제의 자원 공유 대상을 보고 process/thread를 구분한다. race condition이 나오면 lock 등 동기화를 연결한다.','資源共有対象からprocess/threadを区別。race conditionならlock等の同期を結び付ける。','모든 메모리를 thread별로 독립 보유한다고 생각하지 않는다. stack은 보통 thread별이다.','全memoryをthread別に独立保持するわけではない。stackは通常thread別。','process=집, thread=집 안의 작업자; 거실은 공유, 개인 작업 stack은 따로.','process=家、thread=家の作業者。共有領域と個別stack。','두 thread가 같은 counter를 동시에 증가시키면 동기화 없이는 lost update가 생길 수 있다.','2 threadが同じcounterを同時更新すると同期なしではlost updateが起こり得る。',20,1),
('A-21','A','OS','OS','CPU 스케줄링','CPUスケジューリング','준비 상태의 프로세스 중 어느 프로세스에 CPU를 언제 할당할지 결정하는 정책이다.','ready状態のprocessからどれにCPUをいつ割り当てるか決める方針。','FCFS는 도착순, SJF는 짧은 작업 우선, Round Robin은 time quantum만큼 순환, priority는 우선순위에 따라 선택한다.','FCFSは到着順、SJFは短いjob優先、Round Robinはtime quantumで循環、priorityは優先度で選ぶ。','대기시간, turnaround time, response time을 구분한다. RR quantum이 너무 작으면 context switch overhead가 증가한다.','waiting time、turnaround time、response timeを区別。RR quantumが小さすぎるとcontext switch overhead増加。','Gantt chart를 그려 실행 순서를 정한 뒤 completion-arrival로 turnaround, turnaround-burst로 waiting을 계산한다.','Gantt chartで実行順を決め、completion-arrivalでturnaround、turnaround-burstでwaitingを計算。','SJF와 SRTF(선점형)를 혼동하지 않는다. priority 방식은 starvation 가능성이 있고 aging이 대책이다.','SJFとSRTF(プリエンプティブ)を混同しない。priorityはstarvationの可能性、agingが対策。','RR=시간조각, priority starvation→aging.','RR=時間片、priority starvation→aging。','burst 4,3인 두 작업이 동시에 도착해 FCFS P1→P2면 대기시간은 0,4이다.','burst 4,3の2job同時到着でFCFS P1→P2なら待ち時間0,4。',21,1),
('A-22','A','OS','OS','가상메모리·페이징','仮想記憶・ページング','프로그램이 실제 물리메모리보다 큰 연속 주소공간을 사용하는 것처럼 보이게 하고, paging은 이를 고정 크기 page/frame으로 관리한다.','実物理memoryより大きな連続address空間を使えるよう見せ、pagingは固定サイズpage/frameで管理する。','가상주소는 page번호+offset으로 나뉘며 page table이 page를 frame에 매핑한다. TLB는 최근 주소변환을 cache한다.','仮想addressはpage番号+offset、page tableがpageをframeへmapping。TLBは最近のaddress変換をcacheする。','page 크기가 2^k byte면 offset은 k bit. 내부 단편화와 page table 크기 trade-off를 이해한다.','page sizeが2^k byteならoffsetはk bit。内部fragmentationとpage table sizeのtrade-offを理解。','주소를 page size로 나눠 quotient=page번호, remainder=offset으로 계산한다.','addressをpage sizeで割りquotient=page番号、remainder=offset。','page와 frame 크기는 paging에서 같다. segmentation의 가변 크기와 혼동하지 않는다.','pagingではpageとframeサイズは同じ。segmentationの可変長と混同しない。','page=가상, frame=물리, offset은 그대로.','page=仮想、frame=物理、offsetはそのまま。','page 4KB에서 주소 0x2345는 page 2, offset 0x345이다.','page 4KBでaddress 0x2345はpage 2、offset 0x345。',22,1),
('A-23','A','OS','OS','페이지 폴트·스래싱','ページフォールト・スラッシング','page fault는 참조 page가 물리메모리에 없어 disk에서 가져와야 하는 상태이고, thrashing은 page 교체가 지나치게 빈번해 실제 처리보다 paging에 시간을 쓰는 현상이다.','page faultは参照pageが物理memoryになくdiskから読込む状態。thrashingはpage交換が過度に頻発し処理よりpagingに時間を費やす現象。','page fault 시 OS가 빈 frame 또는 victim을 선택해 page를 적재하고 page table을 갱신한다. working set에 비해 frame이 부족하면 thrashing 위험이 커진다.','page fault時OSが空frameまたはvictimを選びpageをloadしpage table更新。working setに対しframe不足でthrashing risk増大。','FIFO, LRU, Optimal 교체 알고리즘의 선택 기준과 page fault 수 추적이 출제된다. FIFO에는 Belady anomaly가 가능하다.','FIFO、LRU、Optimalの選択とpage fault数追跡が出題。FIFOではBelady anomalyが起こり得る。','reference string을 왼쪽부터 따라가며 frame 상태와 hit/fault를 표로 기록한다.','reference stringを左から追いframe状態とhit/faultを表に記録する。','page fault 자체가 오류/프로그램 실패라는 뜻은 아니다. LRU는 가장 오래전에 적재된 것이 아니라 가장 오래 사용되지 않은 page를 교체한다.','page faultはprogram errorではない。LRUは最古loadではなく最長未使用pageを交換。','FIFO=먼저 들어온 것, LRU=오래 안 쓴 것, Optimal=가장 늦게 다시 쓸 것.','FIFO=先入、LRU=最長未使用、Optimal=次回使用が最も遅い。','frame 3개에서 1,2,3,1은 앞 세 번 fault 후 마지막 1은 hit다.','frame 3個で1,2,3,1なら最初3回fault、最後1はhit。',23,1),
('A-24','A','OS','OS','데드락','デッドロック','여러 프로세스가 서로 상대가 가진 자원을 기다려 어느 쪽도 진행하지 못하는 상태다.','複数processが互いに相手の資源を待ち、どれも進行できない状態。','Coffman 4조건은 상호배제, 점유대기, 비선점, 순환대기이며 네 조건이 동시에 성립해야 deadlock 가능성이 생긴다.','Coffmanの4条件は相互排他、保持待ち、非横取り、循環待ちで、全て同時成立するとdeadlock可能性が生じる。','예방은 조건 하나를 깨고, 회피는 unsafe state 진입을 피하며 Bankers algorithm이 대표적이다. 검출·회복 전략도 있다.','予防は条件を一つ崩し、回避はunsafe stateを避けBanker algorithmが代表。検出・回復戦略もある。','resource allocation graph에서 cycle을 찾는다. Banker 문제는 Available과 Need=Max-Allocation을 계산해 safe sequence를 찾는다.','resource allocation graphでcycle確認。BankerではAvailableとNeed=Max-Allocationからsafe sequenceを探す。','cycle이 있으면 자원 인스턴스가 하나인 경우 deadlock이지만 여러 인스턴스에서는 반드시 deadlock이라고 단정할 수 없다.','cycleがあってもresource instance複数なら必ずdeadlockとは限らない。','상·점·비·순 네 조건.','相互排他・保持待ち・非横取り・循環待ちの4条件。','P1이 R1을 잡고 R2를 기다리고 P2가 R2를 잡고 R1을 기다리면 순환대기다.','P1がR1保持しR2待ち、P2がR2保持しR1待ちなら循環待ち。',24,1),
('A-25','A','데이터베이스','データベース','기본키·외래키','主キー・外部キー','기본키는 행을 유일하게 식별하는 속성이고 외래키는 다른 테이블의 후보키/기본키를 참조해 관계를 표현한다.','主キーは行を一意識別する属性、外部キーは他tableの候補キー/主キーを参照し関係を表す。','entity integrity는 기본키가 NULL일 수 없음을, referential integrity는 외래키 값이 참조 대상에 존재하거나 허용된 NULL이어야 함을 뜻한다.','entity integrityは主キーNULL不可、referential integrityは外部キー値が参照先に存在するか許可されたNULLであること。','candidate key, primary key, alternate key, composite key를 구분한다. ON DELETE 동작도 자주 묻는다.','candidate key、primary key、alternate key、composite keyを区別。ON DELETE動作も重要。','테이블의 유일성 조건과 업무 관계를 보고 key를 선택한다. 참조 삭제 문제는 RESTRICT/CASCADE/SET NULL 의미를 확인한다.','一意性条件と業務関係からkeyを選ぶ。参照削除はRESTRICT/CASCADE/SET NULLを確認。','외래키는 반드시 유일할 필요가 없다. 기본키는 한 테이블에 하나지만 여러 열로 구성될 수 있다.','外部キーは一意でなくてよい。主キーは1tableに一つだが複数列で構成可能。','PK=내 행 식별, FK=남의 키 참조.','PK=自分の行識別、FK=他のkey参照。','Orders.customer_id가 Customers.id를 참조하면 customer_id가 외래키다.','Orders.customer_idがCustomers.idを参照するならcustomer_idが外部キー。',25,1),
('A-26','A','데이터베이스','データベース','ER 모델','ERモデル','현실의 업무 대상을 entity, 속성, entity 간 relationship으로 모델링하는 개념적 데이터 설계 방법이다.','現実の業務対象をentity、属性、entity間relationshipでmodelingする概念data設計法。','1:1, 1:N, M:N cardinality와 optional/mandatory participation을 표현한다. M:N은 관계형 DB에서 중간 테이블로 해소하는 것이 일반적이다.','1:1、1:N、M:N cardinalityとoptional/mandatory participationを表現。M:Nは中間tableで解消するのが一般的。','명사에서 entity 후보, 식별자에서 key, 업무 규칙에서 관계와 cardinality를 찾는다.','名詞からentity候補、識別子からkey、業務ruleからrelationship/cardinalityを探す。','요구문장을 읽어 한 A가 여러 B를 가질 수 있는지, B가 여러 A에 속할 수 있는지 양방향으로 확인한다.','要件文からA→BとB→Aの両方向で多重度を確認する。','M:N 관계를 한쪽 FK 하나만으로 직접 표현하려 하지 않는다. 속성과 entity를 혼동하지 않는다.','M:Nを片側FK一つだけで直接表現しない。属性とentityを混同しない。','M:N이면 연결 entity/table을 떠올린다.','M:Nなら連結entity/tableを考える。','학생과 과목이 M:N이면 수강(학생ID,과목ID,성적) 테이블을 둔다.','学生と科目がM:Nなら履修(学生ID,科目ID,成績)tableを置く。',26,1),
('A-27','A','데이터베이스','データベース','정규화','正規化','데이터 중복과 삽입·갱신·삭제 이상을 줄이기 위해 함수 종속을 기준으로 테이블을 분해하는 과정이다.','data重複と挿入・更新・削除異常を減らすため関数従属性に基づきtableを分解する過程。','1NF는 원자값, 2NF는 부분 함수 종속 제거, 3NF는 이행 함수 종속 제거, BCNF는 모든 결정자가 후보키여야 한다.','1NFは原子値、2NFは部分関数従属除去、3NFは推移関数従属除去、BCNFは全決定項が候補キー。','복합키 일부→비키 속성이면 2NF 위반, 비키→비키 종속으로 키→A→B면 3NF 위반을 의심한다.','複合keyの一部→非key属性なら2NF違反、非key→非keyでkey→A→Bなら3NF違反を疑う。','후보키와 함수 종속을 먼저 적고 1NF→2NF→3NF 순으로 위반을 찾는다. 무손실 분해와 종속 보존도 확인한다.','候補keyと関数従属を書き1NF→2NF→3NF順に違反確認。lossless分解と従属保存も見る。','정규화 단계 숫자만 외우지 말고 어떤 종속을 제거하는지 구분한다. surrogate key를 추가했다고 자동으로 정규화되는 것은 아니다.','段階番号だけでなく除去する従属を区別。surrogate key追加だけで自動正規化ではない。','1 원자, 2 부분, 3 이행.','1原子、2部分、3推移。','(학생ID,과목ID)→성적이고 학생ID→학생명이라면 학생명은 부분 종속이므로 별도 학생 테이블로 분리한다.','(学生ID,科目ID)→成績、学生ID→学生名なら学生名は部分従属なので学生tableへ分離。',27,1),
('A-28','A','데이터베이스','データベース','SQL JOIN','SQL JOIN','둘 이상의 테이블을 관련 열 조건으로 결합해 하나의 결과집합으로 조회하는 연산이다.','複数tableを関連列条件で結合し一つの結果集合として取得する演算。','INNER JOIN은 양쪽에 일치하는 행, LEFT JOIN은 왼쪽 모든 행과 일치하는 오른쪽 행을 반환하며 불일치는 NULL로 채운다.','INNER JOINは両側一致行、LEFT JOINは左全行と一致する右行を返し不一致はNULL。','JOIN 조건 누락 시 Cartesian product가 발생한다. OUTER JOIN에서 WHERE 조건 위치에 따라 결과가 INNER처럼 변할 수 있다.','JOIN条件欠落でCartesian product。OUTER JOINではWHERE条件位置によりINNERのようになる場合がある。','작은 표를 직접 그리고 각 왼쪽 행마다 매칭되는 오른쪽 행 수를 세어 결과행을 만든다.','小さい表を書き各左行にmatchingする右行数を数えて結果行を作る。','LEFT JOIN 후 WHERE right.col=값을 쓰면 NULL 행이 제거된다. ON 조건과 WHERE 조건 효과를 구분한다.','LEFT JOIN後WHERE right.col=値ではNULL行が除去される。ONとWHEREの効果を区別。','INNER=교집합, LEFT=왼쪽 보존.','INNER=一致部分、LEFT=左を保存。','고객 3명 중 주문 있는 고객 2명이라도 LEFT JOIN은 주문 없는 고객을 NULL과 함께 남긴다.','顧客3人中注文あり2人でもLEFT JOINは注文なし顧客をNULL付きで残す。',28,1),
('A-29','A','데이터베이스','データベース','GROUP BY·HAVING','GROUP BY・HAVING','GROUP BY는 같은 값을 가진 행을 그룹으로 묶어 집계하고 HAVING은 집계된 그룹에 조건을 적용한다.','GROUP BYは同値行をgroup化して集計し、HAVINGは集計後groupへ条件適用する。','SQL 논리 순서는 FROM/JOIN→WHERE→GROUP BY→HAVING→SELECT→ORDER BY로 이해하면 조건 위치를 판단하기 쉽다.','SQL論理順序をFROM/JOIN→WHERE→GROUP BY→HAVING→SELECT→ORDER BYと考えると条件位置を判断しやすい。','WHERE는 그룹 전 행 필터, HAVING은 그룹 후 필터. COUNT(*), COUNT(col)의 NULL 처리 차이를 안다.','WHEREはgroup前の行filter、HAVINGはgroup後。COUNT(*)とCOUNT(col)のNULL扱いを区別。','원본 행에 WHERE를 먼저 적용하고 그룹을 만든 뒤 SUM/COUNT/AVG를 계산하고 HAVING으로 제거한다.','元行へWHERE適用→group化→SUM/COUNT/AVG→HAVINGで除外。','집계함수 조건을 무조건 WHERE에 두지 않는다. COUNT(col)은 NULL을 세지 않는다.','集約関数条件を無条件にWHEREへ置かない。COUNT(col)はNULLを数えない。','WHERE=묶기 전, HAVING=묶은 후.','WHERE=group前、HAVING=group後。','SELECT dept,COUNT(*) FROM emp GROUP BY dept HAVING COUNT(*)>=3은 직원 3명 이상 부서만 반환한다.','...HAVING COUNT(*)>=3は社員3人以上の部署だけ返す。',29,1),
('A-30','A','데이터베이스','データベース','ACID','ACID','트랜잭션이 신뢰성 있게 처리되기 위해 가져야 하는 원자성, 일관성, 격리성, 지속성의 네 특성이다.','transactionを信頼性高く処理するためのAtomicity、Consistency、Isolation、Durabilityの4特性。','Atomicity는 전부 또는 전무, Consistency는 규칙 보존, Isolation은 동시 transaction 간 간섭 제어, Durability는 commit 결과의 영속성이다.','Atomicityはall-or-nothing、Consistencyは制約維持、Isolationは同時transaction干渉制御、Durabilityはcommit結果の永続性。','rollback은 원자성과 연결되고, log/WAL·복구는 지속성과 밀접하다. 격리수준은 동시성 이상현상과 연결된다.','rollbackはAtomicity、log/WAL・recoveryはDurability、isolation levelは並行実行異常と関連。','사례에서 무엇이 깨졌는지 본다. 일부만 반영→Atomicity, commit 후 소실→Durability, 동시 간섭→Isolation.','事例で何が破られたかを見る。一部だけ反映→Atomicity、commit後消失→Durability、同時干渉→Isolation。','Consistency를 단순히 데이터가 항상 같은 값이라는 뜻으로 해석하지 않는다.','Consistencyをdataが常に同じ値という意味にしない。','A 전부/전무, C 규칙, I 서로 격리, D 커밋 보존.','A全か無、C制約、I隔離、Dcommit保存。','계좌이체에서 출금만 되고 입금이 실패했는데 그대로 남으면 Atomicity 위반이다.','振込で出金だけ成功し入金失敗のままならAtomicity違反。',30,1),
('A-31','A','데이터베이스','データベース','Lock·동시성제어','Lock・同時実行制御','여러 트랜잭션이 같은 데이터를 동시에 읽고 쓸 때 일관성을 지키도록 접근 순서를 제어하는 기술이다.','複数transactionが同じdataを同時read/writeするとき整合性を守るためaccess順を制御する技術。','shared lock은 여러 read가 공존 가능하고 exclusive lock은 write를 위해 다른 충돌 lock을 막는다. 2PL은 lock 획득 단계와 해제 단계를 분리한다.','shared lockは複数read共存可、exclusive lockはwriteのため衝突lockを排除。2PLはlock取得phaseと解放phaseを分ける。','S-S는 호환, S-X와 X-X는 충돌한다. lock 순서가 엇갈리면 deadlock이 발생할 수 있다.','S-Sは互換、S-XとX-Xは衝突。lock取得順が交差するとdeadlockが起こり得る。','transaction별 lock 획득/대기 순서를 시간순으로 표로 그려 blocking과 deadlock을 찾는다.','transaction別lock取得/待ちを時系列表にしてblocking/deadlockを探す。','lock을 많이 잡으면 항상 좋은 것이 아니다. 일관성은 높지만 동시성이 낮아질 수 있다.','lockを多く取れば常に良いわけではない。整合性は上がるが並行性低下。','S=같이 읽기, X=혼자 쓰기.','S=共有read、X=排他write。','T1이 행 X lock을 보유한 동안 T2의 같은 행 update는 기다린다.','T1が行X lock保持中、T2の同一行updateは待機する。',31,1),
('A-32','A','데이터베이스','データベース','Index','インデックス','테이블 전체를 매번 검색하지 않고 특정 열 값을 빠르게 찾도록 별도의 탐색 구조를 유지하는 기능이다.','table全体を毎回scanせず特定列値を高速検索するため別の探索構造を維持する機能。','B-tree/B+tree 계열 index는 검색·범위조건에 널리 쓰이며 index는 조회를 빠르게 하지만 INSERT/UPDATE/DELETE 시 유지비용과 저장공간이 든다.','B-tree/B+tree系indexは検索・範囲条件に広く使われ、参照高速化の代わりに更新costと保存領域が必要。','선택도가 높은 열, 자주 WHERE/JOIN/ORDER에 쓰는 열이 후보. 복합 index는 열 순서와 leftmost prefix가 중요하다.','selectivityが高くWHERE/JOIN/ORDERで頻用する列が候補。複合indexは列順序とleftmost prefixが重要。','쿼리의 조건, 반환 비율, 정렬, 갱신 빈도를 함께 보고 index 효과를 판단한다.','query条件、返却割合、sort、更新頻度を合わせてindex効果を判断する。','index가 있으면 모든 쿼리가 빨라지는 것은 아니다. 작은 테이블/낮은 선택도/대량 조회에서는 full scan이 유리할 수 있다.','indexがあれば全queryが速いわけではない。小table・低selectivity・大量取得ではfull scanが有利な場合もある。','index=책 색인: 찾기는 빠르게, 추가·수정에는 관리비.','index=本の索引。検索は速く、追加・更新には管理cost。','수백만 행에서 유일한 user_id를 자주 검색하면 user_id index의 효과가 크다.','数百万行で一意user_idを頻繁検索するならuser_id index効果が大きい。',32,1);

-- Three representative AP question patterns per concept: calculation/trace, judgment, application.
INSERT OR REPLACE INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,1,'계산·추적형','計算・追跡型',1 FROM ap_concepts WHERE sort_order BETWEEN 14 AND 32;
INSERT OR REPLACE INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,2,'개념·판단형','概念・判断型',2 FROM ap_concepts WHERE sort_order BETWEEN 14 AND 32;
INSERT OR REPLACE INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,3,'응용·함정형','応用・注意型',3 FROM ap_concepts WHERE sort_order BETWEEN 14 AND 32;

-- Helper pattern: two questions per type. Questions are bilingual and explanations state the solving rule.
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'10^9개 명령, CPI=1.5, 3GHz CPU의 실행시간은?','10^9命令、CPI=1.5、3GHz CPUの実行時間は?','["0.25초","0.5초","1.5초","2초"]','["0.25秒","0.5秒","1.5秒","2秒"]',1,'0.5초','0.5秒','10^9×1.5/(3×10^9)=0.5초.','10^9×1.5/(3×10^9)=0.5秒。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-14' AND t.type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,2,'실행시간이 4초에서 2.5초로 줄었다. speedup은?','実行時間が4秒から2.5秒になった。speedupは?','["1.2배","1.4배","1.6배","2.5배"]','["1.2倍","1.4倍","1.6倍","2.5倍"]',2,'1.6배','1.6倍','4/2.5=1.6.','4/2.5=1.6。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-14' AND t.type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'CPU 실행시간을 줄이는 방향으로 옳은 것은?','CPU実行時間を短くする方向として正しいのは?','["CPI 증가","명령수 증가","클록주기 감소","주파수 감소"]','["CPI増加","命令数増加","クロック周期減少","周波数減少"]',2,'클록주기 감소','クロック周期減少','식의 곱 요소가 작아지면 실행시간이 줄어든다.','式の積要素が小さくなると実行時間は短くなる。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-14' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'5단계 pipeline으로 20명령을 stall 없이 처리할 때 cycle 수는?','5段pipelineで20命令をstallなし処理するcycle数は?','["20","24","25","100"]','["20","24","25","100"]',1,'24','24','k+n-1=5+20-1=24.','k+n-1=5+20-1=24。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-15' AND t.type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'분기 결과가 확정될 때까지 다음 명령을 결정하기 어려운 hazard는?','分岐結果確定まで次命令を決めにくいhazardは?','["구조","데이터","제어","메모리"]','["構造","data","control","memory"]',2,'제어 해저드','control hazard','분기·jump는 control hazard의 대표 원인이다.','分岐・jumpはcontrol hazardの代表原因。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-15' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'cache 5ns, miss 시 추가 95ns, hit율 80%의 평균 접근시간은?','cache 5ns、miss追加95ns、hit率80%の平均access時間は?','["19ns","24ns","76ns","81ns"]','["19ns","24ns","76ns","81ns"]',1,'24ns','24ns','5+0.2×95=24ns.','5+0.2×95=24ns。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-16' AND t.type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'최근 사용한 데이터가 다시 사용될 가능성이 높은 성질은?','最近使ったdataが再利用されやすい性質は?','["시간적 지역성","공간적 지역성","배타성","원자성"]','["時間的局所性","空間的局所性","排他性","原子性"]',0,'시간적 지역성','時間的局所性','시간적으로 가까운 시점에 같은 데이터를 재참조하는 성질이다.','時間的に近い時点で同じdataを再参照する性質。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-16' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'4TB disk 5대로 RAID5 구성 시 유효용량은?','4TB disk 5台でRAID5構成時の有効容量は?','["4TB","10TB","16TB","20TB"]','["4TB","10TB","16TB","20TB"]',2,'16TB','16TB','(5-1)×4=16TB.','(5-1)×4=16TB。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-17' AND t.type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'내결함성이 없는 구성은?','耐障害性がない構成は?','["RAID0","RAID1","RAID5","mirroring"]','["RAID0","RAID1","RAID5","mirroring"]',0,'RAID0','RAID0','RAID0은 striping만 하며 redundancy가 없다.','RAID0はstripingのみでredundancyがない。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-17' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'MTBF=990시간, MTTR=10시간이면 가용성은?','MTBF=990時間、MTTR=10時間なら可用性は?','["90%","95%","99%","99.9%"]','["90%","95%","99%","99.9%"]',2,'99%','99%','990/(990+10)=0.99.','990/(990+10)=0.99。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-18' AND t.type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'가용성 0.8 장치 두 대를 독립 병렬로 구성한 가용성은?','可用性0.8の装置2台を独立並列構成した可用性は?','["0.64","0.80","0.96","1.60"]','["0.64","0.80","0.96","1.60"]',2,'0.96','0.96','1-(0.2×0.2)=0.96.','1-(0.2×0.2)=0.96。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-18' AND t.type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'장애 발생 시 대기계로 서비스를 자동 전환하는 것은?','障害時に待機系へserviceを自動切替するのは?','["failover","failback","backup","batch"]','["failover","failback","backup","batch"]',0,'failover','failover','장애 시 정상계로 전환하는 동작이 failover다.','障害時に正常系へ切替える動作がfailover。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-19' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'가장 짧은 RTO를 목표로 대기계를 항상 기동·동기화하는 방식은?','最短RTOを狙い待機系を常時起動・同期する方式は?','["cold standby","hot standby","offline backup","archive"]','["cold standby","hot standby","offline backup","archive"]',1,'hot standby','hot standby','hot standby는 즉시 전환 준비 수준이 가장 높다.','hot standbyは即時切替の準備度が高い。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-19' AND t.type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'같은 process의 thread들이 일반적으로 공유하지 않는 것은?','同一processのthreadが一般に共有しないものは?','["code","heap","전역변수","각 thread의 stack"]','["code","heap","global変数","各threadのstack"]',3,'각 thread의 stack','各threadのstack','stack과 register context는 thread별로 가진다.','stackとregister contextはthreadごとに持つ。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-20' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'두 thread가 공유 변수에 동시 write할 때 필요한 대표 대책은?','2 threadが共有変数へ同時writeするときの代表対策は?','["mutex","DNS","RAID0","paging"]','["mutex","DNS","RAID0","paging"]',0,'mutex','mutex','critical section을 lock으로 보호해 race condition을 막는다.','critical sectionをlockで保護しrace conditionを防ぐ。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-20' AND t.type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'동시 도착한 burst 3,5,2 작업을 비선점 SJF로 실행하는 순서는?','同時到着burst 3,5,2のjobを非preemptive SJFで実行する順は?','["3→5→2","2→3→5","5→3→2","2→5→3"]','["3→5→2","2→3→5","5→3→2","2→5→3"]',1,'2→3→5','2→3→5','SJF는 실행시간이 가장 짧은 작업부터 선택한다.','SJFは実行時間が最短のjobから選ぶ。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-21' AND t.type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'priority scheduling의 starvation 완화 기법은?','priority schedulingのstarvation緩和手法は?','["aging","striping","hashing","paging"]','["aging","striping","hashing","paging"]',0,'aging','aging','오래 기다린 process의 priority를 점차 높인다.','長く待つprocessのpriorityを徐々に上げる。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-21' AND t.type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'page size가 8KB일 때 offset bit 수는?','page sizeが8KBのときoffset bit数は?','["8","10","13","16"]','["8","10","13","16"]',2,'13bit','13bit','8KB=8192=2^13 byte.','8KB=8192=2^13 byte。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-22' AND t.type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'TLB의 주된 목적은?','TLBの主目的は?','["주소변환 고속화","disk mirroring","CPU scheduling","deadlock 검출"]','["address変換高速化","disk mirroring","CPU scheduling","deadlock検出"]',0,'주소변환 고속화','address変換高速化','최근 page table 변환 결과를 cache한다.','最近のpage table変換結果をcacheする。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-22' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'LRU가 교체하는 page는?','LRUが置換するpageは?','["가장 먼저 적재","가장 오래 사용되지 않음","가장 자주 사용","가장 큰 번호"]','["最初にload","最も長く未使用","最頻使用","最大番号"]',1,'가장 오래 사용되지 않은 page','最も長く未使用のpage','LRU는 최근 사용 시점을 기준으로 가장 오래된 참조를 교체한다.','LRUは最終使用時点が最も古いpageを置換。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-23' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'thrashing 완화에 직접적인 방법은?','thrashing緩和に直接有効なのは?','["process에 충분한 frame 할당","quantum을 0으로","RAID0 구성","DNS cache 삭제"]','["processへ十分なframe割当","quantumを0","RAID0構成","DNS cache削除"]',0,'충분한 frame 할당','十分なframe割当','working set을 담을 frame을 확보하면 page fault 폭증을 줄일 수 있다.','working setを保持できるframe確保でpage fault急増を抑える。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-23' AND t.type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'deadlock 필요조건이 아닌 것은?','deadlockの必要条件でないものは?','["상호배제","점유대기","선점 가능","순환대기"]','["相互排他","保持待ち","横取り可能","循環待ち"]',2,'선점 가능','横取り可能','필요조건은 비선점(non-preemption)이다.','必要条件は非横取り(non-preemption)。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-24' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'Banker algorithm이 판단하려는 것은?','Banker algorithmが判断するものは?','["safe state","cache hit","SQL join","RAID parity"]','["safe state","cache hit","SQL join","RAID parity"]',0,'safe state','safe state','자원 할당 후에도 모든 process가 완료 가능한 안전순서가 있는지 본다.','資源割当後も全process完了可能な安全順序があるかを見る。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-24' AND t.type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'기본키에 대한 설명으로 옳은 것은?','主キーの説明として正しいのは?','["NULL 가능","중복 가능","행을 유일 식별","항상 한 열"]','["NULL可","重複可","行を一意識別","必ず1列"]',2,'행을 유일 식별','行を一意識別','기본키는 NULL/중복 없이 행을 식별하며 복합키일 수도 있다.','主キーはNULL/重複なしで行を識別し複合keyも可能。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-25' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'부모 행 삭제 시 자식 행도 자동 삭제하는 FK 동작은?','親行削除時に子行も自動削除するFK動作は?','["CASCADE","RESTRICT","SET DEFAULT","GROUP BY"]','["CASCADE","RESTRICT","SET DEFAULT","GROUP BY"]',0,'CASCADE','CASCADE','ON DELETE CASCADE는 참조 자식 행까지 삭제한다.','ON DELETE CASCADEは参照子行も削除する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-25' AND t.type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'회원 한 명이 여러 주문을 하고 각 주문은 한 회원에 속한다. 관계는?','会員1人が複数注文し各注文は1会員に属する。関係は?','["1:1","1:N","M:N","관계 없음"]','["1:1","1:N","M:N","関係なし"]',1,'1:N','1:N','회원→주문은 하나 대 여러 개다.','会員→注文は1対多。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-26' AND t.type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'M:N 관계를 관계형 DB로 구현할 때 일반적인 방법은?','M:N関係をRDBで実装する一般的方法は?','["중간 테이블","FK 제거","모든 값을 한 셀","PK 제거"]','["中間table","FK削除","全値を1cell","PK削除"]',0,'중간 테이블','中間table','양쪽 key를 참조하는 associative table을 둔다.','両側keyを参照するassociative tableを置く。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-26' AND t.type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'복합키 일부에만 종속되는 비키 속성을 제거하는 단계는?','複合keyの一部だけに従属する非key属性を除去する段階は?','["1NF","2NF","3NF","4NF"]','["1NF","2NF","3NF","4NF"]',1,'2NF','2NF','2NF는 부분 함수 종속을 제거한다.','2NFは部分関数従属を除去する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-27' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'학생ID→학과ID, 학과ID→학과명일 때 학생ID→학과명의 종속은?','学生ID→学科ID、学科ID→学科名のとき学生ID→学科名は?','["부분 종속","이행 종속","다치 종속","종속 없음"]','["部分従属","推移従属","多値従属","従属なし"]',1,'이행 종속','推移従属','key→비키→비키 형태이므로 3NF에서 제거 대상이다.','key→非key→非keyなので3NFで除去対象。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-27' AND t.type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'LEFT JOIN의 왼쪽 행에 일치하는 오른쪽 행이 없으면?','LEFT JOINで左行に一致する右行がない場合は?','["왼쪽 행 삭제","오른쪽 열이 NULL로 남음","오류","Cartesian product"]','["左行削除","右列がNULLで残る","error","Cartesian product"]',1,'오른쪽 열이 NULL로 남음','右列がNULLで残る','LEFT JOIN은 왼쪽 행을 보존한다.','LEFT JOINは左行を保持する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-28' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'JOIN 조건을 빠뜨려 양쪽 모든 행 조합이 생기는 것은?','JOIN条件を忘れ両table全行の組合せになるのは?','["Cartesian product","normalization","rollback","index seek"]','["Cartesian product","normalization","rollback","index seek"]',0,'Cartesian product','Cartesian product','m행과 n행이면 최대 m×n 조합이 생긴다.','m行とn行なら最大m×n組合せ。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-28' AND t.type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'집계 결과 COUNT(*)>=5인 그룹만 남길 때 사용하는 절은?','集計結果COUNT(*)>=5のgroupだけ残す句は?','["WHERE","HAVING","FROM","VALUES"]','["WHERE","HAVING","FROM","VALUES"]',1,'HAVING','HAVING','집계 후 그룹 조건은 HAVING이다.','集計後のgroup条件はHAVING。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-29' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'COUNT(nullable_col)의 특징은?','COUNT(nullable_col)の特徴は?','["NULL도 셈","NULL 제외","항상 1","문자열만 셈"]','["NULLも数える","NULL除外","常に1","文字列のみ"]',1,'NULL 제외','NULL除外','COUNT(column)은 NULL 값을 제외한다.','COUNT(column)はNULL値を除外する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-29' AND t.type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'commit된 데이터가 장애 후에도 보존되어야 한다는 특성은?','commit済dataが障害後も保持される特性は?','["Atomicity","Consistency","Isolation","Durability"]','["Atomicity","Consistency","Isolation","Durability"]',3,'Durability','Durability','commit 결과의 영속성을 뜻한다.','commit結果の永続性。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-30' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'transaction 도중 오류가 나 일부 변경을 모두 취소하는 것은 어떤 특성과 가장 관련 깊은가?','transaction途中errorで一部変更を全て取消すのはどの特性と最も関連する?','["Atomicity","Isolation","Durability","Indexing"]','["Atomicity","Isolation","Durability","Indexing"]',0,'Atomicity','Atomicity','all-or-nothing을 rollback으로 보장한다.','all-or-nothingをrollbackで保証する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-30' AND t.type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'같은 데이터에 대한 lock 호환 조합은?','同じdataに対するlock互換組合せは?','["S-S","S-X","X-S","X-X"]','["S-S","S-X","X-S","X-X"]',0,'S-S','S-S','shared read끼리는 공존할 수 있다.','shared read同士は共存可能。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-31' AND t.type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'T1과 T2가 서로 다른 자원을 X lock한 뒤 상대 자원을 기다린다. 가능한 현상은?','T1とT2が別資源をX lock後、互いの資源を待つ。起こり得るのは?','["deadlock","cache hit","normalization","failover"]','["deadlock","cache hit","normalization","failover"]',0,'deadlock','deadlock','서로 lock 해제를 기다리는 순환대기가 된다.','互いのlock解放を待つ循環待ちになる。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-31' AND t.type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'index의 일반적인 trade-off로 옳은 것은?','indexの一般的trade-offとして正しいのは?','["조회↑ 갱신비용↑","조회↓ 갱신비용↓","저장공간 0","항상 full scan"]','["検索性能↑ 更新cost↑","検索性能↓ 更新cost↓","保存領域0","常にfull scan"]',0,'조회 성능 향상, 갱신 비용 증가','検索性能向上、更新cost増加','index 구조를 유지해야 하므로 write 비용과 공간이 든다.','index構造維持のためwrite costと領域が必要。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-32' AND t.type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,t.id,1,'수백만 행 중 성별처럼 값 종류가 매우 적은 열만 단독 조건으로 대부분의 행을 읽는 경우는?','数百万行で性別のように値種類が少ない列だけを条件に大半行を読む場合は?','["index가 항상 최선","full scan이 유리할 수도 있음","PK가 자동 삭제됨","JOIN 불가"]','["indexが常に最善","full scanが有利な場合もある","PK自動削除","JOIN不可"]',1,'full scan이 유리할 수도 있음','full scanが有利な場合もある','선택도가 낮고 많은 행을 읽으면 index random access 이점이 작다.','selectivityが低く大量行取得ならindex random accessの利点が小さい。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-32' AND t.type_no=3;

-- Ensure every type has at least two questions; generic but concept-specific application questions fill uncovered slots.
INSERT OR IGNORE INTO ap_concept_questions(problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT t.id,2,
 c.title_ko||' 문제를 풀 때 가장 먼저 해야 할 것은?', c.title_ja||'の問題を解くとき最初に行うべきことは?',
 json_array('문제 조건과 단위를 확인한다','공식을 무조건 암기값으로 대입한다','선택지를 읽지 않는다','중간 계산을 생략한다'),
 json_array('問題条件と単位を確認する','公式へ無条件に暗記値を代入する','選択肢を読まない','途中計算を省略する'),0,
 '문제 조건과 단위를 확인한다','問題条件と単位を確認する',
 c.title_ko||'은 정의와 조건을 먼저 식별한 뒤 해당 계산법·판단 규칙을 적용해야 함정을 피할 수 있다.',
 c.title_ja||'は定義と条件を先に識別し、対応する計算法・判断規則を適用するとひっかけを避けられる。',2,2
FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id
WHERE c.sort_order BETWEEN 14 AND 32;
