-- 0051 AP concepts A-33..A-46: network + security
PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES
('A-33','A','네트워크','ネットワーク','OSI·TCP/IP','OSI・TCP/IP','네트워크 통신 기능을 계층으로 나누어 각 계층의 역할과 프로토콜을 이해하는 모델이다.','ネットワーク通信機能を階層化し，各層の役割とプロトコルを理解するモデル。','OSI 7계층과 TCP/IP 계층은 캡슐화와 역캡슐화로 데이터를 전달한다.','OSI 7階層とTCP/IP階層はカプセル化と非カプセル化でデータを伝送する。','L2는 MAC·frame, L3는 IP·packet, L4는 TCP/UDP·port, 상위계층은 HTTP·DNS 등 응용 프로토콜을 다룬다.','L2はMAC・frame，L3はIP・packet，L4はTCP/UDP・port，上位層はHTTP・DNSなどの応用protocolを扱う。','문제에 나온 장비·주소·프로토콜을 어느 계층인지 먼저 분류한다.','機器・address・protocolをまず対応する層へ分類する。','switch를 무조건 L3 장비로 보거나 IP와 port의 역할을 혼동하지 않는다.','switchを常にL3機器とみなしたりIPとportの役割を混同しない。','MAC=L2, IP=L3, port=L4.','MAC=L2、IP=L3、port=L4。','router는 IP 주소를 보고 L3에서 경로를 결정한다.','routerはIP addressを見てL3で経路を決定する。',33,1),
('A-34','A','네트워크','ネットワーク','IPv4·CIDR','IPv4・CIDR','IPv4 주소와 prefix 길이로 네트워크 부분과 host 부분을 표현한다.','IPv4 addressとprefix長でnetwork部とhost部を表す。','/n은 앞 n bit가 network bit이고 나머지 32-n bit가 host bit다.','/nは先頭n bitがnetwork bit，残り32-n bitがhost bit。','host 수는 일반 subnet에서 2^(32-n)-2, mask는 prefix bit를 1로 채워 구한다.','host数は通常2^(32-n)-2，maskはprefix分を1で埋めて求める。','prefix→mask→host bit 순으로 계산한다.','prefix→mask→host bitの順に計算する。','/31·/32 등 특수 용도를 일반 host 공식에 기계적으로 적용하지 않는다.','/31・/32など特殊用途へ通常host公式を機械的に適用しない。','/24=host 8bit=일반적으로 254대.','/24=host 8bit=通常254台。','192.168.10.0/26은 일반 host 62개를 수용한다.','192.168.10.0/26は通常62 hostを収容する。',34,1),
('A-35','A','네트워크','ネットワーク','Subnet','Subnet','하나의 IP 네트워크를 더 작은 네트워크로 분할해 주소를 효율적으로 사용하는 방법이다.','一つのIP networkをより小さいnetworkへ分割しaddressを効率利用する方法。','network address는 host bit가 모두 0, broadcast는 모두 1이다.','network addressはhost bit全0，broadcastは全1。','block size를 구하면 subnet 경계를 빠르게 찾을 수 있다. /26이면 마지막 octet 단위가 64다.','block sizeを求めるとsubnet境界を早く求められる。/26なら最終octetは64刻み。','IP가 속한 block의 시작값과 끝값을 찾고 첫/마지막을 제외해 host 범위를 구한다.','IPが属するblockの開始・終了を求め，先頭/末尾を除きhost範囲を求める。','network/broadcast 주소를 usable host로 세지 않는다.','network/broadcast addressをusable hostへ数えない。','경계 찾기→network→broadcast→host.','境界→network→broadcast→host。','192.168.1.70/26은 64~127 block, network=64, broadcast=127이다.','192.168.1.70/26は64～127 block，network=64，broadcast=127。',35,1),
('A-36','A','네트워크','ネットワーク','TCP·UDP','TCP・UDP','전송계층에서 application 간 데이터를 전달하는 대표 프로토콜이다.','transport層でapplication間のdataを伝送する代表protocol。','TCP는 연결지향·순서보장·재전송·흐름/혼잡제어를 제공하고 UDP는 비연결·경량이다.','TCPはconnection oriented・順序保証・再送・flow/congestion controlを提供し，UDPはconnectionlessで軽量。','TCP 3-way handshake, seq/ack, port 번호와 UDP의 낮은 overhead를 구분한다.','TCP 3-way handshake，seq/ack，port番号とUDPの低overheadを区別する。','신뢰성 요구와 지연/overhead 요구를 보고 선택한다.','信頼性要件と遅延/overhead要件から選択する。','UDP가 항상 더 좋은 것이 아니며 TCP가 application message 경계를 보존한다고 생각하지 않는다.','UDPが常に優れるわけではなくTCPがapplication message境界を保持すると誤解しない。','TCP=신뢰성, UDP=가벼움.','TCP=信頼性，UDP=軽量。','파일전송은 TCP가 일반적이고 실시간 음성은 UDP가 자주 사용된다.','file transferはTCP，real-time音声はUDPがよく使われる。',36,1),
('A-37','A','네트워크','ネットワーク','DNS·DHCP·NAT','DNS・DHCP・NAT','DNS는 이름해석, DHCP는 IP 설정 자동배포, NAT는 주소 변환을 담당한다.','DNSは名前解決，DHCPはIP設定自動配布，NATはaddress変換を行う。','DNS query로 name→IP, DHCP DORA로 설정 수신, NAT/NAPT로 private/public 주소·port를 변환한다.','DNS queryでname→IP，DHCP DORAで設定受信，NAT/NAPTでprivate/public address・portを変換する。','DNS cache/TTL, DHCP lease, NAT table의 의미를 알아야 한다.','DNS cache/TTL，DHCP lease，NAT tableの意味を理解する。','증상에서 이름만 실패하면 DNS, IP 설정 획득 실패면 DHCP를 우선 의심한다.','症状で名前だけ失敗ならDNS，IP設定取得失敗ならDHCPを優先する。','NAT가 암호화를 제공한다고 생각하지 않는다.','NATが暗号化を提供すると誤解しない。','이름=DNS, 배포=DHCP, 변환=NAT.','名前=DNS，配布=DHCP，変換=NAT。','IP로 접속되지만 hostname으로 안 되면 DNS 문제 가능성이 높다.','IPでは接続できhostnameでは不可ならDNS問題の可能性が高い。',37,1),
('A-38','A','네트워크','ネットワーク','Routing','Routing','목적지 IP까지 packet을 전달할 next hop과 interface를 결정하는 과정이다.','宛先IPまでpacketを届けるnext hopとinterfaceを決定する処理。','routing table에서 목적지와 일치하는 경로 중 가장 긴 prefix를 선택한다.','routing tableで宛先に一致する経路のうち最長prefixを選ぶ。','default route는 /0, metric은 동일 prefix 후보의 우선도 판단에 사용될 수 있다.','default routeは/0，metricは同prefix候補の優先度判断に使われる。','각 route의 network 범위를 계산해 destination이 포함되는지 확인하고 longest prefix를 고른다.','各routeのnetwork範囲を確認しdestinationを含む最長prefixを選ぶ。','metric이 작다는 이유로 더 구체적인 prefix보다 먼저 선택한다고 생각하지 않는다.','metricが小さいだけでより具体的なprefixより先に選ぶと誤解しない。','먼저 longest prefix, 그다음 metric.','まずlongest prefix，次にmetric。','10.1.2.5가 /8과 /24 모두 일치하면 /24를 선택한다.','10.1.2.5が/8と/24両方に一致すれば/24を選ぶ。',38,1),
('A-39','A','네트워크','ネットワーク','HTTP·HTTPS·TLS','HTTP・HTTPS・TLS','HTTP는 Web application protocol이고 HTTPS는 HTTP를 TLS로 보호한 통신이다.','HTTPはWeb application protocol，HTTPSはHTTPをTLSで保護した通信。','TLS는 server certificate 검증과 key agreement 후 대칭키로 application data를 암호화한다.','TLSはserver certificate検証とkey agreement後，共通鍵でapplication dataを暗号化する。','HTTP method/status, cookie/session, certificate의 hostname·유효기간·trust chain을 이해한다.','HTTP method/status，cookie/session，certificateのhostname・有効期限・trust chainを理解する。','HTTPS 문제는 인증서 검증과 암호화 대상을 분리해 판단한다.','HTTPS問題はcertificate検証と暗号化対象を分けて判断する。','HTTPS가 server 자체의 취약점을 없애거나 URL의 domain까지 숨기는 것은 아니다.','HTTPSがserver自身の脆弱性を無くしたりURLのdomainまで隠すわけではない。','TLS=상대 확인+키 합의+암호화.','TLS=相手確認+key合意+暗号化。','browser는 인증서의 서명 chain과 hostname을 검증한다.','browserはcertificateの署名chainとhostnameを検証する。',39,1),
('A-40','A','보안','セキュリティ','대칭키·공개키 암호','共通鍵・公開鍵暗号','대칭키는 같은 key로 암복호화하고 공개키 방식은 public/private key pair를 사용한다.','共通鍵は同じkeyで暗復号し，公開鍵方式はpublic/private key pairを使う。','대칭키는 빠른 bulk encryption에, 공개키는 key exchange·signature 등에 적합하다.','共通鍵は高速なbulk encryption，公開鍵はkey exchange・signature等に適する。','기밀성에서는 recipient public key로 암호화하고 recipient private key로 복호화한다.','機密性では受信者public keyで暗号化し受信者private keyで復号する。','누구의 key인지와 목적이 기밀성인지 서명인지 먼저 구분한다.','誰のkeyか，目的が機密性か署名かを先に区別する。','sender private key로 암호화하면 기밀성이 생긴다고 단순화하지 않는다.','sender private keyで暗号化すれば機密性が得られると単純化しない。','기밀성=수신자 공개키, 서명=송신자 개인키.','機密性=受信者public key，署名=送信者private key。','TLS는 공개키 기술로 session key를 합의한 뒤 대칭키로 데이터를 암호화한다.','TLSは公開鍵技術でsession keyを合意後，共通鍵でdataを暗号化する。',40,1),
('A-41','A','보안','セキュリティ','Hash·Salt','Hash・Salt','hash는 입력을 고정길이 digest로 바꾸는 단방향 함수이고 salt는 password hash에 추가하는 random value다.','hashは入力を固定長digestへ変える一方向関数，saltはpassword hashへ加えるrandom value。','암호학적 hash는 preimage resistance와 collision resistance가 중요하다. salt는 동일 password의 동일 hash를 방지한다.','暗号学的hashはpreimage resistanceとcollision resistanceが重要。saltは同じpasswordの同一hash化を防ぐ。','password 저장은 plain text나 빠른 일반 hash보다 salt+password KDF를 사용한다.','password保存はplain textや高速一般hashよりsalt+password KDFを使う。','무결성 검증인지 password 보호인지 목적을 구분한다.','完全性検証かpassword保護か目的を区別する。','hash는 encryption이 아니므로 복호화 key가 없다. salt는 비밀일 필요가 없지만 user마다 달라야 한다.','hashはencryptionではなく復号keyがない。saltは秘密でなくてもよいがuserごとに異なるべき。','hash=요약, salt=같은 암호도 다르게.','hash=要約，salt=同じpasswordも異なる値へ。','두 사용자가 같은 password여도 salt가 다르면 저장 hash가 달라진다.','同じpasswordでもsaltが異なれば保存hashは異なる。',41,1),
('A-42','A','보안','セキュリティ','전자서명·PKI','電子署名・PKI','전자서명은 message의 무결성·송신자 인증·부인방지를 지원하고 PKI는 공개키와 신원을 certificate로 연결한다.','電子署名はmessageの完全性・送信者認証・否認防止を支援し，PKIは公開鍵と身元をcertificateで結ぶ。','sender가 digest에 private key로 signature를 만들고 receiver는 sender public key로 검증한다.','senderがdigestへprivate keyでsignatureを作り，receiverはsender public keyで検証する。','CA, certificate, CRL/OCSP, trust chain의 역할을 구분한다.','CA，certificate，CRL/OCSP，trust chainの役割を区別する。','서명 검증은 certificate의 신뢰성과 유효성까지 포함해 판단한다.','署名検証はcertificateの信頼性と有効性まで含めて判断する。','전자서명 자체는 message 기밀성을 제공하지 않는다.','電子署名自体はmessageの機密性を提供しない。','서명=개인키로 만들고 공개키로 확인.','署名=private keyで作りpublic keyで確認。','software 배포파일에 서명을 검증하면 변조 여부와 배포자를 확인할 수 있다.','software配布fileの署名検証で改ざんと配布者を確認できる。',42,1),
('A-43','A','보안','セキュリティ','MFA·접근제어','MFA・アクセス制御','MFA는 서로 다른 인증요소를 조합하고 접근제어는 인증된 주체의 허용행위를 제한한다.','MFAは異なる認証要素を組み合わせ，access controlは認証済み主体の許可行為を制限する。','knowledge·possession·inherence 중 서로 다른 요소를 2개 이상 사용해야 MFA다. least privilege와 RBAC가 핵심이다.','knowledge・possession・inherenceの異なる要素を2つ以上使うとMFA。least privilegeとRBACが重要。','password+PIN은 같은 knowledge 요소라 MFA가 아니다. 권한은 업무 role에 필요한 최소 범위로 준다.','password+PINは同じknowledge要素でMFAではない。権限はroleに必要な最小範囲にする。','인증요소 종류와 권한범위를 따로 판단한다.','認証要素の種類と権限範囲を別々に判断する。','2단계 절차가 모두 같은 요소면 MFA라고 할 수 없다.','2段階でも同じ要素だけならMFAとはいえない。','알고있음·가지고있음·몸 자체 중 다른 종류를 조합.','知識・所持・生体の異なる種類を組合せる。','password+smartphone OTP는 knowledge+possession이라 MFA다.','password+smartphone OTPはknowledge+possessionでMFA。',43,1),
('A-44','A','보안','セキュリティ','SQL Injection','SQL Injection','외부 입력이 SQL 구조의 일부로 해석되게 만들어 의도하지 않은 query를 실행시키는 공격이다.','外部入力をSQL構造の一部として解釈させ意図しないqueryを実行する攻撃。','문자열 이어붙이기로 query를 만들 때 위험하며 parameterized query로 구조와 값을 분리한다.','文字列連結でqueryを作ると危険で，parameterized queryで構造と値を分離する。','prepared statement, 최소 DB 권한, 입력검증을 함께 사용한다.','prepared statement，最小DB権限，入力検証を併用する。','code에서 SQL 문자열 연결 여부와 bind parameter 사용 여부를 확인한다.','codeでSQL文字列連結とbind parameter使用有無を確認する。','escape만으로 모든 경우를 해결하거나 client-side validation만 믿지 않는다.','escapeだけで全て解決したりclient-side validationだけを信頼しない。','SQL 구조와 값을 분리=parameter binding.','SQL構造と値を分離=parameter binding。','WHERE id = ? 형태에 값을 bind하면 입력이 SQL 문법으로 해석되지 않는다.','WHERE id = ?へ値をbindすれば入力はSQL文法として解釈されない。',44,1),
('A-45','A','보안','セキュリティ','XSS·CSRF','XSS・CSRF','XSS는 browser에서 공격 script를 실행시키고 CSRF는 로그인된 사용자의 인증상태를 악용해 원치 않는 요청을 보낸다.','XSSはbrowserで攻撃scriptを実行し，CSRFはlogin済みuserの認証状態を悪用し意図しないrequestを送る。','XSS는 output encoding·CSP, CSRF는 anti-CSRF token·SameSite cookie 등이 핵심 대책이다.','XSSはoutput encoding・CSP，CSRFはanti-CSRF token・SameSite cookie等が主要対策。','stored/reflected/DOM XSS와 CSRF의 공격조건을 구분한다.','stored/reflected/DOM XSSとCSRFの攻撃条件を区別する。','script 실행이면 XSS, 사용자 권한으로 요청 강제면 CSRF를 우선 의심한다.','script実行ならXSS，user権限でrequest強制ならCSRFを疑う。','CSRF 대책으로 단순 HTML escaping을 선택하거나 XSS 대책으로 CSRF token만 고르지 않는다.','CSRF対策に単純HTML escaping，XSS対策にCSRF tokenだけを選ばない。','XSS=스크립트, CSRF=요청 위조.','XSS=script，CSRF=request偽造。','게시판 입력이 다른 user browser에서 script로 실행되면 stored XSS다.','掲示板入力が他user browserでscript実行されればstored XSS。',45,1),
('A-46','A','보안','セキュリティ','FW·WAF·IDS·IPS','FW・WAF・IDS・IPS','network와 Web traffic을 통제·탐지·차단하는 보안장비/기능이다.','networkとWeb trafficを制御・検知・遮断するsecurity機能。','FW는 IP/port 중심, WAF는 HTTP application 공격, IDS는 탐지, IPS는 inline 차단이 핵심이다.','FWはIP/port中心，WAFはHTTP application攻撃，IDSは検知，IPSはinline遮断が中心。','배치위치와 분석계층, 탐지 후 행동을 구분한다.','配置位置，分析layer，検知後の動作を区別する。','공격이 SQLi/XSS면 WAF, network rule이면 FW, 단순 경보면 IDS, 자동차단이면 IPS를 우선 연결한다.','SQLi/XSSならWAF，network ruleならFW，alert中心ならIDS，自動遮断ならIPSを対応させる。','어떤 장비도 모든 공격을 막는다고 보지 않는다. 암호화 traffic은 가시성 문제가 있을 수 있다.','どの装置も全攻撃を防ぐわけではない。暗号化trafficでは可視性問題がある。','FW=문, WAF=웹, IDS=알림, IPS=차단.','FW=門，WAF=Web，IDS=通知，IPS=遮断。','Web server 앞 WAF는 SQLi pattern을 탐지해 request를 차단할 수 있다.','Web server前のWAFはSQLi patternを検知しrequestを遮断できる。',46,1);

-- Three AP-relevant problem patterns per concept.
INSERT OR REPLACE INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,1,CASE concept_code
 WHEN 'A-33' THEN '계층·프로토콜 대응' WHEN 'A-34' THEN 'prefix·mask 계산' WHEN 'A-35' THEN 'network·broadcast 계산' WHEN 'A-36' THEN 'TCP/UDP 특성판단' WHEN 'A-37' THEN 'DNS·DHCP·NAT 역할판단' WHEN 'A-38' THEN 'routing table 추적' WHEN 'A-39' THEN 'TLS·인증서 흐름' WHEN 'A-40' THEN '키 사용방향' WHEN 'A-41' THEN 'hash·salt 판단' WHEN 'A-42' THEN '서명·인증서 검증' WHEN 'A-43' THEN '인증요소·MFA 판별' WHEN 'A-44' THEN '취약 code 판별' WHEN 'A-45' THEN 'XSS·CSRF 구분' WHEN 'A-46' THEN '보안장비 역할대응' END,
CASE concept_code
 WHEN 'A-33' THEN '階層・protocol対応' WHEN 'A-34' THEN 'prefix・mask計算' WHEN 'A-35' THEN 'network・broadcast計算' WHEN 'A-36' THEN 'TCP/UDP特性判断' WHEN 'A-37' THEN 'DNS・DHCP・NAT役割判断' WHEN 'A-38' THEN 'routing table追跡' WHEN 'A-39' THEN 'TLS・certificate流れ' WHEN 'A-40' THEN 'key使用方向' WHEN 'A-41' THEN 'hash・salt判断' WHEN 'A-42' THEN '署名・certificate検証' WHEN 'A-43' THEN '認証要素・MFA判定' WHEN 'A-44' THEN '脆弱code判定' WHEN 'A-45' THEN 'XSS・CSRF区別' WHEN 'A-46' THEN 'security機器役割対応' END,1
FROM ap_concepts WHERE sort_order BETWEEN 33 AND 46;
INSERT OR REPLACE INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,2,CASE concept_code
 WHEN 'A-33' THEN '주소·장비 계층판단' WHEN 'A-34' THEN 'host 수·주소범위' WHEN 'A-35' THEN 'subnet 소속판단' WHEN 'A-36' THEN 'handshake·신뢰성' WHEN 'A-37' THEN '장애원인 추적' WHEN 'A-38' THEN 'longest prefix' WHEN 'A-39' THEN 'HTTPS 보안속성' WHEN 'A-40' THEN '대칭·공개키 선택' WHEN 'A-41' THEN '무결성·password 저장' WHEN 'A-42' THEN 'PKI·CA·폐기확인' WHEN 'A-43' THEN 'least privilege·RBAC' WHEN 'A-44' THEN 'parameter binding' WHEN 'A-45' THEN '대책 선택' WHEN 'A-46' THEN '배치·탐지·차단' END,
CASE concept_code
 WHEN 'A-33' THEN 'address・機器layer判断' WHEN 'A-34' THEN 'host数・address範囲' WHEN 'A-35' THEN 'subnet所属判断' WHEN 'A-36' THEN 'handshake・信頼性' WHEN 'A-37' THEN '障害原因追跡' WHEN 'A-38' THEN 'longest prefix' WHEN 'A-39' THEN 'HTTPS security属性' WHEN 'A-40' THEN '共通鍵・公開鍵選択' WHEN 'A-41' THEN '完全性・password保存' WHEN 'A-42' THEN 'PKI・CA・失効確認' WHEN 'A-43' THEN 'least privilege・RBAC' WHEN 'A-44' THEN 'parameter binding' WHEN 'A-45' THEN '対策選択' WHEN 'A-46' THEN '配置・検知・遮断' END,2
FROM ap_concepts WHERE sort_order BETWEEN 33 AND 46;
INSERT OR REPLACE INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,3,CASE concept_code
 WHEN 'A-33' THEN '캡슐화·통신흐름' WHEN 'A-34' THEN 'CIDR 응용' WHEN 'A-35' THEN 'subnet 설계' WHEN 'A-36' THEN '용도별 protocol 선택' WHEN 'A-37' THEN 'cache·lease·translation 응용' WHEN 'A-38' THEN 'default·metric 응용' WHEN 'A-39' THEN '인증서 오류분석' WHEN 'A-40' THEN 'hybrid 암호 응용' WHEN 'A-41' THEN '공격·방어 응용' WHEN 'A-42' THEN '서명과 기밀성 비교' WHEN 'A-43' THEN '권한설계 시나리오' WHEN 'A-44' THEN '공격·방어 시나리오' WHEN 'A-45' THEN 'Web 공격 시나리오' WHEN 'A-46' THEN '다계층 방어설계' END,
CASE concept_code
 WHEN 'A-33' THEN 'カプセル化・通信flow' WHEN 'A-34' THEN 'CIDR応用' WHEN 'A-35' THEN 'subnet設計' WHEN 'A-36' THEN '用途別protocol選択' WHEN 'A-37' THEN 'cache・lease・translation応用' WHEN 'A-38' THEN 'default・metric応用' WHEN 'A-39' THEN 'certificate error分析' WHEN 'A-40' THEN 'hybrid暗号応用' WHEN 'A-41' THEN '攻撃・防御応用' WHEN 'A-42' THEN '署名と機密性比較' WHEN 'A-43' THEN '権限設計scenario' WHEN 'A-44' THEN '攻撃・防御scenario' WHEN 'A-45' THEN 'Web攻撃scenario' WHEN 'A-46' THEN '多層防御設計' END,3
FROM ap_concepts WHERE sort_order BETWEEN 33 AND 46;

-- One strong question for every type; 0052 adds a second question per type.
INSERT OR REPLACE INTO ap_concept_questions(problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT t.id,1,
CASE c.concept_code||'-'||t.type_no
 WHEN 'A-33-1' THEN 'IP 주소를 이용해 경로를 결정하는 계층은?' WHEN 'A-33-2' THEN 'MAC 주소를 주로 사용하는 계층은?' WHEN 'A-33-3' THEN '송신 시 application data에 TCP header와 IP header가 순차적으로 붙는 과정을 무엇이라 하는가?'
 WHEN 'A-34-1' THEN '/26의 subnet mask는?' WHEN 'A-34-2' THEN '/27 network의 일반 usable host 수는?' WHEN 'A-34-3' THEN '10.0.0.0/24를 동일 크기 4개 subnet으로 나눌 때 새 prefix는?'
 WHEN 'A-35-1' THEN '192.168.1.70/26의 network address는?' WHEN 'A-35-2' THEN '192.168.1.130/26의 broadcast address는?' WHEN 'A-35-3' THEN '최소 50 host가 필요한 subnet에 적절한 prefix는?'
 WHEN 'A-36-1' THEN '순서보장과 재전송을 기본 제공하는 protocol은?' WHEN 'A-36-2' THEN 'TCP 연결설정의 기본 절차는?' WHEN 'A-36-3' THEN '지연을 줄이고 일부 packet 손실을 application이 허용하는 실시간 음성에 일반적으로 적합한 것은?'
 WHEN 'A-37-1' THEN 'hostname을 IP로 변환하는 기능은?' WHEN 'A-37-2' THEN 'PC가 자동으로 IP·gateway·DNS 정보를 받지 못한다. 우선 확인할 service는?' WHEN 'A-37-3' THEN '여러 private host가 하나의 public IP를 port까지 이용해 공유하는 방식은?'
 WHEN 'A-38-1' THEN '10.1.2.3에 /8과 /24 route가 모두 일치할 때 선택되는 것은?' WHEN 'A-38-2' THEN 'default route의 prefix는?' WHEN 'A-38-3' THEN '동일 prefix 경로가 여러 개일 때 protocol에 따라 우선도 비교에 쓰이는 값은?'
 WHEN 'A-39-1' THEN 'HTTPS에서 server 신원확인에 사용하는 것은?' WHEN 'A-39-2' THEN 'TLS가 application data 암호화에 주로 사용하는 것은?' WHEN 'A-39-3' THEN 'certificate의 hostname과 접속 hostname이 다르면 browser가 경고하는 주된 이유는?'
 WHEN 'A-40-1' THEN '수신자만 읽게 하려면 공개키 방식에서 어떤 key로 암호화하는가?' WHEN 'A-40-2' THEN '대용량 data 암호화에 일반적으로 더 빠른 방식은?' WHEN 'A-40-3' THEN 'TLS가 공개키와 대칭키를 함께 쓰는 주된 이유는?'
 WHEN 'A-41-1' THEN '같은 password라도 user마다 다른 저장값이 되게 추가하는 값은?' WHEN 'A-41-2' THEN 'file 변조 여부를 비교할 때 적합한 기술은?' WHEN 'A-41-3' THEN 'salt가 rainbow table 공격을 어렵게 하는 이유는?'
 WHEN 'A-42-1' THEN '전자서명 생성에 사용하는 key는?' WHEN 'A-42-2' THEN 'certificate를 발급해 public key와 신원을 연결하는 주체는?' WHEN 'A-42-3' THEN '전자서명만으로 보장되지 않는 속성은?'
 WHEN 'A-43-1' THEN 'password+smartphone OTP는 MFA인가?' WHEN 'A-43-2' THEN '업무에 필요한 최소 권한만 부여하는 원칙은?' WHEN 'A-43-3' THEN '직무별 role에 권한을 묶어 user에게 role을 부여하는 방식은?'
 WHEN 'A-44-1' THEN '사용자 입력을 SQL 문자열에 직접 이어붙이는 code의 대표 취약점은?' WHEN 'A-44-2' THEN 'SQL injection의 가장 기본적인 code 대책은?' WHEN 'A-44-3' THEN 'DB 계정에 최소 권한을 주는 것이 SQL injection 피해를 줄이는 이유는?'
 WHEN 'A-45-1' THEN '게시글에 삽입한 script가 다른 사용자 browser에서 실행되면?' WHEN 'A-45-2' THEN 'CSRF의 대표 대책은?' WHEN 'A-45-3' THEN '로그인 user가 악성 site 방문만으로 송금 request를 보내게 됐다. 어떤 공격인가?'
 WHEN 'A-46-1' THEN 'HTTP request의 SQLi/XSS pattern을 분석하는 장비는?' WHEN 'A-46-2' THEN '공격을 탐지해 alert하지만 일반적으로 inline 차단이 주목적이 아닌 것은?' WHEN 'A-46-3' THEN 'IP/port filtering과 Web 공격 차단을 함께 강화하려면 어떤 조합이 자연스러운가?' END,
CASE c.concept_code||'-'||t.type_no
 WHEN 'A-33-1' THEN 'IP addressで経路を決定するlayerは?' WHEN 'A-33-2' THEN 'MAC addressを主に使うlayerは?' WHEN 'A-33-3' THEN '送信時application dataへTCP header，IP headerが順に付加される処理は?'
 WHEN 'A-34-1' THEN '/26のsubnet maskは?' WHEN 'A-34-2' THEN '/27 networkの通常usable host数は?' WHEN 'A-34-3' THEN '10.0.0.0/24を同じ大きさ4 subnetへ分割する新prefixは?'
 WHEN 'A-35-1' THEN '192.168.1.70/26のnetwork addressは?' WHEN 'A-35-2' THEN '192.168.1.130/26のbroadcast addressは?' WHEN 'A-35-3' THEN '最低50 hostに必要な適切なprefixは?'
 WHEN 'A-36-1' THEN '順序保証と再送を標準提供するprotocolは?' WHEN 'A-36-2' THEN 'TCP connection確立の基本手順は?' WHEN 'A-36-3' THEN '低遅延を優先し一部lossを許容するreal-time音声に一般的に適するのは?'
 WHEN 'A-37-1' THEN 'hostnameをIPへ変換する機能は?' WHEN 'A-37-2' THEN 'PCがIP・gateway・DNSを自動取得できない。まず確認するserviceは?' WHEN 'A-37-3' THEN '複数private hostが一つのpublic IPをportまで使って共有する方式は?'
 WHEN 'A-38-1' THEN '10.1.2.3に/8と/24 routeが一致するとき選ぶのは?' WHEN 'A-38-2' THEN 'default routeのprefixは?' WHEN 'A-38-3' THEN '同一prefix経路が複数ある時，protocolにより優先比較へ使う値は?'
 WHEN 'A-39-1' THEN 'HTTPSでserver身元確認に使うものは?' WHEN 'A-39-2' THEN 'TLSがapplication data暗号化へ主に使うものは?' WHEN 'A-39-3' THEN 'certificate hostnameと接続hostnameが違うとbrowserが警告する主因は?'
 WHEN 'A-40-1' THEN '受信者だけ読めるよう公開鍵方式で暗号化するkeyは?' WHEN 'A-40-2' THEN '大量data暗号化に一般に高速な方式は?' WHEN 'A-40-3' THEN 'TLSが公開鍵と共通鍵を併用する主な理由は?'
 WHEN 'A-41-1' THEN '同じpasswordでもuserごとに異なる保存値にする追加値は?' WHEN 'A-41-2' THEN 'file改ざん確認に適する技術は?' WHEN 'A-41-3' THEN 'saltがrainbow table攻撃を難しくする理由は?'
 WHEN 'A-42-1' THEN '電子署名生成に使うkeyは?' WHEN 'A-42-2' THEN 'certificateを発行しpublic keyと身元を結ぶ主体は?' WHEN 'A-42-3' THEN '電子署名だけでは保証されない属性は?'
 WHEN 'A-43-1' THEN 'password+smartphone OTPはMFAか?' WHEN 'A-43-2' THEN '業務に必要な最小権限だけ与える原則は?' WHEN 'A-43-3' THEN '職務roleに権限をまとめuserへroleを付与する方式は?'
 WHEN 'A-44-1' THEN 'user入力をSQL文字列へ直接連結するcodeの代表的脆弱性は?' WHEN 'A-44-2' THEN 'SQL injectionの基本的なcode対策は?' WHEN 'A-44-3' THEN 'DB accountの最小権限がSQL injection被害を減らす理由は?'
 WHEN 'A-45-1' THEN '掲示板へ入れたscriptが他user browserで実行された。何攻撃?' WHEN 'A-45-2' THEN 'CSRFの代表対策は?' WHEN 'A-45-3' THEN 'login userが悪性site訪問だけで送金requestを送らされた。何攻撃?'
 WHEN 'A-46-1' THEN 'HTTP requestのSQLi/XSS patternを分析する装置は?' WHEN 'A-46-2' THEN '攻撃を検知しalertするがinline遮断が主目的でないものは?' WHEN 'A-46-3' THEN 'IP/port filteringとWeb攻撃遮断を共に強化する自然な組合せは?' END,
NULL,NULL,NULL,
CASE c.concept_code||'-'||t.type_no
 WHEN 'A-33-1' THEN '네트워크 계층(L3)' WHEN 'A-33-2' THEN '데이터링크 계층(L2)' WHEN 'A-33-3' THEN '캡슐화' WHEN 'A-34-1' THEN '255.255.255.192' WHEN 'A-34-2' THEN '30' WHEN 'A-34-3' THEN '/26' WHEN 'A-35-1' THEN '192.168.1.64' WHEN 'A-35-2' THEN '192.168.1.191' WHEN 'A-35-3' THEN '/26' WHEN 'A-36-1' THEN 'TCP' WHEN 'A-36-2' THEN 'SYN→SYN/ACK→ACK' WHEN 'A-36-3' THEN 'UDP' WHEN 'A-37-1' THEN 'DNS' WHEN 'A-37-2' THEN 'DHCP' WHEN 'A-37-3' THEN 'NAPT' WHEN 'A-38-1' THEN '/24 route' WHEN 'A-38-2' THEN '/0' WHEN 'A-38-3' THEN 'metric' WHEN 'A-39-1' THEN 'server certificate' WHEN 'A-39-2' THEN 'session 대칭키' WHEN 'A-39-3' THEN '접속 대상의 신원과 certificate가 일치하지 않기 때문' WHEN 'A-40-1' THEN '수신자의 공개키' WHEN 'A-40-2' THEN '대칭키 암호' WHEN 'A-40-3' THEN '공개키로 안전하게 key를 합의하고 빠른 대칭키로 data를 처리하기 위해' WHEN 'A-41-1' THEN 'salt' WHEN 'A-41-2' THEN 'hash' WHEN 'A-41-3' THEN '같은 password도 salt별로 다른 hash가 되어 사전계산표 재사용이 어려워지기 때문' WHEN 'A-42-1' THEN '송신자의 개인키' WHEN 'A-42-2' THEN 'CA' WHEN 'A-42-3' THEN '기밀성' WHEN 'A-43-1' THEN '예' WHEN 'A-43-2' THEN '최소권한 원칙' WHEN 'A-43-3' THEN 'RBAC' WHEN 'A-44-1' THEN 'SQL Injection' WHEN 'A-44-2' THEN 'prepared statement/parameter binding' WHEN 'A-44-3' THEN '공격 query가 실행돼도 수행 가능한 작업 범위를 제한하기 때문' WHEN 'A-45-1' THEN 'Stored XSS' WHEN 'A-45-2' THEN 'anti-CSRF token 또는 SameSite cookie' WHEN 'A-45-3' THEN 'CSRF' WHEN 'A-46-1' THEN 'WAF' WHEN 'A-46-2' THEN 'IDS' WHEN 'A-46-3' THEN 'FW + WAF' END,
CASE c.concept_code||'-'||t.type_no
 WHEN 'A-33-1' THEN 'network層(L3)' WHEN 'A-33-2' THEN 'data link層(L2)' WHEN 'A-33-3' THEN 'カプセル化' WHEN 'A-34-1' THEN '255.255.255.192' WHEN 'A-34-2' THEN '30' WHEN 'A-34-3' THEN '/26' WHEN 'A-35-1' THEN '192.168.1.64' WHEN 'A-35-2' THEN '192.168.1.191' WHEN 'A-35-3' THEN '/26' WHEN 'A-36-1' THEN 'TCP' WHEN 'A-36-2' THEN 'SYN→SYN/ACK→ACK' WHEN 'A-36-3' THEN 'UDP' WHEN 'A-37-1' THEN 'DNS' WHEN 'A-37-2' THEN 'DHCP' WHEN 'A-37-3' THEN 'NAPT' WHEN 'A-38-1' THEN '/24 route' WHEN 'A-38-2' THEN '/0' WHEN 'A-38-3' THEN 'metric' WHEN 'A-39-1' THEN 'server certificate' WHEN 'A-39-2' THEN 'session共通鍵' WHEN 'A-39-3' THEN '接続先の身元とcertificateが一致しないため' WHEN 'A-40-1' THEN '受信者の公開鍵' WHEN 'A-40-2' THEN '共通鍵暗号' WHEN 'A-40-3' THEN '公開鍵で安全にkeyを合意し高速な共通鍵でdata処理するため' WHEN 'A-41-1' THEN 'salt' WHEN 'A-41-2' THEN 'hash' WHEN 'A-41-3' THEN '同じpasswordでもsaltごとにhashが異なり事前計算表を再利用しにくいため' WHEN 'A-42-1' THEN '送信者のprivate key' WHEN 'A-42-2' THEN 'CA' WHEN 'A-42-3' THEN '機密性' WHEN 'A-43-1' THEN 'はい' WHEN 'A-43-2' THEN '最小権限原則' WHEN 'A-43-3' THEN 'RBAC' WHEN 'A-44-1' THEN 'SQL Injection' WHEN 'A-44-2' THEN 'prepared statement/parameter binding' WHEN 'A-44-3' THEN '攻撃queryが実行されても可能な操作範囲を制限できるため' WHEN 'A-45-1' THEN 'Stored XSS' WHEN 'A-45-2' THEN 'anti-CSRF tokenまたはSameSite cookie' WHEN 'A-45-3' THEN 'CSRF' WHEN 'A-46-1' THEN 'WAF' WHEN 'A-46-2' THEN 'IDS' WHEN 'A-46-3' THEN 'FW + WAF' END,
CASE c.concept_code||'-'||t.type_no
 WHEN 'A-34-1' THEN '/26은 마지막 octet의 상위 2bit가 network라 11000000₂=192다.' WHEN 'A-34-2' THEN 'host bit 5개이므로 2^5-2=30이다.' WHEN 'A-34-3' THEN '4개 subnet에는 2bit를 더 빌려 /24→/26이 된다.' WHEN 'A-35-1' THEN '/26 block size 64이므로 70은 64~127에 속한다.' WHEN 'A-35-2' THEN '130은 128~191 block에 속해 broadcast는 191이다.' WHEN 'A-35-3' THEN '/27은 30 host로 부족하고 /26은 62 host라 충족한다.' ELSE '핵심 정의와 역할을 연결해 판단한다.' END,
CASE c.concept_code||'-'||t.type_no
 WHEN 'A-34-1' THEN '/26は最終octet上位2bitがnetworkで11000000₂=192。' WHEN 'A-34-2' THEN 'host bitは5なので2^5-2=30。' WHEN 'A-34-3' THEN '4 subnetには2bit追加で必要なので/24→/26。' WHEN 'A-35-1' THEN '/26のblock sizeは64，70は64～127に属する。' WHEN 'A-35-2' THEN '130は128～191 blockに属しbroadcastは191。' WHEN 'A-35-3' THEN '/27は30 hostで不足，/26は62 hostで要件を満たす。' ELSE '基本定義と役割を対応させて判断する。' END,
2,t.type_no
FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.sort_order BETWEEN 33 AND 46;
