-- 0052 AP concepts A-47..A-68: development, PM, service, audit, strategy, accounting/legal
PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES
('A-47','A','시스템개발','システム開発','Waterfall·Agile','Waterfall・Agile','Waterfall은 공정을 순차 진행하고 Agile은 짧은 반복으로 가치와 feedback을 빠르게 반영한다.','Waterfallは工程を順次進め，Agileは短い反復で価値とfeedbackを素早く反映する。','요구 변화 가능성, release 빈도, 고객 참여 수준에 따라 적합성이 달라진다.','要件変更可能性，release頻度，顧客参加度により適性が変わる。','Waterfall=단계별 산출물·변경비용 증가, Agile=iteration·backlog·increment.','Waterfall=工程別成果物・変更cost増，Agile=iteration・backlog・increment。','문제의 변경 빈도와 feedback 요구를 먼저 본다.','変更頻度とfeedback要求を先に見る。','Agile은 문서가 없다는 뜻이 아니고 Waterfall은 변경이 불가능하다는 뜻이 아니다.','Agileは文書不要ではなくWaterfallは変更不能でもない。','고정·순차=Waterfall, 반복·feedback=Agile.','固定・順次=Waterfall，反復・feedback=Agile。','요구가 자주 바뀌는 Web service는 짧은 iteration이 유리할 수 있다.','要件変化が多いWeb serviceは短いiterationが有利。',47,1),
('A-48','A','시스템개발','システム開発','요구사항 정의','要件定義','사용자와 system이 필요로 하는 기능·품질·제약을 명확하고 검증 가능하게 정리하는 활동이다.','利用者とsystemが必要とする機能・品質・制約を明確かつ検証可能に整理する活動。','기능요구와 비기능요구를 구분하고 모호한 표현을 측정 가능한 조건으로 바꾼다.','機能要件と非機能要件を区別し曖昧表現を測定可能条件へ変える。','성능·가용성·보안·사용성 등은 대표 비기능요구다.','性能・可用性・security・usability等は代表的非機能要件。','누가 무엇을 언제 어떤 기준으로 해야 하는지 acceptance 기준까지 정의한다.','誰が何をいつどの基準で行うかacceptance基準まで定義する。','좋아야 한다·빠르게 같은 비측정 표현을 그대로 두지 않는다.','良い・速い等の非測定表現をそのままにしない。','기능=무엇을, 비기능=얼마나 잘.','機能=何を，非機能=どれだけ良く。','응답시간 95 percentile 2초 이하처럼 측정 가능하게 쓴다.','応答時間95 percentile 2秒以下のように測定可能にする。',48,1),
('A-49','A','시스템개발','システム開発','UML','UML','system 구조와 동작을 표준 diagram으로 모델링하는 표기법이다.','systemの構造と動作を標準diagramでmodelingする表記法。','Use Case는 actor와 기능, Class는 정적 구조, Sequence는 시간순 message 흐름을 표현한다.','Use Caseはactorと機能，Classは静的構造，Sequenceは時系列message flowを表す。','Activity·State·Component diagram의 목적도 구분한다.','Activity・State・Component diagramの目的も区別する。','문제에서 보고 싶은 것이 구조인지 interaction인지 상태변화인지 먼저 판단한다.','構造・interaction・状態変化のどれを見たいか先に判断する。','Sequence를 database ER diagram처럼 해석하지 않는다.','Sequenceをdatabase ER diagramのように解釈しない。','Use Case=기능, Class=구조, Sequence=시간.','Use Case=機能，Class=構造，Sequence=時間。','login 처리에서 browser→API→DB 호출순서는 Sequence가 적합하다.','login処理のbrowser→API→DB呼出順はSequenceが適する。',49,1),
('A-50','A','소프트웨어공학','ソフトウェア工学','테스트 단계','テスト工程','software를 단위부터 system 전체와 사용자 acceptance까지 단계적으로 검증하는 활동이다.','softwareをunitからsystem全体，user acceptanceまで段階的に検証する活動。','unit→integration→system→acceptance로 범위가 넓어진다.','unit→integration→system→acceptanceの順に範囲が広がる。','integration은 interface, system은 전체 요구, acceptance는 사용자/발주 관점이 핵심이다.','integrationはinterface，systemは全体要件，acceptanceはuser/発注側観点が中心。','검증 대상의 범위를 보고 test level을 판단한다.','検証対象の範囲からtest levelを判断する。','developer가 한다고 모두 unit test는 아니다.','developerが行うから全てunit testではない。','단위→연결→전체→사용자.','unit→接続→全体→user。','두 module 간 API 연결검증은 integration test다.','2 module間API接続検証はintegration test。',50,1),
('A-51','A','소프트웨어공학','ソフトウェア工学','동등분할·경계값분석','同値分割・境界値分析','입력 domain을 대표 group으로 나누고 경계 주변을 집중 검사하는 black-box test 설계기법이다.','入力domainを代表groupへ分け境界付近を重点検査するblack-box test設計技法。','동등분할은 같은 동작을 기대하는 class에서 대표값을, 경계값은 min/max 주변값을 고른다.','同値分割は同じ動作を期待するclassの代表値，境界値はmin/max付近を選ぶ。','유효·무효 class와 경계-1, 경계, 경계+1을 체계적으로 만든다.','有効・無効classと境界-1，境界，境界+1を系統的に作る。','조건 범위를 수직선으로 그려 class와 경계를 표시한다.','条件範囲を数直線にしてclassと境界を示す。','경계값분석을 random test와 혼동하지 않는다.','境界値分析をrandom testと混同しない。','대표값=동등분할, 끝점 주변=경계값.','代表値=同値分割，端点付近=境界値。','1~100 유효라면 0,1,2,99,100,101이 대표 경계 후보다.','1～100有効なら0,1,2,99,100,101が代表境界候補。',51,1),
('A-52','A','소프트웨어공학','ソフトウェア工学','Review·형상관리','Review・構成管理','review는 산출물 결함을 조기에 찾고 형상관리는 version과 변경을 식별·통제·추적한다.','reviewは成果物欠陥を早期発見し，構成管理はversionと変更を識別・統制・追跡する。','walkthrough·inspection 등 review와 baseline·version·change control을 구분한다.','walkthrough・inspection等のreviewとbaseline・version・change controlを区別する。','변경요청 승인, 영향분석, version tagging, traceability가 중요하다.','変更要求承認，影響分析，version tagging，traceabilityが重要。','결함검출 활동인지 변경통제 활동인지 먼저 구분한다.','欠陥検出か変更統制かを先に区別する。','backup만 해두면 형상관리라고 볼 수 없다.','backupだけでは構成管理とはいえない。','Review=찾기, 형상관리=바뀐 것 통제.','Review=見つける，構成管理=変更を統制。','release v1.2의 source와 requirement를 함께 추적 가능하게 관리한다.','release v1.2のsourceとrequirementを追跡可能に管理する。',52,1),
('A-53','A','프로젝트관리','プロジェクト管理','PERT·Critical Path','PERT network에서 작업 선후관계와 소요시간으로 project 최소기간과 critical path를 구한다.','PERT networkで作業順序と所要時間からproject最短期間とcritical pathを求める。','critical path는 slack이 0인 경로이며 지연되면 전체기간이 지연될 수 있다.','critical pathはslack 0の経路で遅延すると全体期間が遅れる。','forward pass로 earliest, backward pass로 latest, slack=latest-earliest.','forward passでearliest，backward passでlatest，slack=latest-earliest。','모든 시작→끝 경로 시간을 계산하거나 node별 earliest/latest를 구한다.','全start→end経路時間またはnode別earliest/latestを求める。','작업 수가 가장 많은 경로가 critical이라고 판단하지 않는다.','作業数が最多の経路がcriticalとは限らない。','가장 긴 시간 경로=critical.','最長時間経路=critical。','A 3일 후 B 5일과 C 2일이 병렬이면 긴 B 경로가 완료시점을 좌우한다.','A 3日後B 5日とC 2日が並列なら長いB経路が完了時点を左右する。',53,1),
('A-54','A','프로젝트관리','プロジェクト管理','EVM','EVM','PV·EV·AC를 이용해 일정과 비용 performance를 정량평가하는 기법이다.','PV・EV・ACでscheduleとcost performanceを定量評価する技法。','SV=EV-PV, CV=EV-AC. 양수면 각각 일정/비용 측면에서 유리하다.','SV=EV-PV，CV=EV-AC。正なら各schedule/cost面で良好。','PV=계획가치, EV=실적가치, AC=실제비용을 정확히 구분한다.','PV=計画価値，EV=出来高，AC=実コストを区別する。','먼저 PV/EV/AC를 표에 적고 차이를 계산한다.','まずPV/EV/ACを表へ整理して差を計算する。','EV를 실제 지출액으로 착각하지 않는다.','EVを実支出額と誤解しない。','일정=EV-PV, 비용=EV-AC.','schedule=EV-PV，cost=EV-AC。','EV 80, PV 100이면 SV=-20으로 일정 지연이다.','EV 80，PV 100ならSV=-20でschedule遅延。',54,1),
('A-55','A','프로젝트관리','プロジェクト管理','CPI·SPI','CPI・SPI','EVM에서 비용효율과 일정효율을 비율로 나타내는 지표다.','EVMでcost効率とschedule効率を比率で表す指標。','CPI=EV/AC, SPI=EV/PV. 1보다 크면 각각 비용·일정 효율이 좋다.','CPI=EV/AC，SPI=EV/PV。1より大なら各cost・schedule効率が良い。','CPI<1은 budget 대비 성과가 낮고 SPI<1은 계획보다 진척이 늦다.','CPI<1はcost効率悪化，SPI<1は計画より進捗が遅い。','분자 EV를 고정하고 분모가 AC인지 PV인지 구분한다.','分子EVは共通，分母がACかPVかを区別する。','CPI와 CPU CPI를 혼동하지 않는다.','CPIをCPUのCPIと混同しない。','cost는 AC, schedule은 PV.','costはAC，scheduleはPV。','EV=90, AC=100이면 CPI=0.9다.','EV=90，AC=100ならCPI=0.9。',55,1),
('A-56','A','프로젝트관리','プロジェクト管理','위험관리','リスク管理','project 목표에 영향을 줄 불확실성을 식별·분석·대응·monitoring하는 활동이다.','project目標へ影響する不確実性を識別・分析・対応・monitoringする活動。','부정위험 대응은 회피·완화·전가·수용이 대표적이다.','負のrisk対応は回避・軽減・転嫁・受容が代表。','발생확률×영향도로 우선순위를 정하고 owner와 대응책을 둔다.','発生確率×影響度で優先順位を付けownerと対応策を定める。','대응 행동이 원인을 없애는지, 확률/영향을 줄이는지, 제3자에게 넘기는지 본다.','原因除去，確率/影響低減，第三者移転のどれかを見る。','보험 가입은 위험 자체 제거가 아니라 전가다.','保険加入はrisk除去ではなく転嫁。','없앰=회피, 줄임=완화, 넘김=전가, 그냥 감수=수용.','無くす=回避，減らす=軽減，移す=転嫁，受け入れる=受容。','외부 보험으로 금전손실 부담을 넘기는 것은 전가다.','保険で金銭損失負担を移すのは転嫁。',56,1),
('A-57','A','서비스관리','サービス管理','SLA·SLM','SLA는 service provider와 고객 사이 목표 service level 합의이고 SLM은 이를 지속 관리하는 활동이다.','SLAはproviderと顧客間のservice level合意，SLMはそれを継続管理する活動。','가용성·응답시간·복구시간 등 측정 가능한 SLI/SLO를 정하고 보고·개선한다.','可用性・応答時間・復旧時間等の測定可能SLI/SLOを定め報告・改善する。','SLA는 계약/합의, SLM은 monitoring과 review process다.','SLAは合意，SLMはmonitoringとreview process。','목표수치인지 관리활동인지 구분한다.','目標値か管理活動かを区別する。','SLA를 단순 기술사양서로만 보지 않는다.','SLAを単なる技術仕様書とみなさない。','SLA=약속, SLM=약속 관리.','SLA=約束，SLM=約束管理。','월 가용성 99.9%를 합의하고 매월 측정·review한다.','月間可用性99.9%を合意し毎月測定・reviewする。',57,1),
('A-58','A','서비스관리','サービス管理','Incident·Problem','Incident・Problem','incident management는 service를 빠르게 정상화하고 problem management는 근본원인과 재발방지를 다룬다.','incident managementはserviceを迅速復旧し，problem managementは根本原因と再発防止を扱う。','incident의 목표는 신속 복구, problem은 root cause 분석과 known error 관리다.','incidentの目標は迅速復旧，problemはroot cause分析とknown error管理。','workaround은 복구를 빠르게 할 수 있지만 root cause 제거와는 다르다.','workaroundは復旧を早めるがroot cause除去とは異なる。','지금 service를 살리는 일인지 재발원인을 제거하는 일인지 구분한다.','今serviceを戻す作業か再発原因除去かを区別する。','원인분석이 끝날 때까지 service 복구를 미루지 않는다.','原因分析完了までservice復旧を遅らせない。','Incident=빨리 복구, Problem=왜 생겼나.','Incident=早く復旧，Problem=なぜ起きたか。','재기동으로 임시복구 후 memory leak 원인을 분석하는 흐름이다.','再起動で暫定復旧後memory leak原因を分析する流れ。',58,1),
('A-59','A','시스템감사','システム監査','시스템감사','システム監査','정보system의 통제·안전성·효율성 등을 독립적이고 객관적으로 평가하고 개선을 조언하는 활동이다.','情報systemの統制・安全性・効率性等を独立かつ客観的に評価し改善を助言する活動。','감사인은 대상업무로부터 독립성을 확보하고 evidence에 근거해 판단한다.','監査人は対象業務から独立しevidenceに基づき判断する。','audit plan, evidence, finding, recommendation의 흐름을 이해한다.','audit plan，evidence，finding，recommendationの流れを理解する。','감사와 운영책임을 분리해 독립성을 판단한다.','監査と運用責任を分け独立性を判断する。','감사인이 직접 통제를 설계·운영하고 그 결과를 감사하면 독립성 문제가 생긴다.','監査人が自ら統制を設計・運用しその結果を監査すると独立性問題が生じる。','감사=독립·객관·증거.','監査=独立・客観・証拠。','운영부서와 별도 조직이 log·권한자료를 evidence로 확인한다.','運用部門と別組織がlog・権限資料をevidenceとして確認する。',59,1),
('A-60','A','시스템감사','システム監査','직무분장·내부통제','職務分掌・内部統制','한 사람이 승인·실행·기록을 모두 장악하지 않도록 역할을 분리해 오류와 부정을 예방·탐지한다.','一人が承認・実行・記録を全て支配しないよう役割を分離し誤謬・不正を予防・検知する。','authorization, custody, recording을 분리하고 중요한 작업에는 dual control을 적용한다.','authorization，custody，recordingを分離し重要作業へdual controlを適用する。','preventive/detective control, access review, approval log가 중요하다.','preventive/detective control，access review，approval logが重要。','한 사람이 거래 생성과 승인까지 가능한지 확인한다.','一人が取引作成と承認まで可能か確認する。','권한을 많이 주는 것이 업무효율만 높인다고 보지 않는다.','権限集中を単に効率向上とみなさない。','만든 사람과 승인하는 사람을 나눈다.','作る人と承認する人を分ける。','송금등록자와 최종승인자를 분리한다.','振込登録者と最終承認者を分離する。',60,1),
('A-61','A','시스템전략','システム戦略','SWOT','SWOT','조직의 내부 강점·약점과 외부 기회·위협을 구분해 전략을 도출하는 분석기법이다.','組織の内部Strength・Weaknessと外部Opportunity・Threatを区別し戦略を導く分析法。','S/W는 내부, O/T는 외부 환경이다.','S/Wは内部，O/Tは外部環境。','SO·ST·WO·WT 전략 조합으로 활용할 수 있다.','SO・ST・WO・WT戦略組合せへ活用できる。','문장의 통제 가능성과 조직 내부/외부 여부를 먼저 본다.','事象が組織内部か外部かを先に見る。','경쟁사 등장 같은 외부요인을 약점으로 분류하지 않는다.','競合登場のような外部要因をWeaknessへ分類しない。','안=SW, 밖=OT.','内=SW，外=OT。','숙련개발자 보유는 Strength, 시장성장은 Opportunity다.','熟練developer保有はStrength，市場成長はOpportunity。',61,1),
('A-62','A','경영전략','経営戦略','PPM','PPM','사업을 시장성장률과 상대적 시장점유율로 분류해 자원배분을 검토하는 portfolio 분석이다.','事業を市場成長率と相対市場shareで分類し資源配分を検討するportfolio分析。','Star, Cash Cow, Question Mark, Dog의 4영역을 사용한다.','Star，Cash Cow，Question Mark，Dogの4領域を使う。','성장률 high/low와 점유율 high/low 축을 정확히 조합한다.','成長率high/lowとshare high/low軸を正確に組み合わせる。','두 축을 표로 그린 뒤 분류한다.','2軸を表にして分類する。','매출액 크기만으로 Cash Cow를 판단하지 않는다.','売上高だけでCash Cowを判断しない。','고성장·고점유=Star, 저성장·고점유=Cash Cow.','高成長・高share=Star，低成長・高share=Cash Cow。','성숙시장 high share 사업은 Cash Cow가 될 수 있다.','成熟市場high share事業はCash Cowになり得る。',62,1),
('A-63','A','경영전략','経営戦略','5 Forces','5 Forces','산업 수익성과 경쟁강도에 영향을 주는 다섯 경쟁요인을 분석하는 framework다.','業界収益性と競争強度へ影響する5つの競争要因を分析するframework。','기존경쟁, 신규진입, 대체재, 구매자 교섭력, 공급자 교섭력을 본다.','既存競争，新規参入，代替品，買い手交渉力，売り手交渉力を見る。','진입장벽과 switching cost가 각 force에 미치는 영향을 이해한다.','参入障壁とswitching costが各forceへ与える影響を理解する。','사례가 어느 이해관계자/위협인지 연결한다.','事例がどのstakeholder/脅威か対応させる。','SWOT과 같은 내부역량 분석으로 착각하지 않는다.','SWOTのような内部能力分析と混同しない。','경쟁자·신규·대체·고객·공급자.','競合・新規・代替・顧客・供給者。','원재료 공급업체가 소수면 공급자 교섭력이 강해질 수 있다.','原材料supplierが少数なら売り手交渉力が強くなり得る。',63,1),
('A-64','A','경영전략','経営戦略','4P·4C','4P・4C','marketing mix를 기업 관점 4P와 고객 관점 4C로 바라보는 framework다.','marketing mixを企業視点4Pと顧客視点4Cで捉えるframework。','4P=Product, Price, Place, Promotion. 4C=Customer value, Cost, Convenience, Communication.','4P=Product, Price, Place, Promotion。4C=Customer value, Cost, Convenience, Communication。','P와 대응하는 C 관계를 이해한다.','Pと対応するCの関係を理解する。','사례의 초점이 제품·가격·유통·촉진 중 무엇인지 판별한다.','事例の焦点が製品・価格・流通・販促のどれか判定する。','Promotion을 할인가격 그 자체와 혼동하지 않는다.','Promotionを値引価格そのものと混同しない。','제품·가격·유통·촉진.','製品・価格・流通・販促。','온라인 판매채널 확대는 Place/Convenience와 관련된다.','online販売channel拡大はPlace/Convenienceに関係する。',64,1),
('A-65','A','회계','会計','손익분기점','損益分岐点','매출과 총비용이 같아 이익이 0이 되는 판매량 또는 매출액이다.','売上と総費用が等しく利益0となる販売量または売上高。','단위당 공헌이익=판매단가-단위변동비, BEP수량=고정비/단위공헌이익.','単位限界利益=販売単価-単位変動費，BEP数量=固定費/単位限界利益。','변동비율을 쓰면 BEP매출=고정비/(1-변동비율).','変動費率ならBEP売上=固定費/(1-変動費率)。','고정비와 변동비를 분리하고 공헌이익부터 계산한다.','固定費と変動費を分け限界利益から計算する。','고정비를 판매량으로 다시 곱하지 않는다.','固定費を販売数量で再度掛けない。','가격-변동비=한 개 팔 때 고정비 회수분.','価格-変動費=1個販売時の固定費回収分。','가격100, 변동비60, 고정비4000이면 BEP=100개.','価格100，変動費60，固定費4000ならBEP=100個。',65,1),
('A-66','A','회계','会計','ROI·재무지표','ROI・財務指標','투자 대비 이익과 다양한 재무비율로 사업성과와 건전성을 평가한다.','投資に対する利益や各種財務比率で事業成果と健全性を評価する。','ROI=이익/투자액×100. 지표마다 분자·분모 의미를 정확히 읽어야 한다.','ROI=利益/投資額×100。指標ごとの分子・分母を正確に読む。','수익성·안전성·효율성 지표를 구분한다.','収益性・安全性・効率性指標を区別する。','단위와 기간을 맞춘 뒤 비율을 계산한다.','単位と期間をそろえて比率計算する。','매출액과 투자액을 뒤집어 ROI를 계산하지 않는다.','売上高と投資額を逆にしてROI計算しない。','ROI=번 돈/넣은 돈.','ROI=利益/投資。','투자1000, 이익120이면 ROI=12%.','投資1000，利益120ならROI=12%。',66,1),
('A-67','A','법무','法務','저작권·특허권','著作権・特許権','저작권은 창작적 표현을, 특허권은 일정 요건을 충족한 기술적 발명을 보호한다.','著作権は創作的表現，特許権は要件を満たす技術的発明を保護する。','저작권은 창작과 동시에 발생하는 것이 원칙이고 특허는 출원·심사를 거쳐 권리가 성립한다.','著作権は創作時発生が原則，特許は出願・審査を経て権利成立する。','idea와 표현의 차이, software source의 저작권, 발명의 신규성·진보성을 구분한다.','ideaと表現の違い，software sourceの著作権，発明の新規性・進歩性を区別する。','보호대상이 표현인지 기술적 발명인지 먼저 판단한다.','保護対象が表現か技術的発明か先に判断する。','저작권 보호에 등록이 항상 필수라고 생각하지 않는다.','著作権保護に登録が常に必須と誤解しない。','표현=저작권, 발명=특허.','表現=著作権，発明=特許。','작성한 source code는 저작물로 보호될 수 있다.','作成したsource codeは著作物として保護され得る。',67,1),
('A-68','A','법무','法務','개인정보·표준화','個人情報・標準化','개인정보를 적법하게 처리하고 표준을 통해 system·제품 간 호환성과 품질을 높이는 개념이다.','個人情報を適法に扱い，標準によりsystem・製品間の互換性と品質を高める概念。','개인정보는 목적명확화·최소수집·안전관리·적절한 제공통제가 중요하고 표준은 공통 규격을 제공한다.','個人情報は目的明確化・最小収集・安全管理・適切な提供統制が重要，標準は共通規格を提供する。','익명화·가명화의 차이, 목적외 이용, international/industry standard의 역할을 이해한다.','匿名化・仮名化の違い，目的外利用，international/industry standardの役割を理解する。','사례의 data 식별가능성과 처리목적·동의/근거를 확인한다.','dataの識別可能性と処理目的・同意/根拠を確認する。','필요 이상 data를 모으는 것이 안전하다고 보지 않는다.','必要以上のdata収集が安全とは考えない。','개인정보=목적·최소·보호, 표준=공통규칙.','個人情報=目的・最小・保護，標準=共通規則。','서비스 목적에 불필요한 주민번호를 수집하지 않는 것이 최소수집 원칙에 맞다.','service目的に不要な識別番号を収集しないことは最小収集原則に合う。',68,1);

-- Three practical problem types for each concept.
INSERT OR REPLACE INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,1,CASE concept_code
 WHEN 'A-47' THEN '개발방법론 비교' WHEN 'A-48' THEN '기능·비기능 요구 구분' WHEN 'A-49' THEN 'UML diagram 선택' WHEN 'A-50' THEN 'test level 판별' WHEN 'A-51' THEN '동등분할 설계' WHEN 'A-52' THEN 'review·형상관리 구분' WHEN 'A-53' THEN 'critical path 계산' WHEN 'A-54' THEN 'PV·EV·AC 계산' WHEN 'A-55' THEN 'CPI·SPI 계산' WHEN 'A-56' THEN 'risk 대응전략 판별' WHEN 'A-57' THEN 'SLA 지표판단' WHEN 'A-58' THEN 'incident·problem 구분' WHEN 'A-59' THEN '감사 독립성' WHEN 'A-60' THEN '직무분장 판단' WHEN 'A-61' THEN 'SWOT 분류' WHEN 'A-62' THEN 'PPM 분류' WHEN 'A-63' THEN '5 Forces 분류' WHEN 'A-64' THEN '4P 분류' WHEN 'A-65' THEN 'BEP 계산' WHEN 'A-66' THEN 'ROI 계산' WHEN 'A-67' THEN '권리종류 판별' WHEN 'A-68' THEN '개인정보 처리판단' END,
CASE concept_code
 WHEN 'A-47' THEN '開発手法比較' WHEN 'A-48' THEN '機能・非機能要件区別' WHEN 'A-49' THEN 'UML diagram選択' WHEN 'A-50' THEN 'test level判定' WHEN 'A-51' THEN '同値分割設計' WHEN 'A-52' THEN 'review・構成管理区別' WHEN 'A-53' THEN 'critical path計算' WHEN 'A-54' THEN 'PV・EV・AC計算' WHEN 'A-55' THEN 'CPI・SPI計算' WHEN 'A-56' THEN 'risk対応戦略判定' WHEN 'A-57' THEN 'SLA指標判断' WHEN 'A-58' THEN 'incident・problem区別' WHEN 'A-59' THEN '監査独立性' WHEN 'A-60' THEN '職務分掌判断' WHEN 'A-61' THEN 'SWOT分類' WHEN 'A-62' THEN 'PPM分類' WHEN 'A-63' THEN '5 Forces分類' WHEN 'A-64' THEN '4P分類' WHEN 'A-65' THEN 'BEP計算' WHEN 'A-66' THEN 'ROI計算' WHEN 'A-67' THEN '権利種類判定' WHEN 'A-68' THEN '個人情報取扱判断' END,1 FROM ap_concepts WHERE sort_order BETWEEN 47 AND 68;
INSERT OR REPLACE INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,2,CASE concept_code
 WHEN 'A-47' THEN '변경·iteration 판단' WHEN 'A-48' THEN '측정가능성·acceptance' WHEN 'A-49' THEN '관계·message 해석' WHEN 'A-50' THEN '검증범위 판단' WHEN 'A-51' THEN '경계값 설계' WHEN 'A-52' THEN 'version·baseline·변경통제' WHEN 'A-53' THEN 'slack 계산' WHEN 'A-54' THEN 'SV·CV 해석' WHEN 'A-55' THEN '효율지표 해석' WHEN 'A-56' THEN '확률·영향 우선순위' WHEN 'A-57' THEN 'SLA·SLM 구분' WHEN 'A-58' THEN '복구·근본원인 판단' WHEN 'A-59' THEN 'evidence·finding 판단' WHEN 'A-60' THEN '예방·탐지통제' WHEN 'A-61' THEN 'SO·ST·WO·WT 응용' WHEN 'A-62' THEN '성장률·점유율 해석' WHEN 'A-63' THEN '교섭력·진입장벽' WHEN 'A-64' THEN '4C 대응' WHEN 'A-65' THEN '공헌이익·BEP 매출' WHEN 'A-66' THEN '재무비율 해석' WHEN 'A-67' THEN '저작권·특허 차이' WHEN 'A-68' THEN '목적·최소수집 판단' END,
CASE concept_code
 WHEN 'A-47' THEN '変更・iteration判断' WHEN 'A-48' THEN '測定可能性・acceptance' WHEN 'A-49' THEN '関係・message解釈' WHEN 'A-50' THEN '検証範囲判断' WHEN 'A-51' THEN '境界値設計' WHEN 'A-52' THEN 'version・baseline・変更統制' WHEN 'A-53' THEN 'slack計算' WHEN 'A-54' THEN 'SV・CV解釈' WHEN 'A-55' THEN '効率指標解釈' WHEN 'A-56' THEN '確率・影響優先順位' WHEN 'A-57' THEN 'SLA・SLM区別' WHEN 'A-58' THEN '復旧・根本原因判断' WHEN 'A-59' THEN 'evidence・finding判断' WHEN 'A-60' THEN '予防・検知統制' WHEN 'A-61' THEN 'SO・ST・WO・WT応用' WHEN 'A-62' THEN '成長率・share解釈' WHEN 'A-63' THEN '交渉力・参入障壁' WHEN 'A-64' THEN '4C対応' WHEN 'A-65' THEN '限界利益・BEP売上' WHEN 'A-66' THEN '財務比率解釈' WHEN 'A-67' THEN '著作権・特許差異' WHEN 'A-68' THEN '目的・最小収集判断' END,2 FROM ap_concepts WHERE sort_order BETWEEN 47 AND 68;
INSERT OR REPLACE INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,3,CASE concept_code
 WHEN 'A-47' THEN '개발 scenario 선택' WHEN 'A-48' THEN '요구변경·traceability' WHEN 'A-49' THEN 'modeling scenario' WHEN 'A-50' THEN 'test 전략 scenario' WHEN 'A-51' THEN '복합 test case' WHEN 'A-52' THEN '변경사고 scenario' WHEN 'A-53' THEN '일정단축 scenario' WHEN 'A-54' THEN 'EVM 종합판단' WHEN 'A-55' THEN 'EVM 종합판단' WHEN 'A-56' THEN 'risk scenario' WHEN 'A-57' THEN 'service level 개선' WHEN 'A-58' THEN '운영장애 scenario' WHEN 'A-59' THEN '감사 scenario' WHEN 'A-60' THEN '부정방지 scenario' WHEN 'A-61' THEN '전략도출 scenario' WHEN 'A-62' THEN '사업portfolio scenario' WHEN 'A-63' THEN '산업구조 scenario' WHEN 'A-64' THEN 'marketing scenario' WHEN 'A-65' THEN '이익계획 scenario' WHEN 'A-66' THEN '투자판단 scenario' WHEN 'A-67' THEN 'software 권리 scenario' WHEN 'A-68' THEN 'data 활용 scenario' END,
CASE concept_code
 WHEN 'A-47' THEN '開発scenario選択' WHEN 'A-48' THEN '要件変更・traceability' WHEN 'A-49' THEN 'modeling scenario' WHEN 'A-50' THEN 'test戦略scenario' WHEN 'A-51' THEN '複合test case' WHEN 'A-52' THEN '変更事故scenario' WHEN 'A-53' THEN '日程短縮scenario' WHEN 'A-54' THEN 'EVM総合判断' WHEN 'A-55' THEN 'EVM総合判断' WHEN 'A-56' THEN 'risk scenario' WHEN 'A-57' THEN 'service level改善' WHEN 'A-58' THEN '運用障害scenario' WHEN 'A-59' THEN '監査scenario' WHEN 'A-60' THEN '不正防止scenario' WHEN 'A-61' THEN '戦略導出scenario' WHEN 'A-62' THEN '事業portfolio scenario' WHEN 'A-63' THEN '業界構造scenario' WHEN 'A-64' THEN 'marketing scenario' WHEN 'A-65' THEN '利益計画scenario' WHEN 'A-66' THEN '投資判断scenario' WHEN 'A-67' THEN 'software権利scenario' WHEN 'A-68' THEN 'data活用scenario' END,3 FROM ap_concepts WHERE sort_order BETWEEN 47 AND 68;

-- Seed one concept-specific question for every problem type.
INSERT OR REPLACE INTO ap_concept_questions(problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT t.id,1,
CASE c.concept_code||'-'||t.type_no
 WHEN 'A-47-1' THEN '요구변경이 매우 잦고 짧은 주기로 release하는 project에 일반적으로 더 적합한 접근은?' WHEN 'A-47-2' THEN 'Agile에서 우선순위가 정해진 요구목록을 무엇이라 하는가?' WHEN 'A-47-3' THEN '규제문서와 단계승인이 매우 엄격하고 요구가 안정적인 project라면 어떤 접근이 상대적으로 적합한가?'
 WHEN 'A-48-1' THEN '응답시간 2초 이하는 기능요구인가 비기능요구인가?' WHEN 'A-48-2' THEN '좋은 성능을 제공한다라는 요구의 가장 큰 문제는?' WHEN 'A-48-3' THEN '요구변경 영향분석을 쉽게 하려면 requirement와 design/test 간 무엇을 유지해야 하는가?'
 WHEN 'A-49-1' THEN 'actor와 system 기능 관계를 표현하기 적합한 UML은?' WHEN 'A-49-2' THEN 'object 간 message 시간순서를 나타내는 UML은?' WHEN 'A-49-3' THEN 'class의 속성·method·관계를 나타내는 UML은?'
 WHEN 'A-50-1' THEN '한 function 단독 동작을 검증하는 것은?' WHEN 'A-50-2' THEN '두 subsystem interface를 검증하는 것은?' WHEN 'A-50-3' THEN '사용자가 업무요구 충족을 최종 확인하는 것은?'
 WHEN 'A-51-1' THEN '입력 1~100에서 동등분할의 유효 대표값 예는?' WHEN 'A-51-2' THEN '1~100 경계값 후보로 가장 적절한 집합에 포함될 값은?' WHEN 'A-51-3' THEN '0~120 나이와 회원여부 두 조건을 함께 test하려면 경계값 외 어떤 기법도 고려할 수 있는가?'
 WHEN 'A-52-1' THEN '설계서 결함을 coding 전에 찾아내는 활동은?' WHEN 'A-52-2' THEN 'release source와 설정의 version을 식별·통제하는 것은?' WHEN 'A-52-3' THEN '승인되지 않은 변경이 production에 들어가는 것을 막는 핵심 절차는?'
 WHEN 'A-53-1' THEN 'project 완료기간을 결정하는 slack 0 경로는?' WHEN 'A-53-2' THEN '어떤 작업의 earliest=8, latest=11이면 slack은?' WHEN 'A-53-3' THEN '전체 기간을 단축하려면 우선 어느 경로 작업을 단축해야 효과적인가?'
 WHEN 'A-54-1' THEN 'EV=80, PV=100, AC=90일 때 SV는?' WHEN 'A-54-2' THEN 'EV=80, AC=90일 때 CV는?' WHEN 'A-54-3' THEN 'SV<0이고 CV>0이면 상태를 어떻게 해석하는가?'
 WHEN 'A-55-1' THEN 'EV=90, AC=100일 때 CPI는?' WHEN 'A-55-2' THEN 'EV=90, PV=120일 때 SPI는?' WHEN 'A-55-3' THEN 'CPI>1, SPI<1의 의미는?'
 WHEN 'A-56-1' THEN '위험 원인이 되는 기능 자체를 project 범위에서 제거했다. 대응은?' WHEN 'A-56-2' THEN '발생확률과 영향도를 낮추기 위해 사전 test를 강화했다. 대응은?' WHEN 'A-56-3' THEN '보험으로 손실부담을 제3자에게 넘겼다. 대응은?'
 WHEN 'A-57-1' THEN '월 가용성 99.9% 같은 합의는 무엇인가?' WHEN 'A-57-2' THEN 'SLA 달성률을 지속 측정하고 개선하는 활동은?' WHEN 'A-57-3' THEN 'SLA 지표는 어떤 형태가 바람직한가?'
 WHEN 'A-58-1' THEN '장애 발생 직후 service를 신속히 복구하는 활동은?' WHEN 'A-58-2' THEN '반복 장애의 root cause를 분석해 재발을 막는 활동은?' WHEN 'A-58-3' THEN '임시 workaround 적용 후 다음으로 수행할 적절한 활동은?'
 WHEN 'A-59-1' THEN '감사인이 감사대상 system 운영책임자라면 가장 큰 문제는?' WHEN 'A-59-2' THEN '감사 finding은 무엇에 근거해야 하는가?' WHEN 'A-59-3' THEN '감사인이 개선안을 제시하는 것은 가능하지만 직접 운영통제를 수행하면 어떤 원칙이 훼손될 수 있는가?'
 WHEN 'A-60-1' THEN '송금 등록자와 승인자를 분리하는 통제는?' WHEN 'A-60-2' THEN '사후 log review는 예방통제와 탐지통제 중 어느 쪽인가?' WHEN 'A-60-3' THEN '한 user가 계정생성·권한부여·승인을 모두 한다면 어떤 위험이 커지는가?'
 WHEN 'A-61-1' THEN '숙련개발자 보유는 SWOT 중 무엇인가?' WHEN 'A-61-2' THEN '시장 급성장은 SWOT 중 무엇인가?' WHEN 'A-61-3' THEN '강점을 이용해 외부 기회를 활용하는 전략은?'
 WHEN 'A-62-1' THEN '고성장·고점유 사업은 PPM에서?' WHEN 'A-62-2' THEN '저성장·고점유 사업은?' WHEN 'A-62-3' THEN '고성장·저점유 사업은?'
 WHEN 'A-63-1' THEN '원재료 supplier가 소수라 협상력이 커졌다. 어떤 force인가?' WHEN 'A-63-2' THEN '새로운 competitor가 쉽게 들어올 수 있다. 어떤 force인가?' WHEN 'A-63-3' THEN '대체 service가 급성장한다. 어떤 force인가?'
 WHEN 'A-64-1' THEN '판매가격 결정은 4P 중?' WHEN 'A-64-2' THEN '고객의 구매편의는 4C 중?' WHEN 'A-64-3' THEN '온라인 유통채널 확대는 4P 중?'
 WHEN 'A-65-1' THEN '가격100, 변동비60, 고정비4000이면 BEP 판매량은?' WHEN 'A-65-2' THEN '단위 공헌이익 공식은?' WHEN 'A-65-3' THEN 'BEP보다 많이 판매하면 일반적으로 이익은 어떻게 되는가?'
 WHEN 'A-66-1' THEN '투자1000, 이익120이면 ROI는?' WHEN 'A-66-2' THEN 'ROI의 분모는 일반적으로 무엇인가?' WHEN 'A-66-3' THEN '동일 이익이면 투자액이 작을수록 ROI는 어떻게 되는가?'
 WHEN 'A-67-1' THEN '작성한 source code의 창작적 표현을 주로 보호하는 권리는?' WHEN 'A-67-2' THEN '기술적 발명을 출원·심사로 보호하는 권리는?' WHEN 'A-67-3' THEN '저작권은 일반적으로 언제 발생하는가?'
 WHEN 'A-68-1' THEN '서비스에 불필요한 개인정보까지 수집하지 않는 원칙은?' WHEN 'A-68-2' THEN '개인정보 이용목적을 정하고 그 범위 내에서 처리하는 이유는?' WHEN 'A-68-3' THEN '표준화의 대표 효과는?' END,
CASE c.concept_code||'-'||t.type_no
 WHEN 'A-47-1' THEN '要件変更が多く短周期releaseするprojectに一般に適するapproachは?' WHEN 'A-47-2' THEN 'Agileで優先順位付き要求一覧を何という?' WHEN 'A-47-3' THEN '規制文書・工程承認が厳格で要件が安定したprojectに比較的適するapproachは?'
 WHEN 'A-48-1' THEN '応答時間2秒以下は機能要件か非機能要件か?' WHEN 'A-48-2' THEN '良い性能を提供するという要件の最大問題は?' WHEN 'A-48-3' THEN '要件変更の影響分析を容易にするためrequirementとdesign/test間で何を維持する?'
 WHEN 'A-49-1' THEN 'actorとsystem機能関係に適するUMLは?' WHEN 'A-49-2' THEN 'object間messageを時系列で表すUMLは?' WHEN 'A-49-3' THEN 'classの属性・method・関係を表すUMLは?'
 WHEN 'A-50-1' THEN '一つのfunction単独を検証するtestは?' WHEN 'A-50-2' THEN '2 subsystemのinterfaceを検証するtestは?' WHEN 'A-50-3' THEN 'userが業務要件充足を最終確認するtestは?'
 WHEN 'A-51-1' THEN '入力1～100で同値分割の有効代表値例は?' WHEN 'A-51-2' THEN '1～100の境界値候補に含める値は?' WHEN 'A-51-3' THEN '年齢0～120と会員有無の2条件を共にtestする時，境界値以外に考慮できる技法は?'
 WHEN 'A-52-1' THEN '設計書欠陥をcoding前に見つける活動は?' WHEN 'A-52-2' THEN 'release sourceと設定versionを識別・統制する活動は?' WHEN 'A-52-3' THEN '未承認変更がproductionへ入るのを防ぐ核心手続は?'
 WHEN 'A-53-1' THEN 'project完了期間を決めるslack 0の経路は?' WHEN 'A-53-2' THEN 'earliest=8, latest=11の作業slackは?' WHEN 'A-53-3' THEN '全体期間短縮にはまずどの経路作業を短縮すると効果的?'
 WHEN 'A-54-1' THEN 'EV=80, PV=100, AC=90のSVは?' WHEN 'A-54-2' THEN 'EV=80, AC=90のCVは?' WHEN 'A-54-3' THEN 'SV<0かつCV>0をどう解釈する?'
 WHEN 'A-55-1' THEN 'EV=90, AC=100のCPIは?' WHEN 'A-55-2' THEN 'EV=90, PV=120のSPIは?' WHEN 'A-55-3' THEN 'CPI>1, SPI<1の意味は?'
 WHEN 'A-56-1' THEN 'risk原因となる機能自体をproject範囲から除去した。対応は?' WHEN 'A-56-2' THEN '発生確率・影響を下げるため事前testを強化した。対応は?' WHEN 'A-56-3' THEN '保険で損失負担を第三者へ移した。対応は?'
 WHEN 'A-57-1' THEN '月可用性99.9%のような合意は?' WHEN 'A-57-2' THEN 'SLA達成率を継続測定・改善する活動は?' WHEN 'A-57-3' THEN 'SLA指標はどのような形が望ましい?'
 WHEN 'A-58-1' THEN '障害直後serviceを迅速復旧する活動は?' WHEN 'A-58-2' THEN '反復障害のroot causeを分析し再発防止する活動は?' WHEN 'A-58-3' THEN '暫定workaround適用後に次に行う適切な活動は?'
 WHEN 'A-59-1' THEN '監査人が監査対象systemの運用責任者なら最大問題は?' WHEN 'A-59-2' THEN '監査findingは何に基づくべき?' WHEN 'A-59-3' THEN '監査人が改善案提示は可能だが直接運用統制を行うと何原則が損なわれる?'
 WHEN 'A-60-1' THEN '振込登録者と承認者を分ける統制は?' WHEN 'A-60-2' THEN '事後log reviewは予防統制と検知統制のどちら?' WHEN 'A-60-3' THEN '一人がaccount作成・権限付与・承認を全て行うと何riskが高まる?'
 WHEN 'A-61-1' THEN '熟練developer保有はSWOTの何?' WHEN 'A-61-2' THEN '市場急成長はSWOTの何?' WHEN 'A-61-3' THEN 'Strengthを使ってOpportunityを活用する戦略は?'
 WHEN 'A-62-1' THEN '高成長・高share事業はPPMで?' WHEN 'A-62-2' THEN '低成長・高share事業は?' WHEN 'A-62-3' THEN '高成長・低share事業は?'
 WHEN 'A-63-1' THEN '原材料supplierが少数で交渉力が増した。何force?' WHEN 'A-63-2' THEN '新規competitorが参入しやすい。何force?' WHEN 'A-63-3' THEN '代替serviceが急成長。何force?'
 WHEN 'A-64-1' THEN '販売価格決定は4Pの何?' WHEN 'A-64-2' THEN '顧客の購入利便性は4Cの何?' WHEN 'A-64-3' THEN 'online流通channel拡大は4Pの何?'
 WHEN 'A-65-1' THEN '価格100,変動費60,固定費4000ならBEP販売量は?' WHEN 'A-65-2' THEN '単位限界利益の式は?' WHEN 'A-65-3' THEN 'BEPより多く販売すると一般に利益はどうなる?'
 WHEN 'A-66-1' THEN '投資1000,利益120ならROIは?' WHEN 'A-66-2' THEN 'ROIの分母は一般に何?' WHEN 'A-66-3' THEN '同じ利益なら投資額が小さいほどROIはどうなる?'
 WHEN 'A-67-1' THEN '作成source codeの創作的表現を主に保護する権利は?' WHEN 'A-67-2' THEN '技術的発明を出願・審査で保護する権利は?' WHEN 'A-67-3' THEN '著作権は一般にいつ発生する?'
 WHEN 'A-68-1' THEN 'serviceに不要な個人情報まで収集しない原則は?' WHEN 'A-68-2' THEN '個人情報の利用目的を定め範囲内で処理する理由は?' WHEN 'A-68-3' THEN '標準化の代表的効果は?' END,
NULL,NULL,NULL,
CASE c.concept_code||'-'||t.type_no
 WHEN 'A-47-1' THEN 'Agile' WHEN 'A-47-2' THEN 'Product Backlog' WHEN 'A-47-3' THEN 'Waterfall' WHEN 'A-48-1' THEN '비기능요구' WHEN 'A-48-2' THEN '측정·검증 기준이 모호하다' WHEN 'A-48-3' THEN 'traceability' WHEN 'A-49-1' THEN 'Use Case Diagram' WHEN 'A-49-2' THEN 'Sequence Diagram' WHEN 'A-49-3' THEN 'Class Diagram' WHEN 'A-50-1' THEN 'Unit Test' WHEN 'A-50-2' THEN 'Integration Test' WHEN 'A-50-3' THEN 'Acceptance Test' WHEN 'A-51-1' THEN '50' WHEN 'A-51-2' THEN '0,1,100,101 등' WHEN 'A-51-3' THEN '결정표' WHEN 'A-52-1' THEN 'Review' WHEN 'A-52-2' THEN '형상관리' WHEN 'A-52-3' THEN '변경승인·change control' WHEN 'A-53-1' THEN 'Critical Path' WHEN 'A-53-2' THEN '3' WHEN 'A-53-3' THEN 'Critical Path' WHEN 'A-54-1' THEN '-20' WHEN 'A-54-2' THEN '-10' WHEN 'A-54-3' THEN '일정은 지연이지만 비용은 계획보다 효율적' WHEN 'A-55-1' THEN '0.9' WHEN 'A-55-2' THEN '0.75' WHEN 'A-55-3' THEN '비용효율은 좋지만 일정은 지연' WHEN 'A-56-1' THEN '회피' WHEN 'A-56-2' THEN '완화' WHEN 'A-56-3' THEN '전가' WHEN 'A-57-1' THEN 'SLA' WHEN 'A-57-2' THEN 'SLM' WHEN 'A-57-3' THEN '측정 가능한 수치' WHEN 'A-58-1' THEN 'Incident Management' WHEN 'A-58-2' THEN 'Problem Management' WHEN 'A-58-3' THEN 'root cause 분석 및 재발방지' WHEN 'A-59-1' THEN '독립성 훼손' WHEN 'A-59-2' THEN '객관적 audit evidence' WHEN 'A-59-3' THEN '독립성' WHEN 'A-60-1' THEN '직무분장' WHEN 'A-60-2' THEN '탐지통제' WHEN 'A-60-3' THEN '부정·오류 은폐 위험' WHEN 'A-61-1' THEN 'Strength' WHEN 'A-61-2' THEN 'Opportunity' WHEN 'A-61-3' THEN 'SO 전략' WHEN 'A-62-1' THEN 'Star' WHEN 'A-62-2' THEN 'Cash Cow' WHEN 'A-62-3' THEN 'Question Mark' WHEN 'A-63-1' THEN '공급자 교섭력' WHEN 'A-63-2' THEN '신규진입 위협' WHEN 'A-63-3' THEN '대체재 위협' WHEN 'A-64-1' THEN 'Price' WHEN 'A-64-2' THEN 'Convenience' WHEN 'A-64-3' THEN 'Place' WHEN 'A-65-1' THEN '100개' WHEN 'A-65-2' THEN '판매단가-단위변동비' WHEN 'A-65-3' THEN '이익이 발생한다' WHEN 'A-66-1' THEN '12%' WHEN 'A-66-2' THEN '투자액' WHEN 'A-66-3' THEN '높아진다' WHEN 'A-67-1' THEN '저작권' WHEN 'A-67-2' THEN '특허권' WHEN 'A-67-3' THEN '창작 시점' WHEN 'A-68-1' THEN '최소수집' WHEN 'A-68-2' THEN '목적 외 이용을 막고 적법한 처리를 위해' WHEN 'A-68-3' THEN '호환성·상호운용성 향상' END,
CASE c.concept_code||'-'||t.type_no
 WHEN 'A-47-1' THEN 'Agile' WHEN 'A-47-2' THEN 'Product Backlog' WHEN 'A-47-3' THEN 'Waterfall' WHEN 'A-48-1' THEN '非機能要件' WHEN 'A-48-2' THEN '測定・検証基準が曖昧' WHEN 'A-48-3' THEN 'traceability' WHEN 'A-49-1' THEN 'Use Case Diagram' WHEN 'A-49-2' THEN 'Sequence Diagram' WHEN 'A-49-3' THEN 'Class Diagram' WHEN 'A-50-1' THEN 'Unit Test' WHEN 'A-50-2' THEN 'Integration Test' WHEN 'A-50-3' THEN 'Acceptance Test' WHEN 'A-51-1' THEN '50' WHEN 'A-51-2' THEN '0,1,100,101など' WHEN 'A-51-3' THEN '決定表' WHEN 'A-52-1' THEN 'Review' WHEN 'A-52-2' THEN '構成管理' WHEN 'A-52-3' THEN '変更承認・change control' WHEN 'A-53-1' THEN 'Critical Path' WHEN 'A-53-2' THEN '3' WHEN 'A-53-3' THEN 'Critical Path' WHEN 'A-54-1' THEN '-20' WHEN 'A-54-2' THEN '-10' WHEN 'A-54-3' THEN 'schedule遅延だがcostは計画より効率的' WHEN 'A-55-1' THEN '0.9' WHEN 'A-55-2' THEN '0.75' WHEN 'A-55-3' THEN 'cost効率は良いがschedule遅延' WHEN 'A-56-1' THEN '回避' WHEN 'A-56-2' THEN '軽減' WHEN 'A-56-3' THEN '転嫁' WHEN 'A-57-1' THEN 'SLA' WHEN 'A-57-2' THEN 'SLM' WHEN 'A-57-3' THEN '測定可能な数値' WHEN 'A-58-1' THEN 'Incident Management' WHEN 'A-58-2' THEN 'Problem Management' WHEN 'A-58-3' THEN 'root cause分析と再発防止' WHEN 'A-59-1' THEN '独立性の毀損' WHEN 'A-59-2' THEN '客観的audit evidence' WHEN 'A-59-3' THEN '独立性' WHEN 'A-60-1' THEN '職務分掌' WHEN 'A-60-2' THEN '検知統制' WHEN 'A-60-3' THEN '不正・誤謬隠蔽risk' WHEN 'A-61-1' THEN 'Strength' WHEN 'A-61-2' THEN 'Opportunity' WHEN 'A-61-3' THEN 'SO戦略' WHEN 'A-62-1' THEN 'Star' WHEN 'A-62-2' THEN 'Cash Cow' WHEN 'A-62-3' THEN 'Question Mark' WHEN 'A-63-1' THEN '売り手の交渉力' WHEN 'A-63-2' THEN '新規参入の脅威' WHEN 'A-63-3' THEN '代替品の脅威' WHEN 'A-64-1' THEN 'Price' WHEN 'A-64-2' THEN 'Convenience' WHEN 'A-64-3' THEN 'Place' WHEN 'A-65-1' THEN '100個' WHEN 'A-65-2' THEN '販売単価-単位変動費' WHEN 'A-65-3' THEN '利益が発生する' WHEN 'A-66-1' THEN '12%' WHEN 'A-66-2' THEN '投資額' WHEN 'A-66-3' THEN '高くなる' WHEN 'A-67-1' THEN '著作権' WHEN 'A-67-2' THEN '特許権' WHEN 'A-67-3' THEN '創作時点' WHEN 'A-68-1' THEN '最小収集' WHEN 'A-68-2' THEN '目的外利用を防ぎ適法に処理するため' WHEN 'A-68-3' THEN '互換性・相互運用性向上' END,
'핵심 정의와 계산식 또는 분류기준을 먼저 적용한 뒤 사례에 연결한다.','基本定義・計算式または分類基準を先に適用して事例へ結び付ける。',2,t.type_no
FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.sort_order BETWEEN 47 AND 68;
