-- 0052 AP concepts A-47..A-68: development, PM, service, audit, strategy, accounting/legal
-- Rewritten as one INSERT per concept so a malformed row cannot break a multi-row VALUES clause.
PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-47','A','시스템개발','システム開発','Waterfall·Agile','Waterfall・Agile','Waterfall은 공정을 순차 진행하고 Agile은 짧은 반복으로 가치와 feedback을 빠르게 반영한다.','Waterfallは工程を順次進め、Agileは短い反復で価値とfeedbackを素早く反映する。','요구 변화 가능성, release 빈도, 고객 참여 수준에 따라 적합성이 달라진다.','要件変更可能性、release頻度、顧客参加度により適性が変わる。','Waterfall=단계별 산출물, Agile=iteration·backlog·increment.','Waterfall=工程別成果物、Agile=iteration・backlog・increment。','변경 빈도와 feedback 요구를 먼저 본다.','変更頻度とfeedback要求を先に見る。','Agile은 문서가 없다는 뜻이 아니고 Waterfall은 변경 불가능이라는 뜻도 아니다.','Agileは文書不要ではなくWaterfallも変更不能ではない。','고정·순차=Waterfall, 반복·feedback=Agile.','固定・順次=Waterfall、反復・feedback=Agile。','요구가 자주 바뀌는 Web service는 짧은 iteration이 유리할 수 있다.','要件変化が多いWeb serviceは短いiterationが有利。',47,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-48','A','시스템개발','システム開発','요구사항 정의','要件定義','사용자와 system이 필요로 하는 기능·품질·제약을 명확하고 검증 가능하게 정리한다.','利用者とsystemが必要とする機能・品質・制約を明確かつ検証可能に整理する。','기능요구와 비기능요구를 구분하고 모호한 표현을 측정 가능한 조건으로 바꾼다.','機能要件と非機能要件を区別し曖昧表現を測定可能条件へ変える。','성능·가용성·보안·사용성은 대표 비기능요구다.','性能・可用性・security・usabilityは代表的非機能要件。','누가 무엇을 어떤 기준으로 해야 하는지 acceptance 기준까지 정의한다.','誰が何をどの基準で行うかacceptance基準まで定義する。','좋아야 한다, 빠르게 같은 비측정 표현을 그대로 두지 않는다.','良い、速い等の非測定表現をそのままにしない。','기능=무엇을, 비기능=얼마나 잘.','機能=何を、非機能=どれだけ良く。','응답시간 95 percentile 2초 이하처럼 측정 가능하게 쓴다.','応答時間95 percentile 2秒以下のように測定可能にする。',48,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-49','A','시스템개발','システム開発','UML','UML','system 구조와 동작을 표준 diagram으로 모델링하는 표기법이다.','systemの構造と動作を標準diagramでmodelingする表記法。','Use Case는 actor와 기능, Class는 정적 구조, Sequence는 시간순 message 흐름을 표현한다.','Use Caseはactorと機能、Classは静的構造、Sequenceは時系列message flowを表す。','Activity·State·Component diagram의 목적도 구분한다.','Activity・State・Component diagramの目的も区別する。','보고 싶은 것이 구조인지 interaction인지 상태변화인지 먼저 판단한다.','構造・interaction・状態変化のどれを見たいか先に判断する。','Sequence를 ER diagram처럼 해석하지 않는다.','SequenceをER diagramのように解釈しない。','Use Case=기능, Class=구조, Sequence=시간.','Use Case=機能、Class=構造、Sequence=時間。','browser→API→DB 호출순서는 Sequence diagram이 적합하다.','browser→API→DBの呼出順はSequence diagramが適する。',49,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-50','A','소프트웨어공학','ソフトウェア工学','테스트 단계','テスト工程','software를 단위부터 system 전체와 사용자 acceptance까지 단계적으로 검증한다.','softwareをunitからsystem全体、user acceptanceまで段階的に検証する。','unit→integration→system→acceptance로 범위가 넓어진다.','unit→integration→system→acceptanceの順に範囲が広がる。','integration은 interface, system은 전체 요구, acceptance는 사용자 관점이 핵심이다.','integrationはinterface、systemは全体要件、acceptanceはuser観点が中心。','검증 대상의 범위를 보고 test level을 판단한다.','検証対象の範囲からtest levelを判断する。','developer가 한다고 모두 unit test는 아니다.','developerが行うから全てunit testではない。','단위→연결→전체→사용자.','unit→接続→全体→user。','두 module 간 API 연결검증은 integration test다.','2 module間API接続検証はintegration test。',50,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-51','A','소프트웨어공학','ソフトウェア工学','동등분할·경계값분석','同値分割・境界値分析','입력 domain을 대표 group으로 나누고 경계 주변을 집중 검사하는 black-box test 설계기법이다.','入力domainを代表groupへ分け境界付近を重点検査するblack-box test設計技法。','동등분할은 대표값, 경계값은 min/max 주변값을 고른다.','同値分割は代表値、境界値はmin/max付近を選ぶ。','유효·무효 class와 경계-1, 경계, 경계+1을 만든다.','有効・無効classと境界-1、境界、境界+1を作る。','조건 범위를 수직선으로 그려 class와 경계를 표시한다.','条件範囲を数直線にしてclassと境界を示す。','경계값분석을 random test와 혼동하지 않는다.','境界値分析をrandom testと混同しない。','대표값=동등분할, 끝점 주변=경계값.','代表値=同値分割、端点付近=境界値。','1~100 유효라면 0,1,2,99,100,101이 대표 경계 후보다.','1～100有効なら0,1,2,99,100,101が代表境界候補。',51,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-52','A','소프트웨어공학','ソフトウェア工学','Review·형상관리','Review・構成管理','review는 산출물 결함을 조기에 찾고 형상관리는 version과 변경을 식별·통제·추적한다.','reviewは成果物欠陥を早期発見し、構成管理はversionと変更を識別・統制・追跡する。','review와 baseline·version·change control을 구분한다.','reviewとbaseline・version・change controlを区別する。','변경요청 승인, 영향분석, version tagging, traceability가 중요하다.','変更要求承認、影響分析、version tagging、traceabilityが重要。','결함검출인지 변경통제인지 먼저 구분한다.','欠陥検出か変更統制かを先に区別する。','backup만 해두면 형상관리라고 볼 수 없다.','backupだけでは構成管理とはいえない。','Review=찾기, 형상관리=바뀐 것 통제.','Review=見つける、構成管理=変更を統制。','release v1.2의 source와 requirement를 함께 추적 가능하게 관리한다.','release v1.2のsourceとrequirementを追跡可能に管理する。',52,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-53','A','프로젝트관리','プロジェクト管理','PERT·Critical Path','PERT・Critical Path','PERT network에서 작업 선후관계와 소요시간으로 project 최소기간과 critical path를 구한다.','PERT networkで作業順序と所要時間からproject最短期間とcritical pathを求める。','critical path는 slack이 0인 경로이며 지연되면 전체기간이 지연된다.','critical pathはslack 0の経路で遅延すると全体期間が遅れる。','forward pass로 earliest, backward pass로 latest, slack=latest-earliest.','forward passでearliest、backward passでlatest、slack=latest-earliest。','모든 시작→끝 경로 시간 또는 node별 earliest/latest를 구한다.','全start→end経路時間またはnode別earliest/latestを求める。','작업 수가 가장 많은 경로가 critical인 것은 아니다.','作業数が最多の経路がcriticalとは限らない。','가장 긴 시간 경로=critical.','最長時間経路=critical。','A 3일 후 B 5일과 C 2일이 병렬이면 긴 B 경로가 완료시점을 좌우한다.','A 3日後B 5日とC 2日が並列なら長いB経路が完了時点を左右する。',53,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-54','A','프로젝트관리','プロジェクト管理','EVM','EVM','PV·EV·AC를 이용해 일정과 비용 performance를 정량평가한다.','PV・EV・ACでscheduleとcost performanceを定量評価する。','SV=EV-PV, CV=EV-AC. 양수면 각각 일정·비용 측면에서 유리하다.','SV=EV-PV、CV=EV-AC。正なら各schedule・cost面で良好。','PV=계획가치, EV=실적가치, AC=실제비용을 구분한다.','PV=計画価値、EV=出来高、AC=実コストを区別する。','먼저 PV/EV/AC를 표에 적고 차이를 계산한다.','まずPV/EV/ACを表へ整理して差を計算する。','EV를 실제 지출액으로 착각하지 않는다.','EVを実支出額と誤解しない。','일정=EV-PV, 비용=EV-AC.','schedule=EV-PV、cost=EV-AC。','EV 80, PV 100이면 SV=-20으로 일정 지연이다.','EV 80、PV 100ならSV=-20でschedule遅延。',54,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-55','A','프로젝트관리','プロジェクト管理','CPI·SPI','CPI・SPI','EVM에서 비용효율과 일정효율을 비율로 나타내는 지표다.','EVMでcost効率とschedule効率を比率で表す指標。','CPI=EV/AC, SPI=EV/PV. 1보다 크면 각각 비용·일정 효율이 좋다.','CPI=EV/AC、SPI=EV/PV。1より大なら各cost・schedule効率が良い。','CPI<1은 비용효율 악화, SPI<1은 계획보다 진척이 늦다는 뜻이다.','CPI<1はcost効率悪化、SPI<1は計画より進捗が遅い。','분자 EV를 고정하고 분모가 AC인지 PV인지 구분한다.','分子EVは共通、分母がACかPVかを区別する。','CPI와 CPU CPI를 혼동하지 않는다.','CPIをCPUのCPIと混同しない。','cost는 AC, schedule은 PV.','costはAC、scheduleはPV。','EV=90, AC=100이면 CPI=0.9다.','EV=90、AC=100ならCPI=0.9。',55,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-56','A','프로젝트관리','プロジェクト管理','위험관리','リスク管理','project 목표에 영향을 줄 불확실성을 식별·분석·대응·monitoring한다.','project目標へ影響する不確実性を識別・分析・対応・monitoringする。','부정위험 대응은 회피·완화·전가·수용이 대표적이다.','負のrisk対応は回避・軽減・転嫁・受容が代表。','발생확률×영향도로 우선순위를 정하고 owner와 대응책을 둔다.','発生確率×影響度で優先順位を付けownerと対応策を定める。','원인 제거, 확률/영향 감소, 제3자 이전, 수용 중 무엇인지 본다.','原因除去、確率/影響低減、第三者移転、受容のどれかを見る。','보험 가입은 위험 제거가 아니라 전가다.','保険加入はrisk除去ではなく転嫁。','없앰=회피, 줄임=완화, 넘김=전가, 감수=수용.','無くす=回避、減らす=軽減、移す=転嫁、受け入れる=受容。','보험으로 금전손실 부담을 넘기는 것은 전가다.','保険で金銭損失負担を移すのは転嫁。',56,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-57','A','서비스관리','サービス管理','SLA·SLM','SLA・SLM','SLA는 service provider와 고객 사이 목표 service level 합의이고 SLM은 이를 지속 관리하는 활동이다.','SLAはproviderと顧客間のservice level合意、SLMはそれを継続管理する活動。','가용성·응답시간·복구시간 등 측정 가능한 SLI/SLO를 정하고 보고·개선한다.','可用性・応答時間・復旧時間等の測定可能SLI/SLOを定め報告・改善する。','SLA는 계약/합의, SLM은 monitoring과 review process다.','SLAは合意、SLMはmonitoringとreview process。','목표수치인지 관리활동인지 구분한다.','目標値か管理活動かを区別する。','SLA를 단순 기술사양서로만 보지 않는다.','SLAを単なる技術仕様書とみなさない。','SLA=약속, SLM=약속 관리.','SLA=約束、SLM=約束管理。','월 가용성 99.9%를 합의하고 매월 측정·review한다.','月間可用性99.9%を合意し毎月測定・reviewする。',57,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-58','A','서비스관리','サービス管理','Incident·Problem','Incident・Problem','incident management는 service를 빠르게 정상화하고 problem management는 근본원인과 재발방지를 다룬다.','incident managementはserviceを迅速復旧し、problem managementは根本原因と再発防止を扱う。','incident의 목표는 신속 복구, problem은 root cause 분석과 known error 관리다.','incidentの目標は迅速復旧、problemはroot cause分析とknown error管理。','workaround은 복구를 빠르게 하지만 root cause 제거와는 다르다.','workaroundは復旧を早めるがroot cause除去とは異なる。','지금 service를 살리는 일인지 재발원인을 제거하는 일인지 구분한다.','今serviceを戻す作業か再発原因除去かを区別する。','원인분석이 끝날 때까지 service 복구를 미루지 않는다.','原因分析完了までservice復旧を遅らせない。','Incident=빨리 복구, Problem=왜 생겼나.','Incident=早く復旧、Problem=なぜ起きたか。','재기동으로 임시복구 후 memory leak 원인을 분석한다.','再起動で暫定復旧後memory leak原因を分析する。',58,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-59','A','시스템감사','システム監査','시스템감사','システム監査','정보system의 통제·안전성·효율성 등을 독립적이고 객관적으로 평가하고 개선을 조언한다.','情報systemの統制・安全性・効率性等を独立かつ客観的に評価し改善を助言する。','감사인은 대상업무로부터 독립성을 확보하고 evidence에 근거해 판단한다.','監査人は対象業務から独立しevidenceに基づき判断する。','audit plan, evidence, finding, recommendation의 흐름을 이해한다.','audit plan、evidence、finding、recommendationの流れを理解する。','감사와 운영책임을 분리해 독립성을 판단한다.','監査と運用責任を分け独立性を判断する。','감사인이 직접 통제를 운영하고 그 결과를 감사하면 독립성 문제가 생긴다.','監査人が自ら統制を運用しその結果を監査すると独立性問題が生じる。','감사=독립·객관·증거.','監査=独立・客観・証拠。','운영부서와 별도 조직이 log·권한자료를 evidence로 확인한다.','運用部門と別組織がlog・権限資料をevidenceとして確認する。',59,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-60','A','시스템감사','システム監査','직무분장·내부통제','職務分掌・内部統制','한 사람이 승인·실행·기록을 모두 장악하지 않도록 역할을 분리해 오류와 부정을 예방·탐지한다.','一人が承認・実行・記録を全て支配しないよう役割を分離し誤謬・不正を予防・検知する。','authorization, custody, recording을 분리하고 중요한 작업에는 dual control을 적용한다.','authorization、custody、recordingを分離し重要作業へdual controlを適用する。','preventive/detective control, access review, approval log가 중요하다.','preventive/detective control、access review、approval logが重要。','한 사람이 거래 생성과 승인까지 가능한지 확인한다.','一人が取引作成と承認まで可能か確認する。','권한 집중을 단순 업무효율 향상으로 보지 않는다.','権限集中を単に効率向上とみなさない。','만든 사람과 승인하는 사람을 나눈다.','作る人と承認する人を分ける。','송금등록자와 최종승인자를 분리한다.','振込登録者と最終承認者を分離する。',60,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-61','A','시스템전략','システム戦略','SWOT','SWOT','조직의 내부 강점·약점과 외부 기회·위협을 구분해 전략을 도출하는 분석기법이다.','組織の内部Strength・Weaknessと外部Opportunity・Threatを区別し戦略を導く分析法。','S/W는 내부, O/T는 외부 환경이다.','S/Wは内部、O/Tは外部環境。','SO·ST·WO·WT 전략 조합으로 활용할 수 있다.','SO・ST・WO・WT戦略組合せへ活用できる。','문장의 요인이 조직 내부인지 외부인지 먼저 본다.','事象が組織内部か外部かを先に見る。','경쟁사 등장 같은 외부요인을 약점으로 분류하지 않는다.','競合登場のような外部要因をWeaknessへ分類しない。','안=SW, 밖=OT.','内=SW、外=OT。','숙련개발자 보유는 Strength, 시장성장은 Opportunity다.','熟練developer保有はStrength、市場成長はOpportunity。',61,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-62','A','경영전략','経営戦略','PPM','PPM','사업을 시장성장률과 상대적 시장점유율로 분류해 자원배분을 검토하는 portfolio 분석이다.','事業を市場成長率と相対市場shareで分類し資源配分を検討するportfolio分析。','Star, Cash Cow, Question Mark, Dog의 4영역을 사용한다.','Star、Cash Cow、Question Mark、Dogの4領域を使う。','성장률 high/low와 점유율 high/low 축을 정확히 조합한다.','成長率high/lowとshare high/low軸を正確に組み合わせる。','두 축을 표로 그린 뒤 분류한다.','2軸を表にして分類する。','매출액 크기만으로 Cash Cow를 판단하지 않는다.','売上高だけでCash Cowを判断しない。','고성장·고점유=Star, 저성장·고점유=Cash Cow.','高成長・高share=Star、低成長・高share=Cash Cow。','성숙시장 high share 사업은 Cash Cow가 될 수 있다.','成熟市場high share事業はCash Cowになり得る。',62,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-63','A','경영전략','経営戦略','5 Forces','5 Forces','산업 수익성과 경쟁강도에 영향을 주는 다섯 경쟁요인을 분석하는 framework다.','業界収益性と競争強度へ影響する5つの競争要因を分析するframework。','기존경쟁, 신규진입, 대체재, 구매자 교섭력, 공급자 교섭력을 본다.','既存競争、新規参入、代替品、買い手交渉力、売り手交渉力を見る。','진입장벽과 switching cost가 각 force에 미치는 영향을 이해한다.','参入障壁とswitching costが各forceへ与える影響を理解する。','사례가 어느 이해관계자/위협인지 연결한다.','事例がどのstakeholder/脅威か対応させる。','SWOT과 같은 내부역량 분석으로 착각하지 않는다.','SWOTのような内部能力分析と混同しない。','경쟁자·신규·대체·고객·공급자.','競合・新規・代替・顧客・供給者。','원재료 공급업체가 소수면 공급자 교섭력이 강해질 수 있다.','原材料supplierが少数なら売り手交渉力が強くなり得る。',63,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-64','A','경영전략','経営戦略','4P·4C','4P・4C','marketing mix를 기업 관점 4P와 고객 관점 4C로 바라보는 framework다.','marketing mixを企業視点4Pと顧客視点4Cで捉えるframework。','4P=Product, Price, Place, Promotion. 4C=Customer value, Cost, Convenience, Communication.','4P=Product, Price, Place, Promotion。4C=Customer value, Cost, Convenience, Communication。','P와 대응하는 C 관계를 이해한다.','Pと対応するCの関係を理解する。','사례의 초점이 제품·가격·유통·촉진 중 무엇인지 판별한다.','事例の焦点が製品・価格・流通・販促のどれか判定する。','Promotion을 할인가격 그 자체와 혼동하지 않는다.','Promotionを値引価格そのものと混同しない。','제품·가격·유통·촉진.','製品・価格・流通・販促。','온라인 판매채널 확대는 Place/Convenience와 관련된다.','online販売channel拡大はPlace/Convenienceに関係する。',64,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-65','A','회계','会計','손익분기점','損益分岐点','매출과 총비용이 같아 이익이 0이 되는 판매량 또는 매출액이다.','売上と総費用が等しく利益0となる販売量または売上高。','단위당 공헌이익=판매단가-단위변동비, BEP수량=고정비/단위공헌이익.','単位限界利益=販売単価-単位変動費、BEP数量=固定費/単位限界利益。','변동비율을 쓰면 BEP매출=고정비/(1-변동비율).','変動費率ならBEP売上=固定費/(1-変動費率)。','고정비와 변동비를 분리하고 공헌이익부터 계산한다.','固定費と変動費を分け限界利益から計算する。','고정비를 판매량으로 다시 곱하지 않는다.','固定費を販売数量で再度掛けない。','가격-변동비=한 개 팔 때 고정비 회수분.','価格-変動費=1個販売時の固定費回収分。','가격100, 변동비60, 고정비4000이면 BEP=100개.','価格100、変動費60、固定費4000ならBEP=100個。',65,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-66','A','회계','会計','ROI·재무지표','ROI・財務指標','투자 대비 이익과 다양한 재무비율로 사업성과와 건전성을 평가한다.','投資に対する利益や各種財務比率で事業成果と健全性を評価する。','ROI=이익/투자액×100. 지표마다 분자·분모 의미를 정확히 읽어야 한다.','ROI=利益/投資額×100。指標ごとの分子・分母を正確に読む。','수익성·안전성·효율성 지표를 구분한다.','収益性・安全性・効率性指標を区別する。','단위와 기간을 맞춘 뒤 비율을 계산한다.','単位と期間をそろえて比率計算する。','매출액과 투자액을 뒤집어 ROI를 계산하지 않는다.','売上高と投資額を逆にしてROI計算しない。','ROI=번 돈/넣은 돈.','ROI=利益/投資。','투자1000, 이익120이면 ROI=12%.','投資1000、利益120ならROI=12%。',66,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-67','A','법무','法務','저작권·특허권','著作権・特許権','저작권은 창작적 표현을, 특허권은 일정 요건을 충족한 기술적 발명을 보호한다.','著作権は創作的表現、特許権は要件を満たす技術的発明を保護する。','저작권은 창작과 동시에 발생하는 것이 원칙이고 특허는 출원·심사를 거쳐 성립한다.','著作権は創作時発生が原則、特許は出願・審査を経て成立する。','idea와 표현의 차이, source code의 저작권, 발명의 신규성·진보성을 구분한다.','ideaと表現の違い、source codeの著作権、発明の新規性・進歩性を区別する。','보호대상이 표현인지 기술적 발명인지 먼저 판단한다.','保護対象が表現か技術的発明か先に判断する。','저작권 보호에 등록이 항상 필수라고 생각하지 않는다.','著作権保護に登録が常に必須と誤解しない。','표현=저작권, 발명=특허.','表現=著作権、発明=特許。','작성한 source code는 저작물로 보호될 수 있다.','作成したsource codeは著作物として保護され得る。',67,1);
INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES ('A-68','A','법무','法務','개인정보·표준화','個人情報・標準化','개인정보를 적법하게 처리하고 표준을 통해 system·제품 간 호환성과 품질을 높이는 개념이다.','個人情報を適法に扱い、標準によりsystem・製品間の互換性と品質を高める概念。','개인정보는 목적명확화·최소수집·안전관리·적절한 제공통제가 중요하고 표준은 공통 규격을 제공한다.','個人情報は目的明確化・最小収集・安全管理・適切な提供統制が重要、標準は共通規格を提供する。','익명화·가명화의 차이, 목적외 이용, 표준의 역할을 이해한다.','匿名化・仮名化の違い、目的外利用、標準の役割を理解する。','data 식별가능성과 처리목적·동의/근거를 확인한다.','dataの識別可能性と処理目的・同意/根拠を確認する。','필요 이상 data를 모으는 것이 안전하다고 보지 않는다.','必要以上のdata収集が安全とは考えない。','개인정보=목적·최소·보호, 표준=공통규칙.','個人情報=目的・最小・保護、標準=共通規則。','서비스 목적에 불필요한 식별번호를 수집하지 않는 것이 최소수집 원칙에 맞다.','service目的に不要な識別番号を収集しないことは最小収集原則に合う。',68,1);

-- Three practical problem types for each concept.
INSERT OR REPLACE INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,1,'기본 개념·계산','基本概念・計算',1 FROM ap_concepts WHERE sort_order BETWEEN 47 AND 68;
INSERT OR REPLACE INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,2,'판단·비교','判断・比較',2 FROM ap_concepts WHERE sort_order BETWEEN 47 AND 68;
INSERT OR REPLACE INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,3,'응용 시나리오','応用シナリオ',3 FROM ap_concepts WHERE sort_order BETWEEN 47 AND 68;

-- One safe seed question per type. Later migrations can replace these with denser concept-specific sets.
INSERT OR REPLACE INTO ap_concept_questions(problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT t.id,1,
  c.title_ko || '에서 가장 먼저 확인해야 할 핵심 개념 또는 판단 기준을 설명하시오.',
  c.title_ja || 'で最初に確認すべき核心概念または判断基準を説明しなさい。',
  NULL,NULL,NULL,
  c.memory_ko,
  c.memory_ja,
  c.definition_ko || ' ' || c.method_ko,
  c.definition_ja || ' ' || c.method_ja,
  CASE WHEN t.type_no=1 THEN 1 WHEN t.type_no=2 THEN 2 ELSE 3 END,
  t.type_no
FROM ap_concept_problem_types t
JOIN ap_concepts c ON c.id=t.concept_id
WHERE c.sort_order BETWEEN 47 AND 68;
