-- 0053 AP Subject B selected learning areas
-- Target: mandatory Information Security + Programming + Database + Network + Information Systems Development
PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO ap_concepts(concept_code,exam_part,unit_ko,unit_ja,title_ko,title_ja,definition_ko,definition_ja,principle_ko,principle_ja,key_points_ko,key_points_ja,method_ko,method_ja,traps_ko,traps_ja,memory_ko,memory_ja,example_ko,example_ja,sort_order,is_published) VALUES
('B-01','B','정보보안','情報セキュリティ','Web 공격 분석','Web攻撃分析','웹 요청, 파라미터, 응답, 로그를 연결해 SQL Injection, XSS, CSRF 등 공격 종류와 영향 범위를 판별하는 능력을 다룬다.','Web要求、parameter、応答、logを関連付け、SQL Injection、XSS、CSRFなどの攻撃種別と影響範囲を判定する。','공격 문자열 자체보다 입력 지점, 서버 처리, 브라우저 실행 여부, 인증 상태를 함께 본다.','攻撃文字列だけでなく入力箇所、server処理、browser実行、認証状態を合わせて確認する。','요청 URL·POST body·Cookie·응답 HTML·DB log를 시간순으로 연결한다.','要求URL・POST body・Cookie・応答HTML・DB logを時系列で関連付ける。','증거→공격유형→성공조건→영향→대책 순서로 정리한다.','証拠→攻撃種別→成立条件→影響→対策の順で整理する。','SQLi와 XSS를 입력값에 특수문자가 있다는 이유만으로 구분하지 않는다.','特殊文字があるだけでSQLiとXSSを判断しない。','DB를 조작하면 SQLi, 브라우저에서 스크립트가 실행되면 XSS, 로그인 상태를 악용하면 CSRF.','DB操作=SQLi、browser script実行=XSS、認証状態悪用=CSRF。','검색 파라미터에 OR 1=1이 들어가고 DB query가 변형됐다면 SQLi를 우선 의심한다.','検索parameterのOR 1=1でDB queryが変形したならSQLiを優先する。',101,1),
('B-02','B','정보보안','情報セキュリティ','인증·MFA 사고 대응','認証・MFAインシデント対応','계정 탈취 징후를 분석하고 비밀번호, OTP, 생체 등 복수 요소를 이용해 인증 강도를 높이는 방법을 다룬다.','アカウント乗っ取り兆候を分析し、password、OTP、生体など複数要素で認証強度を高める。','서로 다른 인증 요소의 조합과 위험 기반 추가 인증을 이해한다.','異なる認証要素の組合せとrisk based追加認証を理解する。','지식·소지·생체 요소를 구분하고 로그인 이력의 IP, 시간, 단말을 비교한다.','知識・所持・生体要素を区別しlogin履歴のIP、時刻、端末を比較する。','의심 로그인 탐지→세션 무효화→자격증명 재설정→MFA 강화 순으로 대응한다.','不審login検知→session無効化→資格情報再設定→MFA強化の順で対応する。','비밀번호+PIN은 둘 다 지식 요소라 진정한 2요소가 아니다.','password+PINは両方知識要素で真の2要素ではない。','다른 종류 두 요소가 MFA.','異なる種類の2要素がMFA。','비밀번호와 스마트폰 OTP 조합은 지식+소지 요소다.','passwordとsmartphone OTPは知識+所持要素。',102,1),
('B-03','B','정보보안','情報セキュリティ','TLS·인증서','TLS・証明書','TLS handshake에서 서버 인증, 키 합의, 암호화 통신이 어떻게 연결되는지 분석한다.','TLS handshakeでserver認証、鍵合意、暗号化通信がどうつながるか分析する。','인증서는 공개키와 주체 정보를 CA 서명으로 묶고, 세션키는 실제 대량 데이터 암호화에 사용된다.','証明書は公開鍵と主体情報をCA署名で結び、session keyを実データ暗号化に使う。','CN/SAN, 유효기간, CA chain, hostname 검증을 확인한다.','CN/SAN、有効期限、CA chain、hostname検証を確認する。','브라우저 경고 원인을 인증서 이름·만료·신뢰체인 순으로 확인한다.','browser警告原因を証明書名・期限・信頼chainの順で確認する。','HTTPS라고 해서 서버의 애플리케이션 취약점이 사라지는 것은 아니다.','HTTPSでもapplication脆弱性はなくならない。','인증서는 서버 신원, TLS는 통신 보호.','証明書はserver身元、TLSは通信保護。','접속 도메인과 SAN이 불일치하면 인증서 경고가 발생할 수 있다.','接続domainとSAN不一致なら証明書警告が起こり得る。',103,1),
('B-04','B','정보보안','情報セキュリティ','전자서명','ディジタル署名','문서의 무결성, 작성자 인증, 부인방지를 위해 해시와 공개키 암호를 조합하는 구조를 다룬다.','文書の完全性、作成者認証、否認防止のためhashと公開鍵暗号を組み合わせる。','송신자는 개인키로 서명하고 수신자는 공개키로 검증한다.','送信者は秘密鍵で署名し受信者は公開鍵で検証する。','원문 hash, 서명값, 인증서의 공개키 관계를 추적한다.','原文hash、署名値、証明書公開鍵の関係を追跡する。','원문 hash를 다시 계산하고 서명에서 얻은 hash와 비교한다.','原文hashを再計算し署名から得たhashと比較する。','기밀성을 위한 암호화와 전자서명의 목적을 혼동하지 않는다.','機密性の暗号化と電子署名の目的を混同しない。','개인키로 서명, 공개키로 검증.','秘密鍵で署名、公開鍵で検証。','문서가 한 글자라도 바뀌면 hash가 달라져 검증에 실패한다.','文書が変わればhashが変化し検証に失敗する。',104,1),
('B-05','B','정보보안','情報セキュリティ','권한관리·최소권한','権限管理・最小権限','업무 역할에 필요한 최소 권한만 부여하고 과도한 권한을 탐지·회수하는 접근통제를 다룬다.','業務roleに必要最小限の権限だけ付与し過剰権限を検出・回収するaccess controlを扱う。','RBAC, least privilege, segregation of duties를 함께 본다.','RBAC、least privilege、職務分掌を合わせて見る。','사용자-역할-권한 매핑과 휴직·퇴직·부서이동 이벤트를 점검한다.','user-role-permission対応と休職・退職・異動eventを確認する。','필요업무를 기준으로 허용권한을 정의하고 차이를 제거한다.','必要業務基準で許可権限を定義し差分を除去する。','관리 편의를 이유로 관리자 권한을 상시 부여하지 않는다.','管理都合で管理者権限を常時付与しない。','필요한 만큼만, 역할 기준으로.','必要な分だけ、role基準。','조회 담당자에게 삭제 권한까지 있다면 최소권한 위반이다.','閲覧担当者に削除権限まであれば最小権限違反。',105,1),
('B-06','B','정보보안','情報セキュリティ','로그 분석','ログ分析','여러 시스템의 시간, IP, 계정, URL, 결과코드를 연결해 침해 흐름을 재구성한다.','複数systemの時刻、IP、account、URL、statusを関連付け侵害経路を再構成する。','단일 로그보다 상관분석이 중요하며 시간 동기화가 전제다.','単一logより相関分析が重要で時刻同期が前提。','인증로그, WAF, Web, DB, OS 로그를 공통키로 연결한다.','認証log、WAF、Web、DB、OS logを共通keyで関連付ける。','최초 이상징후→권한획득→횡적이동→정보접근 순서를 만든다.','最初の異常→権限取得→横展開→情報アクセスの順に並べる。','timezone과 NAT 때문에 IP/시간만으로 사용자를 단정하지 않는다.','timezoneやNATのためIP/時刻だけでuserを断定しない。','시간선과 공통 식별자를 만든다.','timelineと共通識別子を作る。','같은 session ID가 로그인 성공 후 민감 API 호출에 사용되면 연결 가능한 증거다.','同一session IDがlogin後に機密API呼出しに使われれば関連証拠となる。',106,1),
('B-07','B','정보보안','情報セキュリティ','Incident Response','インシデント対応','보안 사고 발생 시 탐지, 격리, 분석, 제거, 복구, 재발방지의 우선순위를 다룬다.','security incident時の検知、隔離、分析、除去、復旧、再発防止の優先順位を扱う。','서비스 지속과 증거보전 사이 균형을 잡으며 확산을 먼저 막는다.','service継続と証拠保全のバランスを取り拡大防止を優先する。','영향범위·공격경로·현재 확산 여부를 파악한다.','影響範囲・攻撃経路・現在の拡大有無を把握する。','격리→증거보전/분석→원인제거→안전 확인 후 복구한다.','隔離→証拠保全/分析→原因除去→安全確認後復旧する。','감염 서버를 즉시 초기화해 증거를 잃지 않도록 한다.','感染serverを即初期化して証拠を失わない。','먼저 확산 차단, 그 다음 원인 제거.','まず拡大防止、その後原因除去。','랜섬웨어 의심 단말은 네트워크에서 우선 격리한다.','ransomware疑い端末はnetworkから先に隔離する。',107,1),
('B-08','B','프로그래밍','プログラミング','배열·반복문 Trace','配列・反復Trace','의사코드의 변수, 배열, 반복 조건을 한 단계씩 추적해 중간값과 최종결과를 구한다.','疑似codeの変数、配列、反復条件を1stepずつ追跡し中間値と最終結果を求める。','초기값과 반복 경계, 갱신 순서가 결과를 결정한다.','初期値、loop境界、更新順序が結果を決める。','표를 만들어 i, 조건, 변경값을 기록한다.','表を作りi、条件、変更値を記録する。','코드를 머리로만 따라가지 말고 실행표를 작성한다.','頭だけで追わず実行表を作成する。','<와 <=, 0시작/1시작을 놓치지 않는다.','<と<=、0始まり/1始まりに注意。','초기값-조건-실행-갱신 순서.','初期値-条件-実行-更新の順。','for i=0..2에서 a[i]+=i라면 각 반복 후 배열을 기록한다.','for i=0..2でa[i]+=iなら各反復後の配列を記録する。',108,1),
('B-09','B','프로그래밍','プログラミング','BFS','BFS','Queue와 visited를 사용해 시작점에서 가까운 정점부터 탐색하는 과정을 추적한다.','Queueとvisitedを用い開始点から近い頂点順に探索する過程を追跡する。','정점을 queue에 넣을 때 방문처리하면 중복 삽입을 막을 수 있다.','頂点をqueueへ入れる時にvisited処理すると重複投入を防げる。','queue 상태와 distance 배열을 함께 기록한다.','queue状態とdistance配列を一緒に記録する。','dequeue→이웃확인→미방문 enqueue 순으로 추적한다.','dequeue→隣接確認→未訪問enqueueの順に追う。','가중치가 다른 최단경로에 BFS를 그대로 적용하지 않는다.','重みが異なる最短路へBFSをそのまま使わない。','BFS=Queue=가까운 곳부터.','BFS=Queue=近い順。','무가중 그래프의 최소 간선 수 경로는 BFS로 구할 수 있다.','無重みgraphの最小辺数経路はBFSで求められる。',109,1),
('B-10','B','프로그래밍','プログラミング','DFS·재귀','DFS・再帰','재귀호출 또는 stack을 이용해 한 경로를 깊게 탐색한 뒤 되돌아오는 흐름을 추적한다.','再帰またはstackで一経路を深く探索し戻る流れを追跡する。','호출 stack의 push/pop과 방문 순서를 구분한다.','call stackのpush/popと訪問順を区別する。','재귀 진입 시점과 반환 시점을 표시한다.','再帰進入時点とreturn時点を記録する。','함수 호출 tree를 그려 순서를 추적한다.','関数call treeを描いて順序を追う。','base case 누락과 visited 누락은 무한재귀 원인이 된다.','base caseやvisited欠落は無限再帰原因。','DFS=깊게, 막히면 되돌아감.','DFS=深く、行き止まりで戻る。','미로 탐색에서 한 방향을 끝까지 따라간 후 backtracking하는 흐름이다.','迷路で一方向を最後まで進みbacktrackingする流れ。',110,1),
('B-11','B','프로그래밍','プログラミング','이분탐색','二分探索','정렬된 배열에서 low, high, mid를 갱신해 탐색 범위를 절반씩 줄이는 과정을 추적한다.','sorted配列でlow、high、midを更新し探索範囲を半分ずつ減らす。','target과 a[mid] 비교 결과에 따라 한쪽 절반을 버린다.','targetとa[mid]比較結果により片側半分を捨てる。','각 회차의 low/high/mid/value를 표로 작성한다.','各回のlow/high/mid/valueを表にする。','경계값 갱신식을 코드와 동일하게 적용한다.','境界更新式をcode通り適用する。','정렬되지 않은 데이터에 적용하지 않는다.','未sort dataへ適用しない。','정렬+절반제거.','sort+半分除去。','mid 값이 target보다 작으면 오름차순 배열에서 low를 오른쪽으로 이동한다.','mid値がtargetより小さければ昇順配列ではlowを右へ移す。',111,1),
('B-12','B','프로그래밍','プログラミング','정렬 Trace','整列Trace','정렬 알고리즘의 각 pass와 비교·교환 결과를 추적해 배열 상태를 구한다.','sort algorithmの各passと比較・交換結果を追跡し配列状態を求める。','알고리즘마다 한 pass의 의미가 다르다.','algorithmごとに1passの意味が異なる。','Bubble, selection, insertion의 비교 범위와 확정 위치를 구분한다.','Bubble、selection、insertionの比較範囲と確定位置を区別する。','문제에 제시된 pseudo code 기준으로 직접 trace한다.','提示pseudo code基準で直接traceする。','알고리즘 이름만 보고 구현 세부를 추측하지 않는다.','algorithm名だけで実装詳細を推測しない。','한 줄씩 실제 swap을 기록.','1行ずつ実際のswapを記録。','bubble sort는 한 pass 후 큰 값이 끝쪽에 확정되는 구현이 흔하다.','bubble sortは1pass後に大値が末尾へ確定する実装が多い。',112,1),
('B-13','B','프로그래밍','プログラミング','동적계획법 DP','動的計画法DP','중복되는 부분문제의 결과를 저장해 전체 문제를 효율적으로 해결하는 방식을 다룬다.','重複部分問題の結果を保存し全体問題を効率化する。','상태 정의, 점화식, 초기값, 계산 순서가 핵심이다.','state定義、漸化式、初期値、計算順が核心。','dp[i]가 무엇을 의미하는지 먼저 문장으로 정의한다.','dp[i]の意味を先に文章で定義する。','작은 상태에서 큰 상태로 채우며 표를 추적한다.','小stateから大stateへ表を埋める。','greedy와 DP를 혼동하지 않는다.','greedyとDPを混同しない。','상태-점화식-초기값-순서.','state-漸化式-初期値-順序。','최단 비용이 이전 두 상태 중 최소값에 현재비용을 더해 결정될 수 있다.','最小costが前2stateの最小値+現在costで決まる場合がある。',113,1),
('B-14','B','프로그래밍','プログラミング','계산량 분석','計算量分析','반복문과 재귀 구조에서 입력 크기 n에 따른 실행 횟수의 증가율을 구한다.','loopと再帰構造から入力nに対する実行回数の増加率を求める。','연속 loop는 합, 중첩 loop는 곱, 절반씩 줄면 log가 핵심이다.','連続loopは和、nested loopは積、半減ならlogが基本。','가장 큰 차수만 남겨 Big-O를 정리한다.','最大次数だけ残しBig-Oを整理する。','각 loop의 반복횟수를 식으로 쓴다.','各loop反復回数を式にする。','모든 이중 loop가 무조건 O(n²)는 아니다.','全二重loopが必ずO(n²)ではない。','반복횟수를 먼저 식으로.','反復回数を先に式化。','i를 매번 2배로 증가시키는 loop는 O(log n)이다.','iを毎回2倍にするloopはO(log n)。',114,1),
('B-17','B','네트워크','ネットワーク','Subnet·CIDR 계산','Subnet・CIDR計算','CIDR prefix를 이용해 network, host 범위, broadcast 주소를 계산한다.','CIDR prefixからnetwork、host範囲、broadcast addressを計算する。','host bit 수=32-prefix, block size와 mask 경계를 이용한다.','host bit数=32-prefix、block sizeとmask境界を使う。','/24,/25,/26,/27,/28의 block size를 빠르게 계산한다.','/24,/25,/26,/27,/28のblock sizeを素早く計算する。','해당 octet의 block 시작값과 끝값을 구한다.','対象octetのblock開始値と終了値を求める。','network와 broadcast를 일반 host로 세지 않는다.','networkとbroadcastを通常hostに数えない。','block 시작=network, 마지막=broadcast.','block開始=network、最後=broadcast。','192.168.1.130/26은 128~191 block에 속한다.','192.168.1.130/26は128～191 blockに属する。',117,1),
('B-18','B','네트워크','ネットワーク','Routing Table','Routing Table','목적지 IP와 routing table을 비교해 가장 긴 prefix가 일치하는 경로를 선택한다.','宛先IPとrouting tableを比較し最長prefix一致の経路を選択する。','longest prefix match가 기본 원칙이다.','longest prefix matchが基本原則。','후보 route들의 prefix 길이와 포함 여부를 비교한다.','候補routeのprefix長と包含関係を比較する。','목적지에 일치하는 route만 남긴 뒤 가장 긴 prefix를 선택한다.','宛先に一致するrouteだけ残し最長prefixを選ぶ。','metric이 낮아도 더 구체적인 prefix가 우선할 수 있다.','metricが低くてもより具体的prefixが優先され得る。','가장 구체적인 경로.','最も具体的な経路。','/24와 /16이 둘 다 일치하면 /24를 선택한다.','/24と/16が両方一致なら/24を選ぶ。',118,1),
('B-19','B','네트워크','ネットワーク','TCP Seq·ACK','TCP Seq・ACK','TCP의 byte stream에서 sequence와 acknowledgment 번호를 데이터 길이와 함께 추적한다.','TCP byte streamでsequenceとacknowledgment番号をdata長とともに追跡する。','ACK 번호는 다음에 받고 싶은 byte 번호를 나타낸다.','ACK番号は次に受信したいbyte番号を表す。','payload 길이, SYN/FIN의 sequence 소비 여부를 구분한다.','payload長、SYN/FINのsequence消費を区別する。','현재 seq + 전송 byte 수를 기준으로 다음 값을 계산한다.','現在seq+送信byte数を基準に次値を計算する。','packet 수가 아니라 byte 수 기준임을 잊지 않는다.','packet数ではなくbyte数基準。','ACK=다음 byte 번호.','ACK=次のbyte番号。','seq=1001에서 500byte를 보내면 정상 수신 후 ACK는 1501이다.','seq=1001から500byte送れば正常受信後ACKは1501。',119,1),
('B-20','B','네트워크','ネットワーク','DNS 장애 분석','DNS障害分析','이름 접속과 IP 직접 접속의 차이, resolver log, cache 상태를 이용해 DNS 장애 위치를 추정한다.','名前接続とIP直接接続の差、resolver log、cache状態からDNS障害箇所を推定する。','IP 접속 성공+이름 접속 실패면 이름해석 계층을 우선 의심한다.','IP接続成功+名前接続失敗なら名前解決層を優先疑う。','client 설정, recursive DNS, authoritative DNS, record를 순서대로 본다.','client設定、recursive DNS、authoritative DNS、recordの順に見る。','nslookup/dig 결과와 TTL, NXDOMAIN을 확인한다.','nslookup/dig結果とTTL、NXDOMAINを確認する。','모든 접속 실패를 DNS 문제로 단정하지 않는다.','全接続失敗をDNS問題と断定しない。','IP는 되는데 이름만 안 되면 DNS 우선.','IP可で名前だけ不可ならDNS優先。','A record 누락 시 이름해석 실패가 발생할 수 있다.','A record欠落で名前解決失敗が起こり得る。',120,1),
('B-21','B','네트워크','ネットワーク','Firewall Rule','Firewall Rule','source, destination, protocol, port, direction을 기반으로 최소허용 firewall rule을 설계하고 충돌을 분석한다.','source、destination、protocol、port、directionで最小許可firewall ruleを設計し競合を分析する。','상단 rule 우선 방식이면 순서가 결과를 바꾼다.','上位rule優先方式では順序が結果を変える。','업무 흐름을 통신 5-tuple로 변환한다.','業務flowを通信5-tupleへ変換する。','필요한 source/destination/port만 허용하고 나머지는 차단한다.','必要source/destination/portだけ許可し残りを遮断する。','any-any 허용은 최소권한 원칙에 어긋난다.','any-any許可は最小権限に反する。','필요한 통신만 좁게 허용.','必要通信だけ狭く許可。','Web 서버에서 DB 5432만 필요하면 해당 방향과 대상을 한정한다.','Web serverからDB 5432だけ必要なら方向と対象を限定する。',121,1),
('B-22','B','네트워크','ネットワーク','VPN·Cloud 연결','VPN・Cloud接続','거점간 또는 원격 사용자와 cloud 사이의 안전한 연결 구조와 routing, 암호화 범위를 판단한다.','拠点間・remote userとcloud間の安全な接続構成、routing、暗号化範囲を判断する。','site-to-site와 remote-access VPN의 목적을 구분한다.','site-to-siteとremote-access VPNの目的を区別する。','tunnel endpoint, route, NAT, 접근대상을 함께 확인한다.','tunnel endpoint、route、NAT、access対象を合わせて確認する。','통신 주체와 보호해야 할 구간을 먼저 그린다.','通信主体と保護区間を先に図示する。','VPN 연결만으로 내부 권한통제가 끝나는 것은 아니다.','VPN接続だけで内部access controlが完了するわけではない。','누가 어디까지 tunnel을 쓰는지 본다.','誰がどこまでtunnelを使うかを見る。','지사와 VPC를 상시 연결하면 site-to-site VPN이 적합할 수 있다.','支社とVPCを常時接続ならsite-to-site VPNが適する場合がある。',122,1),
('B-23','B','데이터베이스','データベース','ER 설계','ER設計','업무 요구에서 entity, attribute, key, 관계, cardinality를 도출해 논리 모델을 만든다.','業務要件からentity、attribute、key、relation、cardinalityを導出し論理modelを作る。','명사 후보를 entity로 보고 식별자와 관계를 검증한다.','名詞候補をentityとし識別子とrelationを検証する。','1:N, M:N, optional 관계를 업무 규칙과 연결한다.','1:N、M:N、optional relationを業務ruleと結び付ける。','문장 속 하나/여러개/반드시/선택 표현을 표시한다.','文章中の1つ/複数/必須/任意表現を拾う。','M:N을 그대로 관계형 테이블 하나에 넣지 않는다.','M:Nをそのまま一tableへ押し込まない。','업무규칙→cardinality.','業務rule→cardinality。','한 주문에 여러 상품, 한 상품이 여러 주문에 속하면 중간 entity가 필요하다.','1注文に複数商品、1商品が複数注文なら中間entityが必要。',123,1),
('B-24','B','데이터베이스','データベース','SQL 결과 추적','SQL結果Trace','JOIN, WHERE, GROUP BY, HAVING, subquery 실행 결과를 단계별로 계산한다.','JOIN、WHERE、GROUP BY、HAVING、subqueryの結果を段階的に計算する。','논리적 처리 순서를 이해하면 결과 행 수와 집계값을 예측하기 쉽다.','論理処理順を理解すると結果行数と集計値を予測しやすい。','FROM/JOIN→WHERE→GROUP BY→HAVING→SELECT 순으로 표를 줄인다.','FROM/JOIN→WHERE→GROUP BY→HAVING→SELECT順に表を絞る。','작은 중간 테이블을 직접 그린다.','小さな中間tableを実際に描く。','LEFT JOIN 후 WHERE의 오른쪽 테이블 조건이 outer join을 사실상 inner처럼 만들 수 있다.','LEFT JOIN後WHEREの右table条件で実質INNER化する場合がある。','중간 결과를 단계별로 만든다.','中間結果を段階的に作る。','HAVING COUNT(*)>=2는 그룹 생성 후 적용한다.','HAVING COUNT(*)>=2はgroup生成後に適用する。',124,1),
('B-25','B','데이터베이스','データベース','정규화','正規化','함수 종속과 후보키를 분석해 중복과 갱신이상을 줄이도록 relation을 분해한다.','関数従属性とcandidate keyを分析し重複・更新異常を減らすようrelationを分解する。','부분함수종속과 이행함수종속을 구분한다.','部分関数従属と推移関数従属を区別する。','키→속성 종속 관계를 화살표로 적는다.','key→attribute依存を矢印で書く。','후보키를 먼저 확정하고 2NF,3NF 위반을 찾는다.','candidate keyを先に確定し2NF、3NF違反を探す。','무조건 테이블을 많이 나누는 것이 정규화 목적이 아니다.','無条件にtableを増やすことが目的ではない。','키와 함수종속부터.','keyと関数従属から。','학번→학과코드, 학과코드→학과명이라면 학과명은 이행종속될 수 있다.','学生番号→学科code、学科code→学科名なら学科名は推移従属し得る。',125,1),
('B-26','B','데이터베이스','データベース','Transaction·Lock','Transaction・Lock','동시 transaction의 read/write 순서를 추적해 lock 충돌, 대기, deadlock을 분석한다.','同時transactionのread/write順を追いlock競合、wait、deadlockを分析する。','S lock과 X lock compatibility, lock 획득 순서가 핵심이다.','S lockとX lock compatibility、lock取得順が核心。','각 transaction별 보유 lock과 대기 lock을 시간순으로 적는다.','transaction別の保持lockと待機lockを時系列で書く。','wait-for graph를 그려 cycle을 확인한다.','wait-for graphを描きcycleを確認する。','대기가 있다고 모두 deadlock은 아니다.','waitがあっても全てdeadlockではない。','서로 상대 lock을 기다리는 cycle이면 deadlock.','互いのlock待ちcycleならdeadlock。','T1이 A를, T2가 B를 잠근 뒤 서로 상대 자원을 요구하면 교착 가능성이 있다.','T1がA、T2がBをlock後に互いの資源を要求するとdeadlock可能性。',126,1),
('B-27','B','데이터베이스','データベース','Isolation 이상현상','Isolation異常','동시 transaction에서 dirty read, non-repeatable read, phantom read가 어떻게 발생하는지 구분한다.','同時transactionでdirty read、non-repeatable read、phantom readの発生を区別する。','같은 행 값 변화와 행 집합 변화의 차이를 본다.','同じ行の値変化と行集合変化を区別する。','누가 commit 전 값을 읽었는지, 같은 query 결과가 어떻게 바뀌었는지 추적한다.','誰がcommit前値を読んだか、同一query結果がどう変化したか追う。','시간선으로 transaction 작업을 배열한다.','timelineでtransaction操作を並べる。','phantom read와 non-repeatable read를 혼동하지 않는다.','phantom readとnon-repeatable readを混同しない。','값이 바뀜=non-repeatable, 행이 생김/사라짐=phantom.','値変化=non-repeatable、行集合変化=phantom。','같은 조건 SELECT의 행 수가 새 INSERT로 바뀌면 phantom이다.','同条件SELECTの行数が新INSERTで変化すればphantom。',127,1),
('B-28','B','데이터베이스','データベース','Index 설계','Index設計','조회 조건, 정렬, selectivity, 갱신 빈도를 보고 적절한 index와 컬럼 순서를 판단한다.','検索条件、sort、selectivity、更新頻度から適切なindexとcolumn順を判断する。','복합 index는 선두 컬럼 사용 방식이 중요하다.','複合indexは先頭column利用が重要。','WHERE/JOIN/ORDER BY와 cardinality를 함께 본다.','WHERE/JOIN/ORDER BYとcardinalityを合わせて見る。','실제 query 패턴 기준으로 후보 index를 비교한다.','実query pattern基準で候補indexを比較する。','index가 많을수록 무조건 빠른 것이 아니다.','indexが多いほど常に速いわけではない。','읽기 이득과 쓰기 비용의 trade-off.','read利得とwrite costのtrade-off。','(user_id, created_at) index는 user_id 조건 후 기간 조회에 유리할 수 있다.','(user_id, created_at) indexはuser_id条件後の期間検索に有利な場合がある。',128,1),
('B-29','B','정보시스템개발','情報システム開発','요구변경 영향분석','要件変更影響分析','요구사항 변경이 화면, API, DB, batch, test, 운영 절차에 미치는 영향을 추적한다.','要件変更が画面、API、DB、batch、test、運用手順へ与える影響を追跡する。','traceability를 이용해 상·하위 산출물의 연결을 본다.','traceabilityで上位・下位成果物の関連を見る。','요구ID와 설계/코드/test case 매핑을 확인한다.','要件IDと設計/code/test case対応を確認する。','변경점→직접영향→간접영향→회귀test 범위를 정한다.','変更点→直接影響→間接影響→regression test範囲を決める。','화면만 바뀌어 보인다고 backend 영향이 없다고 단정하지 않는다.','画面だけの変更に見えてもbackend影響なしと断定しない。','요구에서 DB와 test까지 연결.','要件からDBとtestまでつなぐ。','주소 입력 규칙 변경은 validation, API, DB 길이, test data까지 영향을 줄 수 있다.','住所入力rule変更はvalidation、API、DB長、test dataまで影響し得る。',129,1),
('B-30','B','정보시스템개발','情報システム開発','테스트케이스 설계','テストケース設計','요구조건에서 동등분할, 경계값, 결정표를 이용해 최소한의 효과적인 test case를 도출한다.','要件条件から同値分割、境界値、決定表で効果的なtest caseを導出する。','조건 범위와 조합을 체계적으로 줄이는 것이 핵심이다.','条件範囲と組合せを体系的に減らすことが核心。','유효/무효 class, 경계 직전/경계/직후, 조건 조합을 구분한다.','有効/無効class、境界直前/境界/直後、条件組合せを区別する。','요구문장을 조건과 action으로 분해한다.','要件文をconditionとactionへ分解する。','정상값만 여러 개 넣는 것은 경계 test가 아니다.','正常値だけ複数入れるのは境界testではない。','범위면 경계, 조합이면 결정표.','範囲なら境界、組合せなら決定表。','1~100 허용이면 0,1,100,101이 대표 경계값이다.','1～100許可なら0,1,100,101が代表境界値。',130,1),
('B-31','B','정보시스템개발','情報システム開発','장애 원인분석','障害原因分析','화면 증상, HTTP status, console, server log, DB 결과를 조합해 조사 우선순위를 정한다.','画面症状、HTTP status、console、server log、DB結果を組み合わせ調査優先順位を決める。','관측된 사실로 layer를 좁혀가는 가설검증이 핵심이다.','観測事実からlayerを絞る仮説検証が核心。','client→network→API→service→DB 흐름에서 어디까지 정상인지 확인한다.','client→network→API→service→DBのどこまで正常か確認する。','가장 가까운 실패증거부터 재현·확인한다.','最も近い失敗証拠から再現・確認する。','HTTP 200이라고 frontend가 정상이라는 뜻은 아니다.','HTTP 200でもfrontend正常とは限らない。','정상인 구간을 지워가며 범위를 좁힌다.','正常区間を除外し範囲を狭める。','200+정상 JSON+console undefined라면 frontend data mapping을 먼저 본다.','200+正常JSON+console undefinedならfrontend data mappingを先に見る。',131,1),
('B-32','B','정보시스템개발','情報システム開発','Review·품질관리','Review・品質管理','review 결과와 결함 지표를 이용해 결함이 많이 유입되는 공정과 개선대상을 찾는다.','review結果と欠陥指標から欠陥流入が多い工程と改善対象を特定する。','결함 수뿐 아니라 규모, 검출시점, 원인, 재발성을 함께 본다.','欠陥数だけでなく規模、検出時点、原因、再発性を合わせて見る。','defect density, review effectiveness, escape defect를 비교한다.','defect density、review effectiveness、escape defectを比較する。','상류에서 유입된 결함이 하류에서 발견되는 패턴을 추적한다.','上流流入欠陥が下流で発見されるpatternを追う。','결함이 많이 발견된 공정이 반드시 품질이 나쁜 공정은 아니다.','欠陥が多く発見された工程が必ずしも悪い工程ではない。','발견공정과 유입공정을 구분.','発見工程と混入工程を区別。','시스템 test에서 요구 누락이 반복 발견되면 요구/설계 review 강화가 필요할 수 있다.','system testで要件漏れが繰返し見つかるなら要件/設計review強化が必要。',132,1);

DELETE FROM ap_concept_problem_types WHERE concept_id IN (SELECT id FROM ap_concepts WHERE exam_part='B');

INSERT INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,1,'장문 시나리오 분석','長文シナリオ分析',1 FROM ap_concepts WHERE exam_part='B';
INSERT INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,2,'추적·계산·판단','追跡・計算・判断',2 FROM ap_concepts WHERE exam_part='B';
INSERT INTO ap_concept_problem_types(concept_id,type_no,type_name_ko,type_name_ja,sort_order)
SELECT id,3,'대책·설계 서술','対策・設計記述',3 FROM ap_concepts WHERE exam_part='B';

-- Each selected B concept gets a first exam-style scenario question. Additional multi-part questions are added in the next migration.
INSERT OR REPLACE INTO ap_concept_questions(problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT t.id,1,
'다음 상황을 읽고 이 개념을 이용해 가장 먼저 확인해야 할 정보와 판단 근거를 서술하시오. 상황: 운영 중인 시스템에서 이상 징후가 발생했고 여러 로그와 설정값이 제공되었다. 단순 용어 설명이 아니라 어떤 순서로 무엇을 확인할지 답하시오.',
'次の状況を読み、この概念を用いて最初に確認すべき情報と判断根拠を記述せよ。状況：稼働中systemで異常兆候が発生し、複数のlogと設定値が与えられている。単なる用語説明ではなく、どの順序で何を確認するか答えよ。',
NULL,NULL,NULL,
'문제에 제시된 사실을 시간순 또는 처리흐름 순으로 정리한 뒤, 이 개념의 핵심 판단 기준을 적용해 조사대상과 근거를 제시한다.',
'問題の事実を時系列または処理flow順に整理し、この概念の核心判断基準を適用して調査対象と根拠を示す。',
'과목 B에서는 정답 키워드만 쓰기보다 지문 속 근거와 연결해야 한다. 먼저 정상/비정상 구간을 나누고, 이 개념의 핵심 기준으로 후보를 좁힌 뒤, 답안에는 근거가 되는 로그·값·조건을 함께 적는다.',
'科目Bでは正答keywordだけでなく本文根拠との接続が必要。まず正常/異常区間を分け、概念の判断基準で候補を絞り、解答には根拠となるlog・値・条件も記述する。',3,1
FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.exam_part='B' AND t.type_no=1;
