-- 0054 AP Subject B exam-style scenario questions
-- Adds realistic long-form scenario/subquestion data to selected Subject B concepts.
PRAGMA foreign_keys = ON;

-- B-01 Web attack analysis
UPDATE ap_concept_problem_types SET type_name_ko='장문 로그·요청 분석', type_name_ja='長文ログ・要求分析' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-01') AND type_no=1;
UPDATE ap_concept_problem_types SET type_name_ko='공격 성립조건·영향 추적', type_name_ja='攻撃成立条件・影響追跡' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-01') AND type_no=2;
UPDATE ap_concept_problem_types SET type_name_ko='대책 설계·서술', type_name_ja='対策設計・記述' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-01') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[상황] 쇼핑몰 검색 API에서 q 파라미터가 그대로 SQL 문자열에 연결된다. 10:02:11에 q=%27%20OR%201=1-- 요청 직후 DB 로그에 SELECT * FROM product WHERE name LIKE ''%'' OR 1=1--%'' 가 기록되었다. 이 정황으로 가장 타당한 공격 유형과 근거를 쓰시오.','【状況】ECサイトの検索APIでq parameterがSQL文字列へ直接連結される。10:02:11にq=%27%20OR%201=1--の要求直後、DB logにSELECT * FROM product WHERE name LIKE ''%'' OR 1=1--%''が記録された。最も妥当な攻撃種別と根拠を答えよ。',NULL,NULL,NULL,'SQL Injection. 입력값이 SQL 구문 구조를 변경해 WHERE 조건을 항상 참으로 만들고 있다.','SQL Injection。入力値がSQL構文を変更しWHERE条件を常に真にしている。','문자열에 특수문자가 있다는 사실보다 실제 DB 쿼리 구조가 변형되었는지가 핵심이다. 요청과 DB 로그를 시간순으로 연결하면 공격 성공 가능성을 판단할 수 있다.','特殊文字の存在だけでなく、実際のDB query構造が変形した点が重要。要求とDB logを時系列で関連付けて成立可否を判断する。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-01') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,2,'[소문항] 같은 공격이 성공했을 때 발생 가능한 영향 2가지를 쓰고, 그중 기밀성에 직접 관련된 영향을 하나 고르시오.','【小問】同攻撃が成功した場合に起こり得る影響を2つ挙げ、そのうち機密性に直接関係する影響を一つ選べ。',NULL,NULL,NULL,'예: 인증우회, 데이터 대량조회. 기밀성과 직접 관련된 것은 데이터 대량조회·유출이다.','例：認証回避、データ大量参照。機密性に直接関係するのはデータ大量参照・漏えい。','AP 과목 B에서는 공격명만 맞히는 것보다 영향 범위를 CIA 관점에서 연결하는 문제가 자주 나온다.','科目Bでは攻撃名だけでなく、影響範囲をCIAの観点と結び付けることが重要。',2,2 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-01') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[서술] 이 취약점을 근본적으로 막기 위한 서버 측 대책을 두 가지 쓰시오.','【記述】この脆弱性を根本的に防ぐserver側対策を二つ答えよ。',NULL,NULL,NULL,'Prepared Statement(바인드 변수) 사용, 입력값을 SQL 문법과 분리해 처리. 필요 시 최소권한 DB 계정도 병행.','Prepared Statement（bind変数）の使用、入力値をSQL構文と分離して処理。必要に応じ最小権限DB accountも併用。','핵심 대책은 입력을 단순 이스케이프하는 것보다 SQL 구조와 데이터 값을 분리하는 것이다.','中心対策は単純escapeよりSQL構造とデータ値を分離すること。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-01') AND type_no=3;

-- B-02 Authentication/MFA
UPDATE ap_concept_problem_types SET type_name_ko='로그인 이력·계정탈취 분석', type_name_ja='Login履歴・乗っ取り分析' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-02') AND type_no=1;
UPDATE ap_concept_problem_types SET type_name_ko='인증요소 판단', type_name_ja='認証要素判定' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-02') AND type_no=2;
UPDATE ap_concept_problem_types SET type_name_ko='사고대응·MFA 설계', type_name_ja='Incident対応・MFA設計' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-02') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[상황] 평소 일본에서 접속하던 사용자가 02:10에 해외 IP에서 로그인했고 2분 뒤 이메일과 출금계좌를 변경했다. 기존 세션은 계속 유효하다. 우선 조사할 로그 항목 3가지를 쓰시오.','【状況】普段日本から接続するuserが02:10に海外IPからloginし2分後にmailと振込口座を変更。既存sessionは有効のまま。優先して確認するlog項目を3つ答えよ。',NULL,NULL,NULL,'로그인 IP/국가, 단말·User-Agent 또는 device ID, 로그인 성공시각과 MFA 결과, 세션 ID, 변경 API 호출기록 중 3개.','login IP/国、端末・User-Agentまたはdevice ID、login成功時刻とMFA結果、session ID、変更API呼出し記録のうち3つ。','단일 IP만으로 확정하지 않고 시간·단말·세션·민감 작업을 연결해 계정탈취 흐름을 재구성한다.','単一IPだけで断定せず、時刻・端末・session・機密操作を関連付ける。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-02') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'비밀번호+PIN, 비밀번호+OTP, 지문+얼굴인증 중 서로 다른 인증요소를 조합한 MFA는 어느 것인가? 이유도 쓰시오.','password+PIN、password+OTP、指紋+顔認証のうち異なる認証要素を組み合わせたMFAはどれか。理由も答えよ。',NULL,NULL,NULL,'비밀번호+OTP. 비밀번호는 지식요소, OTP 단말은 소지요소다.','password+OTP。passwordは知識要素、OTP端末は所持要素。','비밀번호+PIN은 둘 다 지식, 지문+얼굴은 둘 다 생체이므로 요소 종류가 다르지 않다.','password+PINは知識同士、指紋+顔は生体同士で要素種類が異ならない。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-02') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[서술] 계정탈취가 의심될 때 즉시 조치 순서를 4단계로 제시하시오.','【記述】account乗っ取り疑い時の即時対応順序を4段階で示せ。',NULL,NULL,NULL,'세션 무효화 → 비밀번호/토큰 재설정 → 의심 로그인·민감 변경 확인 및 복구 → MFA 강화와 재발방지.','session無効化→password/token再設定→不審login・機密変更確認と復旧→MFA強化・再発防止。','서비스를 계속 열어둔 채 비밀번호만 바꾸면 이미 발급된 세션이 남아 있을 수 있다.','password変更だけでは既発行sessionが残る場合がある。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-02') AND type_no=3;

-- B-08 Array/loop trace
UPDATE ap_concept_problem_types SET type_name_ko='의사코드 실행추적', type_name_ja='疑似コード実行Trace' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-08') AND type_no=1;
UPDATE ap_concept_problem_types SET type_name_ko='경계조건·오류분석', type_name_ja='境界条件・誤り分析' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-08') AND type_no=2;
UPDATE ap_concept_problem_types SET type_name_ko='알고리즘 수정 서술', type_name_ja='Algorithm修正記述' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-08') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'배열 a=[3,1,4,1,5]에 대해 s=0으로 시작하고 i=0부터4까지 반복하여 i가 짝수이면 s=s+a[i], 홀수이면 s=s-a[i]를 실행한다. 각 반복 후 s와 최종값을 쓰시오.','配列a=[3,1,4,1,5]、s=0。i=0から4まで、iが偶数ならs=s+a[i]、奇数ならs=s-a[i]。各反復後のsと最終値を答えよ。',NULL,NULL,NULL,'i=0:3, i=1:2, i=2:6, i=3:5, i=4:10. 최종 10.','i=0:3、i=1:2、i=2:6、i=3:5、i=4:10。最終10。','실행표를 만들고 인덱스, 조건판정, 갱신 후 값을 매 단계 적는 것이 안전하다.','実行表でindex、条件判定、更新後値を各step記録する。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-08') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'길이가 n인 배열에서 for i=0; i<=n; i++ 로 a[i]를 읽을 때 발생 가능한 오류와 수정식을 쓰시오.','長さnの配列でfor i=0; i<=n; i++としてa[i]を読む場合の誤りと修正式を答えよ。',NULL,NULL,NULL,'i=n에서 범위를 벗어난다. 조건을 i<n으로 수정한다.','i=nで範囲外。条件をi<nへ修正する。','0부터 시작하는 배열의 마지막 유효 인덱스는 n-1이다.','0始まり配列の最後の有効indexはn-1。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-08') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[서술] 중첩 반복문에서 불필요한 동일 계산을 매번 수행하는 코드가 있다. 과목 B 답안 관점에서 개선방법을 한 문장으로 쓰시오.','【記述】nested loop内で同じ計算を毎回繰り返すcodeがある。科目B答案として改善方法を一文で答えよ。',NULL,NULL,NULL,'반복문 밖에서 한 번 계산 가능한 값은 사전 계산해 변수에 저장하고 내부에서는 재사용한다.','loop外で一度だけ計算可能な値は事前計算して変数へ保存し、内部では再利用する。','복잡도뿐 아니라 가독성과 중복 연산 제거 이유까지 쓰면 서술형 답안이 명확하다.','計算量だけでなく重複演算削減の理由も示すと記述答案が明確。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-08') AND type_no=3;

-- B-09 BFS
UPDATE ap_concept_problem_types SET type_name_ko='Queue·visited 추적', type_name_ja='Queue・visited追跡' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-09') AND type_no=1;
UPDATE ap_concept_problem_types SET type_name_ko='최단거리·복잡도 판단', type_name_ja='最短距離・計算量判定' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-09') AND type_no=2;
UPDATE ap_concept_problem_types SET type_name_ko='구현오류·개선', type_name_ja='実装誤り・改善' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-09') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'그래프 간선이 A-B,A-C,B-D,C-D,D-E이고 인접정점은 알파벳순으로 방문한다. A에서 BFS할 때 dequeue 순서를 쓰시오.','graphの辺がA-B,A-C,B-D,C-D,D-Eで、隣接頂点はalphabet順に訪問する。AからBFSしたときのdequeue順を答えよ。',NULL,NULL,NULL,'A, B, C, D, E.','A, B, C, D, E。','A에서 B,C를 enqueue하고 B 처리 시 D, C 처리 시 D는 이미 visited이므로 중복 삽입하지 않는다.','AでB,Cをenqueue、B処理時D、C処理時Dはvisited済みなので重複enqueueしない。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-09') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'가중치가 없는 그래프에서 BFS가 시작점으로부터 간선 수 기준 최단거리를 구할 수 있는 이유를 쓰시오.','重みなしgraphでBFSが始点から辺数基準の最短距離を求められる理由を答えよ。',NULL,NULL,NULL,'시작점에서 거리 0,1,2… 순으로 같은 레벨의 정점을 먼저 방문하기 때문이다.','始点から距離0,1,2…のlevel順に頂点を訪問するため。','Queue의 FIFO 특성이 레벨 순회를 보장한다.','QueueのFIFO特性がlevel順探索を保証する。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-09') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'visited 표시를 dequeue 시점에만 하면 어떤 문제가 생길 수 있는가?','visitedをdequeue時だけ付けるとどんな問題が起こり得るか。',NULL,NULL,NULL,'같은 정점이 여러 경로에서 반복 enqueue되어 Queue가 불필요하게 커지고 중복처리가 발생할 수 있다.','同じ頂点が複数経路から重複enqueueされQueueが不要に大きくなり重複処理が起こり得る。','보통 enqueue 시점에 visited를 표시해 중복 삽입을 막는다.','通常はenqueue時にvisitedを付け重複挿入を防ぐ。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-09') AND type_no=3;

-- B-17 Subnet/CIDR
UPDATE ap_concept_problem_types SET type_name_ko='CIDR 계산', type_name_ja='CIDR計算' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-17') AND type_no=1;
UPDATE ap_concept_problem_types SET type_name_ko='주소범위·할당 판단', type_name_ja='Address範囲・割当判定' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-17') AND type_no=2;
UPDATE ap_concept_problem_types SET type_name_ko='서브넷 설계 서술', type_name_ja='Subnet設計記述' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-17') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'192.168.10.130/26의 네트워크 주소, 브로드캐스트 주소, 사용 가능한 호스트 범위를 쓰시오.','192.168.10.130/26のnetwork address、broadcast address、利用可能host範囲を答えよ。',NULL,NULL,NULL,'네트워크 192.168.10.128, 브로드캐스트 192.168.10.191, 호스트 192.168.10.129~190.','network 192.168.10.128、broadcast 192.168.10.191、host 192.168.10.129～190。','/26은 블록크기 64이므로 0,64,128,192 경계 중 130이 포함된 128~191 블록이다.','/26はblock size64。0,64,128,192の境界で130は128～191に含まれる。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-17') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'호스트 50대를 수용하려면 IPv4에서 최소 몇 bit의 host부가 필요하며 prefix는 몇인가?','host 50台を収容するにはIPv4で最低何bitのhost部が必要でprefixはいくつか。',NULL,NULL,NULL,'6bit, /26. 2^6-2=62개의 호스트를 사용할 수 있다.','6bit、/26。2^6-2=62 hostを利用できる。','네트워크와 브로드캐스트 주소 2개를 제외한다.','networkとbroadcastの2addressを除く。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-17') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[서술] 부서별 주소를 나눌 때 필요 호스트 수가 서로 다르면 동일 크기 서브넷보다 VLSM이 유리한 이유를 쓰시오.','【記述】部署ごとの必要host数が異なる場合、固定長subnetよりVLSMが有利な理由を答えよ。',NULL,NULL,NULL,'부서별 필요한 크기에 맞게 prefix를 다르게 할당해 주소 낭비를 줄일 수 있기 때문이다.','部署ごとに必要サイズに応じprefixを変えて割り当てaddress浪費を減らせるため。','설계형에서는 단순 정의보다 요구수량과 주소 효율을 연결해 서술한다.','設計問題では定義だけでなく要求数とaddress効率を結び付けて記述する。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-17') AND type_no=3;

-- B-18 Routing
UPDATE ap_concept_problem_types SET type_name_ko='Routing Table 추적', type_name_ja='Routing Table追跡' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-18') AND type_no=1;
UPDATE ap_concept_problem_types SET type_name_ko='최장 prefix 판단', type_name_ja='Longest Prefix判定' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-18') AND type_no=2;
UPDATE ap_concept_problem_types SET type_name_ko='경로설계·장애분석', type_name_ja='経路設計・障害分析' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-18') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'Routing table에 10.0.0.0/8→A, 10.10.0.0/16→B, 10.10.20.0/24→C, default→D가 있다. 목적지 10.10.20.55의 next hop은? 이유도 쓰시오.','Routing tableに10.0.0.0/8→A、10.10.0.0/16→B、10.10.20.0/24→C、default→Dがある。宛先10.10.20.55のnext hopは何か。理由も答えよ。',NULL,NULL,NULL,'C. 일치하는 경로 중 prefix 길이가 가장 긴 /24가 선택된다.','C。一致routeの中でprefix長が最も長い/24が選択される。','metric 비교보다 먼저 longest prefix match가 적용된다.','metric比較より先にlongest prefix matchを適用する。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-18') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'목적지에 /16 경로와 /24 경로가 모두 일치하지만 /16의 metric이 더 작다. 일반적인 IP routing에서 어느 경로가 우선인가?','宛先に/16と/24のrouteが共に一致し、/16のmetricが小さい。一般的なIP routingではどちらが優先か。',NULL,NULL,NULL,'/24 경로. 먼저 더 구체적인 prefix가 선택된다.','/24 route。まずより具体的なprefixが選択される。','같은 prefix 길이 후보끼리 metric을 비교하는 것으로 이해하면 안전하다.','同じprefix長の候補同士でmetricを比較すると理解するとよい。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-18') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[장애] 특정 /24 대역만 통신되지 않고 상위 /16 대역은 정상이다. 우선 확인할 설정을 쓰시오.','【障害】特定/24帯だけ通信不可で上位/16帯は正常。優先して確認する設定を答えよ。',NULL,NULL,NULL,'해당 /24의 정적·동적 라우팅 엔트리와 next hop, ACL을 우선 확인한다.','該当/24の静的・動的route entryとnext hop、ACLを優先確認する。','더 구체적인 경로가 잘못 등록되면 상위 /16 정상 여부와 무관하게 해당 대역만 영향받을 수 있다.','より具体的routeが誤登録されると上位/16正常でも該当帯だけ影響し得る。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-18') AND type_no=3;

-- B-23 ER design
UPDATE ap_concept_problem_types SET type_name_ko='요구사항→ER 도출', type_name_ja='要件→ER導出' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-23') AND type_no=1;
UPDATE ap_concept_problem_types SET type_name_ko='카디널리티·키 판단', type_name_ja='Cardinality・Key判定' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-23') AND type_no=2;
UPDATE ap_concept_problem_types SET type_name_ko='M:N 해소·설계', type_name_ja='M:N解消・設計' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-23') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[요구사항] 한 고객은 여러 주문을 할 수 있고, 한 주문은 한 고객에게만 속한다. 한 주문에는 여러 상품이 포함되고 한 상품도 여러 주문에 포함된다. 필요한 엔터티와 관계를 쓰시오.','【要件】1顧客は複数注文可能、1注文は1顧客だけに属する。1注文には複数商品が含まれ、1商品も複数注文に含まれる。必要entityとrelationを答えよ。',NULL,NULL,NULL,'고객, 주문, 상품, 주문상세(중간 엔터티). 고객1:N주문, 주문1:N주문상세, 상품1:N주문상세.','顧客、注文、商品、注文明細（中間entity）。顧客1:N注文、注文1:N注文明細、商品1:N注文明細。','주문-상품의 M:N 관계를 주문상세로 해소하는 것이 핵심이다.','注文-商品のM:N relationを注文明細で解消するのが核心。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-23') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'주문 테이블에 고객ID를 외래키로 두는 이유를 참조무결성 관점에서 쓰시오.','注文tableに顧客IDをforeign keyとして持つ理由を参照整合性の観点で答えよ。',NULL,NULL,NULL,'존재하지 않는 고객을 참조하는 주문이 생성되는 것을 방지하기 위해서다.','存在しない顧客を参照する注文の作成を防ぐため。','외래키는 단순 JOIN 편의가 아니라 참조무결성 제약이라는 점을 기억한다.','foreign keyはJOIN便利機能ではなく参照整合性制約。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-23') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'주문상세의 기본키 후보를 하나 제시하고 이유를 쓰시오.','注文明細のprimary key候補を一つ示し理由を答えよ。',NULL,NULL,NULL,'(주문ID, 상품ID) 복합키. 동일 주문 내 동일 상품 행을 식별할 수 있다. 별도 상세ID를 PK로 두고 UNIQUE(주문ID,상품ID)를 둘 수도 있다.','(注文ID,商品ID)複合key。同一注文内の商品行を識別できる。別途明細IDをPKとしUNIQUE(注文ID,商品ID)も可。','요구사항에 동일 상품을 여러 행으로 허용하는지에 따라 설계가 달라질 수 있음을 언급하면 좋다.','同一商品を複数行許容する要件かで設計が変わる点も重要。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-23') AND type_no=3;

-- B-24 SQL trace
UPDATE ap_concept_problem_types SET type_name_ko='JOIN 결과 추적', type_name_ja='JOIN結果追跡' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-24') AND type_no=1;
UPDATE ap_concept_problem_types SET type_name_ko='GROUP BY·서브쿼리 계산', type_name_ja='GROUP BY・Subquery計算' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-24') AND type_no=2;
UPDATE ap_concept_problem_types SET type_name_ko='쿼리 수정·설계', type_name_ja='Query修正・設計' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-24') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'Customer(id,name)={(1,A),(2,B),(3,C)}, Order(customer_id,amount)={(1,100),(1,200),(2,50)}일 때 LEFT JOIN 후 고객별 SUM(amount)를 구하면 각 고객 결과는?','Customer(id,name)={(1,A),(2,B),(3,C)}, Order(customer_id,amount)={(1,100),(1,200),(2,50)}。LEFT JOIN後に顧客別SUM(amount)を求めた結果は? ',NULL,NULL,NULL,'A=300, B=50, C=NULL. COALESCE를 쓰면 C=0으로 표시 가능하다.','A=300、B=50、C=NULL。COALESCEを使えばC=0表示可能。','LEFT JOIN은 주문 없는 C도 남지만 SUM의 입력이 NULL뿐이면 결과는 NULL이다.','LEFT JOINで注文なしCも残るがSUM入力がNULLのみなら結果はNULL。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-24') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'주문 합계가 100 이상인 고객만 구하려면 WHERE와 HAVING 중 어느 쪽에 SUM(amount)>=100 조건을 두어야 하는가?','注文合計100以上の顧客だけ求めるにはSUM(amount)>=100条件をWHEREとHAVINGのどちらに置くか。',NULL,NULL,NULL,'HAVING. 집계가 끝난 그룹 결과에 조건을 적용하기 때문이다.','HAVING。集計後のgroup結果へ条件適用するため。','WHERE는 그룹화 이전 행에 적용된다.','WHEREはgroup化前の行に適用される。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-24') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'주문 없는 고객도 0으로 표시하도록 집계 SQL을 설계할 때 필요한 핵심 요소를 쓰시오.','注文なし顧客も0表示する集計SQLの重要要素を答えよ。',NULL,NULL,NULL,'Customer 기준 LEFT JOIN과 COALESCE(SUM(amount),0)를 사용한다.','Customer基準LEFT JOINとCOALESCE(SUM(amount),0)を使う。','INNER JOIN을 쓰면 주문 없는 고객 자체가 사라진다.','INNER JOINでは注文なし顧客自体が消える。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-24') AND type_no=3;

-- B-26 Transaction/Lock
UPDATE ap_concept_problem_types SET type_name_ko='Lock 순서 추적', type_name_ja='Lock順序追跡' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-26') AND type_no=1;
UPDATE ap_concept_problem_types SET type_name_ko='Deadlock 판정', type_name_ja='Deadlock判定' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-26') AND type_no=2;
UPDATE ap_concept_problem_types SET type_name_ko='동시성 제어 개선', type_name_ja='同時実行制御改善' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-26') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'T1이 A를 X-lock 후 B를 기다리고, T2가 B를 X-lock 후 A를 기다린다. 현재 상태를 설명하시오.','T1がAをX-lock後B待ち、T2がBをX-lock後A待ち。現在状態を説明せよ。',NULL,NULL,NULL,'Deadlock. T1↔T2 사이에 순환대기가 형성되어 서로 진행할 수 없다.','Deadlock。T1↔T2に循環待ちが形成され相互に進めない。','대기그래프에 cycle이 있는지 보면 빠르게 판단할 수 있다.','wait-for graphのcycle有無で判断できる。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-26') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'위 deadlock을 예방하는 대표적인 설계 방법을 하나 쓰시오.','上記deadlockを予防する代表的設計方法を一つ答えよ。',NULL,NULL,NULL,'모든 트랜잭션이 A→B처럼 동일한 순서로 자원을 잠그도록 규칙화한다.','全transactionでA→Bのように同一順序でresourceをlockする。','lock 순서를 통일하면 순환대기 조건을 깨는 데 도움이 된다.','lock順序統一で循環待ち条件を崩せる。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-26') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[서술] 긴 트랜잭션이 많은 시스템에서 lock 경합을 줄이는 방법을 두 가지 쓰시오.','【記述】長いtransactionが多いsystemでlock競合を減らす方法を二つ答えよ。',NULL,NULL,NULL,'트랜잭션 범위를 짧게 하고 불필요한 사용자 대기시간을 트랜잭션 밖으로 이동한다. 필요한 행만 잠그고 적절한 인덱스를 사용해 잠금 범위를 줄인다.','transaction範囲を短くしuser待ちを外へ出す。必要行だけlockし適切なindexでlock範囲を減らす。','무조건 isolation level을 낮추는 답보다 일관성 요구를 유지하면서 경합 원인을 줄이는 답이 안전하다.','単純にisolation levelを下げるより整合性要件を維持し競合原因を減らす答案が安全。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-26') AND type_no=3;

-- B-29 Requirement change impact
UPDATE ap_concept_problem_types SET type_name_ko='요구변경 영향분석', type_name_ja='要件変更影響分析' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-29') AND type_no=1;
UPDATE ap_concept_problem_types SET type_name_ko='설계·DB·API 연계추적', type_name_ja='設計・DB・API連携追跡' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-29') AND type_no=2;
UPDATE ap_concept_problem_types SET type_name_ko='테스트·릴리스 계획', type_name_ja='Test・Release計画' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-29') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[상황] 기존 주문상태가 NEW, PAID, SHIPPED 세 가지였는데 CANCELED가 추가된다. 화면, API, DB, 배치, 테스트 관점에서 영향항목을 각각 하나씩 쓰시오.','【状況】既存注文statusがNEW, PAID, SHIPPEDの3種でCANCELEDを追加する。画面、API、DB、batch、test観点で影響項目を各一つ答えよ。',NULL,NULL,NULL,'화면: 상태표시/취소버튼, API: 상태검증·전이, DB: CHECK/코드마스터, 배치: 집계·추출조건, 테스트: 신규 상태와 기존 상태 회귀테스트.','画面:status表示/取消button、API:status検証・遷移、DB:CHECK/code master、batch:集計・抽出条件、test:新statusと既存status回帰test。','요구변경은 한 레이어만 보는 것이 아니라 데이터 흐름 전체를 따라 영향도를 추적한다.','要件変更は1layerだけでなくdata flow全体で影響追跡する。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-29') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'CANCELED 상태가 추가됐지만 DB 컬럼 길이는 충분하다. 그래도 DB 영향분석이 필요한 이유를 쓰시오.','CANCELED status追加でDB column長は十分。それでもDB影響分析が必要な理由を答えよ。',NULL,NULL,NULL,'CHECK 제약, 코드마스터, 인덱스 조건, 통계/뷰/프로시저 등 값의 의미에 의존하는 객체가 있을 수 있기 때문이다.','CHECK制約、code master、index条件、view/procedure等が値意味に依存している可能性があるため。','스키마 길이만 맞는다고 데이터 모델 영향이 없는 것은 아니다.','schema長だけでdata model影響なしとは言えない。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-29') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[서술] 요구변경 배포 전 최소한 수행해야 할 테스트 범위를 신규기능과 회귀 관점에서 쓰시오.','【記述】要件変更release前に最低限実施すべきtest範囲を新機能と回帰の観点で答えよ。',NULL,NULL,NULL,'CANCELED 생성·전이·표시·집계의 신규 테스트와 NEW/PAID/SHIPPED 기존 흐름이 깨지지 않는 회귀 테스트를 수행한다.','CANCELED生成・遷移・表示・集計の新規testと、NEW/PAID/SHIPPED既存flowが壊れない回帰testを行う。','과목 B에서는 변경점 자체와 주변 영향 범위를 함께 쓰는 답안이 좋다.','科目Bでは変更点自体と周辺影響範囲を併記する答案がよい。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-29') AND type_no=3;

-- B-30 Test case design
UPDATE ap_concept_problem_types SET type_name_ko='동등분할·경계값 설계', type_name_ja='同値分割・境界値設計' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-30') AND type_no=1;
UPDATE ap_concept_problem_types SET type_name_ko='결정표·조합 테스트', type_name_ja='Decision Table・組合せTest' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-30') AND type_no=2;
UPDATE ap_concept_problem_types SET type_name_ko='회귀·우선순위 설계', type_name_ja='Regression・優先順位設計' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-30') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'나이 입력 허용범위가 18~65(포함)일 때 경계값 분석으로 우선 테스트할 값을 쓰시오.','年齢入力許容範囲18～65（含む）のとき境界値分析で優先testする値を答えよ。',NULL,NULL,NULL,'17,18,19,64,65,66.','17,18,19,64,65,66。','하한·상한 바로 아래, 경계값, 바로 위를 본다.','下限・上限の直前、境界、直後を見る。',1,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-30') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'무료배송 조건이 회원 여부와 구매금액 5,000엔 이상 여부의 조합으로 결정된다. 네 조합을 빠짐없이 테스트하는 데 적합한 기법은? 이유도 쓰시오.','送料無料条件が会員か否かと購入額5000円以上か否かの組合せで決まる。4組合せを漏れなくtestするのに適した技法と理由を答えよ。',NULL,NULL,NULL,'결정표. 여러 조건 조합과 결과를 체계적으로 열거할 수 있다.','Decision Table。複数条件の組合せと結果を体系的に列挙できる。','조건이 2개 이상이고 조합별 행동이 달라질 때 결정표가 유용하다.','条件が複数で組合せごとにactionが変わる場合に有効。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-30') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[서술] 결제 로직을 수정했을 때 신규 테스트 외에 회귀 테스트 우선순위를 정하는 기준을 두 가지 쓰시오.','【記述】決済logic修正時、新規test以外の回帰test優先順位基準を二つ答えよ。',NULL,NULL,NULL,'변경 코드와 직접 연결된 기능, 장애 시 영향이 큰 핵심 결제 흐름을 우선한다. 과거 결함이 잦은 영역도 우선순위가 높다.','変更codeと直接関連する機能、障害影響が大きい主要決済flowを優先。過去欠陥多発領域も優先度が高い。','위험 기반 테스트 관점으로 영향도와 발생가능성을 함께 고려한다.','risk based testとして影響度と発生可能性を合わせて考える。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-30') AND type_no=3;

-- B-31 Incident root-cause analysis
UPDATE ap_concept_problem_types SET type_name_ko='로그·증상 우선순위 분석', type_name_ja='Log・症状優先順位分析' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-31') AND type_no=1;
UPDATE ap_concept_problem_types SET type_name_ko='원인구간 분리', type_name_ja='原因区間切分け' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-31') AND type_no=2;
UPDATE ap_concept_problem_types SET type_name_ko='재발방지·관측성 개선', type_name_ja='再発防止・Observability改善' WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-31') AND type_no=3;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[상황] 화면 목록이 비어 있다. Network는 HTTP 200, Response JSON에는 20건, backend error log는 없음, browser console에는 Cannot read properties of undefined가 있다. 조사 우선순위를 쓰시오.','【状況】画面一覧が空。NetworkはHTTP200、Response JSONに20件、backend error logなし、browser consoleにCannot read properties of undefined。調査優先順位を答えよ。',NULL,NULL,NULL,'프론트의 response mapping/렌더링 코드 → undefined가 발생한 객체/필드 → 타입·조건분기 → 필요 시 API 계약 확인 순으로 본다.','frontendのresponse mapping/render code→undefined対象object/field→type・条件分岐→必要ならAPI契約確認の順。','서버 응답 자체는 정상 증거가 강하므로 먼저 클라이언트 데이터 처리 경로를 확인한다.','server response正常の証拠が強いためclient data処理経路を先に確認する。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-31') AND type_no=1;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'HTTP 200만으로 백엔드가 완전히 정상이라고 단정할 수 없는 이유를 쓰시오.','HTTP200だけでbackendが完全正常と断定できない理由を答えよ。',NULL,NULL,NULL,'응답 스키마나 값의 의미가 계약과 다를 수 있고, 정상 status로 오류 내용을 반환하는 잘못된 구현도 가능하기 때문이다.','response schemaや値意味が契約と異なる可能性や、正常statusでerror内容を返す誤実装もあり得るため。','증거에 따라 우선순위를 정하되 가능성을 완전히 배제하지 않는 것이 장애분석의 기본이다.','証拠で優先順位を付けつつ可能性を完全排除しないのが障害分析の基本。',2,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-31') AND type_no=2;
INSERT OR REPLACE INTO ap_concept_questions SELECT NULL,id,1,'[서술] 같은 장애의 재발 원인 파악 시간을 줄이기 위한 관측성 개선을 두 가지 쓰시오.','【記述】同様障害の原因特定時間を短縮するobservability改善を二つ答えよ。',NULL,NULL,NULL,'프론트 error tracking에 stack trace와 request ID를 남기고, backend/API log와 동일 correlation ID로 연결한다. 응답 스키마 검증도 자동화한다.','frontend error trackingへstack traceとrequest IDを記録し、backend/API logと同一correlation IDで連携。response schema検証も自動化する。','장애 재발방지는 코드 수정뿐 아니라 진단 가능한 로그·추적성까지 포함한다.','再発防止はcode修正だけでなく診断可能なlog・traceabilityも含む。',3,1 FROM ap_concept_problem_types WHERE concept_id=(SELECT id FROM ap_concepts WHERE concept_code='B-31') AND type_no=3;
