-- 0071 AP Subject A network/security exam-style bank (A-33..A-46)

-- Validated AP Subject A four-choice questions.

-- Replaces generic/open-ended seed question_no=1 for targeted concepts.

PRAGMA foreign_keys = ON;



INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'IP 주소를 사용해 패킷의 경로를 결정하는 OSI 계층은?','IPアドレスを用いてパケットの経路を決定するOSI層はどれか。','["データリンク層","ネットワーク層","トランスポート層","セッション層"]','["データリンク層","ネットワーク層","トランスポート層","セッション層"]',1,'네트워크 계층','ネットワーク層','IP 주소와 라우팅은 L3의 역할이다.','IPアドレスとルーティングはネットワーク層（L3）の役割である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-33' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'TCP/UDP의 포트 번호가 속하는 계층으로 가장 적절한 것은?','TCP/UDPのポート番号を扱う層はどれか。','["物理層","データリンク層","ネットワーク層","トランスポート層"]','["物理層","データリンク層","ネットワーク層","トランスポート層"]',3,'전송 계층','トランスポート層','포트 번호는 L4에서 애플리케이션 종단점을 구분한다.','ポート番号はトランスポート層でアプリケーションの終端を識別する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-33' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'송신 시 애플리케이션 데이터에 TCP 헤더와 IP 헤더가 차례로 붙는 과정은?','送信時，アプリケーションデータにTCPヘッダ，IPヘッダが順に付加される処理はどれか。','["カプセル化","フラグメンテーション","ルーティング","名前解決"]','["カプセル化","フラグメンテーション","ルーティング","名前解決"]',0,'캡슐화','カプセル化','하위 계층으로 내려가며 각 계층 헤더가 추가되는 것이 캡슐화다.','下位層へ渡す際に各層のヘッダを付加する処理がカプセル化である。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-33' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'IPv4 주소가 /26일 때 서브넷 마스크는?','IPv4アドレスのプレフィックス長が/26のとき，サブネットマスクはどれか。','["255.255.255.0","255.255.255.128","255.255.255.192","255.255.255.224"]','["255.255.255.0","255.255.255.128","255.255.255.192","255.255.255.224"]',2,'255.255.255.192','255.255.255.192','/26은 마지막 옥텟의 상위 2비트가 1이므로 11000000₂=192다.','/26では最終オクテットの上位2ビットが1なので，11000000₂=192となる。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-34' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'일반적인 IPv4 /27 서브넷에서 사용 가능한 호스트 주소 수는?','通常のIPv4 /27サブネットで使用可能なホストアドレス数は幾つか。','["14","30","32","62"]','["14","30","32","62"]',1,'30','30','호스트 비트가 5개이므로 2^5-2=30이다.','ホスト部は5ビットなので，2^5-2=30である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-34' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'10.0.0.0/24를 같은 크기의 4개 서브넷으로 나눌 때 새 프리픽스는?','10.0.0.0/24を同じ大きさの4個のサブネットに分割するとき，新しいプレフィックス長はどれか。','["/25","/26","/27","/28"]','["/25","/26","/27","/28"]',1,'/26','/26','4개로 나누려면 2비트를 빌리므로 /24→/26이다.','4分割には2ビット借用するので，/24から/26になる。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-34' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'192.168.1.70/26의 네트워크 주소는?','192.168.1.70/26のネットワークアドレスはどれか。','["192.168.1.0","192.168.1.64","192.168.1.70","192.168.1.127"]','["192.168.1.0","192.168.1.64","192.168.1.70","192.168.1.127"]',1,'192.168.1.64','192.168.1.64','/26의 블록 크기는 64이고 70은 64~127 범위에 속한다.','/26のブロックサイズは64であり，70は64～127の範囲に属する。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-35' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'192.168.1.130/26의 브로드캐스트 주소는?','192.168.1.130/26のブロードキャストアドレスはどれか。','["192.168.1.127","192.168.1.128","192.168.1.191","192.168.1.255"]','["192.168.1.127","192.168.1.128","192.168.1.191","192.168.1.255"]',2,'192.168.1.191','192.168.1.191','130은 128~191 블록에 있으므로 마지막 주소 191이 브로드캐스트다.','130は128～191のブロックに属するので，末尾の191がブロードキャストアドレスである。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-35' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'최소 50대의 호스트를 수용해야 할 때 가장 작은 일반 IPv4 서브넷은?','50台以上のホストを収容するための最小の通常IPv4サブネットはどれか。','["/25","/26","/27","/28"]','["/25","/26","/27","/28"]',1,'/26','/26','/27은 30개로 부족하고 /26은 62개를 사용할 수 있다.','/27は30台で不足し，/26なら62台を収容できる。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-35' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'데이터의 순서 보장과 재전송 기능을 표준으로 제공하는 프로토콜은?','データの順序制御と再送制御を標準で提供するプロトコルはどれか。','["IP","TCP","UDP","ARP"]','["IP","TCP","UDP","ARP"]',1,'TCP','TCP','TCP는 연결지향이며 순서제어와 재전송을 제공한다.','TCPはコネクション型で，順序制御と再送制御を行う。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-36' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'TCP 연결 설정의 3-way handshake 순서는?','TCPのコネクション確立時の3ウェイハンドシェイクの順序はどれか。','["SYN→ACK→SYN/ACK","SYN→SYN/ACK→ACK","ACK→SYN→SYN/ACK","SYN/ACK→SYN→ACK"]','["SYN→ACK→SYN/ACK","SYN→SYN/ACK→ACK","ACK→SYN→SYN/ACK","SYN/ACK→SYN→ACK"]',1,'SYN→SYN/ACK→ACK','SYN→SYN/ACK→ACK','클라이언트 SYN, 서버 SYN/ACK, 클라이언트 ACK 순이다.','クライアントのSYN，サーバのSYN/ACK，クライアントのACKの順である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-36' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'일부 패킷 손실보다 지연 감소가 중요한 실시간 음성 전송에 일반적으로 적합한 것은?','一部のパケット損失より遅延低減を重視するリアルタイム音声に，一般に適するプロトコルはどれか。','["TCP","UDP","ICMP","ARP"]','["TCP","UDP","ICMP","ARP"]',1,'UDP','UDP','UDP는 연결 설정과 재전송 오버헤드가 작아 실시간 전송에 자주 사용된다.','UDPはコネクション確立や再送のオーバヘッドが小さく，リアルタイム通信で用いられることが多い。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-36' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'호스트명에서 IP 주소를 얻기 위해 사용하는 서비스는?','ホスト名からIPアドレスを得るために使用するサービスはどれか。','["DNS","DHCP","NTP","SNMP"]','["DNS","DHCP","NTP","SNMP"]',0,'DNS','DNS','DNS가 이름을 IP 주소로 해석한다.','DNSはホスト名をIPアドレスへ名前解決する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-37' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'PC가 IP 주소, 기본 게이트웨이, DNS 서버 주소를 자동으로 받지 못할 때 우선 확인할 서비스는?','PCがIPアドレス，デフォルトゲートウェイ，DNSサーバアドレスを自動取得できないとき，最初に確認すべきサービスはどれか。','["DHCP","DNS","HTTP","SMTP"]','["DHCP","DNS","HTTP","SMTP"]',0,'DHCP','DHCP','DHCP가 IP 설정 정보를 자동 배포한다.','DHCPはIP設定情報を自動的に配布する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-37' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'여러 사설 호스트가 하나의 공인 IPv4 주소를 포트 번호까지 이용해 공유하는 방식은?','複数のプライベートホストが一つのグローバルIPv4アドレスをポート番号も用いて共有する方式はどれか。','["NAPT","DNSSEC","VLAN","IPsec"]','["NAPT","DNSSEC","VLAN","IPsec"]',0,'NAPT','NAPT','NAPT는 주소뿐 아니라 포트 번호도 변환하여 다수의 내부 호스트가 하나의 공인 주소를 공유하게 한다.','NAPTはアドレスに加えてポート番号も変換し，複数ホストで一つのグローバルアドレスを共有する。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-37' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'10.1.2.3에 대해 10.0.0.0/8과 10.1.2.0/24가 모두 일치한다. 선택되는 경로는?','宛先10.1.2.3に対して10.0.0.0/8と10.1.2.0/24が一致する。選択される経路はどれか。','["10.0.0.0/8","10.1.2.0/24","デフォルトルート","必ずメトリックが小さい方"]','["10.0.0.0/8","10.1.2.0/24","デフォルトルート","必ずメトリックが小さい方"]',1,'10.1.2.0/24','10.1.2.0/24','라우팅은 가장 긴 프리픽스 일치를 우선한다.','ルーティングでは最長プレフィックス一致が優先される。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-38' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'IPv4 기본 경로(default route)의 프리픽스 표기는?','IPv4のデフォルトルートを表すプレフィックスはどれか。','["0.0.0.0/0","127.0.0.0/8","169.254.0.0/16","255.255.255.255/32"]','["0.0.0.0/0","127.0.0.0/8","169.254.0.0/16","255.255.255.255/32"]',0,'0.0.0.0/0','0.0.0.0/0','어떤 목적지에도 일치할 수 있는 /0이 기본 경로다.','全ての宛先に一致し得る/0がデフォルトルートである。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-38' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'동일한 프리픽스 길이의 경로 후보가 여러 개일 때 라우팅 프로토콜이 우선도 비교에 사용하는 값으로 가장 적절한 것은?','同じプレフィックス長の経路候補が複数あるとき，ルーティングプロトコルが優先度比較に用いる値として最も適切なものはどれか。','["メトリック","MACアドレス","TCPシーケンス番号","DNS TTL"]','["メトリック","MACアドレス","TCPシーケンス番号","DNS TTL"]',0,'metric','メトリック','같은 수준의 경로 후보에서는 프로토콜의 메트릭이 경로 선택에 사용될 수 있다.','同一条件の経路候補では，ルーティングプロトコルのメトリックが選択に用いられる。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-38' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'HTTPS에서 접속한 서버의 신원을 확인하는 데 직접 사용되는 것은?','HTTPSで接続先サーバの身元確認に直接用いるものはどれか。','["サーバ証明書","共通鍵だけ","DNSキャッシュ","HTTP Cookie"]','["サーバ証明書","共通鍵だけ","DNSキャッシュ","HTTP Cookie"]',0,'서버 인증서','サーバ証明書','브라우저는 서버 인증서의 신뢰체인과 호스트명을 검증한다.','ブラウザはサーバ証明書の信頼チェーンとホスト名を検証する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-39' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'TLS에서 대량의 애플리케이션 데이터를 암호화할 때 주로 사용하는 방식은?','TLSで大量のアプリケーションデータを暗号化するとき，主に用いられる方式はどれか。','["共通鍵暗号","公開鍵暗号だけ","ハッシュだけ","電子署名だけ"]','["共通鍵暗号","公開鍵暗号だけ","ハッシュだけ","電子署名だけ"]',0,'대칭키 암호','共通鍵暗号','TLS는 키 합의 후 효율적인 대칭키 암호로 실제 데이터를 보호한다.','TLSでは鍵共有後，効率のよい共通鍵暗号で実データを保護する。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-39' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'서버 인증서의 SAN에 접속한 호스트명이 포함되어 있지 않을 때 브라우저가 경고하는 주된 이유는?','サーバ証明書のSANに接続先ホスト名が含まれていない場合，ブラウザが警告する主な理由はどれか。','["接続先の身元を証明書で確認できないから","HTTPメソッドがGETだから","DNS TTLが短いから","TCPポートが443だから"]','["接続先の身元を証明書で確認できないから","HTTPメソッドがGETだから","DNS TTLが短いから","TCPポートが443だから"]',0,'인증서의 호스트명 불일치','接続先ホスト名と証明書の不一致','접속 대상 이름과 인증서가 나타내는 이름이 일치해야 서버 신원을 확인할 수 있다.','接続先ホスト名と証明書が示す名前の一致は，サーバ認証の重要な検証項目である。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-39' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'수신자만 읽을 수 있도록 공개키 암호 방식으로 데이터를 암호화할 때 사용하는 키는?','受信者だけが読めるよう公開鍵暗号方式でデータを暗号化するとき，使用する鍵はどれか。','["送信者の公開鍵","送信者の秘密鍵","受信者の公開鍵","受信者の秘密鍵"]','["送信者の公開鍵","送信者の秘密鍵","受信者の公開鍵","受信者の秘密鍵"]',2,'수신자의 공개키','受信者の公開鍵','수신자의 공개키로 암호화하면 대응하는 수신자의 개인키로만 복호화할 수 있다.','受信者の公開鍵で暗号化し，対応する受信者の秘密鍵で復号する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-40' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'일반적으로 대용량 데이터의 암호화에 더 적합한 방식은?','一般に，大容量データの暗号化により適する方式はどれか。','["共通鍵暗号","公開鍵暗号","電子署名","ハッシュ"]','["共通鍵暗号","公開鍵暗号","電子署名","ハッシュ"]',0,'대칭키 암호','共通鍵暗号','대칭키 암호는 공개키 암호보다 계산 비용이 작아 대량 데이터 처리에 적합하다.','共通鍵暗号は公開鍵暗号より処理負荷が小さく，大量データの暗号化に適する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-40' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'TLS가 공개키 기술과 대칭키 암호를 함께 사용하는 이유로 가장 적절한 것은?','TLSが公開鍵技術と共通鍵暗号を併用する理由として最も適切なものはどれか。','["安全な鍵共有と高速なデータ暗号化を両立するため","ハッシュを可逆にするため","IPアドレスを隠すため","DNSを不要にするため"]','["安全な鍵共有と高速なデータ暗号化を両立するため","ハッシュを可逆にするため","IPアドレスを隠すため","DNSを不要にするため"]',0,'안전한 키 합의와 빠른 데이터 암호화를 함께 달성하기 위해','安全な鍵共有と高速なデータ暗号化を両立するため','공개키 기술은 인증·키 합의에, 대칭키는 이후 데이터 암호화에 적합하다.','公開鍵技術は認証・鍵共有に，共通鍵暗号はその後のデータ暗号化に適している。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-40' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'같은 비밀번호를 사용하더라도 사용자별 저장 해시값을 다르게 만드는 데 사용하는 값은?','同じパスワードでも利用者ごとの保存ハッシュ値を異ならせるために用いる値はどれか。','["ソルト","IVだけ","ポート番号","シーケンス番号"]','["ソルト","IVだけ","ポート番号","シーケンス番号"]',0,'salt','ソルト','사용자별 무작위 salt를 비밀번호와 함께 처리하면 동일 비밀번호도 다른 해시가 된다.','利用者ごとに異なるソルトを加えることで，同じパスワードでも異なるハッシュ値となる。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-41' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'파일의 변조 여부를 확인하기 위한 기술로 가장 적절한 것은?','ファイルの改ざん有無を確認するための技術として最も適切なものはどれか。','["ハッシュ値の比較","NAT","DHCP","RAID0"]','["ハッシュ値の比較","NAT","DHCP","RAID0"]',0,'해시값 비교','ハッシュ値の比較','원본과 현재 파일의 해시값을 비교하면 내용 변경 여부를 검출할 수 있다.','元のファイルと現在のファイルのハッシュ値を比較することで改ざんを検出できる。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-41' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'비밀번호 저장 시 단순한 고속 해시보다 salt와 함께 비밀번호 전용 KDF를 사용하는 주된 이유는?','パスワード保存で単純な高速ハッシュより，ソルト付きのパスワード用KDFを用いる主な理由はどれか。','["総当たり攻撃の計算コストを高めるため","復号鍵を共有するため","通信遅延をなくすため","IPアドレスを匿名化するため"]','["総当たり攻撃の計算コストを高めるため","復号鍵を共有するため","通信遅延をなくすため","IPアドレスを匿名化するため"]',0,'무차별 대입 공격의 계산 비용을 높이기 위해','総当たり攻撃の計算コストを高めるため','비밀번호 KDF는 의도적으로 계산 비용을 높여 대량 추측 공격을 어렵게 한다.','パスワード用KDFは意図的に計算コストを高くし，大量の推測攻撃を困難にする。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-41' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'전자서명을 생성할 때 서명자가 사용하는 키는?','ディジタル署名を生成するとき，署名者が使用する鍵はどれか。','["署名者の秘密鍵","署名者の公開鍵","受信者の秘密鍵","CAの公開鍵"]','["署名者の秘密鍵","署名者の公開鍵","受信者の秘密鍵","CAの公開鍵"]',0,'송신자의 개인키','署名者の秘密鍵','서명은 서명자의 개인키로 생성하고 대응 공개키로 검증한다.','署名は署名者の秘密鍵で生成し，対応する公開鍵で検証する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-42' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'공개키와 그 소유자의 신원을 결합한 인증서를 발행하는 주체는?','公開鍵とその所有者の身元を結び付けた証明書を発行する主体はどれか。','["CA","DHCPサーバ","ルータ","IDS"]','["CA","DHCPサーバ","ルータ","IDS"]',0,'CA','CA','CA(인증기관)가 인증서에 서명하여 공개키와 주체 정보를 결합한다.','CA（認証局）が証明書へ署名し，公開鍵と主体情報を結び付ける。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-42' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'전자서명만으로 직접 보장되지 않는 것은?','ディジタル署名だけでは直接保証されないものはどれか。','["完全性","送信者の認証","否認防止","機密性"]','["完全性","送信者の認証","否認防止","機密性"]',3,'기밀성','機密性','전자서명은 무결성·인증·부인방지를 제공하지만 내용 암호화 자체는 아니다.','ディジタル署名は完全性・認証・否認防止に用いるが，内容の機密性を直接提供するものではない。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-42' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'비밀번호와 스마트폰 OTP를 함께 사용하는 인증은 무엇에 해당하는가?','パスワードとスマートフォンのOTPを組み合わせる認証はどれか。','["単一要素認証","多要素認証","匿名認証","公開鍵認証だけ"]','["単一要素認証","多要素認証","匿名認証","公開鍵認証だけ"]',1,'MFA','多要素認証','비밀번호는 지식 요소, 스마트폰 OTP는 소지 요소이므로 서로 다른 두 요소를 사용한다.','パスワードは知識要素，スマートフォンOTPは所持要素であり，異なる要素を組み合わせている。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-43' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'업무 수행에 필요한 최소한의 권한만 사용자에게 부여하는 원칙은?','業務遂行に必要な最小限の権限だけを利用者へ付与する原則はどれか。','["最小権限の原則","可用性優先の原則","フェールセーフ","オープンデザイン"]','["最小権限の原則","可用性優先の原則","フェールセーフ","オープンデザイン"]',0,'최소권한 원칙','最小権限の原則','불필요한 권한을 줄여 계정 오용이나 침해 시 피해 범위를 제한한다.','不要な権限を減らし，アカウント悪用や侵害時の被害範囲を小さくする。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-43' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'직무 역할별로 권한 묶음을 정의하고 사용자에게 역할을 부여하는 접근제어 방식은?','職務上の役割ごとに権限をまとめ，利用者へ役割を割り当てるアクセス制御方式はどれか。','["RBAC","DACだけ","NAT","RAID"]','["RBAC","DACだけ","NAT","RAID"]',0,'RBAC','RBAC','RBAC는 역할에 권한을 연결한 뒤 사용자에게 역할을 부여한다.','RBACは役割に権限を対応付け，利用者へ役割を割り当てる。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-43' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'사용자 입력을 검증 없이 SQL 문자열에 직접 이어 붙이는 코드에서 대표적으로 발생할 수 있는 취약점은?','利用者入力を検証せずSQL文の文字列へ直接連結する処理で，代表的に発生し得る脆弱性はどれか。','["SQLインジェクション","CSRF","クリックジャッキング","DNSキャッシュポイズニング"]','["SQLインジェクション","CSRF","クリックジャッキング","DNSキャッシュポイズニング"]',0,'SQL Injection','SQLインジェクション','입력값이 SQL 구문의 일부로 해석되면 쿼리 의미가 변조될 수 있다.','入力値がSQL構文の一部として解釈されると，問合せの意味を改変されるおそれがある。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-44' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'SQL Injection의 기본적인 애플리케이션 대책으로 가장 적절한 것은?','SQLインジェクションに対する基本的なアプリケーション対策として最も適切なものはどれか。','["プレースホルダを用いたパラメータ化","全ての通信をUDPにする","DBのポートを変更するだけ","CSSを無効化する"]','["プレースホルダを用いたパラメータ化","全ての通信をUDPにする","DBのポートを変更するだけ","CSSを無効化する"]',0,'parameterized query','プレースホルダを用いたパラメータ化','SQL 문과 데이터 값을 분리해 입력이 SQL 구문으로 해석되지 않도록 한다.','SQL文とデータ値を分離し，入力値がSQL構文として解釈されないようにする。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-44' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'DB 계정에 최소권한을 적용하는 것이 SQL Injection 피해를 줄이는 이유는?','DBアカウントへ最小権限を適用するとSQLインジェクション被害を抑えられる主な理由はどれか。','["不正なSQLが実行されても可能な操作範囲を制限できるから","SQL構文自体が消えるから","ブラウザのCookieが無効になるから","DNS問合せが暗号化されるから"]','["不正なSQLが実行されても可能な操作範囲を制限できるから","SQL構文自体が消えるから","ブラウザのCookieが無効になるから","DNS問合せが暗号化されるから"]',0,'실행 가능한 작업 범위를 제한할 수 있기 때문','不正なSQLが実行されても操作範囲を制限できるため','취약점 자체를 없애는 대책은 아니지만 침해 시 권한 범위를 제한하는 방어층이 된다.','脆弱性そのものを除去する対策ではないが，侵害時に実行可能な操作を限定できる。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-44' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'게시판에 저장된 스크립트가 다른 사용자의 브라우저에서 실행되는 공격은?','掲示板に保存されたスクリプトが他の利用者のブラウザで実行される攻撃はどれか。','["格納型XSS","CSRF","SQLインジェクション","DoS"]','["格納型XSS","CSRF","SQLインジェクション","DoS"]',0,'Stored XSS','格納型XSS','서버에 저장된 악성 스크립트가 다른 사용자에게 전달되어 실행되는 형태다.','サーバに保存された悪意あるスクリプトが他の利用者へ配信され実行される形態である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-45' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'CSRF의 대표적인 대책으로 가장 적절한 것은?','CSRFの代表的な対策として最も適切なものはどれか。','["推測困難なCSRFトークンを検証する","SQLへプレースホルダを使うだけ","パスワードを平文保存する","全Cookieを永続化する"]','["推測困難なCSRFトークンを検証する","SQLへプレースホルダを使うだけ","パスワードを平文保存する","全Cookieを永続化する"]',0,'CSRF token 검증','推測困難なCSRFトークンの検証','요청이 정당한 화면 흐름에서 만들어졌는지 검증하는 토큰이 대표 대책이다.','正規の画面遷移で生成された要求かを検証するトークンは代表的な対策である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-45' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'로그인한 사용자가 악성 사이트를 방문한 것만으로 의도하지 않은 송금 요청이 전송되었다. 가장 관련 있는 공격은?','ログイン済み利用者が悪意あるサイトを閲覧しただけで，意図しない送金要求が送信された。最も関連する攻撃はどれか。','["CSRF","格納型XSS","SQLインジェクション","ARPスプーフィング"]','["CSRF","格納型XSS","SQLインジェクション","ARPスプーフィング"]',0,'CSRF','CSRF','브라우저의 기존 인증 상태를 악용해 사용자의 의도와 다른 요청을 보내게 하는 공격이다.','ブラウザに残る認証状態を悪用し，利用者の意図しない要求を送信させる攻撃である。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-45' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'HTTP 요청의 SQL Injection이나 XSS 패턴을 애플리케이션 계층에서 검사해 차단하는 장비는?','HTTP要求のSQLインジェクションやXSSのパターンをアプリケーション層で検査して遮断する装置はどれか。','["WAF","L2スイッチ","DHCPサーバ","NTPサーバ"]','["WAF","L2スイッチ","DHCPサーバ","NTPサーバ"]',0,'WAF','WAF','WAF는 웹 애플리케이션 요청 내용을 분석하여 대표적인 웹 공격을 탐지·차단한다.','WAFはWebアプリケーションへの要求内容を解析し，代表的なWeb攻撃を検知・遮断する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-46' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'네트워크 공격을 탐지해 경보를 내지만 일반적으로 inline 차단이 주목적이 아닌 것은?','ネットワーク攻撃を検知して警告するが，一般にインライン遮断を主目的としないものはどれか。','["IDS","IPS","WAF","ファイアウォール"]','["IDS","IPS","WAF","ファイアウォール"]',0,'IDS','IDS','IDS는 탐지와 알림이 중심이고 IPS는 인라인에서 차단까지 수행하는 구성이 일반적이다.','IDSは検知・通知が中心で，IPSはインラインで遮断まで行う構成が一般的である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-46' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'IP 주소·포트 기반 접근제어와 웹 애플리케이션 공격 방어를 함께 강화하려는 구성으로 가장 적절한 것은?','IPアドレス・ポートによるアクセス制御とWebアプリケーション攻撃対策を併せて強化する構成として最も適切なものはどれか。','["ファイアウォールとWAF","DNSとDHCP","RAID1とUPS","NTPとSNMP"]','["ファイアウォールとWAF","DNSとDHCP","RAID1とUPS","NTPとSNMP"]',0,'Firewall + WAF','ファイアウォールとWAF','방화벽은 네트워크/전송 계층 조건, WAF는 HTTP 요청 내용을 중심으로 서로 다른 층을 보완한다.','ファイアウォールは主にネットワーク・トランスポート層条件，WAFはHTTP要求内容を扱い，相互に補完する。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-46' AND t.type_no=3;
