-- 0072 AP Subject A development/management/strategy exam-style bank (A-47..A-68)

-- Validated AP Subject A four-choice questions.

-- Replaces generic/open-ended seed question_no=1 for targeted concepts.

PRAGMA foreign_keys = ON;



INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'요구사항 변경이 자주 발생하고 짧은 주기로 가치를 제공해야 하는 프로젝트에 일반적으로 더 적합한 접근은?','要件変更が頻繁で，短い周期で価値を提供する必要があるプロジェクトに，一般により適するアプローチはどれか。','["アジャイル開発","ウォータフォール開発だけ","ビッグバン移行だけ","ベンチマーク"]','["アジャイル開発","ウォータフォール開発だけ","ビッグバン移行だけ","ベンチマーク"]',0,'Agile','アジャイル開発','짧은 반복과 피드백을 통해 변화에 대응하기 쉽다.','短い反復とフィードバックによって変化へ対応しやすい。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-47' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'애자일 개발에 대한 설명으로 가장 적절한 것은?','アジャイル開発の説明として最も適切なものはどれか。','["短い反復で動作する成果物を継続的に改善する","文書を一切作成しない","要件変更を禁止する","全工程を必ず一度だけ実施する"]','["短い反復で動作する成果物を継続的に改善する","文書を一切作成しない","要件変更を禁止する","全工程を必ず一度だけ実施する"]',0,'짧은 반복으로 동작하는 결과물을 지속 개선','短い反復で動作する成果物を継続的に改善する','애자일은 문서 부재가 아니라 반복적 가치 전달과 피드백을 중시한다.','アジャイルは文書不要を意味せず，反復的な価値提供とフィードバックを重視する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-47' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'계약상 요구사항이 매우 안정적이고 단계별 승인 산출물이 엄격히 요구되는 프로젝트에서 상대적으로 적용하기 쉬운 방식은?','契約上の要件が安定し，各工程の承認成果物が厳格に求められるプロジェクトで，相対的に適用しやすい方式はどれか。','["ウォータフォール","スクラムだけ","カンバンだけ","A/Bテスト"]','["ウォータフォール","スクラムだけ","カンバンだけ","A/Bテスト"]',0,'Waterfall','ウォータフォール','공정을 순차적으로 관리하고 단계별 산출물을 명확히 하는 특성과 잘 맞는다.','工程を順次管理し，各工程の成果物を明確にする特性と合いやすい。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-47' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'다음 중 비기능 요구사항에 해당하는 것은?','次のうち，非機能要件に該当するものはどれか。','["利用者が注文を登録できる","95%の要求を2秒以内に応答する","管理者が商品を削除できる","利用者が履歴を検索できる"]','["利用者が注文を登録できる","95%の要求を2秒以内に応答する","管理者が商品を削除できる","利用者が履歴を検索できる"]',1,'95% 요청을 2초 이내 응답','95%の要求を2秒以内に応答する','성능 기준은 시스템이 얼마나 잘 동작해야 하는지를 나타내는 비기능 요구다.','性能基準は，システムがどの程度よく動作すべきかを示す非機能要件である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-48' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'요구사항 문장으로 가장 적절한 것은?','要件の記述として最も適切なものはどれか。','["画面は速く表示する","使いやすくする","通常時の応答時間を95パーセンタイルで2秒以下とする","できるだけ安全にする"]','["画面は速く表示する","使いやすくする","通常時の応答時間を95パーセンタイルで2秒以下とする","できるだけ安全にする"]',2,'측정 가능한 응답시간 기준','通常時の応答時間を95パーセンタイルで2秒以下とする','검증 가능한 수치와 조건이 있는 요구사항이 모호성이 적다.','検証可能な数値と条件を含む要件は曖昧さが少ない。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-48' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'요구사항 정의에서 acceptance 기준을 명확히 하는 주된 목적은?','要件定義で受入れ基準を明確にする主な目的はどれか。','["完成判定を客観的に行えるようにする","開発者だけが仕様を変更できるようにする","テストを不要にする","全ての変更を禁止する"]','["完成判定を客観的に行えるようにする","開発者だけが仕様を変更できるようにする","テストを不要にする","全ての変更を禁止する"]',0,'완료 판정을 객관화','完成判定を客観的に行えるようにする','수용 기준은 요구가 충족되었는지 검증할 기준이 된다.','受入れ基準は，要件が満たされたかを検証する判断基準となる。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-48' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'시간 순서에 따른 객체 간 메시지 교환을 표현하는 UML 다이어그램은?','時間順にオブジェクト間のメッセージ交換を表すUML図はどれか。','["クラス図","シーケンス図","ユースケース図","状態遷移図"]','["クラス図","シーケンス図","ユースケース図","状態遷移図"]',1,'Sequence diagram','シーケンス図','시퀀스 다이어그램은 객체 간 메시지 흐름을 시간축으로 표현한다.','シーケンス図はオブジェクト間のメッセージの流れを時間軸で表す。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-49' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'시스템의 정적 클래스 구조와 클래스 간 관계를 표현하는 UML 다이어그램은?','システムの静的なクラス構造とクラス間の関係を表すUML図はどれか。','["クラス図","アクティビティ図","シーケンス図","ユースケース図"]','["クラス図","アクティビティ図","シーケンス図","ユースケース図"]',0,'Class diagram','クラス図','클래스 다이어그램은 클래스, 속성, 연산, 관계의 정적 구조를 나타낸다.','クラス図はクラス，属性，操作，関係などの静的構造を表す。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-49' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'사용자 역할과 시스템이 제공하는 기능의 관계를 나타내는 데 가장 적절한 UML 다이어그램은?','利用者の役割とシステムが提供する機能の関係を表すのに最も適するUML図はどれか。','["ユースケース図","配置図","クラス図","タイミング図"]','["ユースケース図","配置図","クラス図","タイミング図"]',0,'Use Case diagram','ユースケース図','유스케이스 다이어그램은 액터와 시스템 기능의 관계를 표현한다.','ユースケース図はアクターとシステム機能との関係を表す。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-49' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'두 모듈 사이의 API 연동이 올바른지 확인하는 테스트 단계는?','二つのモジュール間のAPI連携が正しいかを確認するテスト段階はどれか。','["単体テスト","結合テスト","システムテスト","受入れテスト"]','["単体テスト","結合テスト","システムテスト","受入れテスト"]',1,'통합 테스트','結合テスト','인터페이스와 모듈 간 연동 검증은 결합 테스트의 핵심이다.','インタフェースやモジュール間連携の検証は結合テストの中心である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-50' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'사용자 업무 요구를 만족하는지 최종 확인하는 테스트로 가장 적절한 것은?','利用者の業務要件を満たすかを最終確認するテストとして最も適切なものはどれか。','["受入れテスト","単体テスト","静的解析だけ","コードレビューだけ"]','["受入れテスト","単体テスト","静的解析だけ","コードレビューだけ"]',0,'인수 테스트','受入れテスト','인수 테스트는 사용자 관점에서 시스템이 수용 가능한지 확인한다.','受入れテストは利用者の観点でシステムを受け入れられるか確認する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-50' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'개별 함수의 경계값과 반환값을 독립적으로 검증하는 데 가장 가까운 테스트 단계는?','個々の関数の境界値や戻り値を独立して検証するのに最も近いテスト段階はどれか。','["単体テスト","結合テスト","システムテスト","運用テスト"]','["単体テスト","結合テスト","システムテスト","運用テスト"]',0,'단위 테스트','単体テスト','작은 프로그램 단위의 내부 기능을 검증하는 것은 단위 테스트에 해당한다.','小さなプログラム単位の機能を検証するのは単体テストである。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-50' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'입력 가능한 나이가 18~65세일 때 경계값 분석의 대표 테스트 데이터 조합은?','入力可能な年齢が18～65歳のとき，境界値分析の代表的なテストデータの組合せはどれか。','["17,18,19,64,65,66","20,30,40,50","18,30,65だけ","0,100だけ"]','["17,18,19,64,65,66","20,30,40,50","18,30,65だけ","0,100だけ"]',0,'17,18,19,64,65,66','17,18,19,64,65,66','경계 직전·경계·경계 직후 값을 확인하는 것이 대표적이다.','境界の直前・境界値・直後の値を確認するのが代表的である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-51' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'동등분할의 목적은?','同値分割の目的はどれか。','["同じ性質をもつ入力領域ごとに代表値を選ぶ","全入力値を必ず試す","境界値だけを試す","内部コードの全分岐を網羅する"]','["同じ性質をもつ入力領域ごとに代表値を選ぶ","全入力値を必ず試す","境界値だけを試す","内部コードの全分岐を網羅する"]',0,'같은 특성의 입력 영역별 대표값 선택','同じ性質をもつ入力領域ごとに代表値を選ぶ','동일하게 처리될 것으로 기대되는 입력 집합을 클래스별로 나눈다.','同じように処理されると期待できる入力集合をクラスに分ける。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-51' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'1~100만 유효한 입력에서 동등분할 관점의 대표값 선택으로 가장 적절한 것은?','1～100だけが有効な入力で，同値分割の観点から代表値を選ぶ組合せとして最も適切なものはどれか。','["50,0,101","1,2,3","99,100だけ","全ての整数"]','["50,0,101","1,2,3","99,100だけ","全ての整数"]',0,'50,0,101','50,0,101','유효 클래스 1개와 하한 미만·상한 초과의 무효 클래스를 대표하도록 고른다.','有効クラスと，下限未満・上限超過の無効クラスを代表する値を選ぶ。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-51' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'소스코드 버전, 변경 이력, 베이스라인을 식별·통제하는 활동은?','ソースコードの版，変更履歴，ベースラインを識別・統制する活動はどれか。','["構成管理","負荷テスト","容量計画","名前解決"]','["構成管理","負荷テスト","容量計画","名前解決"]',0,'형상관리','構成管理','형상관리는 구성항목과 버전·변경을 식별하고 통제한다.','構成管理は構成品目と版・変更を識別し，統制する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-52' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'리뷰의 주된 목적은?','レビューの主な目的はどれか。','["成果物の欠陥を早期に発見する","バックアップ容量を増やす","IPアドレスを割り当てる","暗号鍵を配布する"]','["成果物の欠陥を早期に発見する","バックアップ容量を増やす","IPアドレスを割り当てる","暗号鍵を配布する"]',0,'산출물 결함의 조기 발견','成果物の欠陥を早期に発見する','요구서·설계서·코드 등을 검토해 후공정 전에 문제를 찾는 것이 핵심이다.','要件書・設計書・コードなどを確認し，後工程へ進む前に欠陥を見つける。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-52' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'정식 릴리스 기준으로 승인된 구성항목 집합을 의미하는 것은?','正式なリリース基準として承認された構成品目の集合を表す用語はどれか。','["ベースライン","インシデント","スプリント","ワークアラウンド"]','["ベースライン","インシデント","スプリント","ワークアラウンド"]',0,'baseline','ベースライン','베이스라인은 승인된 기준 상태로 이후 변경은 통제 절차를 거친다.','ベースラインは承認された基準状態であり，以後の変更は統制手続を経る。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-52' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'PERT에서 프로젝트 전체 기간을 결정하는 경로는?','PERTでプロジェクト全体の期間を決定する経路はどれか。','["クリティカルパス","最短経路","作業数が最少の経路","費用が最小の経路"]','["クリティカルパス","最短経路","作業数が最少の経路","費用が最小の経路"]',0,'critical path','クリティカルパス','여유시간이 0인 최장 소요 경로가 전체 완료시점을 좌우한다.','余裕時間が0の最長所要時間経路が全体の完了時点を左右する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-53' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'어떤 작업의 earliest start가 5일, latest start가 8일이면 slack은?','ある作業の最早開始時刻が5日，最遅開始時刻が8日のとき，余裕時間は何日か。','["0","3","5","13"]','["0","3","5","13"]',1,'3일','3日','slack=latest-earliest=8-5=3이다.','余裕時間=最遅開始-最早開始=8-5=3日である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-53' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'critical path상의 작업이 2일 지연되고 다른 여유가 없을 때 일반적으로 발생하는 것은?','クリティカルパス上の作業が2日遅延し，他に余裕がない場合，一般にどうなるか。','["プロジェクト完了も2日遅れる","影響はない","必ず2日早まる","コストだけ変わる"]','["プロジェクト完了も2日遅れる","影響はない","必ず2日早まる","コストだけ変わる"]',0,'프로젝트 완료도 2일 지연','プロジェクト完了も2日遅れる','critical path에는 여유가 없으므로 해당 지연이 전체 기간에 직접 반영된다.','クリティカルパスには余裕がないため，その遅延が全体期間へ直接反映される。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-53' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'EVM에서 EV=80, PV=100일 때 일정차이 SV는?','EVMでEV=80，PV=100のとき，スケジュール差異SVは幾つか。','["-20","20","80","180"]','["-20","20","80","180"]',0,'-20','-20','SV=EV-PV=80-100=-20이다.','SV=EV-PV=80-100=-20である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-54' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'EVM에서 EV=90, AC=110일 때 비용차이 CV는?','EVMでEV=90，AC=110のとき，コスト差異CVは幾つか。','["-20","20","0","200"]','["-20","20","0","200"]',0,'-20','-20','CV=EV-AC=90-110=-20이므로 비용 측면에서 불리하다.','CV=EV-AC=90-110=-20であり，コスト面で不利である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-54' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'EVM 지표의 의미로 가장 적절한 것은?','EVM指標の意味として最も適切なものはどれか。','["PVは計画価値，EVは出来高，ACは実コスト","PVは実コスト，EVは計画価値，ACは利益","全て同じ値","EVは必ず支出額"]','["PVは計画価値，EVは出来高，ACは実コスト","PVは実コスト，EVは計画価値，ACは利益","全て同じ値","EVは必ず支出額"]',0,'PV 계획가치, EV 실적가치, AC 실제비용','PVは計画価値，EVは出来高，ACは実コスト','세 지표의 의미를 구분해야 일정·비용 성과를 계산할 수 있다.','三つの値の意味を区別することで，日程・コストの実績を評価できる。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-54' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'EV=90, AC=100일 때 CPI는?','EV=90，AC=100のとき，CPIは幾つか。','["0.9","1.0","1.1","10"]','["0.9","1.0","1.1","10"]',0,'0.9','0.9','CPI=EV/AC=90/100=0.9다.','CPI=EV/AC=90/100=0.9である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-55' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'SPI가 0.8이라는 의미로 가장 적절한 것은?','SPIが0.8であることの意味として最も適切なものはどれか。','["計画より進捗が遅れている","計画より進捗が進んでいる","コストが必ず20%超過した","品質が20%低下した"]','["計画より進捗が遅れている","計画より進捗が進んでいる","コストが必ず20%超過した","品質が20%低下した"]',0,'계획보다 진척이 느림','計画より進捗が遅れている','SPI=EV/PV이고 1보다 작으면 계획 대비 실적 진척이 낮다.','SPI=EV/PVであり，1未満なら計画に対して進捗が遅れている。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-55' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'CPI와 SPI의 공통 분자는?','CPIとSPIに共通する分子はどれか。','["EV","PV","AC","BAC"]','["EV","PV","AC","BAC"]',0,'EV','EV','CPI=EV/AC, SPI=EV/PV이므로 둘 다 분자가 EV다.','CPI=EV/AC，SPI=EV/PVなので，どちらも分子はEVである。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-55' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'위험의 발생 원인을 제거하여 해당 위험이 더 이상 발생하지 않게 하는 대응은?','リスクの発生原因を除去し，そのリスクが発生しないようにする対応はどれか。','["回避","軽減","転嫁","受容"]','["回避","軽減","転嫁","受容"]',0,'회피','回避','위험 자체를 없애는 방향은 회피다.','リスク自体をなくす方向の対応が回避である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-56' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'보험 가입을 통한 위험 대응은 일반적으로 무엇에 해당하는가?','保険加入によるリスク対応は，一般にどれに該当するか。','["転嫁","回避","軽減だけ","受容だけ"]','["転嫁","回避","軽減だけ","受容だけ"]',0,'전가','転嫁','금전적 손실 부담을 제3자에게 이전하는 대표적인 전가 방식이다.','金銭的損失の負担を第三者へ移す代表的な転嫁である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-56' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'발생확률은 낮지만 영향이 매우 큰 위험에 대한 판단으로 가장 적절한 것은?','発生確率は低いが影響が非常に大きいリスクへの判断として最も適切なものはどれか。','["確率だけで無視せず影響も含めて評価する","必ず無視する","必ず受容する","記録しない"]','["確率だけで無視せず影響も含めて評価する","必ず無視する","必ず受容する","記録しない"]',0,'확률과 영향도를 함께 평가','確率だけでなく影響も含めて評価する','위험 우선순위는 일반적으로 발생 가능성과 영향을 함께 본다.','リスクの優先度は，一般に発生可能性と影響度を合わせて評価する。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-56' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'고객과 서비스 제공자 사이에 월 가용성 99.9% 같은 목표 수준을 합의한 문서는?','顧客とサービス提供者の間で，月間可用性99.9%などの目標水準を合意したものはどれか。','["SLA","SLM","RTO","WBS"]','["SLA","SLM","RTO","WBS"]',0,'SLA','SLA','SLA는 서비스 수준 목표를 고객과 합의한 것이다.','SLAはサービスレベルの目標を顧客と合意したものである。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-57' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'합의된 서비스 수준을 지속적으로 측정·보고·개선하는 활동은?','合意したサービスレベルを継続的に測定・報告・改善する活動はどれか。','["SLM","SLAだけ","DNS","EVM"]','["SLM","SLAだけ","DNS","EVM"]',0,'SLM','SLM','SLM은 SLA에서 정한 목표를 지속 관리하는 프로세스다.','SLMはSLAで定めた目標を継続的に管理するプロセスである。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-57' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'SLA 지표로 가장 적절한 것은?','SLAの指標として最も適切なものはどれか。','["月間可用性99.95%以上","システムはできるだけ速くする","担当者は努力する","障害は起こさない"]','["月間可用性99.95%以上","システムはできるだけ速くする","担当者は努力する","障害は起こさない"]',0,'측정 가능한 가용성 목표','月間可用性99.95%以上','SLA는 측정·검증 가능한 서비스 수준으로 표현하는 것이 적절하다.','SLAは測定・検証可能なサービス水準として定義するのが適切である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-57' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'장애 발생 직후 서비스를 가능한 빨리 정상화하는 데 초점을 두는 활동은?','障害発生直後，サービスを可能な限り早く正常化することを重視する活動はどれか。','["インシデント管理","問題管理","構成管理だけ","監査"]','["インシデント管理","問題管理","構成管理だけ","監査"]',0,'Incident management','インシデント管理','인시던트 관리는 서비스 복구를 우선한다.','インシデント管理はサービスの迅速な復旧を優先する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-58' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'반복 장애의 근본원인을 분석하고 재발방지책을 찾는 활동은?','繰り返し発生する障害の根本原因を分析し，再発防止策を検討する活動はどれか。','["問題管理","インシデント管理だけ","可用性計算","DNS管理"]','["問題管理","インシデント管理だけ","可用性計算","DNS管理"]',0,'Problem management','問題管理','problem 관리는 근본원인과 재발 방지에 초점을 둔다.','問題管理は根本原因の分析と再発防止に焦点を当てる。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-58' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'재기동으로 서비스를 임시 복구했지만 근본원인은 남아 있다. 이 재기동 조치의 성격은?','再起動でサービスを暫定復旧したが根本原因は残っている。この再起動措置の性質はどれか。','["ワークアラウンド","恒久対策","監査証拠","SLA"]','["ワークアラウンド","恒久対策","監査証拠","SLA"]',0,'workaround','ワークアラウンド','근본원인을 제거하지 않고 일시적으로 서비스를 복구하는 조치는 workaround다.','根本原因を除去せず，一時的にサービスを復旧させる措置はワークアラウンドである。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-58' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'시스템 감사인의 독립성을 가장 잘 확보한 사례는?','システム監査人の独立性を最もよく確保した例はどれか。','["監査対象システムの運用担当者とは別の組織が監査する","運用担当者が自分の作業だけを監査する","開発責任者が承認なしで監査結果を変更する","監査証拠を残さない"]','["監査対象システムの運用担当者とは別の組織が監査する","運用担当者が自分の作業だけを監査する","開発責任者が承認なしで監査結果を変更する","監査証拠を残さない"]',0,'운영과 독립된 조직이 감사','監査対象の運用部門とは別組織が監査する','감사 대상 업무로부터 독립된 위치에서 객관적으로 평가해야 한다.','監査対象業務から独立した立場で客観的に評価する必要がある。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-59' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'감사 결론을 뒷받침하기 위해 가장 중요한 것은?','監査結論を裏付けるために最も重要なものはどれか。','["十分かつ適切な監査証拠","担当者の印象だけ","推測だけ","口頭のうわさだけ"]','["十分かつ適切な監査証拠","担当者の印象だけ","推測だけ","口頭のうわさだけ"]',0,'충분하고 적절한 감사 증거','十分かつ適切な監査証拠','감사 판단은 객관적 증거에 근거해야 한다.','監査判断は客観的な証拠に基づく必要がある。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-59' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'감사인이 직접 접근통제 규칙을 운영하고 그 결과를 다시 감사하는 경우 가장 우려되는 것은?','監査人が自らアクセス制御を運用し，その結果を自分で監査する場合，最も懸念されることはどれか。','["独立性の低下","可用性の向上","暗号強度の向上","ネットワーク帯域の増加"]','["独立性の低下","可用性の向上","暗号強度の向上","ネットワーク帯域の増加"]',0,'독립성 저하','独立性の低下','운영 책임과 감사 책임이 같은 사람에게 집중되면 독립성과 객관성이 훼손될 수 있다.','運用責任と監査責任が同一人物に集中すると，独立性・客観性が損なわれるおそれがある。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-59' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'송금 등록자와 최종 승인자를 서로 다른 사람으로 분리하는 통제는?','振込登録者と最終承認者を別の人に分ける統制はどれか。','["職務分掌","RAID","キャッシュ","ルーティング"]','["職務分掌","RAID","キャッシュ","ルーティング"]',0,'직무분장','職務分掌','승인·실행 등의 역할을 분리해 오류와 부정 위험을 줄인다.','承認・実行などの役割を分離し，誤謬や不正のリスクを低減する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-60' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'한 사용자가 거래 생성과 승인까지 모두 할 수 있는 상태의 주된 위험은?','一人の利用者が取引の作成と承認を両方できる状態の主なリスクはどれか。','["不正や誤りを単独で完結できる","通信速度が遅くなる","DNS障害が増える","CPU使用率が必ず下がる"]','["不正や誤りを単独で完結できる","通信速度が遅くなる","DNS障害が増える","CPU使用率が必ず下がる"]',0,'부정/오류를 단독으로 완결할 위험','不正や誤りを単独で完結できる','상호 견제가 사라져 내부통제 위험이 커진다.','相互牽制が働かず，内部統制上のリスクが高まる。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-60' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'예방통제(preventive control)의 예로 가장 적절한 것은?','予防的統制の例として最も適切なものはどれか。','["重要処理を権限のある利用者だけに制限する","事後にログを分析するだけ","障害後に原因報告書を書く","月次レポートを保存するだけ"]','["重要処理を権限のある利用者だけに制限する","事後にログを分析するだけ","障害後に原因報告書を書く","月次レポートを保存するだけ"]',0,'권한 제한','重要処理を権限のある利用者だけに制限する','사전에 부적절한 행위를 막는 접근권한 통제가 예방통제에 해당한다.','不適切な行為を事前に防ぐアクセス制御は予防的統制に当たる。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-60' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'SWOT 분석에서 경쟁사의 신규 진입은 일반적으로 어디에 분류되는가?','SWOT分析で競合企業の新規参入は，一般にどこへ分類されるか。','["Threat","Strength","Weakness","Opportunity"]','["Threat","Strength","Weakness","Opportunity"]',0,'Threat','Threat','경쟁사 신규 진입은 조직 외부의 불리한 환경요인이므로 Threat다.','競合企業の新規参入は組織外部の不利な環境要因なのでThreatである。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-61' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'SWOT에서 조직 내부의 강점을 의미하는 것은?','SWOTで組織内部の強みを表すものはどれか。','["Strength","Opportunity","Threat","Market"]','["Strength","Opportunity","Threat","Market"]',0,'Strength','Strength','S/W는 내부, O/T는 외부 요인이다.','S/Wは内部要因，O/Tは外部要因である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-61' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'조직의 강한 브랜드 인지도와 시장 성장이라는 기회를 결합해 적극 확장하는 전략은 어떤 조합에 가까운가?','強いブランド認知という強みと市場成長という機会を組み合わせ，積極的に拡大する戦略はどの組合せに近いか。','["SO","ST","WO","WT"]','["SO","ST","WO","WT"]',0,'SO','SO','강점을 활용해 기회를 잡는 전략은 SO 조합이다.','強みを活用して機会を捉える戦略はSOである。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-61' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'PPM에서 시장성장률이 높고 상대적 시장점유율도 높은 사업은?','PPMで市場成長率が高く，相対的市場占有率も高い事業はどれか。','["Star","Cash Cow","Question Mark","Dog"]','["Star","Cash Cow","Question Mark","Dog"]',0,'Star','Star','고성장·고점유 영역은 Star다.','高成長・高占有率の領域はStarである。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-62' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'PPM에서 시장성장률은 낮지만 상대적 시장점유율이 높은 사업은?','PPMで市場成長率は低いが，相対的市場占有率が高い事業はどれか。','["Cash Cow","Star","Question Mark","Dog"]','["Cash Cow","Star","Question Mark","Dog"]',0,'Cash Cow','Cash Cow','저성장·고점유 영역은 Cash Cow다.','低成長・高占有率の領域はCash Cowである。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-62' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'PPM에서 시장성장률은 높지만 상대적 시장점유율이 낮아 추가 투자 여부 판단이 중요한 사업은?','PPMで市場成長率は高いが，相対的市場占有率が低く，追加投資の判断が重要な事業はどれか。','["Question Mark","Cash Cow","Star","Dog"]','["Question Mark","Cash Cow","Star","Dog"]',0,'Question Mark','Question Mark','고성장·저점유는 Question Mark다.','高成長・低占有率はQuestion Markである。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-62' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'원재료 공급업체 수가 매우 적어 가격 협상력이 강해지는 현상은 5 Forces 중 무엇과 관련되는가?','原材料供給業者が少数で価格交渉力が強い状況は，5 Forcesのどれに関係するか。','["売り手の交渉力","買い手の交渉力","代替品の脅威","新規参入の脅威"]','["売り手の交渉力","買い手の交渉力","代替品の脅威","新規参入の脅威"]',0,'공급자 교섭력','売り手の交渉力','공급업체가 소수이면 공급자의 협상력이 커질 수 있다.','供給業者が少数であれば，売り手の交渉力が強くなりやすい。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-63' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'기존 제품과 다른 방식으로 같은 고객 요구를 충족하는 서비스의 등장은 어떤 경쟁요인인가?','既存製品とは異なる方法で同じ顧客ニーズを満たすサービスの登場は，どの競争要因か。','["代替品の脅威","売り手の交渉力","既存企業間競争だけ","参入障壁"]','["代替品の脅威","売り手の交渉力","既存企業間競争だけ","参入障壁"]',0,'대체재 위협','代替品の脅威','같은 필요를 다른 수단으로 충족하면 대체재가 될 수 있다.','同じニーズを別の手段で満たすものは代替品となり得る。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-63' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'높은 초기 투자비용과 강한 규제가 일반적으로 낮추는 경쟁요인은?','高い初期投資費用と強い規制が一般に低下させる競争要因はどれか。','["新規参入の脅威","買い手の交渉力","代替品の脅威","既存競争の数"]','["新規参入の脅威","買い手の交渉力","代替品の脅威","既存競争の数"]',0,'신규 진입 위협','新規参入の脅威','진입장벽이 높아지면 신규 경쟁자의 시장 진입이 어려워진다.','参入障壁が高くなると，新規企業の参入が難しくなる。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-63' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'4P에서 유통경로와 판매장소에 해당하는 요소는?','4Pで流通経路や販売場所に該当する要素はどれか。','["Place","Product","Price","Promotion"]','["Place","Product","Price","Promotion"]',0,'Place','Place','Place는 제품이 고객에게 전달되는 유통·채널을 다룬다.','Placeは製品を顧客へ届ける流通・チャネルを扱う。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-64' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'4C에서 고객이 구매와 이용을 얼마나 편리하게 할 수 있는지에 해당하는 요소는?','4Cで，顧客が購入・利用しやすいかという観点に該当する要素はどれか。','["Convenience","Cost","Communication","Customer Value"]','["Convenience","Cost","Communication","Customer Value"]',0,'Convenience','Convenience','접근성과 구매 편의성은 Convenience 관점이다.','アクセス性や購入のしやすさはConvenienceの観点である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-64' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'온라인 판매 채널 확대를 4P/4C 관점에서 연결한 것으로 가장 적절한 것은?','オンライン販売チャネルの拡大を4P/4Cで対応付けたものとして最も適切なのはどれか。','["PlaceとConvenience","PriceとCommunication","PromotionとCost","ProductとCostだけ"]','["PlaceとConvenience","PriceとCommunication","PromotionとCost","ProductとCostだけ"]',0,'Place와 Convenience','PlaceとConvenience','유통 채널 확대는 기업 관점의 Place, 고객 관점의 편의성 향상과 연결된다.','流通チャネル拡大は企業側のPlace，顧客側のConvenienceと関係する。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-64' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'판매단가 100, 단위변동비 60, 고정비 4,000일 때 손익분기 판매량은?','販売単価100，単位変動費60，固定費4,000のとき，損益分岐点販売数量は幾つか。','["40","67","100","160"]','["40","67","100","160"]',2,'100개','100個','단위 공헌이익은 40, 따라서 4000/40=100개다.','単位限界利益は40なので，4,000/40=100個である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-65' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'단위당 공헌이익의 계산식은?','単位限界利益の計算式はどれか。','["販売単価-単位変動費","販売単価+固定費","固定費-売上高","売上高÷固定費"]','["販売単価-単位変動費","販売単価+固定費","固定費-売上高","売上高÷固定費"]',0,'판매단가 - 단위변동비','販売単価-単位変動費','한 단위를 팔아 고정비와 이익에 기여하는 금액이다.','1単位販売したとき，固定費回収と利益へ寄与する額である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-65' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'고정비가 증가하고 판매단가와 단위변동비가 변하지 않을 때 손익분기 판매량은 일반적으로 어떻게 되는가?','固定費が増加し，販売単価と単位変動費が変わらないとき，損益分岐点販売数量は一般にどうなるか。','["増加する","減少する","変わらない","必ず0になる"]','["増加する","減少する","変わらない","必ず0になる"]',0,'증가','増加する','BEP 수량=고정비/단위공헌이익이므로 분자가 커지면 수량이 늘어난다.','BEP数量=固定費/単位限界利益なので，固定費が増えれば必要数量も増える。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-65' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'투자액 1,000, 이익 120일 때 ROI는?','投資額1,000，利益120のとき，ROIは何%か。','["8%","12%","20%","120%"]','["8%","12%","20%","120%"]',1,'12%','12%','ROI=이익/투자액×100=120/1000×100=12%.','ROI=利益/投資額×100=120/1,000×100=12%である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-66' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'ROI 계산에서 분모로 사용하는 값은?','ROIの計算で分母に用いる値はどれか。','["投資額","利益","売上高だけ","固定費だけ"]','["投資額","利益","売上高だけ","固定費だけ"]',0,'투자액','投資額','ROI는 투자 대비 이익의 비율이다.','ROIは投資に対する利益の比率である。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-66' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'서로 다른 투자안의 ROI를 비교할 때 주의할 점으로 가장 적절한 것은?','異なる投資案のROIを比較するときの注意点として最も適切なものはどれか。','["利益と投資額の対象期間・定義をそろえる","売上高だけ比較すればよい","投資額を無視する","単位が違ってもそのまま比較する"]','["利益と投資額の対象期間・定義をそろえる","売上高だけ比較すればよい","投資額を無視する","単位が違ってもそのまま比較する"]',0,'기간과 정의를 맞춰 비교','利益と投資額の対象期間・定義をそろえる','비율 비교는 분자·분모의 기준과 기간이 같아야 의미가 있다.','比率比較では，分子・分母の定義と対象期間をそろえる必要がある。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-66' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'프로그램의 소스코드와 같은 창작적 표현을 보호하는 권리로 가장 적절한 것은?','プログラムのソースコードのような創作的表現を保護する権利として最も適切なものはどれか。','["著作権","特許権だけ","商標権だけ","所有権だけ"]','["著作権","特許権だけ","商標権だけ","所有権だけ"]',0,'저작권','著作権','프로그램 코드는 저작물로 보호될 수 있다.','プログラムのコードは著作物として保護され得る。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-67' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'특허권에 대한 설명으로 가장 적절한 것은?','特許権の説明として最も適切なものはどれか。','["一定の要件を満たす発明について出願・審査を経て権利化される","創作した瞬間に全て自動成立する","アイデアなら無条件に保護される","登録不要で永久に続く"]','["一定の要件を満たす発明について出願・審査を経て権利化される","創作した瞬間に全て自動成立する","アイデアなら無条件に保護される","登録不要で永久に続く"]',0,'출원·심사를 거쳐 성립','一定の要件を満たす発明について出願・審査を経て権利化される','특허는 신규성·진보성 등 요건을 충족한 발명에 대해 출원과 심사를 거친다.','特許は新規性・進歩性などの要件を満たす発明について，出願・審査を経て成立する。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-67' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'저작권과 특허권의 차이로 가장 적절한 것은?','著作権と特許権の違いとして最も適切なものはどれか。','["著作権は表現，特許権は技術的発明を主に保護する","両者とも必ず同じ対象を保護する","著作権は技術的発明だけを保護する","特許権は文章表現だけを保護する"]','["著作権は表現，特許権は技術的発明を主に保護する","両者とも必ず同じ対象を保護する","著作権は技術的発明だけを保護する","特許権は文章表現だけを保護する"]',0,'저작권=표현, 특허=기술적 발명','著作権は表現，特許権は技術的発明を主に保護する','보호 대상의 성격이 다르므로 먼저 표현인지 기술적 발명인지 구분한다.','保護対象の性質が異なるため，表現か技術的発明かを区別する。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-67' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'서비스 목적에 필요하지 않은 식별정보를 수집하지 않는 것은 개인정보 처리의 어떤 원칙과 가장 관련 있는가?','サービス目的に不要な識別情報を収集しないことは，個人情報取扱いのどの考え方に最も関係するか。','["必要最小限の収集","無制限収集","目的外利用","公開優先"]','["必要最小限の収集","無制限収集","目的外利用","公開優先"]',0,'최소수집','必要最小限の収集','업무 목적에 필요한 범위만 수집하면 개인정보 노출 위험을 줄일 수 있다.','利用目的に必要な範囲だけ収集することで，個人情報の取扱いリスクを抑えられる。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-68' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'표준화의 주된 효과로 가장 적절한 것은?','標準化の主な効果として最も適切なものはどれか。','["製品・システム間の互換性や共通性を高める","全ての製品を同一価格にする","競争を完全になくす","セキュリティ事故を必ずゼロにする"]','["製品・システム間の互換性や共通性を高める","全ての製品を同一価格にする","競争を完全になくす","セキュリティ事故を必ずゼロにする"]',0,'호환성·공통성 향상','製品・システム間の互換性や共通性を高める','공통 규격을 통해 상호운용성과 품질 관리가 쉬워질 수 있다.','共通規格によって相互運用性や品質管理を向上させやすい。',1,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-68' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,1,'개인정보를 원래 수집 목적과 다른 목적으로 이용하려 할 때 가장 먼저 확인해야 할 사항으로 적절한 것은?','個人情報を当初の収集目的とは異なる目的で利用しようとするとき，最初に確認すべき事項として適切なものはどれか。','["利用目的と法的根拠・同意の有無","CPUクロック数","RAIDレベル","DNS TTL"]','["利用目的と法的根拠・同意の有無","CPUクロック数","RAIDレベル","DNS TTL"]',0,'이용 목적과 법적 근거/동의','利用目的と法的根拠・同意の有無','목적외 이용 여부와 적법한 처리 근거를 확인해야 한다.','目的外利用に当たるか，適法な処理根拠があるかを確認する必要がある。',2,1 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-68' AND t.type_no=3;
