-- 0073 AP Subject A replace generic fallback bank (A-14..A-32)

-- Validated AP Subject A four-choice replacements.

-- Replaces generic fallback question_no=2 for targeted concepts.

PRAGMA foreign_keys = ON;



INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'명령 수 2×10^9, CPI=1.5, 클록 주파수 3GHz인 CPU의 실행시간은?','命令数2×10^9，CPI=1.5，クロック周波数3GHzのCPU実行時間はどれか。','["0.5秒","1秒","1.5秒","3秒"]','["0.5秒","1秒","1.5秒","3秒"]',1,'1초','1秒','2×10^9×1.5/(3×10^9)=1초다.','2×10^9×1.5/(3×10^9)=1秒である。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-14' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'다른 조건이 같을 때 CPU 실행시간을 절반으로 줄이는 변화는?','他の条件が同じとき，CPU実行時間を半分にする変化はどれか。','["クロック周波数を2倍にする","CPIを2倍にする","命令数を2倍にする","クロック周期を2倍にする"]','["クロック周波数を2倍にする","CPIを2倍にする","命令数を2倍にする","クロック周期を2倍にする"]',0,'클록 주파수를 2배로','クロック周波数を2倍にする','실행시간은 주파수에 반비례한다.','CPU実行時間はクロック周波数に反比例する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-14' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'두 CPU의 성능 비교에 대한 설명으로 옳은 것은?','二つのCPUの性能比較について正しいものはどれか。','["同一処理なら実行時間が短い方が高性能","周波数だけ高ければ必ず高性能","CPIが大きいほど必ず高性能","命令数は性能に無関係"]','["同一処理なら実行時間が短い方が高性能","周波数だけ高ければ必ず高性能","CPIが大きいほど必ず高性能","命令数は性能に無関係"]',0,'동일 처리의 실행시간이 짧은 CPU','同一処理なら実行時間が短い方が高性能','성능은 실행시간의 역수 관계로 비교할 수 있다.','性能は実行時間の逆数として比較できる。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-14' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'4단계 파이프라인에서 8개 명령을 stall 없이 처리할 때 이상적인 cycle 수는?','4段パイプラインで8命令をストールなしに処理するとき，理想的なサイクル数はどれか。','["8","10","11","32"]','["8","10","11","32"]',2,'11','11','k+n-1=4+8-1=11이다.','k+n-1=4+8-1=11である。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-15' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'앞 명령의 계산 결과가 뒤 명령의 입력으로 필요해 발생하는 hazard는?','先行命令の計算結果を後続命令が必要とするために生じるハザードはどれか。','["データハザード","制御ハザード","構造ハザード","ページフォールト"]','["データハザード","制御ハザード","構造ハザード","ページフォールト"]',0,'data hazard','データハザード','명령 간 데이터 의존성 때문에 발생한다.','命令間のデータ依存によって発生する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-15' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'파이프라인의 주된 효과로 가장 적절한 것은?','パイプラインの主な効果として最も適切なものはどれか。','["複数命令の段階を重ねてスループットを高める","1命令の処理段数を必ず1にする","メモリ容量を増やす","全分岐をなくす"]','["複数命令の段階を重ねてスループットを高める","1命令の処理段数を必ず1にする","メモリ容量を増やす","全分岐をなくす"]',0,'처리량 향상','複数命令の段階を重ねてスループットを高める','여러 명령의 단계를 중첩해 단위시간당 완료 명령 수를 높인다.','複数命令の処理段階を重ね，単位時間当たりの完了命令数を増やす。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-15' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'캐시 접근 4ns, miss 시 추가 96ns, hit율 75%일 때 평균 접근시간은?','キャッシュアクセス4ns，ミス時追加96ns，ヒット率75%のとき平均アクセス時間はどれか。','["24ns","28ns","72ns","100ns"]','["24ns","28ns","72ns","100ns"]',1,'28ns','28ns','4+0.25×96=28ns다.','4+0.25×96=28nsである。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-16' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'최근 사용한 데이터가 가까운 시점에 다시 사용될 가능성이 높은 성질은?','最近使用したデータが近い時点で再び使用されやすい性質はどれか。','["時間的局所性","空間的局所性","参照整合性","排他制御"]','["時間的局所性","空間的局所性","参照整合性","排他制御"]',0,'시간적 지역성','時間的局所性','같은 데이터가 시간적으로 가깝게 재참조되는 성질이다.','同じデータが時間的に近い時点で再参照される性質である。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-16' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'write-back 캐시의 설명으로 가장 적절한 것은?','ライトバック方式のキャッシュの説明として最も適切なものはどれか。','["更新をまずキャッシュに反映し，必要時に主記憶へ書き戻す","更新のたび必ず主記憶だけを書き換える","キャッシュを使用しない","読込み専用である"]','["更新をまずキャッシュに反映し，必要時に主記憶へ書き戻す","更新のたび必ず主記憶だけを書き換える","キャッシュを使用しない","読込み専用である"]',0,'cache에 먼저 쓰고 필요 시 메모리에 반영','更新をまずキャッシュに反映し，必要時に主記憶へ書き戻す','write-back은 메모리 쓰기 횟수를 줄일 수 있지만 dirty 데이터 관리가 필요하다.','ライトバックは主記憶への書込み回数を減らせるが，ダーティデータ管理が必要である。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-16' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'3TB 디스크 4대로 RAID5를 구성할 때 유효용량은?','3TBのディスク4台でRAID5を構成するとき，有効容量はどれか。','["3TB","6TB","9TB","12TB"]','["3TB","6TB","9TB","12TB"]',2,'9TB','9TB','RAID5 유효용량=(N-1)×디스크 용량=3×3TB=9TB다.','RAID5の有効容量=(N-1)×ディスク容量=3×3TB=9TBである。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-17' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'RAID0의 특징으로 옳은 것은?','RAID0の特徴として正しいものはどれか。','["ストライピングで性能向上を狙うが冗長性はない","ミラーリングで1台故障に必ず耐える","分散パリティを使う","有効容量は常に半分"]','["ストライピングで性能向上を狙うが冗長性はない","ミラーリングで1台故障に必ず耐える","分散パリティを使う","有効容量は常に半分"]',0,'striping, redundancy 없음','ストライピングで性能向上を狙うが冗長性はない','RAID0은 성능과 용량을 활용하지만 장애복구용 중복정보가 없다.','RAID0は性能・容量を活用するが，障害復旧用の冗長情報を持たない。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-17' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'RAID에 대한 설명으로 가장 적절한 것은?','RAIDについて最も適切な説明はどれか。','["RAIDはバックアップそのものではない","RAIDを使えば別媒体バックアップは不要","RAID0は1台故障に耐える","RAID5は2台で構成できる"]','["RAIDはバックアップそのものではない","RAIDを使えば別媒体バックアップは不要","RAID0は1台故障に耐える","RAID5は2台で構成できる"]',0,'RAID는 backup 자체가 아님','RAIDはバックアップそのものではない','RAID는 가용성 향상에 도움되지만 삭제·오염·재해 등에 대비한 별도 백업을 대체하지 않는다.','RAIDは可用性向上に有効だが，削除・破損・災害などに備える別バックアップの代替ではない。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-17' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'MTBF=900시간, MTTR=100시간인 시스템의 가용성은?','MTBF=900時間，MTTR=100時間のシステムの可用性はどれか。','["0.1","0.9","1.0","9.0"]','["0.1","0.9","1.0","9.0"]',1,'0.9','0.9','900/(900+100)=0.9다.','900/(900+100)=0.9である。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-18' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'가용성 0.8인 독립 장치 2대를 병렬 이중화했을 때 전체 가용성은?','可用性0.8の独立した装置2台を並列冗長化したとき，全体の可用性はどれか。','["0.64","0.8","0.96","1.6"]','["0.64","0.8","0.96","1.6"]',2,'0.96','0.96','1-(1-0.8)^2=0.96이다.','1-(1-0.8)^2=0.96である。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-18' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'MTBF가 같을 때 MTTR을 줄이면 일반적으로 가용성은 어떻게 되는가?','MTBFが同じとき，MTTRを短くすると一般に可用性はどうなるか。','["高くなる","低くなる","変わらない","必ず0になる"]','["高くなる","低くなる","変わらない","必ず0になる"]',0,'높아짐','高くなる','가용성=MTBF/(MTBF+MTTR)이므로 복구시간이 줄면 가용성이 높아진다.','可用性=MTBF/(MTBF+MTTR)なので，修復時間が短くなると可用性は高くなる。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-18' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'장애 발생 시 대기 시스템으로 처리를 전환하는 동작은?','障害発生時に待機系へ処理を切り替える動作はどれか。','["フェールオーバ","フェールバック","バックアップ","ロールバック"]','["フェールオーバ","フェールバック","バックアップ","ロールバック"]',0,'failover','フェールオーバ','장애 시 정상계로 전환하는 것이 failover다.','障害時に正常系へ切り替えることがフェールオーバである。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-19' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'가장 빠른 장애 전환을 목표로 대기계를 평상시에도 기동·동기화하는 방식은?','最短の障害切替を目標に，待機系を平常時から起動・同期しておく方式はどれか。','["ホットスタンバイ","コールドスタンバイ","オフラインバックアップ","アーカイブ"]','["ホットスタンバイ","コールドスタンバイ","オフラインバックアップ","アーカイブ"]',0,'hot standby','ホットスタンバイ','hot standby는 즉시 전환 준비 수준이 높다.','ホットスタンバイは即時切替の準備度が高い。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-19' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'서버는 이중화했지만 두 서버가 하나의 전원장치만 공유한다. 남은 위험은?','サーバは二重化したが，2台とも一つの電源装置だけを共有している。残るリスクはどれか。','["電源がSPOFになる","必ずActive-Activeになる","RAID0になる","DNSが不要になる"]','["電源がSPOFになる","必ずActive-Activeになる","RAID0になる","DNSが不要になる"]',0,'전원이 SPOF','電源がSPOFになる','구성요소 일부만 이중화하면 공통 의존점이 단일장애점으로 남을 수 있다.','一部だけ冗長化しても，共通依存点が単一障害点として残ることがある。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-19' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'같은 프로세스 내 스레드들이 일반적으로 공유하는 것은?','同一プロセス内のスレッドが一般に共有するものはどれか。','["ヒープ領域","各スレッド固有のスタック","各スレッド固有のレジスタ状態","プログラムカウンタだけ"]','["ヒープ領域","各スレッド固有のスタック","各スレッド固有のレジスタ状態","プログラムカウンタだけ"]',0,'heap','ヒープ領域','같은 프로세스의 스레드는 주소공간의 코드·데이터·힙 등을 공유한다.','同一プロセスのスレッドはコード・データ・ヒープなどのアドレス空間を共有する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-20' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'여러 스레드가 공유 변수에 동시에 접근해 결과가 실행순서에 따라 달라지는 현상은?','複数スレッドが共有変数へ同時アクセスし，実行順序によって結果が変わる現象はどれか。','["競合状態","デッドロックだけ","ページフォールト","キャッシュヒット"]','["競合状態","デッドロックだけ","ページフォールト","キャッシュヒット"]',0,'race condition','競合状態','공유 데이터에 대한 적절한 동기화가 없을 때 발생할 수 있다.','共有データへの適切な同期がないと発生し得る。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-20' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'critical section을 보호하는 대표적인 동기화 수단은?','クリティカルセクションを保護する代表的な同期手段はどれか。','["ミューテックス","DNS","NAT","RAID0"]','["ミューテックス","DNS","NAT","RAID0"]',0,'mutex','ミューテックス','상호배제를 통해 동시에 한 실행흐름만 임계영역에 들어가게 한다.','相互排他により，同時に一つの実行主体だけがクリティカルセクションへ入るようにする。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-20' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'동시에 도착한 실행시간 6,2,4 작업을 비선점 SJF로 실행하는 순서는?','同時到着した実行時間6,2,4のジョブを非プリエンプティブSJFで実行する順序はどれか。','["6→2→4","2→4→6","4→2→6","2→6→4"]','["6→2→4","2→4→6","4→2→6","2→6→4"]',1,'2→4→6','2→4→6','SJF는 실행시간이 짧은 작업부터 선택한다.','SJFは実行時間が短いジョブから選択する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-21' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'Round Robin 스케줄링에서 각 프로세스가 한 번에 실행할 수 있는 최대 시간 단위는?','ラウンドロビン方式で，各プロセスが1回に実行できる最大時間単位を何というか。','["タイムクォンタム","ページサイズ","MTBF","スラック"]','["タイムクォンタム","ページサイズ","MTBF","スラック"]',0,'time quantum','タイムクォンタム','Round Robin은 일정 time quantum마다 실행권을 순환시킨다.','ラウンドロビンでは一定のタイムクォンタムごとに実行権を交代させる。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-21' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'우선순위 스케줄링에서 낮은 우선순위 프로세스의 starvation을 완화하는 기법은?','優先度スケジューリングで低優先度プロセスのスタベーションを緩和する手法はどれか。','["エージング","ストライピング","ページング","ハッシング"]','["エージング","ストライピング","ページング","ハッシング"]',0,'aging','エージング','오래 기다린 프로세스의 우선순위를 점차 높인다.','長時間待っているプロセスの優先度を徐々に上げる。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-21' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'페이지 크기가 4KB일 때 페이지 내 offset에 필요한 비트 수는?','ページサイズが4KBのとき，ページ内オフセットに必要なビット数はどれか。','["10","12","16","20"]','["10","12","16","20"]',1,'12bit','12ビット','4KB=4096=2^12 byte이므로 12bit다.','4KB=4096=2^12バイトなので12ビットである。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-22' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'TLB의 주된 목적은?','TLBの主な目的はどれか。','["仮想アドレスから物理アドレスへの変換を高速化する","ディスクをミラーリングする","CPUをスケジューリングする","ファイルを圧縮する"]','["仮想アドレスから物理アドレスへの変換を高速化する","ディスクをミラーリングする","CPUをスケジューリングする","ファイルを圧縮する"]',0,'주소 변환 고속화','仮想アドレスから物理アドレスへの変換を高速化する','최근 페이지 테이블 변환 결과를 캐시한다.','最近のページテーブル変換結果をキャッシュする。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-22' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'페이지 테이블 항목이 메모리에 없음을 나타내고 보조기억장치에서 페이지를 불러와야 하는 사건은?','必要なページが主記憶に存在せず，補助記憶装置から読み込む必要がある事象はどれか。','["ページフォールト","キャッシュヒット","デッドロック","割込み禁止"]','["ページフォールト","キャッシュヒット","デッドロック","割込み禁止"]',0,'page fault','ページフォールト','참조한 페이지가 주기억에 없으면 page fault가 발생한다.','参照したページが主記憶にないとページフォールトが発生する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-22' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'LRU 페이지 교체 알고리즘이 선택하는 페이지는?','LRUページ置換方式で置換対象となるページはどれか。','["最も長い間参照されていないページ","最も新しく参照されたページ","番号が最大のページ","最初に読み込まれたページとは限らない"]','["最も長い間参照されていないページ","最も新しく参照されたページ","番号が最大のページ","最初に読み込まれたページとは限らない"]',0,'가장 오래 참조되지 않은 페이지','最も長い間参照されていないページ','LRU는 최근 사용시점이 가장 오래된 페이지를 교체한다.','LRUは最終参照時点が最も古いページを置換する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-23' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'프로세스가 필요한 페이지를 충분히 보유하지 못해 page fault가 급증하는 현상은?','プロセスが必要なページを十分保持できず，ページフォールトが急増する現象はどれか。','["スラッシング","スプーリング","パイプライン","ストライピング"]','["スラッシング","スプーリング","パイプライン","ストライピング"]',0,'thrashing','スラッシング','메모리보다 페이지 교체에 시간을 많이 쓰게 되는 상태다.','処理よりページ入替えに多くの時間を費やす状態である。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-23' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'thrashing 완화책으로 가장 직접적인 것은?','スラッシングの緩和策として最も直接的なものはどれか。','["プロセスに十分なページフレームを割り当てる","タイムクォンタムを0にする","RAID0に変更する","DNSキャッシュを削除する"]','["プロセスに十分なページフレームを割り当てる","タイムクォンタムを0にする","RAID0に変更する","DNSキャッシュを削除する"]',0,'충분한 page frame 할당','プロセスに十分なページフレームを割り当てる','working set을 담을 수 있도록 메모리를 확보하면 page fault 폭증을 줄일 수 있다.','ワーキングセットを保持できるだけのフレームを確保すると，ページフォールト急増を抑えられる。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-23' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'deadlock의 필요조건에 포함되지 않는 것은?','デッドロックの必要条件に含まれないものはどれか。','["相互排他","保持待ち","非横取り","いつでも横取り可能"]','["相互排他","保持待ち","非横取り","いつでも横取り可能"]',3,'선점 가능','いつでも横取り可能','필요조건은 상호배제, 점유대기, 비선점, 순환대기다.','必要条件は相互排他，保持待ち，非横取り，循環待ちである。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-24' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'두 프로세스가 서로 상대가 보유한 자원을 기다리며 순환을 이루는 상태는?','二つのプロセスが互いに相手の保持資源を待ち，循環を形成している状態はどれか。','["デッドロック","スタベーションだけ","キャッシュミス","ページヒット"]','["デッドロック","スタベーションだけ","キャッシュミス","ページヒット"]',0,'deadlock','デッドロック','순환대기와 다른 필요조건이 함께 성립하면 deadlock이 발생할 수 있다.','循環待ちなどの必要条件が成立するとデッドロックが発生し得る。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-24' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'Banker 알고리즘의 목적은?','バンカアルゴリズムの目的はどれか。','["資源割当後も安全状態を保てるか判断する","キャッシュヒット率を上げる","SQLを最適化する","RAIDパリティを計算する"]','["資源割当後も安全状態を保てるか判断する","キャッシュヒット率を上げる","SQLを最適化する","RAIDパリティを計算する"]',0,'safe state 판단','資源割当後も安全状態を保てるか判断する','모든 프로세스가 완료 가능한 안전순서가 존재하는지 확인한다.','全プロセスを完了できる安全順序が存在するかを確認する。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-24' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'관계형 DB의 기본키에 대한 설명으로 옳은 것은?','関係データベースの主キーについて正しいものはどれか。','["行を一意に識別しNULLを許さない","必ず一つの列だけで構成する","重複を許す","外部キーと同じ意味"]','["行を一意に識別しNULLを許さない","必ず一つの列だけで構成する","重複を許す","外部キーと同じ意味"]',0,'행을 유일 식별, NULL 불가','行を一意に識別しNULLを許さない','기본키는 행을 유일하게 식별하며 복합키일 수도 있다.','主キーは行を一意に識別し，複数列で構成される場合もある。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-25' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'외래키의 주된 목적은?','外部キーの主な目的はどれか。','["表間の参照整合性を保つ","必ず検索を高速化する","全列を暗号化する","重複行を自動削除する"]','["表間の参照整合性を保つ","必ず検索を高速化する","全列を暗号化する","重複行を自動削除する"]',0,'참조무결성 유지','表間の参照整合性を保つ','외래키는 참조 대상 키와 관계를 유지하도록 제약한다.','外部キーは参照先キーとの関係を維持する制約である。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-25' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'부모 행 삭제 시 이를 참조하는 자식 행도 자동 삭제하는 동작은?','親行の削除時，それを参照する子行も自動削除する動作はどれか。','["ON DELETE CASCADE","ON DELETE RESTRICT","GROUP BY","ROLLBACK ONLY"]','["ON DELETE CASCADE","ON DELETE RESTRICT","GROUP BY","ROLLBACK ONLY"]',0,'ON DELETE CASCADE','ON DELETE CASCADE','CASCADE는 부모 삭제를 관련 자식 행까지 전파한다.','CASCADEは親行の削除を関連する子行へ伝播させる。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-25' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'한 고객이 여러 주문을 할 수 있고 각 주문은 한 고객에 속한다. 관계는?','1人の顧客が複数の注文を行え，各注文は1人の顧客に属する。関係はどれか。','["1対1","1対多","多対多","関係なし"]','["1対1","1対多","多対多","関係なし"]',1,'1:N','1対多','고객에서 주문 방향은 하나 대 여러 개다.','顧客から注文への関係は1対多である。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-26' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'관계형 DB에서 M:N 관계를 구현하는 일반적인 방법은?','関係データベースで多対多関係を実装する一般的な方法はどれか。','["中間表を設ける","両方の主キーを削除する","全値を1セルに入れる","外部キーを使わない"]','["中間表を設ける","両方の主キーを削除する","全値を1セルに入れる","外部キーを使わない"]',0,'중간 테이블','中間表を設ける','양쪽 엔터티의 키를 참조하는 교차 테이블로 M:N을 두 개의 1:N으로 분해한다.','両側のキーを参照する中間表によって，多対多を二つの1対多に分解する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-26' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'ER 모델에서 cardinality가 나타내는 것은?','ERモデルでカーディナリティが表すものはどれか。','["エンティティ間の対応数","列のデータ型","暗号鍵長","CPUコア数"]','["エンティティ間の対応数","列のデータ型","暗号鍵長","CPUコア数"]',0,'엔터티 간 대응 수','エンティティ間の対応数','1:1, 1:N, M:N처럼 관계에 참여하는 개수 제약을 표현한다.','1対1，1対多，多対多など，関係に参加する数の制約を表す。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-26' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'복합키의 일부에만 종속되는 비키 속성을 제거하는 정규형은?','複合キーの一部だけに従属する非キー属性を除去する正規形はどれか。','["第1正規形","第2正規形","第3正規形","BCNFだけ"]','["第1正規形","第2正規形","第3正規形","BCNFだけ"]',1,'2NF','第2正規形','2NF는 부분 함수 종속을 제거한다.','第2正規形は部分関数従属を排除する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-27' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'키→비키A, 비키A→비키B 형태의 종속에서 비키B의 종속은?','キー→非キーA，非キーA→非キーBという依存関係で，非キーBの依存はどれか。','["推移的関数従属","部分関数従属","多値従属だけ","依存なし"]','["推移的関数従属","部分関数従属","多値従属だけ","依存なし"]',0,'이행 함수 종속','推移的関数従属','키가 다른 비키 속성을 거쳐 비키B를 결정하므로 이행 종속이다.','キーが別の非キー属性を介して非キーBを決定するので推移的関数従属である。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-27' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'정규화의 주된 목적은?','正規化の主な目的はどれか。','["データ重複と更新時異常を減らす","表数を無条件に最大化する","検索を必ず最速にする","外部キーを全て削除する"]','["データ重複と更新時異常を減らす","表数を無条件に最大化する","検索を必ず最速にする","外部キーを全て削除する"]',0,'중복·갱신이상 감소','データ重複と更新時異常を減らす','함수 종속을 바탕으로 적절히 분해해 삽입·갱신·삭제 이상을 줄인다.','関数従属性に基づき適切に分解し，挿入・更新・削除時の異常を減らす。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-27' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'LEFT JOIN에서 왼쪽 행과 일치하는 오른쪽 행이 없을 때 결과는?','LEFT JOINで左表の行に一致する右表の行がないとき，結果はどうなるか。','["左行は残り右側列はNULLになる","左行も削除される","必ずエラーになる","全行との直積になる"]','["左行は残り右側列はNULLになる","左行も削除される","必ずエラーになる","全行との直積になる"]',0,'왼쪽 행 유지, 오른쪽 NULL','左行は残り右側列はNULLになる','LEFT JOIN은 왼쪽 테이블의 행을 보존한다.','LEFT JOINは左表の行を保持する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-28' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'JOIN 조건을 빠뜨려 두 테이블의 모든 행 조합이 생성되는 것은?','JOIN条件を指定せず，二つの表の全ての行の組合せが生成されるものはどれか。','["直積","正規化","ロールバック","インデックスシーク"]','["直積","正規化","ロールバック","インデックスシーク"]',0,'Cartesian product','直積','m행과 n행 테이블이면 m×n 조합이 생길 수 있다.','m行とn行の表ならm×n行の組合せが生じ得る。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-28' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'LEFT JOIN 후 WHERE절에서 오른쪽 테이블의 열에 `= 값` 조건을 두면 주의할 점은?','LEFT JOIN後，WHERE句で右表の列に`=値`条件を指定するときの注意点はどれか。','["NULL行が除外され実質的にINNER JOINのようになる場合がある","必ず全左行が残る","JOIN条件が無効になる","GROUP BYが必須になる"]','["NULL行が除外され実質的にINNER JOINのようになる場合がある","必ず全左行が残る","JOIN条件が無効になる","GROUP BYが必須になる"]',0,'실질적으로 INNER처럼 될 수 있음','NULL行が除外され実質的にINNER JOINのようになる場合がある','오른쪽 불일치 행의 열은 NULL이므로 WHERE 조건에서 제거될 수 있다.','右表に一致しない行はNULLになるため，WHERE条件で除外される場合がある。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-28' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'부서별 인원수를 구하고 5명 이상인 부서만 남길 때 사용하는 절은?','部署ごとの人数を集計し，5人以上の部署だけを残すときに使用する句はどれか。','["HAVING","WHEREだけ","VALUES","LIMITだけ"]','["HAVING","WHEREだけ","VALUES","LIMITだけ"]',0,'HAVING','HAVING','집계 후 그룹 조건은 HAVING에서 적용한다.','集計後のグループ条件はHAVING句で指定する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-29' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'COUNT(col)과 COUNT(*)의 차이로 옳은 것은?','COUNT(col)とCOUNT(*)の違いとして正しいものはどれか。','["COUNT(col)はcolがNULLの行を数えない","COUNT(*)はNULL行を全て除外する","両者は常に同じ","COUNT(col)は文字列だけ数える"]','["COUNT(col)はcolがNULLの行を数えない","COUNT(*)はNULL行を全て除外する","両者は常に同じ","COUNT(col)は文字列だけ数える"]',0,'COUNT(col)은 NULL 제외','COUNT(col)はcolがNULLの行を数えない','COUNT(*)는 행 자체를 세고 COUNT(col)은 해당 열의 NULL을 제외한다.','COUNT(*)は行を数え，COUNT(col)は指定列がNULLの行を除外する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-29' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'SQL의 논리적 처리 순서로 가장 적절한 것은?','SQLの論理的な処理順序として最も適切なものはどれか。','["FROM→WHERE→GROUP BY→HAVING→SELECT","SELECT→FROM→HAVING→WHERE→GROUP BY","WHERE→SELECT→FROM→GROUP BY→HAVING","GROUP BY→FROM→SELECT→WHERE→HAVING"]','["FROM→WHERE→GROUP BY→HAVING→SELECT","SELECT→FROM→HAVING→WHERE→GROUP BY","WHERE→SELECT→FROM→GROUP BY→HAVING","GROUP BY→FROM→SELECT→WHERE→HAVING"]',0,'FROM→WHERE→GROUP BY→HAVING→SELECT','FROM→WHERE→GROUP BY→HAVING→SELECT','조건 적용 위치를 판단할 때 이 논리 순서를 이해하면 도움이 된다.','条件を適用する位置を判断するうえで，この論理順序を理解するとよい。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-29' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'트랜잭션 일부만 반영되고 나머지는 실패했는데 rollback되지 않았다. 위반된 ACID 특성은?','トランザクションの一部だけが反映され，残りが失敗したのにロールバックされなかった。違反したACID特性はどれか。','["Atomicity","Consistency","Isolation","Durability"]','["Atomicity","Consistency","Isolation","Durability"]',0,'Atomicity','Atomicity','원자성은 전부 수행되거나 전부 취소되어야 함을 뜻한다.','Atomicityは，全て実行されるか全て取り消されることを要求する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-30' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'commit된 데이터가 시스템 재기동 후 사라졌다. 위반된 특성은?','コミット済みデータがシステム再起動後に失われた。違反した特性はどれか。','["Durability","Atomicity","Isolation","Consistency"]','["Durability","Atomicity","Isolation","Consistency"]',0,'Durability','Durability','지속성은 commit 결과가 장애 후에도 보존되어야 함을 뜻한다.','Durabilityはコミット結果が障害後も保持されることを要求する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-30' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'동시에 실행되는 트랜잭션이 서로의 중간 상태에 부적절하게 영향을 주지 않도록 하는 특성은?','同時実行するトランザクションが互いの途中状態へ不適切に影響しないようにする特性はどれか。','["Isolation","Durability","Atomicity","Availability"]','["Isolation","Durability","Atomicity","Availability"]',0,'Isolation','Isolation','격리성은 동시 트랜잭션 간 간섭을 제어한다.','Isolationは同時実行トランザクション間の干渉を制御する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-30' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'공유락(S lock)끼리의 일반적인 호환성은?','共有ロック（Sロック）同士の一般的な互換性はどれか。','["互換である","必ず競合する","片方がXロックになる","デッドロックが必ず起こる"]','["互換である","必ず競合する","片方がXロックになる","デッドロックが必ず起こる"]',0,'호환','互換である','여러 트랜잭션이 같은 데이터를 읽기 위해 S lock을 함께 가질 수 있다.','複数トランザクションが同じデータを読むためのSロックは共存できる。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-31' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'한 트랜잭션이 X lock을 보유한 행을 다른 트랜잭션이 UPDATE하려 할 때 일반적으로 어떻게 되는가?','あるトランザクションがXロックを保持する行を，別のトランザクションがUPDATEしようとすると一般にどうなるか。','["ロック解放まで待機する","必ず即時成功する","主キーが削除される","自動でREAD ONLYになる"]','["ロック解放まで待機する","必ず即時成功する","主キーが削除される","自動でREAD ONLYになる"]',0,'lock 해제까지 대기','ロック解放まで待機する','X lock은 충돌하는 다른 읽기/쓰기를 제한한다.','Xロックは競合する他のアクセスを制限する。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-31' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'T1이 A를 X lock, T2가 B를 X lock한 뒤 서로 상대 자원을 기다린다. 가능한 현상은?','T1がAをXロック，T2がBをXロックした後，互いに相手の資源を待つ。起こり得る現象はどれか。','["デッドロック","キャッシュヒット","正規化","フェールオーバ"]','["デッドロック","キャッシュヒット","正規化","フェールオーバ"]',0,'deadlock','デッドロック','서로 상대 lock 해제를 기다리는 순환대기가 된다.','互いに相手のロック解放を待つ循環待ちとなる。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-31' AND t.type_no=3;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'수백만 행에서 거의 유일한 user_id를 자주 등가검색할 때 일반적으로 효과적인 것은?','数百万行の表で，ほぼ一意なuser_idを頻繁に等価検索するとき，一般に有効なものはどれか。','["user_idにインデックスを作成する","全ての列を削除する","毎回全表走査を強制する","主キーを無効にする"]','["user_idにインデックスを作成する","全ての列を削除する","毎回全表走査を強制する","主キーを無効にする"]',0,'user_id index','user_idにインデックスを作成する','선택도가 높고 자주 검색되는 열은 인덱스 효과가 크다.','選択性が高く頻繁に検索される列はインデックスの効果が高い。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-32' AND t.type_no=1;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'인덱스의 일반적인 trade-off로 옳은 것은?','インデックスの一般的なトレードオフとして正しいものはどれか。','["検索性能向上と引換えに更新コストや領域が増える","全更新が必ず高速化する","保存領域を全く使わない","全問合せが必ず高速化する"]','["検索性能向上と引換えに更新コストや領域が増える","全更新が必ず高速化する","保存領域を全く使わない","全問合せが必ず高速化する"]',0,'조회 성능↑, 갱신/공간 비용↑','検索性能向上と引換えに更新コストや領域が増える','인덱스 구조를 유지해야 하므로 쓰기 비용과 저장공간이 필요하다.','インデックス構造を維持するため，更新コストと保存領域が必要になる。',1,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-32' AND t.type_no=2;

INSERT OR REPLACE INTO ap_concept_questions (id,problem_type_id,question_no,question_ko,question_ja,choices_ko_json,choices_ja_json,correct_choice,answer_ko,answer_ja,explanation_ko,explanation_ja,difficulty,sort_order)
SELECT NULL,t.id,2,'값 종류가 매우 적고 조건 결과가 테이블 대부분을 차지하는 열의 단독 인덱스에 대한 설명으로 적절한 것은?','値の種類が少なく，条件結果が表の大部分を占める列の単独インデックスについて適切なものはどれか。','["全表走査の方が有利な場合がある","必ずインデックスが最速","必ず主キーになる","更新コストは0になる"]','["全表走査の方が有利な場合がある","必ずインデックスが最速","必ず主キーになる","更新コストは0になる"]',0,'full scan이 유리할 수 있음','全表走査の方が有利な場合がある','선택도가 낮고 많은 행을 읽으면 인덱스 접근 이점이 작을 수 있다.','選択性が低く大量行を取得する場合，インデックス利用の利点が小さいことがある。',2,2 FROM ap_concept_problem_types t JOIN ap_concepts c ON c.id=t.concept_id WHERE c.concept_code='A-32' AND t.type_no=3;
